# /qompassai/dotfiles/.config/inspircd/examples/providers/torexit.conf
# Qompass AI Inspircd Torexit Provider Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#######################################################################
<dnsbl name="torexit.dan.me.uk"
       domain="torexit.dan.me.uk"
       type="record"
       records="100"
       timeout="10s"
       action="zline"
       duration="7d"
       reason="Tor exit nodes are not allowed on this network. See https://metrics.torproject.org/rs.html#search/%ip% for more information.">

<dnsblreply name="torexit.dan.me.uk"
            reply="100"
            description="Tor exit node">
