# 20-profiles.conf
# Qompass AI - [ ]
# Copyright (C) 2026 Qompass AI, All rights reserved
# ----------------------------------------
wireplumber.components = [
  {
    name = libpipewire-module-filter-chain, type = pw-module
    arguments = {
      audio.channels   = 2
      audio.position   = [ FL, FR ]
      node.description = "2ch Equalizer Sink"
      media.name       = "2ch Equalizer Sink"
      node.name        = "filter.sink.smart-equalizer"
      filter.graph = {
        links = [
          { output = "bass:Out",   input = "treble:In" }
        ]
        nodes = [
          {
            control = { "Freq" = 250.0, "Q" = 1.0, "Gain" = 0.0 }
            label   = bq_lowshelf
            name    = bass
            type    = builtin
          }
          {
            control = { "Freq" = 6000.0, "Q" = 1.0, "Gain" = 0.0 }
            label   = bq_peaking
            name    = treble
            type    = builtin
          }
        ]
      }
      capture.props = {
        filter.smart       = true
        filter.smart.name  = "filter.sink.smart-equalizer"
        media.class        = Audio/Sink
        # filter.smart.target = { node.name = "alsa_output.pci-0000_00_01.0.analog-stereo" }
        # filter.smart.before = []
        # filter.smart.after  = []
      }
      playback.props = {
        media.role   = "DSP"
        node.passive = true
      }
    }
    provides = filter.sink.smart-equalizer
  }
]
wireplumber.profiles = {
  audio = {
    inherits       = [ base ]
    hardware.audio = required
  }
  base = {
    check.no-media-session     = required
    support.log-settings       = required
    support.session-services   = required
    support.settings           = required
  }
  bluetooth = {
    inherits           = [ base ]
    hardware.bluetooth = required
  }
  main = {
    hardware.audio         = required
    hardware.bluetooth     = required
    hardware.video-capture = required
    inherits               = [ base ]
    metadata.sm-objects    = required
    metadata.sm-settings   = required
    policy.standard        = required
  }
  main-embedded = {
    inherits = [ main, mixin.systemwide-session, mixin.stateless ]
  }
  main-systemwide = {
    inherits = [ main, mixin.systemwide-session ]
  }
  mixin.stateless = {
    hooks.default-nodes.state = disabled
    hooks.device.profile.state = disabled
    hooks.device.routes.state  = disabled
    hooks.stream.state         = disabled
  }
  mixin.systemwide-session = {
    monitor.alsa.reserve-device     = disabled
    monitor.bluez.seat-monitoring   = disabled
    script.client.access-portal     = disabled
    support.logind                  = disabled
    support.portal-permissionstore  = disabled
    support.reserve-device          = disabled
  }
  policy = {
    agl.filter.equalizer-sink = required 
    filter.sink.smart-equalizer = required
    inherits                  = [ base ]
    metadata.sm-objects       = required
    metadata.sm-settings      = required
    policy.standard           = required
  }
  video-capture = {
    inherits               = [ base ]
    hardware.video-capture = required
  }
  video-only = {
    hardware.audio         = disabled
    hardware.bluetooth     = disabled
    inherits               = [ main ]
  }
}
