# 30-wpcc.conf
# Qompass AI - [ ]
# Copyright (C) 2026 Qompass AI, All rights reserved
# ----------------------------------------
wireplumber.components = [
  {
    name = ensure-no-media-session, type = built-in
    provides = check.no-media-session
  }
  {
    name = export-core, type = built-in
    provides = support.export-core
  }
  {
    name = libpipewire-module-client-node, type = pw-module
    provides = pw.client-node
    wants = [ support.export-core ]
  }
  {
    name = libpipewire-module-client-device, type = pw-module
    provides = pw.client-device
    wants = [ support.export-core ]
  }
  {
    name = libpipewire-module-spa-node-factory, type = pw-module
    provides = pw.node-factory.spa
    requires = [ pw.client-node ]
  }
  {
    name = libpipewire-module-adapter, type = pw-module
    provides = pw.node-factory.adapter
    requires = [ pw.client-node ]
  }
  {
    name = libwireplumber-module-settings, type = module
    arguments = { metadata.name = sm-settings }
    provides = metadata.sm-settings
  }
  {
    name = settings-instance, type = built-in
    arguments = { metadata.name = sm-settings }
    provides = support.settings
    after = [ metadata.sm-settings ]
  }
  {
    name = libwireplumber-module-log-settings, type = module
    provides = support.log-settings
  }
  {
    name = libwireplumber-module-lua-scripting, type = module
    provides = support.lua-scripting
  }
  {
    name = libwireplumber-module-standard-event-source, type = module
    provides = support.standard-event-source
  }
  {
    name = libwireplumber-module-dbus-connection, type = module
    provides = support.dbus
  }
  {
    name = libwireplumber-module-portal-permissionstore, type = module
    provides = support.portal-permissionstore
    requires = [ support.dbus ]
  }
  {
    name = libwireplumber-module-reserve-device, type = module
    provides = support.reserve-device
    requires = [ support.dbus ]
  }
  {
    name = libwireplumber-module-logind, type = module
    provides = support.logind
  }
  {
    name = libwireplumber-module-si-node, type = module
    provides = si.node
  }
  {
    name = libwireplumber-module-si-audio-adapter, type = module
    provides = si.audio-adapter
  }
  {
    name = libwireplumber-module-si-standard-link, type = module
    provides = si.standard-link
  }
  {
    name = libwireplumber-module-default-nodes-api, type = module
    provides = api.default-nodes
  }
  {
    name = libwireplumber-module-mixer-api, type = module
    provides = api.mixer
  }
  {
    name = libwireplumber-module-file-monitor-api, type = module
    provides = api.file-monitor
  }
  {
    name = metadata.lua, type = script/lua
    arguments = { metadata.name = default }
    provides = metadata.default
  }
  {
    name = metadata.lua, type = script/lua
    arguments = { metadata.name = filters }
    provides = metadata.filters
  }
  {
    name = sm-objects.lua, type = script/lua
    provides = metadata.sm-objects
  }
  {
    name = session-services.lua, type = script/lua
    provides = support.session-services
  }
]
