# bluetooth.conf
# Qompass AI - [ ]
# Copyright (C) 2026 Qompass AI, All rights reserved
# ----------------------------------------
monitor.bluez.properties = {
  bluez5.a2dp.opus.pro.bidi.application     = "audio"
  bluez5.a2dp.opus.pro.bidi.channels        = 1
  bluez5.a2dp.opus.pro.bidi.coupled-streams = 0
  bluez5.a2dp.opus.pro.bidi.frame-dms       = 400
  bluez5.a2dp.opus.pro.bidi.locations       = [ FC ]
  bluez5.a2dp.opus.pro.bidi.max-bitrate     = 160000
  bluez5.a2dp.opus.pro.channels             = 3
  bluez5.a2dp.opus.pro.coupled-streams      = 1
  bluez5.a2dp.opus.pro.frame-dms            = 50
  bluez5.a2dp.opus.pro.locations            = [ FL, FR, LFE ]
  bluez5.a2dp.opus.pro.max-bitrate          = 600000
  bluez5.a2dp.opus.pro.application          = "audio"
  bluez5.codecs                             = [ sbc sbc_xq aac ldac aptx aptx_hd aptx_ll aptx_ll_duplex faststream faststream_duplex ]
  bluez5.default.channels                   = 2
  bluez5.default.rate                       = 48000
  bluez5.dummy-avrcp-player                 = true
  bluez5.enable-hw-volume                   = true
  bluez5.enable-msbc                        = true
  bluez5.enable-sbc-xq                      = true
  bluez5.hfphsp-backend                     = "native"
  bluez5.hfphsp-backend-native-modem        = "none"
  bluez5.hw-offload-sco                     = false
  bluez5.roles                              = [ a2dp_sink a2dp_source bap_sink bap_source hfp_ag hfp_hf hsp_ag hsp_hs ]
}
monitor.bluez-midi.properties = {
}
monitor.bluez-midi.servers = [
  "bluez_midi.server"
]
monitor.bluez.rules = [
  {
    matches = [
      {
        device.name                               = "~bluez_card.*"
      }
    ]
    actions = {
      update-props = {
        bluez5.a2dp.aac.bitratemode               = 0
        bluez5.a2dp.ldac.quality                  = "auto"
        bluez5.a2dp.opus.pro.application          = "audio"
        bluez5.a2dp.opus.pro.bidi.application     = "audio"
        bluez5.auto-connect                       = [ hfp_hf hsp_hs a2dp_sink hfp_ag hsp_ag a2dp_source ]
        bluez5.hw-volume                          = [ hfp_hf hsp_hs a2dp_sink hfp_ag hsp_ag a2dp_source ]
      }
    }
  }
  {
    matches = [
      {
        node.name                                 = "~bluez_input.*"
      }
      {
        node.name                                 = "~bluez_output.*"
      }
    ]
    actions = {
      update-props = {
        bluez5.media-source-role                  = "input"
        channelmix.mix-lfe                        = false
        channelmix.normalize                      = false
        monitor.channel-volumes                   = false
        node.nick                                 = "My Node"
        node.pause-on-idle                        = false
        priority.driver                           = 100
        priority.session                          = 100
        resample.quality                          = 4
        session.suspend-timeout-seconds           = 5
      }
    }
  }
]
monitor.bluez-midi.rules = [
  {
    matches = [
      {
        node.name = "~bluez_midi.*"
      }
    ]
    actions = {
      update-props = {
        node.latency-offset-msec        = 0
        node.nick                       = "My Node"
        node.pause-on-idle              = false
        priority.driver                 = 100
        priority.session                = 100
        session.suspend-timeout-seconds = 5
      }
    }
  }
]

