# camera.conf
# Qompass AI - [ ]
# Copyright (C) 2026 Qompass AI, All rights reserved
# ----------------------------------------
monitor.libcamera.properties = {
}
monitor.libcamera.rules = [
   {
     matches = [
       {
         device.name = "~libcamera_device.*"
       }
     ]
     actions = {
       update-props = {
         device.nick       = "My Device"
         device.disabled   = false
       }
     }
   }
   {
     matches = [
       {
         node.name = "~libcamera_input.*"
       }
       {
         node.name = "~libcamera_output.*"
       }
     ]
     actions = {
       update-props = {
         node.nick              = "My Node"
         priority.driver        = 100
         priority.session       = 100
         node.pause-on-idle     = false
         node.disabled = false
       }
     }
   }
]
