# /qompassai/dotfiles/.config/ssync/ssync.conf
# Qompass AI SSync Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
syncrepo="/var/lib/ssync"
gituser="$(pass show gh/user)"
gitemail="$(pass show gh/mail)"
machinebranch=""
giturl=""
syncbranch="main"
gpgkey="$(pass show ssync/k)"
