backlight:
{
    # disabled = true;
    # restore_on_exit = true;
    # no_smooth_transition = true;
    # trans_step = 0.05;
    # trans_timeout = 30;
    # trans_fixed = 1000;
    # ac_timeouts = [ 600, 2700, 300 ];
    # batt_timeouts = [ 1200, 5400, 600 ];
    # shutter_threshold = 0.10;
    # no_auto_calibration = true;
    # pause_on_lid_closed = true;
    # capture_on_lid_opened = true;
    # hotplug_delay = 5;
};
