-- ~/qompassai/Diver/filetype.lua
-- Qompass AI FileType Config
-- Copyright (C) 2025 Qompass AI, All rights reserved
-- ----------------------------------------
vim.filetype.add({
    extension = {
        bri = 'brioche',
        brioche = 'brioche',
        cairo = 'cairo',
        clar = 'clar',
        clarity = 'clarity',
        comp = 'glsl',
        cr = 'crystal',
        cypher = 'cypher',
        frag = 'glsl',
        geom = 'glsl',
        hbs = 'html.handlebars',
        handlebars = 'html.handlebars',
        rst = 'rst',
        schelp = 'scdoc',
        svh = 'systemverilog',
        tesc = 'glsl',
        tese = 'glsl',
        tsx = 'typescript.tsx',
        v = 'verilog',
        verilog = 'verilog',
        vh = 'verilog',
        yaml = 'yaml',
        yml = 'yaml',
        ['yaml.ansible'] = 'yaml.ansible',
        ['yml.ansible'] = 'yaml.ansible',
        ziggy = 'ziggy',
        ['ziggy-schema'] = 'ziggy_schema',
    },
    filename = {
        ['ansible.cfg'] = 'ansible',
        ['project.bri'] = 'brioche',
        brioche = 'brioche',
        Cairo = 'cairo',
        Crystal = 'crystal',
    },
    pattern = {
        ['.*/.*%.als'] = 'alloy',
        ['.*%.ansible%.ya?ml'] = 'yaml.ansible',
        ['.*%.cairo'] = 'cairo',
        ['.*%.clar'] = 'clar',
        ['.*%.clarity'] = 'clarity',
        ['.*%.crystal'] = 'crystal',
        ['^.*/gitconfig.*$'] = 'gitconfig',
        ['^.*/gitignore.*$'] = 'gitignore',
        ['^.*/gitcommit.*$'] = 'gitcommit',
        ['*.gjs'] = 'javascript.glimmer',
        ['*.gts'] = 'typescript.glimmer',
        ['.*/templates/.*%.yaml'] = 'helm',
        ['.*/templates/.*%.yml'] = 'helm',
        ['.*/templates/.*%.tpl'] = 'helm',
        ['.*/values.*%.ya?ml'] = 'yaml.helm-values',
    },
})