# /qompassai/dotfiles/.config/minio/minio.conf
# Qompass AI Minio Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

MINIO_VOLUMES="/srv/minio/data/"
# MINIO_ROOT_USER=example-user
# MINIO_ROOT_PASSWORD=example-password
# MINIO_OPTS="--address :9199"
