#!/usr/bin/env sh -x
# /qompassai/dotfiles/.config/vmware-tools/scripts/vmware/network
# Qompass AI VMWare-Tools VMWare Network Script
# Copyright (C) 2025 Qompass AI, All rights reserved
#############################################################
SOURCE=$0
logdir=/var/log
logbase=$logdir/vmware-network
logfile=$logbase.log
logmode=1
logrotate=1
logsetperms=1
get_logfile() {
   file=`vmware-toolbox-cmd config get logging network.data | \
        sed -e 's/.*= *//' -e 's/ *$//'`
   if [ -n "${file##*"UNSET"*}" ]; then
      logfile=$file
      logdir=`dirname $logfile`
      logbase=`echo $logfile | sed 's/\..*$//'`
   fi
}
get_logconfig() {
   handler=`vmware-toolbox-cmd config get logging network.handler | \
           sed -e 's/.*= *//' -e 's/ *$//'`
   if [ -z "${handler##*"UNSET"*}" ]; then
      # Default unset to file handler
      handler=file
   fi
   case $handler in
      "file")
         get_logfile
         ;;
      "file+")
         get_logfile
         logrotate=0
         ;;
      "vmx"|"std")
         logrotate=0
         logsetperms=0
         ;;
      "syslog")
         logfile=/var/log/syslog
         logdir=`dirname $logfile`
         logrotate=0
         logsetperms=0
         ;;
      *)
         vmtoolsd --cmd "log WARNING: [$SOURCE] Logging unknown network.handler: $handler"
         get_logfile
         ;;
   esac
}
rotate_logfile() {
   if [ $logrotate -eq 1 ]; then
      max=`vmware-toolbox-cmd config get logging network.maxOldLogFiles | \
          sed -e 's/.*= *//' -e 's/ *$//'`
      if [ `expr "$max" : '[0-9]\+$'` -eq 0 ]; then
         max=9
      fi
      if [ $max -lt 1 ]; then
         max=9
      fi
      max=`expr $max - 1`
      for s in `seq $max -1 1`; do
         d=`expr $s + 1`
         mv -f $logbase.$s.log $logbase.$d.log
      done
      mv -f $logbase.log $logbase.1.log
   fi
}
log() {
   if [ $logmode -eq 1 ]; then
      if [ "$handler" = "vmx" ]; then
         vmtoolsd --cmd "log $*"
      elif [ "$handler" = "std" ]; then
         echo `date` ": $*"
      elif [ -w $logdir ]; then
         space=`df -k $logdir | awk 'NR == 2 { print $4 }'`
         if [ $space -gt 1024 ]; then
            echo `date` ": $*" >> $logfile
         else
            vmtoolsd --cmd "log WARNING: [$SOURCE] Logging disabled. No space left in $logdir"
            logmode=0
         fi
      else
         vmtoolsd --cmd "log WARNING: [$SOURCE] Logging disabled. $logdir is not writable"
         logmode=0
      fi
   fi
}
get_logconfig
rotate_logfile
if [ $logsetperms -eq 1 ]; then
   if [ ! -e $logfile ]; then
      touch $logfile
   fi
   chmod 0600 $logfile
fi
log "Executing '$0 $*'"
. `dirname "$0"`/../../statechange.subr
find_networking_script() {
   local script="error"
   for dir in "/etc/init.d" "/sbin/init.d" "/etc" "/etc/rc.d" ; do
      if [ -d "$dir/rc0.d" ] &&
         [ -d "$dir/rc1.d" ] &&
         [ -d "$dir/rc2.d" ] &&
         [ -d "$dir/rc3.d" ] &&
         [ -d "$dir/rc4.d" ] &&
         [ -d "$dir/rc5.d" ] &&
         [ -d "$dir/rc6.d" ]; then
         if [ -d "$dir/init.d" ]; then
            if [ -x "$dir/init.d/network" ]; then
               script="$dir/init.d/network"
            elif [ -x "$dir/init.d/networking" ]; then
               script="$dir/init.d/networking"
            fi
         else
            if [ -x "$dir/network" ]; then
               script="$dir/network"
            elif [ -x "$dir/networking" ]; then
               script="$dir/networking"
            fi
         fi
      fi
   done
   log "$script"
}
exec_networking_script()
{
   local script=$1
   local action=$2
   service=`which service 2>/dev/null`
   if [ $? = 0 -a -n "$service" ]; then
      serviceName=`basename "$script"`
      "$service" "$serviceName" "$action"
   else
      "$script" "$action"
   fi

   return $?
}
exec_systemctl_service()
{
   local rc=1
   local action=$1
   local ctlcmd=$(which systemctl 2>/dev/null)
   local service
   [ -z "$ctlcmd" ] && return $rc
   for svc in systemd-networkd network; do
      if ! $ctlcmd status $svc | grep -iq 'not-found'; then
         service=$svc && break
      fi
   done
   [ -z "$service" ] && return $rc
   $ctlcmd $action $service; rc=$?
   if [ $rc = 0 -a $service = 'systemd-networkd' -a $action = 'stop' ]; then
      config_network_intfs $action; rc=$?
   fi
   return $rc
}
del_intf_ip()
{
   local nic=$1
   $ip_cmd addr flush dev $nic
   return $?
}
ip_intf_ops()
{
   local rc=1
   local nic=$1
   local ops=$2
   [ -z "$ip_cmd" ] && return $rc
   $ip_cmd link set $nic $ops; rc=$?
   if [ $rc = 0 -a $ops = down ]; then
      del_intf_ip $nic; rc=$?
   fi
   return $rc
}
intf_ops()
{
   local rc=0
   local cmd=$1
   local ops=$2
   local nic=$3
   local tmp
   if [ ! -z "$cmd" ]; then
      tmp=$($cmd $nic 2>&1); rc=$?
      if [ $rc = 0 ]; then
         echo $tmp | egrep -iq 'not configured|ignoring unknown' && rc=1
      fi
   fi
   if [ -z "$cmd" -o $rc != 0 ]; then
      ip_intf_ops $nic $ops; rc=$?
   fi
   return $rc
}
exec_intf_ops()
{
   local rc=0
   local action=$1
   local nic=$2
   case $action in
      start)
         intf_ops "$ifup_cmd" up $nic; rc=$?
         ;;
      stop)
         intf_ops "$ifdown_cmd" down $nic; rc=$?
         ;;
      *)
         Panic "Illegal interface action: $action"
         ;;
   esac
   return $rc
}
config_network_intfs()
{
   local rc=0
   local action=$1

   if [ -f "$activeList" ]; then
      while read nic; do
         exec_intf_ops $action $nic
         rc=$(expr $rc \| $?)
      done < $activeList
   fi

   return $rc
}
run_network_script()
{
   local action=$1
   local rc=0
   local script

   while true; do

      exec_systemctl_service $action
      [ $? != 0 ] || break

      script=`find_networking_script`

      if [ $script != "error" ]; then
         exec_networking_script $script $action
         [ $? != 0 ] || break
      fi
      config_network_intfs $action; rc=$?
      break
   done
   return $rc
}
save_active_NIC_list()
{
   local intf_out
   >$activeList
   if [ -n "$ip_cmd" ]; then
      for nic in $($ip_cmd link show up | egrep '\bUP\b' | awk -F: '{print $2}'); do
         $ip_cmd link show ${nic%@*} | grep -iq 'link/ether' && echo ${nic%@*} >> $activeList
      done
   else
      for nic in $($ifconfig_cmd | sed -n 's/^\([^: \t]*\).*$/\1/p'); do
         intf_out=$($ifconfig_cmd $nic)
         echo $intf_out | grep -iq loopback && continue
         echo $intf_out | egrep -q '\bUP\b' && echo $nic >> $activeList
      done
   fi
}
rescue_NIC()
{
   local rc=0
   local intf_out
   if [ -f "$activeList" ]; then
      while read nic; do
         if [ -n "$ip_cmd" ]; then
            intf_out=$($ip_cmd link show $nic up)
         else
            intf_out=$($ifconfig_cmd $nic)
         fi

         if echo $intf_out | grep -q 'UP'; then
            log "[rescue_nic] $nic is already active."
         else
            log "[rescue_nic] activating $nic ..."
            intf_ops "$ifup_cmd" up $nic
            rc=$(expr $rc \| $?)
         fi
      done < $activeList

      rm -f $activeList
   fi
   return $rc
}
TranquilizeNetworkManager()
{
   dbusSend=`which dbus-send 2>/dev/null`
   rc=$?
   if [ $rc -ne 0 ]; then
      return $rc
   fi
   nm_state=`$dbusSend --system --print-reply		\
             --dest=org.freedesktop.NetworkManager	\
             /org/freedesktop/NetworkManager		\
             org.freedesktop.DBus.Properties.Get	\
             string:'org.freedesktop.NetworkManager'	\
             string:'State'				\
             | awk '/variant/ {print $3;}'`
   if [ -z "$nm_state" ]; then
      return 1
   fi
   case $nm_state in
      1|4|10|20)
         # Nothing needs to be done.
         return 0
         ;;
   esac
   $dbusSend --system --print-reply          \
      --dest=org.freedesktop.NetworkManager  \
      /org/freedesktop/NetworkManager        \
      org.freedesktop.NetworkManager.Sleep boolean:true
   rc=$?
   if [ $rc -eq 0 ]; then
      return $rc
   fi
   # NetworkManager 0.9.0
   $dbusSend --system --print-reply          \
      --dest=org.freedesktop.NetworkManager  \
      /org/freedesktop/NetworkManager        \
      org.freedesktop.NetworkManager.Enable boolean:false
   rc=$?
   if [ $rc -eq 0 ]; then
      return $rc
   fi
   # NetworkManager 0.6
   $dbusSend --system --print-reply          \
      --dest=org.freedesktop.NetworkManager  \
      /org/freedesktop/NetworkManager        \
      org.freedesktop.NetworkManager.sleep
   rc=$?

   return $rc
}
WakeNetworkManager()
{
   dbusSend=`which dbus-send 2>/dev/null`
   rc=$?
   if [ $rc = 0 ]; then
      $dbusSend --system --print-reply          \
         --dest=org.freedesktop.NetworkManager  \
         /org/freedesktop/NetworkManager        \
         org.freedesktop.NetworkManager.Sleep boolean:false
      rc=$?
      if [ $rc = 0 ]; then
         return $rc
      fi
      # NetworkManager 0.9.0
      $dbusSend --system --print-reply          \
         --dest=org.freedesktop.NetworkManager  \
         /org/freedesktop/NetworkManager        \
         org.freedesktop.NetworkManager.Enable boolean:true
      rc=$?
      if [ $rc = 0 ]; then
         return $rc
      fi
      # NetworkManager 0.6
      $dbusSend --system --print-reply          \
         --dest=org.freedesktop.NetworkManager  \
         /org/freedesktop/NetworkManager        \
         org.freedesktop.NetworkManager.wake
      rc=$?
   fi
   return $rc
}
confidence_check()
{
   ip_cmd=$(which ip 2>/dev/null)
   ifconfig_cmd=$(which ifconfig 2>/dev/null)
   ifup_cmd=$(which ifup 2>/dev/null)
   ifdown_cmd=$(which ifdown 2>/dev/null)

   [ -z "$ifconfig_cmd" -a -z "$ip_cmd" ] && \
       Panic "ip and ifconfig not in search path."
}
main() {
   exitCode=0
   activeList=/var/run/vmware-active-nics
   case "$1" in
      poweron-vm)
         rm -f $activeList
         ;;
      suspend-vm)
         TranquilizeNetworkManager
         exitCode=$?
         if [ $exitCode != 0 ]; then
            confidence_check suspend-vm
            save_active_NIC_list
            run_network_script stop
            exitCode=$?
         fi
         ;;
      resume-vm)
         WakeNetworkManager
         exitCode=$?
         if [ $exitCode != 0 ]; then
            confidence_check resume-vm
            if [ ! -s $activeList ]; then
               save_active_NIC_list
            fi
            run_network_script start
            rescue_NIC
            exitCode=$?
         fi
         ;;
      *)
         log "No argument supplied."
         ;;
   esac

   return $exitCode
}
main "$@"
log "Finished '$0 $*'"
