-- /qompassai/Diver/lua/types/options.lua
-- Qompass AI Diver Lazy Types
-- Copyright (C) 2025 Qompass AI, All rights reserved
------------------------------------------------------
---@meta

---@class LazyPluginSpec
---@field [1] string?
---@field name string?
---@field dir string?
---@field url string?
---@field dev boolean?
---@field lazy boolean?
---@field enabled boolean? | fun():boolean
---@field cond boolean? | fun():boolean
---@field dependencies string[] | LazyPluginSpec[]
---@field init fun(LazyPlugin)?
---@field opts table? | fun(LazyPlugin):table?
---@field config fun(LazyPlugin, opts:table)? | boolean
---@field main string?
---@field build string? | fun(LazyPlugin)
---@field branch string?
---@field event string? | string[]
---@field cmd string? | string[]
---@field ft string? | string[]
---@field keys string? | string[]
---@field priority number?
