# /qompassai/dotfiles/.config/fcitx5/notifications.conf
# Qompass AI Fcitx5 Notifications Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
HiddenNotifications=
