; /qompassai/dotfiles/.config/pgbouncer/pgbouncer.ini
; Qompass AI PGBouncer Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[pgbouncer]
logfile = /var/log/pgbouncer/pgbouncer.log
pidfile = /run/pgbouncer/pgbouncer.pid
listen_addr = 127.0.0.1
listen_port = 6432
unix_socket_dir = /run/postgresql
unix_socket_mode = 0777
auth_type = trust
auth_file = "$(pass show pgb/af)"
admin_users = postgres
stats_users = stats, postgres
max_client_conn = 100
default_pool_size = 20
[databases]
foodb =/run/user/1000/pgbouncer
bardb = host=localhost dbname=bazdb
forcedb = host=127.0.0.1 port=300 user=baz password=foo client_encoding=UNICODE datestyle=ISO connect_query='SELECT 1'
nondefaultdb = pool_size=50 reserve_pool=10
* = host=testserver
