# /qompassai/dotfiles/.config/bluetooth/mesh-main.conf
# Qompass AI Bluetooth Mesh-Main Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[General]
#Beacon = true
#Relay = true
#Friendship = true
#CRPL = 100
#FriendQueueSize = 32
#ProvTimeout = 60
