schema_version = "1.0.0"
id = "render_profiler"
version = "0.9.4"
name = "Render Profiler"
tagline = "Profile and analyze Blender render/viewport performance"
maintainer = "crantisz@gmail.com"
type = "add-on"

website = "https://multlabs.com"

tags = ["Render", "System"]

blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later",
]


[build]
paths_exclude_pattern = [
  "/.git/",
  "__pycache__/",
  ".gitignore"
]
