# /qompassai/dotfiles/.config/neard/main.conf
# Qompass AI Neard Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
# References: https://wiki.archlinux.org/title/NFC | https://github.com/linux-nfc/neard
[General]
AutoActivate = true
AllowRemoteDevices = true
ConstantPoll = true
DeviceBlacklist = "deviceid1, deviceid2"
DefaultPowered = true
ResetOnError = true
LogLevel = debug
SupportedProtocols = NFC-A,NFC-B,NFC-F
Timeout = 5000
