-- /qompassai/dotfiles./config/lsp/init.lua
-- Qompass AI Diver LSP Init Spec
-- Copyright (C) 2025 Qompass AI, All rights reserved
-- --------------------------------------------------
--https://microsoft.github.io/language-server-protocol/implementors/servers/
vim.filetype.add({
  extension = {
    bri = 'brioche',
    brioche = 'brioche',
    cairo = 'cairo',
    clar = 'clar',
    clarity = 'clarity',
    comp = 'glsl',
    cr = 'crystal',
    cypher = 'cypher',
    frag = 'glsl',
    geom = 'glsl',
    hbs = 'html.handlebars',
    handlebars = 'html.handlebars',
    rst = 'rst',
    schelp = 'scdoc',
    tesc = 'glsl',
    tese = 'glsl',
    tsx = 'typescript.tsx',
  },
  filename = {
    ['project.bri'] = 'brioche',
    brioche = 'brioche',
    Cairo = 'cairo',
    Crystal = 'crystal',
  },
  pattern = {
    ['.*%.als'] = 'alloy',
    ['.*%.cairo'] = 'cairo',
    ['.*%.clar'] = 'clar',
    ['.*%.clarity'] = 'clarity',
    ['.*%.crystal'] = 'crystal',
    ['.*/gitconfig.*'] = 'gitconfig',
    ['.*/gitignore.*'] = 'gitignore',
    ['.*/gitcommit.*'] = 'gitcommit',
    ['.*/templates/.*%.yaml'] = 'helm',
    ['.*/templates/.*%.yml'] = 'helm',
    ['.*/templates/.*%.tpl'] = 'helm',
    ['.*/values.*%.ya?ml'] = 'yaml.helm-values',
    ['.*%.gts'] = 'typescript.glimmer',
    ['.*%.gjs'] = 'javascript.glimmer',
  },
})
vim.lsp.enable({
  'ada_ls',
  --'agda_ls',
  --'ai_ls',
  --'aiken_ls',
  --'air_ls',
  --'alloy_ls',
  --'angular_ls',
  --'ansible_ls',
  --'antlers_ls',
  --'apex_ls',
  --'arduino_ls',
  'asm_ls',
  --'astgrep_ls',
  --'astro_ls',
  --'atlas_ls',
  --'atopile_ls',
  --'autohotkey_ls',
  'autotoo_ls',
  --'awk_ls',
  --'azurepipelines_ls',
  'bacon_ls',
  'basedpy_ls',
  'bash_ls',
  --'basics_ls', --updated last year
  --'bazelrc_ls',
  --'beancount_ls',
  --'bicep_ls',
  --'biome_ls',
  --'bitbake_ls',
  --'blueprint_ls',
  --'bq_ls',
  --'brioche_ls',
  --'bsc_ls',
  'buck2_ls',
  --'buddy_ls', --not-using
  --'buf',
  'buf_ls',
  --'bzl_ls', deprecated
  --'c3_ls',
  'cairo_ls',
  --'cc_ls',
  --'cds_ls',
  --'checkmake_ls',
  --'circom_ls', --last git in 2023
  'clangd_ls',
  'clarinet_ls',
  --'clojure_ls',
  'cmake_ls',
  'cobol_ls',
  --'codebook_ls',
  --'coffeesense_ls', -- two years since last git
  --'contextive_ls',
  --'copilot_ls.lua',
  --'coq_ls',
  'crystalline_ls',
  'csharp_ls',
  --'cspell_ls', ---lsp/linter
  --'css_ls', --last update 1 year ago
  --'cucumber_ls' --testing
  --'dagger_ls' -- deprecated
  --'deno_ls', ---lsp/linter
  --'diagnostic_ls', -2years since last commit
  --'dj_ls',
  --'djt_ls',
  'docker_ls',
  'dockercompose_ls',
  --'dolmen_ls',
  --'dot_ls',
  --'dotenvlint_ls',
  --'dprint_ls',
  --'dspinyin_ls' --deprecated
  --'dts_ls',
  --'editorcc_ls', ---lsp/linter
  --'efm_ls', --last release Nov 2024
  --'elixir_ls',
  --'elm_ls',
  --'elp_ls',
  --'ember_ls',
  --'emmet_ls',
  -- 'emmylua_ls',
  --'erg_ls', --not using
  'esbonio_ls',
  --'eslint_ls', --using biome instead, last updated 1 year ago.
  --'expert_ls',
  --'facility_ls',
  --'fennel_ls',
  'fish_ls',
  'flow_ls',
  'flux_ls',
  --'foam_ls',
  --'fort_ls',
  --'fsautocomplete_ls',
  --'fsharp_ls', --no longer maintained
  --'fstar_ls',
  --'gdscript_ls',
  --'gdshader_ls',
  'ghactions_ls',
  --'ghcide_ls',
  --'ghdl_ls', --last activity one year ago.
  --'ginko_ls', last touched 1 year ago
  --'gitlabci_ls',
  --'glasgow_ls',
  --'gleam_ls',
  --'glint_ls',
  'glslana_ls',
  'golangcilint_ls',
  --'gn_ls',
  'gop_ls',
  --'gradle_ls',
  --'graphql_ls',
  --'groovy_ls',
  --'guile_ls',
  --'h_ls',
  'harper_ls',
  --'haxe_ls',
  --'hdlcheck_ls',
  'helm_ls',
  --'herb_ls',
  --'hie_ls', --deprecated
  --'hlasm',
  'hoon_ls',
  --'html_ls',
  'htmx_ls',
  --'hydra_ls',
  'hypr_ls',
  'intelephense_ls',
  --'java_ls',
  --'jdt_ls',
  'jinja_ls',
  'jq_ls',
  'json_ls',
  --'jsonnet_ls',
  --'julia_ls',
  --'just_ls',
  --'kotlin_ls',
  'laravel_ls',
  --'lean_ls',
  'lemminx_ls',
  --'lexical_ls', deprecated
  --'ltex_ls',
  'ltexplus_ls',
  'lua_ls',
  'luau_ls',
  --'lwc_ls',
  --'m68k_ls',
  --'makelint_ls',
  'markojs_ls',
  'marksman_ls',
  'matlab_ls',
  'mdxana_ls',
  --'meson_ls', deprecated
  'metals_ls',
  'millet_ls',
  'mint_ls',
  'mlir_ls',
  'mlirpdll_ls',
  --'mm0_ls',
  --'moveana_ls', --deprecated
  --'msbuildptoo_ls',
  'muon_ls',
  'mutt_ls',
  --'nelua_ls',
  'neocmake_ls',
  --'nextflow_ls',
  'next_ls',
  'nginx_ls',
  'nginxcf_ls',
  --'nickel_ls',
  'nil_ls',
  'nixd_ls',
  --'nomad_ls',
  'ntt_ls',
  'nu_ls',
  --'nx_ls',
  'ocaml_ls',
  'o_ls',
  --'omnisharp_ls',
  'opencl_ls',
  'openscad_ls',
  'oxlint_ls', ---lsp/linter
  --'pas_ls',
  'pb_ls',
  'perl_ls',
  'perlnav_ls',
  'perlp_ls',
  'phan_ls',
  'phpactor_ls',
  --'pico8_ls',
  --'please_ls',
  --'pli_ls',
  'postgres_ls',
  --'pwrshelles_ls',
  'prisma_ls',
  --'prosemd_ls',
  'proto_ls',
  --'psalm_ls', ---lsp/linter
  'pug_ls',
  'puppetes_ls',
  'puppet_ls',
  --'py_ls',
  --'pylyzer_ls',
  --'pyre', -- deprecated for pyrefly
  'pyrefly_ls', ---lsp/linter
  'qml_ls',
  'quicklintjs_ls',
  --'r_ls',
  --'reason_ls', --deprecated for rescript_ls/ocaml_ls
  'regal_ls', --linter/lsp
  'rego_ls',
  'remark_ls',
  'rescript_ls',
  ---'rnix_ls',| no longer maintained
  'robotcode_ls',
  'robotframework_ls',
  'roslyn_ls',
  'rpmspec_ls',
  'rubocop_ls', ---lsp/linter
  'ruby_ls',
  'ruff_ls',
  'rune_ls',
  'rustana_ls',
  --'salt_ls',
  --scheme_ls --not using
  --'scry_ls', --deprecated for crystalline
  --'selene_ls',
  --'selene3p_ls',
  'served_ls',
  --'sixtyfps_ls', --replaced with slint
  'slangd_ls', ---lsp/linter
  'slint_ls',
  --smarty_ls, --3 years old
  'smithy_ls',
  'snakeskin_ls',
  'solang_ls',
  'solargraph_ls',
  'solc_ls',
  'solidity_ls',
  'solidnomic_ls',
  'somesass_ls',
  'sorbet_ls',
  --'sourcekit_ls',
  --'spectral_ls', --last update was 1-3 years ago
  --'spyglass_ls', deprecated
  --'sqlls' --2 years old
  'sq_ls',
  'sqruff_ls',
  'standardrb_ls',
  'starlark_ls',
  'starp_ls',
  'statix_ls',
  'steep_ls',
  'stimulus_ls',
  --'stylelint_ls', last release 1 year ago
  --'stylua_ls',
  --'stylua3p_ls',
  'superhtml_ls',
  'svelte_ls',
  'svlant_ls',
  'sv_ls',
  'syntaxtree_ls',
  'systemd_ls',
  'tailwindcss_ls',
  'taplo_ls',
  --'tblgen_ls',
  --'teal_ls',
  'templ_ls',
  'termux_ls',
  --'terraform_ls', --last release in 2021
  'texlab_ls',
  --'text_ls',
  'tflint_ls',
  'tofu_ls',
  'tombi_ls', ---lsp/linter
  --'tsgo_ls',
  'ts_ls',
  'tsquery_ls',
  'tsp_ls',
  'ttags_ls',
  --'turbo_ls',
  --'turtle_ls',
  --'tvmffinav_ls',
  'twiggy_ls',
  'ty_ls',
  'typeprof_ls',
  'typst_ls',
  'viva_ls',
  --'ungrammar_ls',
  --'unison_ls',
  --'unocss_ls',
  ---'uv_ls', --doesn't compile
  'vala_ls',
  'vacuum_ls',
  --'vectorcode_ls',
  'verible_ls',
  'veridian_ls',
  'veryl_ls',
  --'v_ls',
  'rocq_ls',
  'vim_ls',
  'vts_ls',
  'vue_ls',
  'wasmlangtoo_ls',
  'wgslana_ls',
  'yaml_ls',
  --'y_ls',
  'ziggy_ls',
  'ziggy_schema_ls',
  --'zk_ls',
  'z_ls',
})
--'bsl_ls', --not using