-- /qompassai/Diver/lsp/ts_ls.lua
-- Qompass AI Typescript LSP Config
-- Copyright (C) 2025 Qompass AI, All rights reserved
-----------------------------------------------------

vim.lsp.config['ts_ls'] = {
  default_config = {
    cmd = {
      'typescript-language-server',
      '--stdio',
    },
    filetypes = {
      'javascript',
      'javascript.jsx',
      'javascriptreact',
      'typescript',
      'typescript.tsx',
      'typescriptreact',
    },
    init_options = {
      hostInfo = 'neovim',
      preferences = {
        includeCompletionsForModuleExports = true,
        includeCompletionsWithClassMemberSnippets = true,
        includeCompletionsWithInsertText = true,
        includeCompletionsWithSnippetText = true,
        includeInlayParameterNameHints = 'all',
        includeInlayParameterNameHintsWhenArgumentMatchesName = false,
        includeInlayFunctionParameterTypeHints = true,
        includeInlayVariableTypeHints = true,
        includeInlayVariableTypeHintsWhenTypeMatchesName = false,
        includeInlayEnumMemberValueHints = true,
        includeInlayFunctionLikeReturnTypeHints = true,
        includeInlayPropertyDeclarationTypeHints = true,
      },
      tsserver = {
        log = 'verbose',
      },
    },
    root_markers = {
      '.git',
      'jsconfig.json',
      'package.json',
      'tsconfig.json',
    },
    settings = {
      completions = {
        completeFunctionCalls = true,
      },
      diagnostics = {
        enable = true,
      },
      format = {
        enable = true,
        insertSpaceAfterCommaDelimiter = true,
        insertSpaceAfterFunctionKeywordForAnonymousFunctions = true,
        insertSpaceAfterKeywordsInControlFlowStatements = true,
        insertSpaceAfterOpeningAndBeforeClosingEmptyBraces = false,
        insertSpaceAfterOpeningAndBeforeClosingJsxExpressionBraces = false,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyBraces = true,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyBrackets = true,
        insertSpaceAfterOpeningAndBeforeClosingNonemptyParenthesis = true,
        insertSpaceAfterSemicolonInForStatements = true,
        insertSpaceBeforeAndAfterBinaryOperators = true,
        placeOpenBraceOnNewLineForControlBlocks = false,
        placeOpenBraceOnNewLineForFunctions = false,
      },
      inlayHints = {
        includeInlayEnumMemberValueHints = true,
        includeInlayFunctionLikeReturnTypeHints = true,
        includeInlayFunctionParameterTypeHints = true,
        includeInlayParameterNameHints = 'all',
        includeInlayParameterNameHintsWhenArgumentMatchesName = false,
        includeInlayPropertyDeclarationTypeHints = true,
        includeInlayVariableTypeHints = true,
        includeInlayVariableTypeHintsWhenTypeMatchesName = false,
      },
    },
  },
  codeActionProvider = {
    codeActionKinds = {
      '',
      'quickfix',
      'refactor',
      'refactor.extract',
      'refactor.inline',
      'refactor.rewrite',
      'source',
      'source.organizeImports',
      'source.fixAll',
    },
    resolveProvider = true,
  },
  colorProvider = true,
  completionProvider = {
    resolveProvider = true,
    triggerCharacters = {
      '.',
      '"',
      "'",
      '`',
      '/',
      '@',
      '<',
      '#',
    },
  },
  definitionProvider = true,
  declarationProvider = true,
  documentFormattingProvider = true,
  documentHighlightProvider = true,
  documentRangeFormattingProvider = true,
  documentSymbolProvider = true,
  hoverProvider = true,
  implementationProvider = true,
  referencesProvider = true,
  renameProvider = true,
  semanticTokensProvider = {
    full = true,
    legend = {
      tokenModifiers = {
        'abstract',
        'async',
        'declaration',
        'defaultLibrary',
        'definition',
        'deprecated',
        'documentation',
        'global',
        'modification',
        'readonly',
        'static',
      },
      tokenTypes = {
        'class',
        'comment',
        'decorator',
        'enum',
        'enumMember',
        'event',
        'function',
        'interface',
        'keyword',
        'macro',
        'method',
        'modifier',
        'namespace',
        'number',
        'operator',
        'parameter',
        'property',
        'regexp',
        'string',
        'struct',
        'type',
        'typeParameter',
        'variable',
      },
    },
    range = true,
  },
  signatureHelpProvider = {
    triggerCharacters = {
      '(',
      ',',
      '<',
    },
  },
  workspaceSymbolProvider = true,
}