-- /qompassai/dotfiles/.config/luacheck/.luacheckrc
-- Qompass AI Diver Luacheck Config
-- Copyright (C) 2025 Qompass AI, All rights reserved
-- --------------------------------------------------
return {
    std = 'luajit',
    read_globals = {
        'Core',
        'Constraint',
        'EventInterest',
        'Log',
        'Plugin',
        'Settings',
        'SimpleEventHook',
        'after_each',
        'arg',
        'assert',
        'before_each',
        'describe',
        'it',
        'jit',
        'm',
        'mock',
        'package',
        'require',
        'spy',
        'use',
        'vim',
        cache = {},
    },
    stds = {
        pandoc = {
            read_globals = {
                'FORMAT',
                'PANDOC_API_VERSION',
                'PANDOC_READER_OPTIONS',
                'PANDOC_SCRIPT_FILE',
                'PANDOC_STATE',
                'PANDOC_VERSION',
                'PANDOC_WRITER_OPTIONS',
                'lpeg',
                'pandoc',
                're',
            },
            globals = {
                'BlockQuote',
                'Blocks',
                'BulletList',
                'Cite',
                'Code',
                'CodeBlock',
                'DefinitionList',
                'Div',
                'Emph',
                'Figure',
                'Header',
                'HorizontalRule',
                'Image',
                'Inlines',
                'LineBlock',
                'LineBreak',
                'Link',
                'Math',
                'Meta',
                'Note',
                'OrderedList',
                'Pandoc',
                'Para',
                'Plain',
                'Quote',
                'RawBlock',
                'RawInline',
                'SmallCaps',
                'SoftBreak',
                'Space',
                'Span',
                'Strikeout',
                'Strong',
                'Subscript',
                'Superscript',
                'Table',
                'Traverse',
                'Underline',
                'traverse',
            },
        },
    },
    globals = {
        '_',
        'after_each',
        'arg',
        'assert',
        'before_each',
        'describe',
        'it',
        'jit',
        'm',
        'mock',
        'package',
        'require',
        'spy',
        'use',
        'vim',
    },
    unused_args = true,
    redefined = true,
    ignore = {
        '113',
        '121',
        '122',
        '211',
        '212/_.*',
        '214',
        '431',
        '542',
        '581',
        '631',
    },
    max_line_length = 150,
    files = {
        ['**/.luacheckrc'] = {
            std = '+luacheckrc',
        },
        ['**/*.rockspec'] = {
            std = '+rockspec',
        },
        ['**/spec/**/*_spec.lua'] = {
            std = '+busted',
        },
        ['**/test/**/*_spec.lua'] = {
            std = '+busted',
        },
        ['**/tests/**/*_spec.lua'] = {
            std = '+busted',
        },
        ['spec/**/*.lua'] = {
            globals = {
                'assert',
                'after_each',
                'before_each',
                'describe',
                'it',
            },
        },
    },
}

