# /qompassai/dotfiles/.config/clustershell/groups.conf.d/genders.conf
# Qompass AI Clustershell Groups.d Genders Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[genders]
map: nodeattr -n $GROUP
all: nodeattr -n ALL
list: nodeattr -l
