# /qompassai/dotfiles/.config/clustershell/groups.conf.d/slurm.conf
# Qompass AI Clustershell Groups.d Slurm Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[slurmpart,sp]
map: sinfo -h -o "%N" -p $GROUP
all: sinfo -h -o "%N"
list: sinfo -h -o "%R"
reverse: sinfo -h -N -o "%R" -n $NODE
[slurmresv,sr]
map: scontrol -o show reservation $GROUP | grep -Po 'Nodes=\K[^ ]+'
all: scontrol -o show reservation | grep -Po 'Nodes=\K[^ ]+'
list: scontrol -o show reservation | grep -Po 'ReservationName=\K[^ ]+'
cache_time: 60
[slurmstate,st]
map: sinfo -h -o "%N" -t $GROUP
all: sinfo -h -o "%N"
list: sinfo -h -o "%T" | tr -d '*~#!%$@+^-'
reverse: sinfo -h -N -o "%T" -n $NODE | tr -d '*~#!%$@+^-'
cache_time: 60
[slurmjob,sj]
map: squeue -h -j $GROUP -o "%N"
list: squeue -h -o "%i" -t R
reverse: squeue -h -w $NODE -o "%i"
cache_time: 60
[slurmuser,su]
map: squeue -h -u $GROUP -o "%N" -t R
list: squeue -h -o "%u" -t R
reverse: squeue -h -w $NODE -o "%u"
cache_time: 60
[slurmaccount,sa]
map: squeue -h -A $GROUP -o "%N" -t R
list: squeue -h -o "%a" -t R
reverse: squeue -h -w $NODE -o "%a" 2>/dev/null || true
cache_time: 60
[slurmqos,sq]
map: squeue -h -q $GROUP -o "%N" -t R
list: squeue -h -o "%q" -t R
reverse: squeue -h -w $NODE -o "%q" 2>/dev/null || true
cache_time: 60
