# /qompassai/dotfiles/.config/gss/mech.d/gssntlmssp.conf
# Qompass AI GSS Mech.d GSSNTL MSSP Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#######################################################
gssntlmssp_v1		1.3.6.1.4.1.311.2.2.10	        /usr/lib/gssntlmssp/gssntlmssp.so
