# /qompassai/dotfiles/.config/gss/mech.d/proxymech.conf
# Qompass AI GSS Mech.d ProxyMech Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#######################################################
gssproxy_v1		2.16.840.1.113730.3.8.15.1	/usr/lib/gssproxy/proxymech.so		<interposer>
