# /qompassai/dotfiles/.config/niriswitcher/config.toml
# Qompass AI NiriSwitcher Config
# Copyright (C) 2025 Qompass AI, All rights reserved
# ###################################################
# References: https://github.com/isaksamsten/niriswitcher | https://aur.archlinux.org/packages/niriswitcher | https://github.com/YaLTeR/niri
center_on_focus = false
current_output_only = false
double_click_to_hide = false
separate_workspaces = true
log_level = "INFO"

[appearance]
icon_size = 128
max_width = 800
min_width = 600
system_theme = "dark"
workspace_format = "{output}-{idx}"

[appearance.animation.reveal]
hide_duration = 200
show_duration = 200
easing = "ease-out-cubic"

[appearance.animation.resize]
duration = 200
easing = "ease-in-out-cubic"

[appearance.animation.workspace]
duration = 200
transition = "slide"

[appearance.animation.switch]
duration = 200
easing = "ease-out-cubic"

[workspace]
mru_sort_in_workspace = false
mru_sort_across_workspace = true

[keys]
modifier = "Alt_L"

[keys.switch]
next = "Tab"
prev = "Shift+Tab"

[keys.window]
close = "q"
abort = "Escape"

[keys.workspace]
next = "grave"
prev = "Shift+asciitilde"
