# /qompassai/dotfiles/.config/containers/mounts.conf
# Qompass AI Containers Mounts Config
# Copyright (C) 2025 Qompass AI, All rights reserved
########################################################
/home/phaedrus/.projects/common-data:/opt/common-data
/home/phaedrus/.ssh:/mnt/ssh
/home/phaedrus/.local/bin:/usr/local/bin
