# /qompassai/dotfiles/.config/containers/registries.conf
# Qompass AI Container Registries Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#######################################################
registries = [
  "artifactregistry.googleapis.com",
  "asia.gcr.io",
  "aws_account_id.dkr.ecr.us-west-2.amazonaws.com",
  "distribution.qompass.ai",
  "docker.io",
  "eu.gcr.io",
  "gcr.io",
  "ghcr.io",
  "gitlab.com",
  "harbor.qompass.ai",
  "mcr.microsoft.com",
  "nexus.mycompany.com",
  "public.ecr.aws",
  "quay.io",
  "registry.access.redhat.com",
  "registry.fedoraproject.org",
  "registry.gitlab.com",
  "registry.opensuse.org",
  "us.gcr.io",
]
