# /qompassai/dotfiles/.config/containers/storage.conf
# Qompass AI Containers Storage Config
# Copyright (C) 2025 Qompass AI, All rights reserved
########################################################
[storage]
driver = "overlay"
runroot = "$XDG_RUNTIME_DIR/containers"
driver_priority = ["overlay", "btrfs"]
graphroot = "$HOME/.local/share/containers/storage"
 imagestore = ""
rootless_storage_path = "$HOME/.local/share/containers/storage"
transient_store = true
[storage.options]
additionalimagestores = []
[storage.options.pull_options]
enable_partial_images = "false"
use_hard_links = "false"
ostree_repos=""
convert_images = "false"
insecure_allow_unpredictable_image_contents = "false"
root-auto-userns-user = "storage"
auto-userns-min-size=1024
auto-userns-max-size=65536
[storage.options.overlay]
ignore_chown_errors = "false"
inodes = ""
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev"
skip_mount_home = "false"
use_composefs = "false"
size = ""
force_mask = ""
