# /qompassai/dotfiles/.config/containers/storage.conf
# Qompass AI Containers Storage Config
# Copyright (C) 2025 Qompass AI, All rights reserved
########################################################
[storage]
driver = "overlay"
driver_priority = ["overlay", "btrfs"]
graphroot = "$XDG_DATA_HOME/containers/storage"
runroot = "$XDG_RUNTIME_DIR/containers"
imagestore = ""
rootless_storage_path = "$XDG_DATA_HOME/containers/storage"
transient_store = true
[storage.options]
additionalimagestores = []
[storage.options.pull_options]
auto-userns-min-size=1024
auto-userns-max-size=65536
enable_partial_images = "false"
use_hard_links = "false"
ostree_repos=""
convert_images = "false"
insecure_allow_unpredictable_image_contents = "false"
root-auto-userns-user = "storage"
[storage.options.overlay]
force_mask = ""
ignore_chown_errors = "false"
inodes = ""
mount_program = "/usr/bin/fuse-overlayfs"
mountopt = "nodev"
size = ""
skip_mount_home = "false"
use_composefs = "false"
