# config/xdg-desktop-portal/hyprland-portals.conf
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

[preferred]
default=hyprland

org.freedesktop.impl.portal.Screenshot=hyprland
org.freedesktop.impl.portal.ScreenCast=hyprland
org.freedesktop.impl.portal.RemoteDesktop=hyprland
org.freedesktop.impl.portal.FileChooser=gtk
org.freedesktop.impl.portal.Settings=gtk
org.freedesktop.impl.portal.Inhibit=gtk
org.freedesktop.impl.portal.Print=gtk
org.freedesktop.impl.portal.Notification=gtk
org.freedesktop.impl.portal.Trash=gtk
org.freedesktop.impl.portal.PowerProfile=gtk
