# /qompassai/dotfiles/.config/infiniband-diags/ibdiag.conf
# Qompass AI Infiniband-Diag Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
CA=mlx4_0
MLX_EPI=false
m_key=0x00
Port=1
sa_key=0x00
timeout=50
