PORT 25
ALIASES /etc/dma/aliases
SPOOLDIR /var/spool/dma
AUTHPATH /etc/dma/auth.conf
SECURETRANSFER
STARTTLS
#VERIFYCERT
#FINGERPRINT 1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF1234567890ABCDEF
#OPPORTUNISTIC_TLS
#CERTFILE
SECURE
#DEFER
#FULLBOUNCE
MAILNAME mail.qompass.ai
MASQUERADE john@  on host "hamlet" will send all mails as john@hamlet
MASQUERADE percolator  will send mails as $username@percolator, e.g. fish@percolator
MASQUERADE herb@ert  will send all mails as herb@ert
#NULLCLIENT
