# /qompassai/dofiles/.config/mkinitcpio-systemd-tool/mkinitcpio-systemd-tool.conf
# Qompass AI Mkinitcpio Systemd Tool Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
openssh_key_convert=true
