# /qompassai/dotfiles/.config/sshuttle/tunnel.conf
# Qompass AI Sshuttle Tunnel Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
Hostname "$(pass show shuttle/h)"
User "$(pass show shuttle/u)"
IdentityFile "$(pass show shuttle/if)"
