; /qompassai/dotfiles/.config/php84/conf.d/10-opcache.ini
; Qompass AI PHP 8.4 Conf.d Opcache Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
zend_extension=opcache.so
