; /qompassai/dotfiles/.config/php84/conf.d/20-curl.ini
; Qompass AI PHP 8.4 Conf.d Curl Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
extension=curl.so
