# /qompassai/rust/cargo/config.toml
# Qompass AI Cargo Config
# Copyright (C) 2025 Qompass AI, All rights reserved
## ##################################################
# Reference: https://doc.rust-lang.org/cargo/reference/config.html
[alias]
b = "build"
c = "check"
r = "run"
rr = "run --release"
t = "test"
zig-x86_64-r = "zigbuild --release --target x86_64-unknown-linux-gnu"
zig-aarch64-r = "zigbuild --release --target aarch64-unknown-linux-gnu"
zig-aarch64-t = "zigbuild test --target aarch64-unknown-linux-gnu"
zigrun-aarch64 = "zigbuild run --target aarch64-unknown-linux-gnu"

[build]
# dep-info-basedir = ""
jobs = 4
incremental = false
rustc = "rustc"
#rustc-wrapper = "sccache"
rustdoc = "rustdoc"
rustflags = ["-C", "target-cpu=native"]
target-dir = "target"

[cache]
auto-clean-frequency = "1 day"

[cargo-new]
vcs = "git"

[doc]
browser = "chromium"

[env]
CARGO_INCREMENTAL = "0"
#SCCACHE_DIR = "/home/phaedrus/.cache/sccache"
#SCCACHE_IDLE_TIMEOUT = "1200"
ZIG_GLOBAL_CACHE_DIR = "/home/phaedrus/.cache/zig"

[future-incompat-report]
frequency = "always"

[http]
debug = false
low-speed-limit = 10
multiplexing = true
timeout = 60
ssl-version.max = "tlsv1.3"
ssl-version.min = "tlsv1.2"

[install]
root = "/home/phaedrus/.local"

[net]
retry = 3
git-fetch-with-cli = true
offline = false

[patch.crates-io]
whisper-rs-sys = { git = "https://codeberg.org/tazz4843/whisper-rs", branch = "master" }

[registry]
default = "crates-io"
global-credential-providers = [
  "cargo:token",
  "cargo:libsecret",
  "cargo:macos-keychain",
  "cargo:wincred"
]

[registries.crates-io]
protocol = "sparse"

[resolver]
incompatible-rust-versions = "allow"

[target.aarch64-apple-darwin]
linker = "clang"
runner = "true"
rustflags = [
  "-Clink-arg=--target=aarch64-apple-darwin",
]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
runner = "env"
rustflags = [
  "-Ctarget-cpu=native",
  "-Clink-arg=-fuse-ld=lld",
]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
runner = "env"
rustflags = [
  "-Clink-arg=--target=aarch64-unknown-linux-gnu",
]

[target.x86_64-apple-darwin]
linker = "clang"
runner = "true"
rustflags = [
  "-Clink-arg=--target=x86_64-apple-darwin",
]

[target.nvptx64-nvidia-cuda]
linker = "ptx-linker"
runner = "env"
rustflags = [
  "-Ctarget-cpu=sm_89",
]

[target.x86_64-unknown-linux-musl]
linker = "clang"
rustflags = [
  "-Clink-arg=--target=x86_64-unknown-linux-musl",
  "-Ctarget-feature=-crt-static",
]

[target.x86_64-pc-windows-gnu]
linker = "clang"
runner = "wine64"
rustflags = [
  "-Clink-arg=--target=x86_64-windows-gnu",
]

[term]
color = "auto"
hyperlinks = true
progress.term-integration = true
progress.when = "auto"
progress.width = 80
unicode = true
verbose = true
quiet = false
