# /qompassai/dotfiles/.config/vpnc/default.conf
# Qompass AI VPNC Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
#Interface name tun0 
#IKE DH Group dh2
#Perfect Forward Secrecy nopfs

#Script /etc/vpnc/vpnc-script
# Enable this option for NAT traversal
UDP Encapsulate

#IPSec gateway my.gateway.com
#IPSec ID someid
#IPSec secret somesecret
#Xauth username myusername
#Xauth password mypassword
