# /qompassai/dotfiles/.config/xkbsel/xkbsel.conf
# Qompass AI XKBSelect Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[shortcut]
cs = cssk(cs)
cs_y = cssk(cs_qwerty)
sk = cssk(sk)
sk_y = cssk(sk_qwerty)
us = xfree86(us)

[mapset]
map[cs] = us cs sk_y sk
map[sk] = us sk_y sk cs
map = us sk sk_y cs cs_y

