# /qompassai/dotfiles/.config/upower/Upower.conf
# Qompass AI UPower Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
[UPower]
EnableWattsUpPro=false
NoPollBatteries=false
IgnoreLid=false
UsePercentageForPolicy=true
PercentageLow=20.0
PercentageCritical=5.0
PercentageAction=2.0
TimeLow=1200
TimeCritical=300
TimeAction=120
AllowRiskyCriticalPowerAction=false
CriticalPowerAction=HybridSleep
