# /qompassai/dotfiles/.config/pacredir/pacredir.conf
[general]
max threads = 0
#max threads = 32
#ignore interfaces = tap0
#ignore interfaces = tun0
#ignore interfaces = openvpn
#ignore interfaces = tap0 tun0 openvpn
#pacserve hosts = test1.domain
#pacserve hosts = test1.domain test2.domain
verbose = 1
