# /qompassai/dotfiles/.config/wazuh-indexer/opensearch-performance-analyzer/performance-analyzer.properties
# Qompass AI Wazuh-Indexer OpenSearch Performance Analyzer Properties Config
# Copyright (C) 2025 Qompass AI, All rights reserved
############################################################################################################
metrics-location = /dev/shm/performanceanalyzer/
metrics-deletion-interval = 1
cleanup-metrics-db-files = true
webservice-listener-port = 9600
rpc-port = 9650
metrics-db-file-prefix-path = /tmp/metricsdb_
https-enabled = false
certificate-file-path = specify_path
private-key-file-path = specify_path
#client-certificate-file-path = specify_path
#client-private-key-file-path = specify_path
#client-trusted-cas-file-path = specify_path
#webservice-bind-host =
plugin-stats-metadata = plugin-stats-metadata
agent-stats-metadata = agent-stats-metadata
