#~/.config/meson/cross/zig-x86_64-linux-musl.ini

[binaries]
c             = 'zig'
cpp           = 'zig'
ar            = 'zig'
strip         = 'zig'
pkgconfig     = 'pkg-config'
cmake         = 'cmake'
llvm-config   = 'llvm-config'

c_ld          = 'zig'
cpp_ld        = 'zig'

[host_machine]
system        = 'linux'
cpu_family    = 'x86_64'
cpu           = 'x86_64'
endian        = 'little'

[properties]
needs_exe_wrapper = true
sys_root      = ''
c_args        = ['-target', 'x86_64-linux-musl', '-Doptimize=ReleaseSafe']
cpp_args      = ['-target', 'x86_64-linux-musl', '-Doptimize=ReleaseSafe']
link_args     = ['-target', 'x86_64-linux-musl']
buildtype     = 'release'
default_library = 'static'
warning_level = 2
strip         = true
cpp_std       = 'c++20'
c_std         = 'gnu17'

[built-in options]
b_lto         = true
b_pie         = true
b_sanitize    = 'none'

