# /qompassai/dotfiles/.config/security/limits.d/10-gamemode.conf
# Qompass AI Security GameMode Limits Config
# Copyright (C) 2025 Qompass AI, All rights reserved
################################################################
@gamemode - nice -10
