# /qompassai/dotfiles/.config/security/limits.d/99-audio.conf
# Qompass AI Security Audio Limits Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#############################################################
@audio   -  rtprio    98
@audio   -  memlock   unlimited
@audio   -  nice     -19
