# /qompassai/dotfiles/.config/clamav/clamd.conf
# Qompass AI Clamd Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
DatabaseDirectory /home/phaedrus/.local/share/clamav
LocalSocket /run/user/1000/clamav/clamd.sock
LocalSocketMode 660
LogFile /home/phaedrus/.cache/clamav/clamd.log
LogTime yes
LogVerbose yes
User phaedrus
MaxThreads 4
ReadTimeout 300
