# /qompassai/dotfiles/.config/clamav/freshclam.conf
# Qompass AI Clamav Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################### 
DatabaseDirectory /home/phaedrus/.local/share/clamav
LocalSocket /run/user/1000/clamav/clamd.sock
LogTime yes
LogVerbose yes
UpdateLogFile /home/phaedrus/.cache/clamav/freshclam.log
DatabaseMirror database.clamav.net
Checks 4
DatabaseOwner phaedrus
