# /qompassai/dotfiles/.config/piprwire.conf.d/20-rnnoise.conf
# Qompass AI 20-RNNOise Pipewire Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###############################################################
context.modules = [
  { name = libpipewire-module-filter-chain
    args = {
      node.description = "RNNoise Mic"
      node.name        = "rnnoise_mic"
      media.class      = "Audio/Source"

      filter.graph = {
        nodes = [
          {
            type   = "ladspa"
            name   = "rnnoise"
            plugin = "/usr/lib/ladspa/librnnoise_ladspa.so"
            label  = "noise_suppressor_mono"
            control = {
              "VAD Threshold (%)"         = 80.0
              "VAD Grace Period (ms)"     = 200
              "Retroactive VAD Grace (ms)"= 0
            }
          }
        ]
      }
      capture.props = {
        node.name   = "capture.rnnoise_source"
        node.target = "echo_cancel_source"
      }
    }
    flags = [ ifexists ]
  }
]
