# /qompassai/dotfiles/.config/babeld/babeld.conf
# # Qompass AI Babeld Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
ipv6-subtrees true
interface eth0
#interface wlan0
debug 1
local-port 33123
diversity true
random-id true
interface eth1 rxcost 10
#interface tun0 faraway true
#interface wlan0 hello-interval 1
default rxcost 42
default hello-interval 5
default enable-timestamps true
interface tun0 max-rtt-penalty 150
interface tun0 rtt-max 100
#in ip 192.168.42.0/24 allow
#in ip 2001:db8:caffe:caffe::/64 allow
#redistribute ip 192.168.1.0/24 local allow
#redistribute ip 2001:db8:caffe:caffe::/64 local allow
#redistribute local deny
#redistribute proto 3 ip 0.0.0.0/0 eq 0 metric 50
#redistribute proto 3 ip ::/0 eq 0 metric 50
