# /qompassai/dotfiles/.config/dmd/dmd.conf
# Qompass AI DMD Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[Environment32]
DFLAGS=-I/usr/include/dlang/dmd -L-L/usr/lib32 -L--export-dynamic -fPIC
[Environment64]
DFLAGS=-I/usr/include/dlang/dmd -L-L/usr/lib -L--export-dynamic -fPIC
