# /qompassai/dotfiles/.config/signal/signal-desktop-flags.conf
# Qompass AI Signal Desktop Flags Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
--enable-features=WaylandWindowDecorations
--ozone-platform-hint=auto
