; /qompassai/dotfiles/.config/openni2/OpenNI.ini
; Qompass AI OpenNI2 Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[Device]
;Override=""
[Drivers]
Repository=OpenNI2/Drivers
[Log]
Verbosity=3
LogToConsole=0
LogToFile=0
