# /qompassai/dotfiles/.config/pipewire/client.conf.d/10-properties.conf
# Qompass AI PipeWire Client Properties Config
# Copyright (C) 2026 Qompass AI, All rights reserved
#   https://docs.pipewire.org/page_man_pipewire-client_conf_5.html
#   https://man.archlinux.org/man/extra/pipewire/pipewire-client.conf.5.en
#########################################################################
alsa.properties = {
    alsa.access                                         = [ MMAP_INTERLEAVED MMAP_NONINTERLEAVED RW_INTERLEAVED RW_NONINTERLEAVED ]
    alsa.buffer-bytes                                   = { min=256 max=4194304 }
    alsa.channels                                       = { min=1 max=64 }
    alsa.deny                                           = false
    alsa.format                                         = [ FLOAT S32 S24 S24_3 S16 U8 ]
    alsa.period-bytes                                   = { min=128 max=2097152 }
    alsa.rate                                           = { min=1 max=384000 }
    alsa.volume-method                                  = cubic
}
stream.properties = {
    channelmix.fc-cutoff                                = 12000
    channelmix.hilbert-taps                             = 0
    channelmix.lfe-cutoff                               = 150
    channelmix.mix-lfe                                  = true
    channelmix.normalize                                = false
    channelmix.rear-delay                               = 12.0
    channelmix.stereo-widen                             = 0.0
    channelmix.upmix                                    = true
    channelmix.upmix-method                             = psd
    dither.noise                                        = 0
    node.autoconnect                                    = true
    resample.quality                                    = 10
}

