# /qompassai/dotfiles/.config/wireguard/caffe.conf
# Qompass AI Wireguard Caffe Server Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

[Interface]
Address = 10.99.97.102, fd00:6361:6666:65::/64
ListenPort = 51820
MTU = 1400
FwMark = 0x512
PostUp = nft add rule inet filter forward iifname "%i" accept
PostDown = nft delete rule inet filter forward iifname "%i" accept
PrivateKey =
SaveConfig = true
#Table = off

[Peer]
# doppio
AllowedIPs = 10.100.111.112, fd00:db8::4/128
Endpoint = peer.example.com:51820
PersistentKeepalive = 25

[Peer]
# pensare
AllowedIPs = 10.112.101.110, fd00:db8::4/128
Endpoint = peer.example.com:51820
PersistentKeepalive = 25

[Peer]
# primo
AllowedIPs = 10.112.114.105, fd00:db8::/64
Endpoint = qompass.ai:51820
PersistentKeepalive = 25

[Peer]
# ristretto
AllowedIPs = 10.114.105.115, fd00:db8::4/128
Endpoint = ristretto.qompass.ai:51820
PersistentKeepalive = 25

