## /qompassai/dotfiles/.config/ant/ant.conf
# Qompass AI Ant Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
ANT_BUILD_FILE=build.xml
ANT_COLOR=true
ANT_HOME=/usr/share/ant
ANT_LIB=/usr/share/ant/lib
ANT_LOG_DIR=$HOME/.cache/ant_logs
ANT_OPTS="-Xmx2G -Xms256M -XX:+UseG1GC"
ANT_VERBOSE=true
JAVA_HOME=/usr/lib/jvm/default
LOCALCLASSPATH=${OPT_JAR_LIST}
OPT_JAR_LIST=/usr/share/java/junit.jar:/usr/share/java/hamcrest-core.jar
export ANT_BUILD_FILE
export ANT_COLOR
export ANT_HOME
export ANT_LIB
export ANT_LOG_DIR
export ANT_OPTS
export ANT_VERBOSE
export JAVA_HOME
export LOCALCLASSPATH
export OPT_JAR_LIST
# vim:ft=sh
