# /qompassai/dotfiles/.config/nfsmount/nfsmount.conf
# Qompass AI NFS Mount Config
# Copyright (C) 2025 Qompass AI, All rights reserved
##########################################
# [ MountPoint "Mount_point" ] 
#     [ MountPoint "/export/home" ]
#       background=True
#
# [ Server "Server_Name" ]
# Example:
#     [ Server "nfsserver.foo.com" ]
#       rsize=32k
#       wsize=32k
#
[ NFSMount_Global_Options ]
Defaultvers=4
Nfsvers=4
Defaultproto=tcp
Proto=tcp
Retrans=2
Retry=2
acregmin=30
acregmax=60
acdirmin=30
acdirmax=60
Acl=False
Ac=True
Background=False
Cto=True
Foreground=True
Hard=True
Soft=False
Lock=True
Rdirplus=True
Rsize=8k
Wsize=8k
Bsize=8k
Sloppy=False
Sharecache=True
Timeo=600
actimeo=30
mountport=4001
mountproto=tcp
mountvers=3
mounthost=hostname
Port=2049
Sec=sys
Intr=True
Lookupcache=all
noatime=True
