# /qompassai/dotfiles/.config/NetworkManager/conf.d/duid.conf
# Qompass AI NetworkManager DUID Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#############################################################
[connection]
ipv6.dhcp-duid=stable-uuid
