# /qompassai/dotfiles/.config/dnscrypt-proxy/dnscrypt-proxy.toml
# Qompass AI DNSCrypt-Proxy Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################################
server_names = ['scaleway-fr', 'google', 'yandex', 'cloudflare']
listen_addresses = ['127.0.0.1:53', '[::1]:53']
#listen_addresses = ['127.0.0.1:53']
max_clients = 250
# user_name = 'nobody'
ipv4_servers = true
ipv6_servers = true
dnscrypt_servers = true
doh_servers = true
odoh_servers = true
require_dnssec = true
require_nolog = true
require_nofilter = true
disabled_server_names = []
force_tcp = false
http3 = true
http3_probe = true
proxy = 'socks5://dnscrypt:dnscrypt@127.0.0.1:9050'
http_proxy = 'http://127.0.0.1:8888'
timeout = 10000
keepalive = 30
edns_client_subnet = ['0.0.0.0/0', '2001:db8::/32']
blocked_query_response = 'refused'
lb_strategy = 'wp2'
lb_estimator = true
enable_hot_reload = true
log_level = 4
log_file = '/var/log/dnscrypt-proxy/dnscrypt-proxy.log'
log_file_latest = true
use_syslog = true
log_files_max_size = 10
log_files_max_age = 7
log_files_max_backups = 1
cert_refresh_concurrency = 10
cert_refresh_delay = 240
cert_ignore_timestamp = false
dnscrypt_ephemeral_keys = false
tls_disable_session_tickets = false
## 49199 = TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
## 49195 = TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
## 52392 = TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
## 52393 = TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305
tls_cipher_suite = [52392, 49199]
tls_key_log_file = '/var/log/dnscrypt-proxy/keylog.txt'
bootstrap_resolvers = ['9.9.9.11:53', '8.8.8.8:53']
ignore_system_dns = true
netprobe_timeout = 60
netprobe_address = '9.9.9.9:53'
offline_mode = false
# query_meta = ['key1:value1', 'key2:value2', 'token:MySecretToken']
block_ipv6 = false
block_unqualified = true
block_undelegated = true
reject_ttl = 10
# forwarding_rules = '/etc/dnscrypt-proxy/forwarding-rules.txt'
# cloaking_rules = '/etc/dnscrypt-proxy/cloaking-rules.txt'
cloak_ttl = 600
cloak_ptr = false
cache = true
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_min_ttl = 60
cache_neg_max_ttl = 600
[captive_portals]
# map_file = '/etc/dnscrypt-proxy/captive-portals.txt'
[local_doh]
# listen_addresses = ['127.0.0.1:3000']
# path = '/dns-query'
## openssl req -x509 -nodes -newkey rsa:2048 -days 5000 -sha256 -keyout localhost.pem -out localhost.pem
# cert_file = "/var/lib/dnscrypt-proxy/localhost.pem"
# cert_key_file = "/var/lib/dnscrypt-proxy/localhost.pem"
[query_log]
## Can be set to /dev/stdout in order to log to the standard output.
# file = '/var/log/dnscrypt-proxy/query.log'
## Query log format (currently supported: tsv and ltsv)
format = 'tsv'
# ignored_qtypes = ['DNSKEY', 'NS']
[nx_log]
file = '/var/log/dnscrypt-proxy/nx.log'
format = 'tsv'
[blocked_names]
# blocked_names_file = '/etc/dnscrypt-proxy/blocked-names.txt'
# log_file = '/var/log/dnscrypt-proxy/blocked-names.log'
# log_format = 'tsv'
[blocked_ips]
# blocked_ips_file = '/etc/dnscrypt-proxy/blocked-ips.txt'
log_file = '/var/log/dnscrypt-proxy/blocked-ips.log'
# log_format = 'tsv'
[allowed_names]
# allowed_names_file = '/etc/dnscrypt-proxy/allowed-names.txt'
log_file = '/var/log/dnscrypt-proxy/allowed-names.log'
log_format = 'tsv'
[allowed_ips]
# allowed_ips_file = '/etc/dnscrypt-proxy/allowed-ips.txt'
log_file = '/var/log/dnscrypt-proxy/allowed-ips.log'
## Optional log format: tsv or ltsv (default: tsv)
log_format = 'tsv'
# {after='21:00', before= '7:00'} matches 0:00-7:00 and 21:00-0:00
# {after= '9:00', before='18:00'} matches 9:00-18:00
[schedules]
# [schedules.time-to-sleep]
#   mon = [{after='21:00', before='7:00'}]
#   tue = [{after='21:00', before='7:00'}]
#   wed = [{after='21:00', before='7:00'}]
#   thu = [{after='21:00', before='7:00'}]
#   fri = [{after='23:00', before='7:00'}]
#   sat = [{after='23:00', before='7:00'}]
#   sun = [{after='21:00', before='7:00'}]

# [schedules.work]
#   mon = [{after='9:00', before='18:00'}]
#   tue = [{after='9:00', before='18:00'}]
#   wed = [{after='9:00', before='18:00'}]
#   thu = [{after='9:00', before='18:00'}]
#   fri = [{after='9:00', before='17:00'}]
[sources]
[sources.public-resolvers]
urls = [
  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md',
  'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md',
]
cache_file = '/var/cache/dnscrypt-proxy/public-resolvers.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 73
prefix = ''
[sources.relays]
urls = [
  'https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md',
  'https://download.dnscrypt.info/resolvers-list/v3/relays.md',
]
cache_file = '/var/cache/dnscrypt-proxy/relays.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 73
prefix = ''

# [sources.odoh-servers]
   urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-servers.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-servers.md']
#   cache_file = '/var/cache/dnscrypt-proxy/odoh-servers.md'
#   minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#   refresh_delay = 73
#   prefix = ''
# [sources.odoh-relays]
#   urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/odoh-relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/odoh-relays.md']
#   cache_file = '/var/cache/dnscrypt-proxy/odoh-relays.md'
#   minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
#   refresh_delay = 73
#   prefix = ''

### Quad9

# [sources.quad9-resolvers]
#   urls = ['https://quad9.net/dnscrypt/quad9-resolvers.md', 'https://raw.githubusercontent.com/Quad9DNS/dnscrypt-settings/main/dnscrypt/quad9-resolvers.md']
#   minisign_key = 'RWQBphd2+f6eiAqBsvDZEBXBGHQBJfeG6G+wJPPKxCZMoEQYpmoysKUN'
#   cache_file = '/var/cache/dnscrypt-proxy/quad9-resolvers.md'
#   prefix = 'quad9-'

### Another example source, with resolvers censoring some websites not appropriate for children
### This is a subset of the `public-resolvers` list, so enabling both is useless.

# [sources.parental-control]
#   urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/parental-control.md', 'https://download.dnscrypt.info/resolvers-list/v3/parental-control.md']
#   cache_file = '/var/cache/dnscrypt-proxy/parental-control.md'
#   minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'

### dnscry.pt servers - See https://www.dnscry.pt

#  [sources.dnscry-pt-resolvers]
#    urls = ["https://www.dnscry.pt/resolvers.md"]
#    minisign_key = "RWQM31Nwkqh01x88SvrBL8djp1NH56Rb4mKLHz16K7qsXgEomnDv6ziQ"
#    cache_file = "/var/cache/dnscrypt-proxy/dnscry.pt-resolvers.md"
#    refresh_delay = 73
#    prefix = "dnscry.pt-"


[broken_implementations]
fragments_blocked = [
  'cisco',
  'cisco-ipv6',
  'cisco-familyshield',
  'cisco-familyshield-ipv6',
  'cisco-sandbox',
  'cleanbrowsing-adult',
  'cleanbrowsing-adult-ipv6',
  'cleanbrowsing-family',
  'cleanbrowsing-family-ipv6',
  'cleanbrowsing-security',
  'cleanbrowsing-security-ipv6',
]
[doh_client_x509_auth]
# creds = [
#    { server_name='*', client_cert='client.crt', client_key='client.key' }
# ]
[anonymized_dns]
# routes = [
#    { server_name='example-server-1', via=['anon-example-1', 'anon-example-2'] },
#    { server_name='example-server-2', via=['sdns://gRIxMzcuNzQuMjIzLjIzNDo0NDM'] }
# ]
skip_incompatible = true
direct_cert_fallback = true
[dns64]
# prefix = ['64:ff9b::/96']
# resolver = ['[2606:4700:4700::64]:53', '[2001:4860:4860::64]:53']
[monitoring_ui]
enabled = true
listen_address = "127.0.0.1:8080"
username = "$USER"
password = "$(pass show dnscrypt/p)"
tls_certificate = ""
tls_key = ""
enable_query_log = true
privacy_level = 2
max_query_log_entries = 100
max_memory_mb = 1
prometheus_enabled = false
prometheus_path = "/metrics"
[static]
# [static.myserver]
#   stamp = 'sdns://AQcAAAAAAAAAAAAQMi5kbnNjcnlwdC1jZXJ0Lg'
