# /qompassai/dotfiles/.config/nvidia-omniverse/config/omniverse.toml
# Qompass AI Nvidia-Omniverse Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
[paths]
confirmed = false
data_root = "$XDG_DATA_HOME/ov/data"
cache_root = "$XDG_CACHE_HOME/ov"
library_root = "$XDG_DATA_HOME/ov/pkg"
content_root = "$XDG_DOWNLOADS_DIR"
extension_root = "$XDG_DOCUMENTS_DIR/kit/shared/exts"
logs_root = "$HOME/.nvidia-omniverse/logs"
