# /qompassai/dofiles/.config/mkinitcpio-systemd-tool/config/ntp.conf
# Qompass AI Mkinitcpio Systemd Tool Initrd-util-usb-hcd Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
#References: https://github.com/random-archer/mkinitcpio-systemd-tool
/etc/modprobe.d/initrd-util-usb-hcd.conf
# /etc/mkinitcpio-systemd-tool/config/initrd-util-usb-hcd.conf
# required module load order: xhci-hcd ehci-hcd uhci-hcd ohci-hcd

softdep ehci-hcd pre: xhci-hcd
softdep uhci-hcd pre: ehci-hcd
softdep ohci-hcd pre: uhci-hcd
