#!/usr/bin/env bash
# /qompassai/dotfiles/.config/scripts/1_rec
# Qompass AI Video Record Script
# Copyright (C) 2026 Qompass AI, All rights reserved
# ----------------------------------------
record() {
  amixer set Capture toggle
  # Original command for my own screen: :0.0+1920,0 ensures only 2nd monitor is captured
  # -c:v sets codec, in this case, H.264; -qp 0 ensures lossless
  # ffmpeg -s 1920x1200 -f x11grab -r 30 -i :0.0+1920,0 -c:v h264 -qp 0 "$HOME/video_$(date '+%a__%b%d__%H_%M_%S').mkv" &
  ffmpeg -s "$(xdpyinfo | awk '/dimensions/{print $2}')" -f x11grab -r 30 -i :0.0 -c:v h264 -qp 0 "$HOME/video_$(date '+%a__%b%d__%H_%M_%S').mkv" &
  echo $! > /tmp/recpid
  ffmpeg -f alsa -i default -af "afftdn=nf=-75" "$HOME/audio_$(date '+%a__%b%d__%H_%M_%S').wav" &
  echo $! > /tmp/audpid
  echo "Rec •" > /tmp/recordingicon && pkill -RTMIN+3 dwmblocks
  notify-send -t 500 -h string:bgcolor:#a3be8c "Recording started & mic toggled"
  }
end() {
  kill -15 "$(cat /tmp/recpid)" "$(cat /tmp/audpid)" && rm -f /tmp/recpid /tmp/audpid
  amixer set Capture toggle
  echo "" > /tmp/recordingicon && pkill -RTMIN+3 dwmblocks
  notify-send -t 500 -h string:bgcolor:#bf616a "Recording ended & mic toggled"
  }
([[ -f /tmp/recpid ]] && end && exit 0) || record
