# /qompassai/dotfiles/.config/netdata/netdata.conf
# Qompass AI NetData Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
#  netdatacli dumpconfig > /etc/netdata/netdata.conf
#
#  wget -O /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
# or
#  curl -o /etc/netdata/netdata.conf http://localhost:19999/netdata.conf
#
