# /qompassai/dotfiles/.config/mosquitto/mostquitto.conf
# Qompass AI Mosquitto Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
per_listener_settings false
allow_zero_length_clientid true
auto_id_prefix auto-
check_retain_source true
max_inflight_bytes 0
max_inflight_messages 20
max_keepalive 65535
max_packet_size 0
max_queued_bytes 0
max_qos 2
max_queued_messages 1000
memory_limit 0
message_size_limit 0
persistent_client_expiration 2m
# persistent_client_expiration 14d
# persistent_client_expiration 1y
pid_file
queue_qos0_messages false
retain_available true
set_tcp_nodelay false
sys_interval 10
upgrade_outgoing_qos false
user mosquitto
listener 0 /tmp/mosquitto.sock
socket_domain
#bind_interface
#http_dir
max_connections -1
#mount_point
protocol mqtt
use_username_as_clientid
websockets_headers_size
#certfile
#keyfile
ciphers_tls1.3
crlfile
dhparamfile
require_certificate true
#cafile
#capath
#use_identity_as_username false
#psk_hint
#ciphers
#use_identity_as_username false
autosave_interval 1800
autosave_on_changes true
#persistence false
persistence_file mosquitto.db
#persistence_location
log_dest stderr
log_type information
connection_messages true
log_facility 5
log_timestamp true
log_timestamp_format %Y-%m-%dT%H:%M:%S
websockets_log_level 0
# For example, setting "secure-" here would mean a client "secure-
# client" could connect but another with clientid "mqtt" couldn't.
#clientid_prefixes

# Boolean value that determines whether clients that connect
# without providing a username are allowed to connect. If set to
# false then a password file should be created (see the
# password_file option) to control authenticated client access.
#
# Defaults to false, unless there are no listeners defined in the configuration
# file, in which case it is set to true, but connections are only allowed from
# the local machine.
#allow_anonymous false

# -----------------------------------------------------------------
#password_file
#psk_file
# user <username>
pattern write sensor/%u/data
# If an plugin is used as well as acl_file, the plugin check will be
# made first.
#acl_file
# plugin_opt_db_host
# plugin_opt_db_port
# plugin_opt_db_username
# plugin_opt_db_password
#bridge_bind_address
bridge_attempt_unsubscribe true
bridge_protocol_version mqttv311
cleansession true
idle_timeout 60
keepalive_interval 60
local_clientid
notifications true
#notification_topic
#remote_clientid
#remote_password
#remote_username
restart_timeout 20
restart_timeout 10 30
estart_timeout 5 30
round_robin false
# Bridges using the "lazy" start type will be started automatically when the
# number of queued messages exceeds the number set with the "threshold"
# parameter. It will be stopped automatically after the time set by the
# "idle_timeout" parameter. Use this start type if you wish the connection to
# only be active when it is needed.
#
threshold 10
try_private true
bridge_outgoing_retain true
bridge_max_packet_size 0
#bridge_cafile
#bridge_capath
#bridge_alpn
bridge_insecure false
#bridge_certfile
#bridge_keyfile
#bridge_identity
#bridge_psk
#include_dir
