# /qompassai/dotfiles/.config/fprintd/fprintd.conf
# Qompass AI FPrintd Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[storage]
type=file
