# /qompassai/dotfiles/.config/abuild/abuild.conf
# Qompass AI Arch Build Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
CLEANUP="srcdir bldroot pkgdir deps"
ERROR_CLEANUP="bldroot deps"
MAINTAINER="$PACKAGER"
MAKEOPTS="-j$(nproc)"
MOVE_CACHES=1
PACKAGER="Qompass AI <map@qompass.ai>"
REPODEST=$HOME/.GH/Qompass/Arch/packages
SRCDEST=/var/cache/distfiles
USE_COLORS=1
USE_CCACHE=1
