# /qompassai/dotfiles/.config/fftrate/fftrate.conf
# Qompass AI FFTRate Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

transform = dct
window = vorbis
zummer = on
