# /qompassai/dotfiles/.config/vdrpbd/vdrpbd.conf
# Qompass AI VDRPDB Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
ER_COUNT=4
ER_TIME=3
TARGET=svdrp
