# /qompassai/dotfiles/.config/netsniff-ng/geoip.conf
# Qompass AI Netsniff-ng GeoIP Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###############################################
geolite.maxmind.com
cryptoism.org
