# /qompassai/dotfiles/.config/gh/config.yml
# Qompass AI Github CLI Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
version: 1
git_protocol: ssh
editor: nvim
prompt: enabled
prefer_editor_prompt: enabled
pager: nvimpager
defaults:
    git_protocol: ssh
    editor: nvim
    pager: nvimpager
aliases:
    co: pr checkout
http_unix_socket:
browser: firefox
color_labels: enabled
gpg-key: 48A003FA78B6123F
security:
    commit_signing: true
ui:
    relative_dates: true
    unicode: true
    color_scheme: dark
