# /qompassai/dotfiles/.config/pcp/indom.conf
# Qompass AI PCP Indom Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
3.9 3.39 3.40
60.0 127.*
