# /qompassai/dotfiles/.config/pcp/tls.conf
# Qompass AI PCP TLS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
tls-key-file = /etc/pcp/tls/pcp.key
tls-cert-file = /etc/pcp/tls/pcp.crt
tls-ca-cert-file = /etc/pcp/tls/ca.crt
#tls-ca-cert-dir = /etc/ssl/certs
#tls-ciphers = DEFAULT:!MEDIUM
#tls-ciphersuites = TLS_CHACHA20_POLY1305_SHA256
tls-verify-clients = true
