# /qompassai/dotfiles/.config/dnssec-tools/dnssec-tools.conf
# Qompass AI Dnssec-tools Config
# Copyright (C) 2025 Qompass AI, All rights reserved
############################################################

admin-email     "$(pass show dnssec/amail)"
mailer-type	smtp
mailer-server	localhost
genkrf		/usr/bin/vendor_perl/genkrf
keyarch		/usr/bin/vendor_perl/keyarch
rollchk		/usr/bin/vendor_perl/rollchk
rollctl		/usr/bin/vendor_perl/rollctl
zonesigner	/usr/bin/vendor_perl/zonesigner
keygen		/usr/bin/dnssec-keygen
rndc		/usr/bin/rndc
zonecheck	/usr/bin/named-checkzone
zonesign	/usr/bin/dnssec-signzone
zonecheck-opts	-i local
zonefile-parser	Net::DNS::ZoneFile
algorithm	rsasha1
ksklength	4096
zsklength	1024
random		/dev/urandom
endtime		+2592000
ksklife		31536000
zsklife		7884000
lifespan-max	94608000
lifespan-min	3600
default_keyrec        output.krf
archivedir      "$(pass show dnssec/archivedir)"
entropy_msg	1
savekeys        1
kskcount	1
zskcount	1
autosign	1
roll_loadzone	1
roll_logfile	/etc/dnssec-tools/log-rollerd
roll_loglevel	info
roll_phasemsg	long
roll_sleeptime	60
roll_username	$USER
zone_errors	3
log_tz		pmt
usegui		0
