#!/usr/bin/env bash
# install_tilt.sh
# Qompass AI Diver Tilt Install Script
# Copyright (C) 2026 Qompass AI, All rights reserved
# ----------------------------------------
set -euo pipefail
VERSION="0.36.0"
: "${XDG_DATA_HOME:="$HOME/.local/share"}"
: "${XDG_CONFIG_HOME:="$HOME/.config"}"
TILT_HOME="${XDG_DATA_HOME}/tilt"
TILT_BIN_DIR="${TILT_HOME}/bin"
TILT_BIN="${TILT_BIN_DIR}/tilt"
BREW="$(command -v brew || true)"
log()  { printf '%s\n' "$*"; }
err()  { printf 'ERROR: %s\n' "$*" >&2; }
info() { printf 'INFO: %s\n' "$*"; }
ensure_dirs() {
  mkdir -p "${TILT_BIN_DIR}"
}
detect_arch() {
  local arch
  case "$(uname -m)" in
    aarch64) arch="arm64" ;;
    armv7l)  arch="arm"   ;;
    *)       arch="$(uname -m)" ;;
  esac
  printf '%s\n' "${arch}"
}
download_and_extract() {
  local os arch url
  os="$(uname | tr '[:upper:]' '[:lower:]')"
  arch="$(detect_arch)"

  if [[ "${os}" != "linux" && "${os}" != "darwin" ]]; then
    err "Unsupported OS: ${os}"
    log "For other installation options, see:"
    log "  https://docs.tilt.dev/install.html#alternative-installations"
    exit 1
  fi
  if [[ "${os}" == "linux" ]]; then
    url="https://github.com/tilt-dev/tilt/releases/download/v${VERSION}/tilt.${VERSION}.linux.${arch}.tar.gz"
  else
    url="https://github.com/tilt-dev/tilt/releases/download/v${VERSION}/tilt.${VERSION}.mac.${arch}.tar.gz"
  fi

  info "Downloading Tilt ${VERSION} from:"
  info "  ${url}"

  curl -fsSL "${url}" | tar -xz tilt
}

copy_binary_rootless() {
  ensure_dirs
  chmod +x tilt
  mv tilt "${TILT_BIN}"
  info "Installed tilt to: ${TILT_BIN}"
}

brew_install_to_xdg() {
  info "Detected Homebrew; using it as a downloader, but keeping install rootless"

  local tmpdir
  tmpdir="$(mktemp -d)"
  trap 'rm -rf "${tmpdir}"' EXIT

  set -x
  brew install tilt || brew upgrade tilt || true
  set +x

  local brew_tilt
  brew_tilt="$(command -v tilt || true)"
  if [[ -z "${brew_tilt}" ]]; then
    err "Brew did not produce a 'tilt' binary on PATH. Falling back to direct download."
    download_and_extract
    copy_binary_rootless
    return
  fi

  info "Using brew tilt from: ${brew_tilt}"
  ensure_dirs
  cp "${brew_tilt}" "${TILT_BIN}"
  chmod +x "${TILT_BIN}"
  info "Copied brew tilt to: ${TILT_BIN}"
}

install_tilt() {
  if [[ "$OSTYPE" == linux* || "$OSTYPE" == darwin* ]]; then
    if [[ -n "${BREW}" ]]; then
      brew_install_to_xdg
    else
      download_and_extract
      copy_binary_rootless
    fi
  else
    err "The Tilt installer does not work for your platform: ${OSTYPE}"
    log "For other installation options, check:"
    log "  https://docs.tilt.dev/install.html#alternative-installations"
    log "If you think your platform should be supported, please file an issue:"
    log "  https://github.com/tilt-dev/tilt/issues/new"
    exit 1
  fi
}

version_check() {
  if ! command -v "${TILT_BIN}" >/dev/null 2>&1; then
    err "Tilt binary not found at ${TILT_BIN}"
    exit 1
  fi

  local version_output
  version_output="$("${TILT_BIN}" version 2>&1 || true)"

  local RUBY_TILT_PATTERN="template engine not found"
  local TILT_DEV_PATTERN='^v[0-9]+\.[0-9]+\.[0-9]+(-dev)?, built [0-9]+-[0-9]+-[0-9]+$'

  if [[ ${version_output} =~ ${RUBY_TILT_PATTERN} ]]; then
    err "Another 'tilt' (Ruby templating) seems to be on PATH ahead of tilt.dev's tilt."
    log "Binary installed at: ${TILT_BIN}"
    exit 1
  elif ! [[ ${version_output} =~ ${TILT_DEV_PATTERN} ]]; then
    info "Tilt installed at: ${TILT_BIN}"
    log "Note: \`${TILT_BIN} version\` did not return the expected tilt.dev version string."
    log "Output was:"
    log "${version_output}"
    log "If you have another 'tilt' on your PATH, ensure ${TILT_BIN_DIR} comes first."
  else
    info "Tilt installed at: ${TILT_BIN}"
    log "Run:"
    log "  ${TILT_BIN} up"
  fi
}

verify_install() {
  if ! "${TILT_BIN}" verify-install; then
    err "tilt verify-install failed"
    exit 1
  fi
}

write_fish_conf() {
  local confd="${XDG_CONFIG_HOME}/fish/conf.d"
  local file="${confd}/tilt.fish"

  mkdir -p "${confd}"

  cat > "${file}" <<EOF
# Auto-generated by install_tilt.sh
# Ensure Tilt bin directory is on PATH
if test -d '${TILT_BIN_DIR}'
  if not contains '${TILT_BIN_DIR}' \$PATH
    set -gx PATH '${TILT_BIN_DIR}' \$PATH
  end
end
EOF

  info "Wrote fish config: ${file}"
}

print_path_hint() {
  cat <<EOF

Tilt has been installed to:
  ${TILT_BIN}

If you use bash or zsh, add this to your shell config:

  export PATH="${TILT_BIN_DIR}:\$PATH"

For fish, a conf.d snippet has been installed at:

  ${XDG_CONFIG_HOME}/fish/conf.d/tilt.fish

EOF
}

main() {
  install_tilt
  version_check
  verify_install
  write_fish_conf
  print_path_hint
}

main "$@"