<?php
/*
 * /qompassai/dotfiles/.config/webapps/pydio/extensions.conf.php
 * Qompass AI Pydio Extensions Config
 * Copyright (C) 2025 Qompass AI, All rights reserved
 *******************************************************************
 */
defined('AJXP_EXEC') or die('Access not allowed');
$RESERVED_EXTENSIONS = array(
    "folder" => array("ajxp_folder", "folder.png", "folder", 8),
    "unkown" => array("ajxp_empty", "mime_empty.png", "file", 23)
);
$EXTENSIONS = array(
    array("aac", "sound.png", "file-music", 59),
    array("avi", "video.png", "file-video", 81),
    array("bib", "bibtex.png", "file-document", 100),
    array("bmp", "image.png", "file-image", 56),
    array("csv", "spreadsheet.png", "file-excel", 64),
    array("css", "css.png", "language-css3", 58),
    array("doc", "word.png", "file-word", 65),
    array("docx", "word.png", "file-word", 65),
    array("dot", "word.png", "file-word", 65),
    array("dotx", "word.png", "file-word", 65),
    array("dwg", "dwg.png", "cube-outline", "DWG"),
    array("ers", "horo.png", "timer", "Timestamp"),
    array("exe", "exe.png", "application", 50),
    array("flv", "flash.png", "movie", 91),
    array("gif", "image.png", "file-image", 12),
    array("gz", "zip.png", "archive", 61),
    array("htm", "html.png", "language-html5", 15),
    array("html", "html.png", "language-html5", 14),
    array("java", "source_pl.png", "file-xml", 18),
    array("js", "javascript.png", "language-javascript", 11),
    array("key", "presentation.png", "file-powerpoint", 446),
    array("m4a", "sound.png", "file-music", 59),
    array("m4v", "video.png", "file-video", 83),
    array("mid", "midi.png", "file-music", 9),
    array("mov", "video.png", "file-video", 80),
    array("mp3", "sound.png", "file-music", 59),
    array("mp4", "video.png", "file-video", 83),
    array("mpg", "video.png", "file-video", 82),
    array("midi", "midi.png", "file-music", 101),
    array("mpeg", "video.png", "file-video", 83),
    array("ods", "spreadsheet.png", "file-excel", 64),
    array("odt", "word.png", "file-word", 65),
    array("odp", "presentation.png", "file-powerpoint", 446),
    array("ogv", "video.png", "file-video", "Video"),
    array("pdf", "pdf.png", "file-pdf", 79),
    array("phar", "php.png", "language-php", 22),
    array("php", "php.png", "language-php", 21),
    array("php3", "php.png", "language-php", 22),
    array("php4", "php.png", "language-php", 22),
    array("phtml", "php.png", "language-php", 22),
    array("pl", "source_pl.png", "file-xml", 18),
    array("png", "image.png", "file-image", 57),
    array("pps", "presentation.png", "file-powerpoint", 446),
    array("ppt", "presentation.png", "file-powerpoint", 446),
    array("psd", "image.png", "file-image", "Photoshop"),
    array("quarto", "quarto.png", "file-quarto", 89),
    array("rmd", "rmd.png", "file-rmd", 90),
    array("ra", "video.png", "file-video", 16),
    array("ram", "video.png", "file-video", 17),
    array("rar", "archive.png", "archive", 60),
    array("rm", "video.png", "file-video", 17),
    array("rst", "rst.png", "file-rst", 102),
    array("rtf", "word.png", "file-word", 65),
    array("sxc", "spreadsheet.png", "file-excel", 64),
    array("svg", "image.png", "file-image", "SVG"),
    array("swf", "flash.png", "movie", 91),
    array("swx", "word.png", "file-word", 65),
    array("sql", "txt2.png", "file-document", 10),
    array("tgz", "archive.png", "archive", 61),
    array("tex", "latex.png", "file-latex", 103),
    array("text", "plaintext.png", "file-plain", 104),
    array("tif", "image.png", "file-image", "TIFF"),
    array("tiff", "image.png", "file-image", "TIFF"),
    array("tsv", "spreadsheet.png", "file-excel", 64),
    array("txt", "txt2.png", "file-document", 10),
    array("wav", "sound.png", "file-music", 20),
    array("webm", "video.png", "file-video", "Video"),
    array("wmv", "video.png", "file-video", 81),
    array("xls", "spreadsheet.png", "file-excel", 64),
    array("xlsx", "spreadsheet.png", "file-excel", 64),
    array("xlt", "spreadsheet.png", "file-excel", 64),
    array("xltx", "spreadsheet.png", "file-excel", 64),
    array("xml", "xml.png", "file-xml", 105),
    array("z", "archive.png", "archive", 61),
    array("zip", "zip.png", "archive", 19)
);
?>
