context.objects = [
    { factory = adapter
       args = {
           factory.name     = support.null-audio-sink
           node.name        = "audiorelay-virtual-mic-sink"
           node.description = "AudioRelay Mic&Sink"
           media.class      = "Audio/Duplex"
           audio.position   = "FL,FR"
       }
    }
]
context.modules = [
    {   name = libpipewire-module-loopback
        args = {
            audio.position = [ FL FR ]
            capture.props = {
                media.class = Audio/Sink
                node.name = audiorelay_Speaker
                node.description = "AudioRelay Speaker"
                #node.latency = 1024/48000
                #audio.rate = 44100
                #audio.channels = 2
                #audio.position = [ FL FR ]
                #target.object = ""
            }
            playback.props = {
                #media.class = Audio/Source
                node.name = audiorelay_source
                node.description = "Virtual Source"
                #node.latency = 1024/48000
                #audio.rate = 44100
                #audio.channels = 2
                #audio.position = [ FL FR ]
                #target.object = ""
            }
        }
    }
]
