# Core PipeWire properties
context.properties = {
    clock.power-of-two-quantum              = true
    context.data-loop.library.name.system   = support/libspa-support
    context.num-data-loops                  = 1
    core.daemon                             = true
    core.name                               = pipewire-0
    cpu.zero.denormals                      = true
    library.name.system                     = support/libspa-support
    link.max-buffers                        = 64
    log.level                               = 5
    log.patterns                            = [ "*:T" ]
    mem.allow-mlock                         = true
    mem.mlock-all                           = false
    mem.warn-mlock                          = false
    rlimit.nofile                           = -1
    support.dbus                            = true
}
