# /qompassai/dotfiles/.config/pipewire/pipewire.conf.d/10-properties.conf
# Qompass AI Pipewire Properties Config
# Copyright (C) 2026 Qompass AI, All rights reserved
#########################################################################
# Reference: https://docs.pipewire.org/page_man_pipewire_conf_5.html#pipewire_conf__context_properties
context.properties = {
    clock.power-of-two-quantum                             = true
    context.data-loop.library.name.system                  = support/libspa-support
    context.num-data-loops                                 = 1
    core.daemon                                            = true
    core.name                                              = pipewire-0
    cpu.zero.denormals                                     = true
    default.clock.allowed-rates                            = [ 44100 48000 88200 96000 ]
    default.clock.max-quantum                              = 2048
    default.clock.min-quantum                              = 256
    default.clock.quantum                                  = 1024
    default.clock.quantum-floor                            = 4
    default.clock.quantum-limit                            = 8192
    default.clock.rate                                     = 48000
    #default.clock.force-quantum                           = 0
    #default.clock.force-rate                              = 0
    default.video.height                                   = 1080
    default.video.rate.denom                               = 1
    default.video.rate.num                                 = 60
    default.video.width                                    = 1920
    library.name.system                                    = support/libspa-support
    link.max-buffers                                       = 64
    log.level                                              = 2
    log.patterns                                           = [ "pw.*:W" ]
    mem.allow-mlock                                        = true
    mem.mlock-all                                          = false
    mem.warn-mlock                                         = false
    resample.disable                                       = false
    resample.quality                                       = 10
    rlimit.nofile                                          = -1
    settings.check-quantum                                 = false
    settings.check-rate                                    = false
    support.dbus                                           = true
}
stream.properties = {
    #node.latency                                       = 1024/48000
    #node.autoconnect                                   = true
    #resample.quality                                   = 4
    #channelmix.normalize                               = false
    #channelmix.mix-lfe                                 = true
    #channelmix.upmix                                   = true
    #channelmix.upmix-method                            = psd  # none, simple
    #channelmix.lfe-cutoff                              = 150
    #channelmix.fc-cutoff                               = 12000
    #channelmix.rear-delay                              = 12.0
    #channelmix.stereo-widen                            = 0.0
    #channelmix.hilbert-taps                            = 0
    #dither.noise                                       = 0
}
