# /qompassai/dotfiles/.config/pipewire/pipewire.conf.d/30-rules.conf
# Qompass AI Pipewire Rules Config
# Copyright (C) 2026 Qompass AI, All rights reserved
####################################################################
alsa.rules = [
    {
        matches = [ { application.process.binary = "resolve" } ]
        actions = {
            update-props = {
                alsa.buffer-bytes = 131072
            }
        }
    }
]
context.properties.rules = [
    {   matches = [ { cpu.vm.name = !null } ]
        actions = {
            update-props = {
                default.clock.min-quantum = 1024
            }
        }
    }
]
