context.objects = [
    { factory                                              = spa-node-factory
        args = {
            factory.name                                   = support.node.driver
            node.name                                      = Dummy-Driver
            node.group                                     = pipewire.dummy
            node.sync-group                                = sync.dummy
            priority.driver                                = 200000
        }
        condition                                          = [ { factory.dummy-driver = !false } ]
    }
    { factory = spa-node-factory
        args = {
            factory.name     = support.node.driver
            node.name        = Freewheel-Driver
            priority.driver  = 190000
            node.group       = pipewire.freewheel
            node.sync-group  = sync.dummy
            node.freewheel   = true
        }
        condition = [ { factory.freewheel-driver = !false } ]
    }
    {
        factory = spa-node-factory
        args = {
            factory.name = api.vulkan.compute.source
            node.name = vulkan-compute-source
            object.export = true
        }
        flags = [ ifexists nofail ]
        condition = [ { factory.vulkan = !false } ]
    }
    {
        factory = spa-node-factory
        args = {
            factory.name = api.vulkan.compute.filter
            node.name = vulkan-compute-filter
            object.export = true
        }
        flags = [ ifexists nofail ]
        condition = [ { factory.vulkan = !false } ]
    }
    {
        factory = spa-node-factory
        args = {
            factory.name = api.vulkan.blit.filter
            node.name = vulkan-blit-filter
            object.export = true
        }
        flags = [ ifexists nofail ]
        condition = [ { factory.vulkan = !false } ]
    }
    {
        factory = spa-node-factory
        args = {
            factory.name = api.vulkan.blit.dsp-filter
            node.name = vulkan-blit-dsp-filter
            object.export = true
        }
        flags = [ ifexists nofail ]
        condition = [ { factory.vulkan = !false } ]
    }
]

