# /qompassai/dotfiles/.config/dkms/r8125/dkms.conf
# Qompass AI R8125 DKMS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
PACKAGE_NAME="r8125"
PACKAGE_VERSION="9.016.01"
MAKE[0]="make -C $kernel_source_dir M=$dkms_tree/$PACKAGE_NAME/$PACKAGE_VERSION/build modules"
BUILT_MODULE_NAME[0]="r8125"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/ethernet/realtek"
AUTOINSTALL="yes"
