# /qompassai/dofiles/.config/biometric-auth/ukui-biometric.conf
# Qompass AI Biometric Auth Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[General]
EnableAuth=false
DefaultDevice=
DoubleAuth=false
UserBind=false
isShownInControlCenter=false
UseFirstDevice=false
MaxFailedTimes=3
HiddenSwitchButton=false
