# /qompassai/dotfiles/.config/inspircd/examples/providers/torexit.conf
# Qompass AI Inspircd Torexit Provider Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#######################################################################
# References: https://www.anope.org
<include file="&dir.example;/services/generic.example.conf">
