# /qompassai/dotfiles/.config/inspircd/examples/services/atheme.conf
# Qompass AI Inspircd Atheme Service Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#######################################################################
# References: https://atheme.github.io/atheme.html
<include file="&dir.example;/services/generic.example.conf">
<alias text="ALIS"      replace="PRIVMSG $requirement :$2-" requires="ALIS"      service="yes">
<alias text="CHANFIX"   replace="PRIVMSG $requirement :$2-" requires="ChanFix"   service="yes">
<alias text="GAMESERV"  replace="PRIVMSG $requirement :$2-" requires="GameServ"  service="yes">
<alias text="GROUPSERV" replace="PRIVMSG $requirement :$2-" requires="GroupServ" service="yes">
<alias text="HELPSERV"  replace="PRIVMSG $requirement :$2-" requires="HelpServ"  service="yes">
<alias text="INFOSERV"  replace="PRIVMSG $requirement :$2-" requires="InfoServ"  service="yes">
<alias text="PROXYSCAN" replace="PRIVMSG $requirement :$2-" requires="Proxyscan" service="yes" operonly="yes">
<alias text="RPGSERV"   replace="PRIVMSG $requirement :$2-" requires="RPGServ"   service="yes">
<alias text="CF" replace="PRIVMSG $requirement :$2-" requires="ChanFix"   service="yes">
<alias text="GS" replace="PRIVMSG $requirement :$2-" requires="GroupServ" service="yes">
<alias text="IS" replace="PRIVMSG $requirement :$2-" requires="InfoServ"  service="yes">
<alias text="LS" replace="PRIVMSG $requirement :$2-" requires="ALIS"      service="yes">
<alias text="PS" replace="PRIVMSG $requirement :$2-" requires="Proxyscan" service="yes" operonly="yes">
<alias text="RS" replace="PRIVMSG $requirement :$2-" requires="RPGServ"   service="yes">
#<alias text="GS" replace="PRIVMSG $requirement :$2-" requires="GameServ" service="yes">
#<alias text="HS" replace="PRIVMSG $requirement :$2-" requires="HelpServ" service="yes">
<badnick nick="ALIS"      reason="Reserved for a network service">
<badnick nick="ChanFix"   reason="Reserved for a network service">
<badnick nick="GameServ"  reason="Reserved for a network service">
<badnick nick="GroupServ" reason="Reserved for a network service">
<badnick nick="HelpServ"  reason="Reserved for a network service">
<badnick nick="InfoServ"  reason="Reserved for a network service">
<badnick nick="Proxyscan" reason="Reserved for a network service">
<badnick nick="RPGServ"   reason="Reserved for a network service">
<badnick nick="SaslServ"  reason="Reserved for a network service">
<exemptfromfilter target="ALIS">
<exemptfromfilter target="ChanFix">
<exemptfromfilter target="GameServ">
<exemptfromfilter target="GroupServ">
<exemptfromfilter target="HelpServ">
<exemptfromfilter target="InfoServ">
<exemptfromfilter target="Proxyscan">
<exemptfromfilter target="RPGServ">
<exemptfromfilter target="SaslServ">
