#!/usr/bin/env sh
# /qompassai/dotfiles/.config/vmware-tools/statechange.subr
# Qompass AI VMWare-Tools StateChange Config
# Copyright (C) 2025 Qompass AI, All rights reserved
##########################################################
Panic() {
   fmt="`date '+%b %d %H:%M:%S'` `basename \"$0\"`"
   if [ -n "$1" ]; then
      fmt="${fmt}: $1"
      shift
   fi

   printf >&2 "${fmt}\n" "$@"
   exit 1
}
