#!/usr/bin/env sh
# /qompassai/dotfiles/.config/vmware-tools/suspend-vm-default
# Qompass AI VMWare-Tools Suspend VM Default Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#############################################################
echo `date` ": Executing '$0'"
TOOLS_CONFDIR=`dirname "$0"`
export TOOLS_CONFDIR
. "$TOOLS_CONFDIR"/statechange.subr
RunScripts() {
   scriptDir="$1"
   if [ -d "$scriptDir" ]; then
      for scriptFile in "$scriptDir"/*; do
         if [ -f "$scriptFile" -a -x "$scriptFile" ]; then
            "$scriptFile" $powerOp
            exitCode=`expr $exitCode \| $?`
         fi
      done
   fi
}

main() {
   powerOp=`basename "$0" | sed 's,-default,,'`
   exitCode=0
   vmwScriptDir="$TOOLS_CONFDIR/scripts/vmware"
   userScriptDir="$TOOLS_CONFDIR/scripts/${powerOp}-default.d"
   case "$powerOp" in
      poweron-vm|resume-vm)
         RunScripts "$vmwScriptDir"
         RunScripts "$userScriptDir"
         ;;
      poweroff-vm|suspend-vm)
         RunScripts "$userScriptDir"
         RunScripts "$vmwScriptDir"
         ;;
      *)
         Panic "Invalid argument: $powerOp"
         ;;
   esac
   return $exitCode
}
main
