# /qompassai/dotfiles/.config/vmware-tools/tools.conf
# Qompass AI VMWar-Tools Tools Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
[unsetenvironment]
[setenvironment]
TMPDIR=/vmware/temp
vmsvc.TMPDIR=/vmware/vmsvc/temp
vmusr.TMPDIR=/vmware/vmusr/temp
[logging]
log = true
vmtoolsd.facility = daemon
vmtoolsd.level = debug
vmtoolsd.handler = file
vmtoolsd.data = c:/tmp/vmtoolsd-${USER}.log
vmsvc.level = debug
vmsvc.handler = file
vmsvc.data = c:/tmp/vmsvc.log
vmresset.level = debug
vmresset.handler = file+
vmresset.data = c:/tmp/vmresset.log
vmusr.level = debug
vmusr.handler = file
vmusr.data = c:/tmp/vmusr.${USER}.log
toolboxcmd.level = debug
toolboxcmd.handler = file
toolboxcmd.data = c:/tmp/vmtoolboxcmd-${USER}.log
deployPkg.level = debug
deployPkg.handler = file
deployPkg.data = c:/tmp/toolsDeployPkg-${USER}.log
log = true
vmsvc.level = debug
vmsvc.handler = vmx
deployPkg.level = debug
deployPkg.handler = vmx
log.file = c:/tmp/vmtools.log
hgfsServer.level = debug
hgfsd.level = debug
vmbackup.level = debug
vmbackup.handler = vmx
vmvss.level = debug
vmvss.handler = vmx
#maxCacheEntries=4096
network.handler = file
network.data = /tmp/network.log
network.maxOldLogFiles = 9
network.handler = vmx
[powerops]
poweron-script=poweron-vm-default
poweroff-script=poweroff-vm-default
resume-script=resume-vm-default
suspend-script=suspend-vm-default
[guestinfo]
disable-perf-mon=false
disable-query-diskinfo=false
poll-interval=30
stats-interval=20
enable-stat-logging=false
#primary-nics=
#low-priority-nics=
exclude-nics=veth*,docker*,virbr*,antrea-*,cali*
exclude-nics=vEthernet*
max-ipv4-routes=100
max-ipv6-routes=100
diskinfo-include-reserved=false
[globalconf]
enabled=true
poll-interval=3600
resource=/vmware/configurations/vmtools/windows/tools.conf
resource=/vmware/configurations/vmtools/linux/tools.conf
[componentmgr]
poll-interval=180
included=all
[appinfo]
disabled=false
poll-interval=21600
useWMI=false
remove-duplicates=true
[containerinfo]
poll-interval=21600
max-containers=256
remove-duplicates=true
#docker-unix-socket=/var/run/docker.sock
#containerd-unix-socket=/run/containerd/containerd.sock
#allowed-namespaces=moby,k8s.io,default
[servicediscovery]
#disabled=false
[unity]
#forceEnable=false
#desktop.backgroundColor=
#pbrpc.socketType
[resolutionKMS]
#enable=true
[guestosinfo]
#short-name=
#long-name=
[vmbackup]
enableSyncDriver=true
#enableVSS=true
# vss.disableAppQuiescing is Windows only.
vss.disableAppQuiescing=false
#excludedFileSystems=
ignoreFrozenFileSystems=false
execScripts=true
#scriptArg=
[guestoperations]
disabled=false
# Whether to use vgauth for guest op authentication
useVGAuth=true
[autoupgrade]
allow-upgrade=true
allow-add-feature=true
allow-remove-feature=true
allow-msi-transforms=true
[deployPkg]
enable-customization=false
wait-cloudinit-timeout=30
[cbhelper]
poll-interval=60
[gueststoreupgrade]
policy=manual
poll-interval=3600
vmtools-version-key=vmtools
[devicehelper]
disabled=false
[gitray]
enabled=true
[giamsi]
enabled=true
amsi-max-client-connections=24
amsi-max-script-size-in-bytes=262144

[timeSync]
disable-all=false
disable-periodic=false
