# /qompassai/dotfiles/.config/vmware-tools/vgauth.conf
# Qompass AI VMWare-Tools VGAuth Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
[service]
samlSchemaDir = $XDG_CONFIG_HOME/vmware-tools/vgauth/schemas

[localization]
msgCatalog = /usr/share/open-vm-tools
