# /qompassai/dotfiles/.config/aria2/aria2.conf
# Qompass AI Aria2 Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
continue=true
dir=${HOME}/Downloads
file-allocation=none
max-connection-per-server=16
min-split-size=5M
log-level=warn
on-download-complete=exit
enable-rpc=true
max-tries=8
timeout=20
retry-wait=5
rpc-listen-all=true
rpc-secret='$(pass show aria2/rpc)'
