# input.conf
# Qompass AI Aria2 Input Config
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
https://archlinux.org/packages/core/x86_64/pacman/download/
    out=pacman-latest.pkg.tar.zst

ftp://ftp5.gwdg.de/pub/linux/archlinux/iso/2025.08.01/archlinux-2025.08.01-x86_64.iso
    dir=~/Downloads
    seed-time=120

magnet:?xt=urn:btih:0123456789abcdef0123456789abcdef01234567
    out=archmagnet.iso

