[vdr]
--audio=cmd
#--cachedir=dir
--chartab=ISO-8859-15
#--config=dir
--daemon
#--device=num
#--dirnames=path[,name[,enc]]
#--epgfile=file
#--filesize=size
--grab=/tmp
--instance=instance
--log=2
#--lib=dir
#--lirc[=path]
#--localedir=dir
#--mute
#--no-kbd
#--port=port
#--record=cmd
#--resdir=dir
--shutdown=/usr/lib/vdr/bin/shutdown-wrapper
#--terminal=tty
#--user=user
#--userdump
#--video=dir
--watchdog=90
