schema_version = "1.0.0"
id = "blender_speed_curve"
version = "1.0.2"
name = "Motion Style"
tagline = "AE-style easing sliders and F-Curve speed visualization"
maintainer = "Willy_work"
type = "add-on"
blender_version_min = "4.2.0"
license = [
  "SPDX:GPL-3.0-or-later"
]
tags = ["Animation"]
