# /qompassai/dotfiles/.config/munin/munin-node.conf
# Qompass AI Munin-Node Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
log_level 4
log_file /var/log/munin/munin-node.log
pid_file /run/munin/munin-node.pid
background 1
setsid 1
user root
group root
global_timeout 900
timeout 60
ignore_file [\#~]$
ignore_file DEADJOE$
ignore_file \.bak$
ignore_file %$
ignore_file \.dpkg-(tmp|new|old|dist)$
ignore_file \.rpm(save|new)$
ignore_file \.pod$
# telnetting to localhost, port 4949
#host_name myhostname
allow ^127\.0\.0\.1$
allow ^::1$
cidr_allow 127.0.0.1/32
cidr_allow 192.0.2.0/24
cidr_deny  192.0.2.42/32
host *
host 127.0.0.1
port 4949
