application.revision.ghidra-Ghidra_11.0.3_build=
application.build.date=2024-Apr-11 1104 UTC
application.build.date.short=20240411
application.name=Ghidra
application.version=11.0.3
application.release.name=DEV
application.layout.version=1
application.gradle.min=7.3
application.gradle.max=
application.java.min=17
application.java.max=
application.java.compiler=17
