schema_version = "1.0.0"

id = "unity_rig"
version = "1.0.1"
name = "Unity Rig"
tagline = "Create Unity Humanoid-compatible rigs and convert Rigify rigs"
maintainer = "Mike Simon"
type = "add-on"

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

tags = ["Rigging", "Import-Export"]

[build]
paths_exclude_pattern = [
    "__pycache__/",
    "*.pyc",
    "*.jpg",
    "*.JPG",
    "*.png",
]
