# /qompassai/dotfiles/.config/amanda/template.d/advanced.conf
# Qompass AI Amanda Advanced Config
# Copyright (C) 2026 Qompass AI, All rights reserved
#############################################################
inparallel 4	
dumporder "sssS"
taperalgo first		
displayunit "g"	
netusage  80000 Kbps
bumpsize 20 Mb
bumppercent 20
bumpdays 1
device_output_buffer_size 1280k
maxdumpsize -1
bumpmult 4
amrecover_changer "changer"	
autoflush no 
infofile "/etc/amanda/DailySet1/curinfo"
logdir   "/etc/amanda/DailySet1"
indexdir "/etc/amanda/DailySet1/index"
holdingdisk hd1 {
    comment "main holding disk"
    directory "/dumps/amanda"	
    use -100 Mb
    chunksize 1Gb 
			  0 
    }
holdingdisk hd2 {
    directory "/dumps2/amanda"
    use 1000 Mb
    }
define interface local {
    comment "a local disk"
    use 8000 kbps
}
define interface le0 {
    comment "10 Mbps ethernet"
    use 400 kbps
}
