# /qompassai/dotfiles/.config/amanda/template.d/amanda-S3.conf
# Qompass AI Amanda Hard-Disk Config
# Copyright (C) 2026 Qompass AI, All rights reserved
#############################################################
org "DailySet1"
mailto "amandabackup"
dumpcycle 1 week	
runspercycle 5
tapecycle 10 tapes
runtapes 1
define changer my_s3 {
    tpchanger "chg-multi:"
    device-property "S3_ACCESS_KEY" ""
    device-property "S3_SECRET_KEY" ""
    device-property "NB_THREADS_BACKUP" "3"
}
tpchanger "my_s3"
tapetype S3
holdingdisk hd2 {
    directory "/var/lib/amanda/holdings/DailySet1"
    use 1000 Mb
    }
autolabel "DailySet1-%%%%" empty
labelstr "^DailySet1-[0-9][0-9]*$"
dtimeout 1800	
ctimeout 30
etimeout 300	
define dumptype global {
        comment "Global definitions"
        auth "bsdtcp"
}
define application-tool app_amgtar {
    comment "amgtar"
    plugin  "amgtar"
    #property "GNUTAR-PATH" "/path/to/gtar"
    #property "GNUTAR-LISTDIR" "/path/to/gnutar_list_dir"
}
define dumptype gui-base {
        global
        program "APPLICATION"
        application "app_amgtar"
        comment "gui base dumptype dumped with tar"
        compress none
        index yes
}
define tapetype S3 {
    comment "S3 pseudo-tape"
    length 10240 gigabytes
    part_size 100G
    part_cache_type none
}
includefile "./advanced.conf"
includefile "/etc/amanda/template.d/dumptypes"
includefile "/etc/amanda/template.d/tapetypes"

