# /qompassai/dotfiles/.config/amanda/template.d/amanda-CAStor.conf
# Qompass AI Amanda CAStor Config
# Copyright (C) 2026 Qompass AI, All rights reserved
#############################################################
org "DailySet1"	
mailto "amandabackup"
dumpcycle 1 week	
runspercycle 5          
tapecycle 10 tapes	
runtapes 1	
define changer my_castor {
    tpchanger "chg-multi:s3:<BUCKET>/<PREFIX>/slot{01,02,03,04,05,06,07,08,09,10}/"
    device-property "STORAGE_API" "CASTOR"
    device-property "S3_HOST" "<CLUSTER>"
    device-property "S3_SSL" "NO"
    device-property "TENANT_NAME" "<DOMAIN>"
    device-property "USERNAME" "<USER>"
    device-property "PASSWORD" "<PASSWORD>"
    device-property "REPS" "<REPS>"
    device-property "REPS_BUCKET" "<REPS>"
    device-property "CREATE_BUCKET" "YES"
    device-property "NB_THREADS_BACKUP" "3"
    device-property "NB_THREADS_RECOVERY" "3"
}
define tapetype CASTOR {
    comment "CAStor pseudo-tape"
    length 10240 gigabytes
    part_size 100 gigabytes
    part_cache_type none
    blocksize 512 megabytes
}

tpchanger "my_castor"
tapetype CASTOR

autolabel "DailySet1-%%%%" empty
labelstr "^DailySet1-[0-9][0-9]*$"

dtimeout 1800
ctimeout 30
etimeout 300
define dumptype global {
        comment "Global definitions"
        auth "bsdtcp"
}
define application-tool app_amgtar {
    comment "amgtar"
    plugin  "amgtar"
    property "GNUTAR-PATH" "/path/to/gtar"
    property "GNUTAR-LISTDIR" "/path/to/gnutar_list_dir"
}
define dumptype gui-base {
        global
        program "APPLICATION"
        application "app_amgtar"
        comment "gui base dumptype dumped with tar"
        compress none
        index yes
}
includefile "./advanced.conf"
includefile "/etc/amanda/template.d/dumptypes"
includefile "/etc/amanda/template.d/tapetypes"
