# /qompassai/dotfiles/.config/amanda/template.d/amanda-tape-changer.conf
# Qompass AI Amanda Tape Changer Config
# Copyright (C) 2026 Qompass AI, All rights reserved
#############################################################
org "DailySet1"	
mailto "amandabackup"	
dumpcycle 1 week
runspercycle 5
tapecycle 10 tapes
runtapes 1

define changer my_robot {
    tpchanger "chg-robot:/dev/sg1"
    property "tape-device" "0=tape:/dev/nst0"
}
tpchanger "my_robot"
tapetype HP-DAT	

holdingdisk hd2 {
    directory "/var/lib/amanda/holdings/DailySet1"
    use 1000 Mb
    }

labelstr "^DailySet1-[0-9][0-9]*$"	

dtimeout 1800		
ctimeout 30	
etimeout 300

define dumptype global {
        comment "Global definitions"
        auth "bsdtcp"
}

define application-tool app_amgtar {
    comment "amgtar"
    plugin  "amgtar"
    #property "GNUTAR-PATH" "/path/to/gtar"
    #property "GNUTAR-LISTDIR" "/path/to/gnutar_list_dir"
}
define dumptype gui-base {
        global
        program "APPLICATION"
        application "app_amgtar"
        comment "gui base dumptype dumped with tar"
        compress none
        index yes
}
includefile "./advanced.conf"
includefile "/etc/amanda/template.d/dumptypes"
includefile "/etc/amanda/template.d/tapetypes"

