# /qompassai/dotfiles/.config/amanda/template.d/chg-manual.conf
# Qompass AI Amanda Change Manual Config
# Copyright (C) 2026 Qompass AI, All rights reserved
#############################################################
resend_mail=3600
timeout_mail=43200
request="tty"
#request="email"
request="tty_email"	
