#!/usr/sbin/nft -f
# /qompassai/dotfiles/.config/nftables/nftables.conf
# Qompass AI NFTables Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
flush ruleset

table inet my_filter {
  chain input {
    type filter hook input priority filter; policy drop;

    ct state established,related accept

    iif "lo" accept

    icmpv6 type { mld-listener-query, nd-router-solicit, nd-neighbor-solicit, nd-neighbor-advert } accept
    icmpv6 type echo-request limit rate 10/second burst 5 packets accept

    ip protocol icmp accept

    udp dport { 53, 51820 } accept
    tcp dport { 22, 80, 443, 9050, 9051, 10028, 10128 } accept

    ct state invalid drop
  }

  chain forward {
    type filter hook forward priority filter; policy drop;
    iifname "wg0" oifname "enp45s0" accept
    iifname "enp45s0" oifname "wg0" accept
  }

  chain output {
    type filter hook output priority filter; policy drop;
    ct state established,related accept
    oif "lo" accept
    udp dport 53 accept
    tcp dport 53 accept
    tcp dport { 3333, 10028, 10128 } accept
  }
}

