# /qompassai/dotfiles/.config/srp/srp_daemon.conf 
# Qompass AI SRP Daemon Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
d       dgid=fe800000000000000002c90200402bd5
a       ioc_guid=00a0b80200402bd7
a       pkey=ffff
a       id_ext=200500A0B81146A1,ioc_guid=00a0b80200402bef

