# /qompassai/dotfiles/.config/dovecot/conf.d/10-master.conf
# Qompass AI Dovecot Master Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###########################################################
service imap-login {
  inet_listener imaps {
    port = 10993
    ssl = yes
  }
  # unix_listener login {
  #   mode = 0600
  # }
}
