# /qompassai/dotfiles/.config/pavucontrol-qt/pavucontrol-qt.conf
# Qompass AI Pavucontrol QT Config
# Copyright (C) 2025 Qompass AI, All rights reserved
################################################################
[window]
showVolumeMeters=true
sinkInputType=0
sinkType=0
size=@Size(1338 895)
sourceOutputType=1
sourceType=1
