# /qompassai/dotfiles/.config/pipewire/pipewire-pulse.conf.d/10-pulse.conf
# Qompass AI PipeWire PulseAudio Compatibility Config
# Copyright (C) 2026 Qompass AI, All rights reserved
#########################################################################
# References: #   https://docs.pipewire.org/page_man_pipewire-pulse_conf_5.html |
# https://docs.pipewire.org/page_module_protocol_pulse.html | https://man.archlinux.org/man/pipewire-pulse.conf.5.en
pulse.properties = {
    pulse.allow-module-loading                          = true
    pulse.default.format                                = F32
    pulse.default.frag                                  = 96000/48000 
    pulse.default.position                              = [ FL FR ]
    pulse.default.req                                   = 960/48000
    pulse.default.tlength                               = 96000/48000
    pulse.idle.timeout                                  = 0
    pulse.min.frag                                      = 256/48000
    pulse.min.quantum                                   = 256/48000
    pulse.min.req                                       = 256/48000
    server.address                                      = [ "unix:native" ]
    server.dbus-name                                    = "org.pulseaudio.Server"
}
pulse.properties.rules = [
    {
        matches = [ { cpu.vm.name = !null } ]
        actions = {
            update-props = {
                pulse.min.quantum                       = 1024/48000 
            }
        }
    }
]
pulse.rules = [
    {
        matches = [ { application.process.binary = "firefox" } ]
        actions = { quirks = [ remove-capture-dont-move ] }
    }
    {
        matches = [ { application.name = "~speech-dispatcher.*" } ]
        actions = {
            update-props = {
                pulse.idle.timeout                      = 5
                pulse.min.quantum                       = 512/48000
                pulse.min.req                           = 512/48000
            }
        }
    }
    {
        matches = [
            { application.process.binary = "skypeforlinux" }
            { application.process.binary = "teams" }
            { application.process.binary = "teams-for-linux" }
            { application.process.binary = "teams-insiders" }
        ]
        actions = { quirks = [ force-s16-info ] }
    }
]
