# /qopmassai/dotfiles/.config/audit/audisp-remote.conf
# Qompass AI Audit Audisp Remote Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
disk_low_action = ignore
disk_full_action = warn_once
disk_error_action = warn_once
generic_error_action = syslog
generic_warning_action = syslog
format = managed
heartbeat_timeout = 0
##krb5_principal = 
##krb5_client_name = auditd
##krb5_key_file = "$(pass show audit/krb5kf)"
##local_port =
max_tries_per_record = 3
max_time_per_record = 5
mode = immediate
network_failure_action = stop
network_retry_time = 1
overflow_action = syslog
port = 60
queue_file = /var/spool/audit/remote.log
queue_depth = 10240
queue_error_action = stop
remote_ending_action = reconnect
remote_server =
startup_failure_action = warn_once_continue
transport = tcp
