# /qompassai/dotfiles/.config/audit/zos-remote.conf
# Qompass AI Audit Zos-Remote Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
server = zos_server.localdomain
port = 389
user = RACF_ID
password = "$(pass show auditzos/p)"
timeout = 15
q_depth = 64
