# /qompassai/dotfiles/.config/isns/isnsadm.conf
# Qompass AI Isns Client Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
AuthKeyFile		= /etc/isns/auth_key
ServerKeyFile		= /etc/isns/server_key.pub
Auth.ReplayWindow 	= 2m
Auth.TimeStampJitter 	= 1s
Network.MaxSockets 	= 1024
Network.ConnectTimeout 	= 60
Network.ReonnectTimeout = 10
Network.CallTimeout 	= 60
SourceName		= iqn.2006-01.com.example.host1
ServerAddress		= isns.example.com
Security		= 1
