# /qompassai/dotfiles/.config/isns/isnsdd.conf
# Qompass AI Isns Discovery Daemon Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
AuthKeyFile		= /etc/isns/auth_key
Auth.ReplayWindow 	= 2m
Auth.TimeStampJitter 	= 1s
Network.MaxSockets 	= 1024
Network.ConnectTimeout 	= 60
Network.ReonnectTimeout = 10
Network.CallTimeout 	= 60
Security		= 1
ServerAddress		= isns.example.com
ServerKeyFile		= /etc/isns/server_key.pub
SourceName		= iqn.2006-01.com.example.host1:monitor


