# /qompassai/dotfiles/.config/kea/kea-dhcp-ddns.conf
# Qompass AI Kea-Dhcp-ddns Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
{
"DhcpDdns":
{
  "ip-address": "127.0.0.1",
  "port": 53001,
  "control-socket": {
      "socket-type": "unix",
      "socket-name": "kea-ddns-ctrl-socket"
  },
  "tsig-keys": [],
  "forward-ddns" : {},
  "reverse-ddns" : {},
  "loggers": [
    {
        "name": "kea-dhcp-ddns",
        "output-options": [
            {
                "output": "kea-ddns.log"
                // "pattern": "%-5p %m\n"
                // "flush": false,
                // "maxsize": 1048576,
                // "maxver": 8
            }
        ],
        "severity": "INFO",
        "debuglevel": 0
    }
  ]
}
}
