#!/bin/sh
# /qompassai/dotfiles/.config/kea/keactrl.conf
# Qompass AI KeaCtrl Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
# shellcheck disable=SC2034
prefix="/usr"
kea_dhcp4_config_file="${prefix}//etc/kea/kea-dhcp4.conf"
kea_dhcp6_config_file="${prefix}//etc/kea/kea-dhcp6.conf"
kea_dhcp_ddns_config_file="${prefix}//etc/kea/kea-dhcp-ddns.conf"
kea_ctrl_agent_config_file="${prefix}//etc/kea/kea-ctrl-agent.conf"
kea_netconf_config_file="${prefix}//etc/kea/kea-netconf.conf"
exec_prefix="${prefix}"
dhcp4_srv="${prefix}/bin/kea-dhcp4"
dhcp6_srv="${prefix}/bin/kea-dhcp6"
dhcp_ddns_srv="${prefix}/bin/kea-dhcp-ddns"
ctrl_agent_srv="${prefix}/bin/kea-ctrl-agent"
netconf_srv="${prefix}/bin/kea-netconf"
dhcp4=yes
dhcp6=yes
dhcp_ddns=no
ctrl_agent=yes
netconf=no
kea_verbose=yes
