; /qompassai/dotfiles/.config/xmake/global.ini
; Qompass AI Xmake Global Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[build]
plat = linux
arch = x86_64
mode = release

[theme]
theme = dark

[cache]
cachedir = /home/phaedrus/.config/xmake/.xmake/cache

[toolchains]
toolchains = /opt/toolchains
ccache = true

[package]
pkg_searchdirs = /home/phaedrus/.config/xmake/packages
pkg_cachedir = /home/phaedrus/.config/xmake/packages/cache
pkg_installdir = /home/phaedrus/.config/xmake/packages/installed

[repository]
repositoriesdir = /home/phaedrus/.config/xmake/repositories

[network]
network = public
proxy = http://proxy.example.com:8080
proxy_hosts = github.com,gitlab.*,*.xmake.io
insecure-ssl = false

[qmake]
qt = /opt/qt
qt_host = /opt/qt/host

[cuda]
cuda = /opt/cuda

[android]
ndk = /opt/android-ndk
ndk_sdkver = 31
android_sdk = /opt/android-sdk
build_toolver = 31.0.0

[vcpkg]
vcpkg = /opt/vcpkg

[mingw]
mingw = /opt/mingw

[emscripten]
emsdk = /opt/emsdk

[service]
debugger = /usr/bin/gdb

[diagnosis]
diagnosis = true

[advanced]
policies = build.warning:all,run.autobuild

[extra]
menu = true


