# /qompassai/dotfiles/.config/signond/signond.conf
# Qompass AI Signond Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
[General]
StoragePath=~$XDG_CONFIG_HOME/signon/
LoggingLevel=2
[SecureStorage]
CryptoManager="cryptsetup"
;AccessControlManager="apparmor-ac"
;SecretsStorage="default"
FileSystemName=signonfs
Size=8
FileSystemType=ext2
[ObjectTimeouts]
IdentityTimeout=30
AuthSessionTimeout=30
DaemonTimeout=5
