# /qompassai/dotfiles/.config/plymouth/plymouthd.conf
# Qompass AI Plymouth Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
[Daemon]
Theme=fade-in
