# /qompassai/dotfiles/.config/sockd/sockd.conf
# Qompass AI Sockd Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
# $Id: sockd.conf,v 1.52.10.2.2.2 2017/01/31 07:16:25 karls Exp $
logoutput: stderr
internal: 10.1.1.1 port = 1080
internal: eth0 port = 1080
#external: 192.168.1.1
#socksmethod: username none #rfc931
#clientmethod: none
#socksmethod: username rfc931 none
#socksmethod: pam
#user.privileged: sockd
#user.unprivileged: sockd
#user.libwrap: libwrap
#compatibility: sameport
#compatibility: reuseaddr
#extension: bind
#timeout.io: 0
#srchost: nodnsunknown nodnsmismatch
client pass {
        from: 10.0.0.0/8 port 1-65535 to: 0.0.0.0/0
        clientmethod: rfc931 # match all idented users that also are in passwordfile
}
client pass {
        from: 10.0.0.0/8 port 1-65535 to: 0.0.0.0/0
}
client block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        log: connect error
}
socks block {
        from: 0.0.0.0/0 to: lo0
        log: connect error
}
socks block {
        from: 0.0.0.0/0 to: 172.16.0.0/12
        libwrap: spawn finger @%a
        log: connect error
}
socks block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        command: bind
        log: connect error
}
socks pass {
        from: 10.0.0.0/8 to: 0.0.0.0/0
        command: bind
        log: connect error
}
socks pass {
        from: 0.0.0.0/0 to: 10.0.0.0/8
        command: bindreply udpreply
        log: connect error
}
socks pass {
        from: 10.0.0.0/8 to: .example.com port = http
        log: connect error
        clientmethod: username
}
socks block {
        from: 0.0.0.0/0 to: .example.com port = http
        log: connect error
}
socks pass {
        from: 10.0.0.0/8 to: 0.0.0.0/0
        protocol: tcp udp
}
socks block {
        from: 0.0.0.0/0 to: 0.0.0.0/0
        log: connect error
}
route {
 from: 10.0.0.0/8 to: 0.0.0.0/0 port = http via: socks.example.net port = socks

