# /qompassai/dotfiles/.config/ufw/ufw.conf
# Qompass AI UFW Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
# References: https://wiki.archlinux.org/title/Uncomplicated_Firewall
ENABLED=yes
LOGLEVEL=low
