[services]
battlenet = True
ea_app = True
egs = True
gog = True
humblebundle = True
itchio = True
steam = True
steamfamily = True
steamwindows = True
ubisoft = True
xdg = True

[lutris]
height = 600
last_library_sync_at = 1780937311
library_ignores = 
icon_type_gridview_egs = game_banner_small
installer_create_desktop_shortcut = True
icon_type_gridview_steam = banner
icon_type_gridview_gog = banner
icon_type_gridview_ubisoft = cover
icon_type_gridview = coverart_med
maximized = True
migration_version = 17
selected_category = platform:Windows
show_advanced_options = True
sidebar_collapsed_sections = runner,service
width = 800
