-- /qompassai/dotfiles/.config/knot-resolver/kresd.conf
-- Qompass AI Knot-Resolver Config
-- Copyright (C) 2025 Qompass AI, All rights reserved
------------------------------
-- vim:syntax=lua:set ts=4 sw=4:
-- References: https://knot-resolver.readthedocs.org/en/stable/
net.listen('127.0.0.1', 53, { kind = 'dns' })
net.listen('127.0.0.1', 853, { kind = 'tls' })
--net.listen('127.0.0.1', 443, { kind = 'doh2' })
net.listen('::1', 53, { kind = 'dns', freebind = true })
net.listen('::1', 853, { kind = 'tls', freebind = true })
net.listen('::1', 443, { kind = 'doh2' })
modules = {
	'hints > iterate',
	'stats',
	'predict',
}
cache.size = 100 * MB
