# /qompassai/dotfiles/.config/vconsole/vconsole.conf
# Qompass AI VConsole Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
KEYMAP=us
XKBLAYOUT=us
XKBMODEL=pc105+inet
XKBOPTIONS=terminate:ctrl_alt_bksp
