# dkms.conf
# Qompass AI RTL8723 DKMS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
PACKAGE_NAME="rtl8723du"
PACKAGE_VERSION="0.1"
MAKE="'make' all -j$(nproc) KVER=${kernelver}"
BUILT_MODULE_NAME[0]="8723du"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless"
AUTOINSTALL="yes"
