# /qompassai/dotfiles/.config/remctl/remctl.conf
# Qompass AI RemCtl Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
include /etc/remctl/conf.d
