# /qompassai/dotfiles/.config/alsa/10-speex.conf
# Qompass AI Advanced Linux Sound Architecture (ALSA) Speex Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################################
pcm.speexrate {
	@args [ SLAVE RATE CONVERTER ]
	@args.SLAVE {
		type string
		default "plug:hw"
	}
	@args.RATE {
		type integer
		default 48000
	}
	@args.CONVERTER {
		type string
		default "speexrate"
	}
	type rate
	converter $CONVERTER
	slave {
		pcm $SLAVE
		rate $RATE
	}
	hint {
		show {
			@func refer
			name defaults.namehint.basic
		}
                description "Rate Converter Plugin Using Speex Resampler"
	}
}
