# /qompassai/dotfiles/.config/alsa/50-arcam-av-ctl.conf
# Qompass AI Advanced Linux Sound Architecture (ALSA) Arcam AV Control Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################################
ctl.arcam_av {
	@args [ PORT ]
	@args.PORT {
		type string
		default "/dev/ttyUSB0"
	}
	type arcam_av
	port $PORT
	hint {
		show {
			@func refer
			name defaults.namehint.basic
		}
		description "Arcam-AV Amplifier"
	}
}
