# /qompassai/dotfiles/.config/alsa/50-oss.conf
# Qompass AI Advanced Linux Sound Architecture (ALSA) Open Source Sound (OSS) Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################################

pcm.oss {
	@args [ DEVICE ]
	@args.DEVICE {
		type string
		default "/dev/dsp"
	}
	type oss
	device $DEVICE
	hint {
		show {
			@func refer
			name defaults.namehint.basic
		}
		description "Open Sound System"
	}
}

ctl.oss {
	@args [ DEVICE ]
	@args.DEVICE {
		type string
		default "/dev/mixer"
	}
	type oss
	device $DEVICE
}
