# /qompassai/dotfiles/.config/soft-serve/soft-serve.conf
a Qompass AI Soft-Serve
# Copyright (C) 2025 Qompass AI, All rights reserved
########################################################

SOFT_SERVE_PORT="$(pass show softserve/port)"
SOFT_SERVE_HOST="$(pass show softserve/host)"
SOFT_SERVE_BIND_ADDRESS="$(pass show softserve/bindadd)"
SOFT_SERVE_KEY_PATH="$(pass show softserve/keypath)"
SOFT_SERVE_REPO_PATH="$(pass show softserve/repos)"
SOFT_SERVE_INITIAL_ADMIN_KEY="$(pass show softserve/akey)"
