# /qompassai/dotfiles/.config/mkpxelinux/mkpxelinux.conf
# Qompass AI Mkpexlinux Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#########################################################
BOOTMESSAGE="/usr/share/mkpxelinux/boot.msg"
KERNEL_BOOT_OPTIONS=""
MKINITCPIO_CONFIG="/etc/mkinitcpio.conf"
VERSION="$(uname -r)"
KERNEL="/boot/vmlinuz-linux"
OPTIONSBOOTMESSAGE="/usr/share/mkpxelinux/options.msg"
PXELINUX_DEFAULT=""
PROMPT="1"
TIMEOUT="300"
INSTALLDIR="/var/tftpboot"
NFSROOTDIR=""
