# /qompassai/dotfiles/.config/ndppd/ndppd.conf
# Qompass AI NdpPPd Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
# Reference: https://manpages.ubuntu.com/manpages/jammy/man5/ndppd.conf.5.html
route-ttl 30000
proxy eth0 {
    router yes
    timeout 500
    ttl 30000
    rule 1111::/128 {
        auto
        # iface eth1
        # static
    }
    # rule <ip>[/<mask>] { ... }
}

