# /qompassai/dotfiles/.config/dkms/v4l2loopback-dc/dkms.conf
# Qompass AI V4L2LoopBack DroidCam DKMS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
PACKAGE_NAME="v4l2loopback_dc"
PACKAGE_VERSION="2.1.4"
MAKE[0]="make all"
BUILT_MODULE_NAME[0]="v4l2loopback-dc"
DEST_MODULE_LOCATION[0]="/updates"
AUTOINSTALL="yes"
