# /qompassai/dotfiles/.config/clustershell/clush.conf.d/sshpass.conf
# Qompass AI Clustershell Sshpass Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[mode:sshpass]
password_prompt: yes
ssh_path: /usr/bin/sshpass /usr/bin/ssh
scp_path: /usr/bin/sshpass /usr/bin/scp
ssh_options: -oBatchMode=no -oStrictHostKeyChecking=no
[mode:sshpass-file]
password_prompt: no
ssh_path: "$(pass show cssh/pwpath)"
scp_path: "$(pass show cssh/scppwpath)"
ssh_options: -oBatchMode=no -oStrictHostKeyChecking=no
