# /qompassai/dotfiles/.config/pipeswitch/pipeswitch.conf
# Qompass AI PipeSwitch Config
# Copyright (C) 2025 Qompass AI, All rights reserved
########################################################
# References: https://github.com/Teascade/pipeswitch/blob/main/README.md#config
[general]
linger_links = false
hotreload_config = true
[log]
level = "INFO"
[link.]
sink = { client = "client_1", node = "node_1" }
source = "Hello there!"
special_empty_ports = true
