; /qompassai/dotfiles/.config/octave/octave-gui.ini
; Qompass AI Octave Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[General]
icon_fallbacks=:/icons/tango/128x128/, :/icons/cursors/
icon_theme=1
monospace_font=3270Medium Nerd Font Mono

[terminal]
fontName=3270Medium Nerd Font Mono
fontSize=9
