# qompasssai/dotfiles/.config/gnupg/gpg.conf
# Qompass AI GNUPG Common Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
# Reference: https://www.gnupg.org/documentation/manuals/gnupg/GPG-Configuration.html
use-keyboxd
