# qompasssai/dotfiles/.config/gnupg/gpgsm.conf
# Qompass AI GNUPGSM Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
agent-program /usr/bin/gpg-agent
armor
auto-issuer-key-retrieve
batch
cipher-algo AES256
compatibility-flags allow-ka-to-encr
digest-algo SHA512
default-key map@qompass.ai
dirmngr-program /usr/bin/dirmngr
enable-ocsp
include-certs 1
log-file ~/.gnupg/gpgsm.log
log-time
no-secmem-warning
verbose
