# /qompassai/dotfiles/.config/NetworkManager/NetworkManager.conf
Qompass AI Network Manager Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
[main]
iwd-convert-path=/var/lib/iwd/
dns=none
plugins=ifupdown,keyfile
migrate-ifcfg-rh=true

[connection]
ipv6.ip6-privacy=2

[device]
wifi.backend=iwd

[ifupdown]
managed=true

[logging]
level=TRACE
domains=ALL
backend=journal
audit=true

[wifi]
powersave = 2
wake-on-wlan = any

[wifi-sec]
pmf = required
fils = enabled

[wireguard]
mtu = 1420
