# /qompassai/dotfiles/foot/foot.ini
# Qompass AI Foot Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
# References: https://man.archlinux.org/man/foot.ini.5.en
[bell]
command=none
command-focused=no
notify=no
system=no
urgent=no
visual=no
[colors]
alpha=0.25
alpha-mode=default
background=000000
cursor=7DF9FF 000000
dim-blend-towards=black
flash=FFF97D
foreground=00FFFF
selection-background=7DF9FF
[csd]
border-width=0
double-click-to-maximize=yes
font=DaddyTimeMono Nerd Font Mono:size=13
preferred=server
size=26
[cursor]
beam-thickness=1.5
blink=no
blink-rate=500
style=beam
unfocused-style=hollow
[desktop-notifications]
command-action-argument=--action ${action-name}=${action-label}
inhibit-when-focused=yes
[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
font-decrease=Control+minus Control+KP_Subtract
font-increase=Control+plus Control+equal Control+KP_Add
font-reset=Control+0 Control+KP_0
maximize=none
minimize=none
quit=Control+q
scrollback-down-page=Page_Down
scrollback-up-line=none
scrollback-up-page=Page_Up
scrollback-up-half-page=none
search-start=Control+f
show-urls-launch=Control+Shift+s
spawn-terminal=Control+Shift+f
unicode-input=Control+Shift+i
[main]
bold-text-in-bright=no
box-drawings-uses-font-glyphs=yes
dpi-aware=yes
font=DaddyTimeMono Nerd Font Mono:size=12
font-size-adjustment=1
gamma-correct-blending=off
horizontal-letter-offset=0
#initial-color-theme=1
#letter-spacing=2px
#line-height=13px
#pad=25x25
resize-delay-ms=100
term=foot
title=foot
uppercase-regex-insert=yes
[mouse]
[scrollback]
indicator-format=""
indicator-position=relative
lines=10000
multiplier=4.0
[search-bindings]
cancel=Escape
commit=Control+Alt+c
delete-prev-word=Control+BackSpace
find-next=F3 Control+G
find-prev=Shift+F3
[text-bindings]
\x03=Control+Shift+d
[tweak]
bold-text-in-bright-amount=1.4
box-drawing-base-thickness=0.05
box-drawing-solid-shades=yes
damage-whole-window=no
delayed-render-lower=500000
delayed-render-upper=8333333
dim-amount=1.0
font-monospace-warn=no
grapheme-shaping=yes
grapheme-width-method=double-width
min-stride-alignment=256
max-shm-pool-size-mb=65536
overflowing-glyphs=yes
pre-apply-damage=yes
#render-timer=both
scaling-filter=lanczos3
sixel=yes
surface-bit-depth=auto
[url]
label-letters=sadfjklewcmpgh
launch=xdg-open ${url}
osc8-underline=url-mode
regex=(((https?://|mailto:|ftp://|file:|ssh:|ssh://|git://|tel:|magnet:|ipfs://|ipns://|gemini://|gopher://|news:)|www.)([0-9a-zA-Z:/?#@!$&*+,;=.~_%^-]+|([]["0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*)|[[()"0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*]|"[][()0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*"|'[][()0-9a-zA-Z:/?#@!$&*+,;=.~_%^-]*')+([0-9a-zA-Z/#@$&*+=~_%^-]|([]["0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*)|[[()"0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*]|"[][()0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*"|'[][()0-9a-zA-Z:/?#@!$&*+,;=.~_%^-]*'))
