# /qompassai/dotfiles/foot/foot.ini
[colors]
background=000000
foreground=7DF9FF

[cursor]
beam-thickness=1.5
blink=no
style=beam

[key-bindings]
clipboard-copy=Control+c
clipboard-paste=Control+v
font-decrease=Control+minus Control+KP_Subtract
font-increase=Control+plus Control+equal Control+KP_Add
font-reset=Control+0 Control+KP_0
scrollback-down-page=Page_Down
scrollback-up-page=Page_Up
search-start=Control+f
spawn-terminal=Control+Alt+n


[main]
bold-text-in-bright=no
dpi-aware=no
font=DaddyTimeMono Nerd Font Mono:size=12
letter-spacing=0
pad=25x25
term=xterm-256color
title=foot

[scrollback]
lines=10000

[search-bindings]
cancel=Escape
delete-prev-word=Control+BackSpace
find-next=F3 Control+G
find-prev=Shift+F3

[text-bindings]
\x03=Control+Shift+c

[tweak]
font-monospace-warn=no

[url]
launch=xdg-open ${url}
