# /qompassai/dotfiles/foot/foot.ini
# Qompass AI Foot Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
# References: https://man.archlinux.org/man/foot.ini.5.en
[bell]
command=none
command-focused=no
notify=no
system=no
urgent=no
visual=no
[colors]
alpha=1.0
alpha-mode=matching
background=000000
cursor=ff0000 00ff00
dim-blend-towards=black
flash=7f7f00
foreground=7DF9FF
[cursor]
beam-thickness=1.5
blink=no
blink-rate=500
style=beam
underline-thickness=font underline thickness
unfocused-style=hollow
[desktop-notifications]
command-action-argument=--action ${action-name}=${action-label}
inhibit-when-focused=yes
[key-bindings]
clipboard-copy=Control+Shift+c XF86Copy
clipboard-paste=Control+Shift+v XF86Paste
font-decrease=Control+minus Control+KP_Subtract
font-increase=Control+plus Control+equal Control+KP_Add
font-reset=Control+0 Control+KP_0
maximize=none
minimize=none
quit=Control+q
scrollback-down-page=Page_Down
scrollback-up-line=none
scrollback-up-page=Page_Up
scrollback-up-half-page=none
search-start=Control+f
show-urls-launch=Control+Shift+s
spawn-terminal=Control+Shift+f
unicode-input=Control+Shift+i
[main]
bell=no
bold-text-in-bright=no
box-drawings-uses-font-glyphs=no
dpi-aware=yes
font=DaddyTimeMono Nerd Font Mono:size=12
font-size-adjustment=0.75
gamma-correct-blending=yes
horizontal-letter-offset=0
ime=yes
letter-spacing=0
line-height=13px
pad=25x25
resize-delay-ms=100
sixel-support=yes
term=foot
title=foot
uppercase-regex-insert=yes
[mouse]
long-press-delay=400
[scrollback]
indicator-format=
indicator-position=relative
lines=10000
multiplier=4.0
[search-bindings]
cancel=Escape
commit=Control+Shift+c
delete-prev-word=Control+BackSpace
find-next=F3 Control+G
find-prev=Shift+F3
[text-bindings]
\x03=Control+Shift+c
[tweak]
allow-overflowing-double-width-glyphs=yes
bold-text-in-bright-amount=1.4
box-drawing-base-thickness=0.05
box-drawing-solid-shades=yes
damage-whole-window=no
delayed-render-lower=500000
delayed-render-upper=8333333
dim-amount=1.5
font-monospace-warn=no
grapheme-shaping=yes
grapheme-width-method=double-width
min-stride-alignment=256
max-shm-pool-size-mb=65536
overflowing-glyphs=yes
pre-apply-damage=yes
render-timer=both
scaling-filter=lanczos3
sixel=yes
surface-bit-depth=auto
[url]
label-letters=sadfjklewcmpgh
launch=xdg-open ${url}
osc8-underline=url-mode
regex=(((https?://|mailto:|ftp://|file:|ssh:|ssh://|git://|tel:|magnet:|ipfs://|ipns://|gemini://|gopher://|news:)|www.)([0-9a-zA-Z:/?#@!$&*+,;=.~_%^-]+|([]["0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*)|[[()"0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*]|"[][()0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*"|'[][()0-9a-zA-Z:/?#@!$&*+,;=.~_%^-]*')+([0-9a-zA-Z/#@$&*+=~_%^-]|([]["0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*)|[[()"0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*]|"[][()0-9a-zA-Z:/?#@!$&'*+,;=.~_%^-]*"|'[][()0-9a-zA-Z:/?#@!$&*+,;=.~_%^-]*'))
