---@class LazyPluginSpec
---@field [1] string? Plugin name or path
---@field name string? Optional plugin name
-----@field dir string? Local directory for plugin
-----@field url string? Custom git url
-----@field dev boolean? Use local dev version
-----@field lazy boolean? Whether to lazy-load
---@field enabled boolean? | fun():boolean Whether the plugin is enabled
---@field cond boolean? | fun():boolean Load condition
---@field dependencies string[] | LazyPluginSpec[] Plugin dependencies
---@field init fun(LazyPlugin)? Function executed during startup
---@field opts table? | fun(LazyPlugin):table? Options for plugin
---@field config fun(LazyPlugin, opts:table)? | boolean Plugin configuration
---@field main string? Main module for config
---@field build string? | fun(LazyPlugin) Build command
---@field branch string? Git branch
---@field event string? | string[] Events that trigger loading
---@field cmd string? | string[] Commands that trigger loading
---@field ft string? | string[] Filetypes that trigger loading
---@field keys string? | string[] Keys that trigger loading
---@field priority number? Load priority for start plugins
