# /qompassai/dotfiels/.config/kde.org/UserFeedback.org.kde.dolphin.conf
# Qompass AI Kde.org Dolphin Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[Source-applicationVersion]
dataSourceCommonSettings\activeState=false

[Source-locale]
dataSourceCommonSettings\activeState=false

[Source-places]
dataSourceCommonSettings\activeState=true

[Source-platform]
dataSourceCommonSettings\activeState=true

[Source-qtVersion]
dataSourceCommonSettings\activeState=true

[Source-screens]
dataSourceCommonSettings\activeState=true

[Source-settings]
dataSourceCommonSettings\activeState=true

[Source-startCount]
dataSourceCommonSettings\activeState=true

[Source-usageTime]
dataSourceCommonSettings\activeState=true

[UserFeedback]
ApplicationStartCount=24
ApplicationTime=9155
