# /qompassai/dotfiles/.config/fwupd/fwupd.conf
# Qompass AI - [Add description here]
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
[fwupd]
ArchiveSizeMax=256
DisabledDevices=
DisabledPlugins=
IdleInhibitStartupThreshold=500
IdleTimeout=300
P2pPolicy=nothing
TestDevices=false
TrustedReports=
UpdateMotd=true
VerboseDomains=
[uefi_capsule]
DisableCapsuleUpdateOnDisk=false
DisableShimForSecureBoot=true
EnableEfiDebugging=false
EnableGrubChainLoad=false
RebootCleanup=true
RequireESPFreeSpace=0
ScreenHeight=0
ScreenWidth=0
