# /qompassai/dotfiles/.config/openmpi/openmpi-mca-params.conf
# Qompass AI OpenMPI MCA Params Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
 $HEADER$
 "$XDG_CONFIG_HOME/openmpi/mca-params.conf:$sysconf/openmpi-mca-params.conf"
mpi_param_check = 0
mca_base_component_path = /usr/local/lib/openmpi:~/my_openmpi_components
# See "ompi_info --param all all --level 9" for a full listing of Open
