# /qompassai/dotfiles/.config/nix/nix.conf
#
accept-flake-config = true
allow-import-from-derivation = true
allowed-users = @nixbld phaedrus @wheel *
auto-optimise-store = true
build-users-group = nixbld
builders-use-substitutes = true
cores = 0
connect-timeout = 5
download-attempts = 3
experimental-features = nix-command flakes pipe-operators ca-derivations recursive-nix auto-allocate-uids cgroups dynamic-derivations fetch-closure no-url-literals
extra-sandbox-paths = /dev/nvidia0 /dev/nvidiactl /dev/nvidia-modeset /dev/nvidia-uvm /dev/nvidia-uvm-tools
extra-trusted-public-keys = cache.flakehub.com-3:hJuILl5sVK4iKm86JzgdXW12Y2Hwd5G07qKtHTOcDCM= cache.flakehub.com-4:Asi8qIv291s0aYLyH6IOnr5Kf6+OF14WVjkE6t3xMio= cuda-maintainers.cachix.org-1:0dq3bujKpuEPMCX6U4WylrUDZ9JyUG0VpVZa7CNfq5E= cache.iog.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=
extra-substituters = https://cache.flakehub.com/ https://cuda-maintainers.cachix.org https://cache.iog.io
fallback = true
flake-registry = https://github.com/NixOS/flake-registry/raw/master/flake-registry.json
gc-keep-outputs = true
gc-reserved-space = 4294967296
http-connections = 25
keep-derivations = true
keep-env-derivations = true
 keep-going = true
keep-outputs = true
log-lines = 50
max-jobs = auto
max-substitution-jobs = 16
min-free = 4294967296
max-free = 10737418240
narinfo-cache-negative-ttl = 3600
require-sigs = true
sandbox = false
show-trace = true
stalled-download-timeout = 300
substituters = https://cache.nixos.org https://nix-community.cachix.org
system-features = nixos-test benchmark big-parallel kvm cuda
netrc-file = /home/phaedrus/.config/nix/netrc
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs=
trusted-substituters = https://cache.nixos.org
trusted-users = phaedrus
use-xdg-base-directories = true
warn-dirty = false
