# /qompassai/dotfiles/.config/fwupd/remotes.d/lvfs-testing.conf
# Qompass AI Fwupd Remotes Linux Vendor Firmware Service (LVFS) Testing Remote Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[fwupd Remote]
AutomaticReports=true
ApprovalRequired=false
Enabled=true
FirmwareBaseURI=https://fwupd.org/downloads
MetadataURI=https://cdn.fwupd.org/downloads/firmware-testing.xml.zst
PrivacyURI=https://lvfs.readthedocs.io/en/latest/privacy.html
OrderBefore=lvfs
ReportURI=https://fwupd.org/lvfs/firmware/report
Title=Linux Vendor Firmware Service (testing)
