# /qompassai/dotfiles/.config/fwupd/remotes.d/lvfs.conf
# Qompass AI Fwupd Remotes LVFS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[fwupd Remote]
ApprovalRequired=false
AutomaticReports=true
AutomaticSecurityReports=true
Enabled=true
FirmwareBaseURI=https://fwupd.org/downloads
MetadataURI=https://cdn.fwupd.org/downloads/firmware.xml.zst
Title=Linux Vendor Firmware Service
ReportURI=https://fwupd.org/lvfs/firmware/report
PrivacyURI=https://lvfs.readthedocs.io/en/latest/privacy.html
