# /qompassai/dotfiles/.config/environment.d/xdg.conf
# Qompass AI Environmentd XDG Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
# Reference: https://wiki.archlinux.org/title/XDG_Base_Directory | https://man.archlinux.org/man/xdg-settings.1
# Qompass AI environment.d XDG configuration

LANG=en_US.UTF-8

XDG_BIN_HOME=$HOME/.local/bin
PATH=$HOME/.local/bin:$PATH

XDG_CACHE_HOME=$HOME/.cache
XDG_CONFIG_HOME=$HOME/.config
XDG_DATA_HOME=$HOME/.local/share
XDG_STATE_HOME=$HOME/.local/state

XDG_CONFIG_DIRS=$HOME/.config/xdg:/etc/xdg:/usr/local/etc/xdg:/usr/etc/xdg
XDG_DATA_DIRS=$HOME/.local/share:$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/nix/var/nix/profiles/default/share:/usr/local/share:/usr/share
