# /qompassai/dotfiles/.config/environment.d/xdg.conf
# Qompass AI Environmentd XDG Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
# Reference: https://wiki.archlinux.org/title/XDG_Base_Directory | https://man.archlinux.org/man/xdg-settings.1
LANG=en_US.UTF-8
PATH=$PATH:$HOME/.local/bin
XDG_BIN_HOME=$HOME/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin
XDG_CACHE_HOME=$HOME/.cache
XDG_CONFIG_DIRS=$XDG_CONFIG_HOME/xdg
XDG_CONFIG_HOME=$HOME/.config
XDG_CURRENT_DESKTOP=Hyprland
XDG_CURRENT_SESSION=Hyprland
XDG_DATA_DIRS=$HOME/.local/share:/usr/local/share:/usr/share
XDG_DATA_HOME=$HOME/.local/share
XDG_DESKTOP_DIR=$HOME/.Desktop
XDG_DESKTOP_PORTAL_DIR=/run/user/1000/xdg-desktop-portal/portals
XDG_DOCUMENTS_DIR=$HOME/.Documents
XDG_DOWNLOAD_DIR=$HOME/.Downloads
XDG_LIB_HOME=$HOME/.local/lib
XDG_MUSIC_DIR=$HOME/.Music
XDG_PICTURES_DIR=$HOME/.Pictures
XDG_RUNTIME_DIR=/run/user/1000
XDG_SESSION_DESKTOP=Hyprland
XDG_SESSION_TYPE=wayland
XDG_STATE_HOME=$HOME/.local/state
XDG_VIDEOS_DIR=$HOME/.Videos
### Debug
XDG_UTILS_DEBUG_LEVEL=3
