# /qompassai/dotfiles/.config/environment.d/wayland.conf
# Qompass AI Environemnt.d Wayland Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
CLUTTER_BACKEND=wayland
MOZ_ENABLE_WAYLAND=1
OZONE_PLATFORM=wayland

