# /qompassai/dotfiles/.config/environment.d/01_wayland.conf
# Qompass AI Environemnt.d Wayland Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
CLUTTER_BACKEND=wayland
MOZ_ENABLE_WAYLAND=1
OZONE_PLATFORM=wayland
BEMENU_BACKEND=wayland
BEMENU_OPTS=--fn 'FiraCode 12' --nb '#222' --nf '#fff'
BEMENU_RENDERER=gles2
