# /qompassai/dotfiles/.config/environmentd./apps.conf
# Qompass AI Environment.d Apps Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
BROWSER=firefox
FFMPEG_INCLUDE_DIR=/usr/include
FFMPEG_LIB_DIR=/usr/lib
FFMPEG_DIR=/usr/include/ffmpeg4.4
TERMINAL=ghostty
