# /qompassai/dotfiles/.config/environemnt.d/10_qt.conf
# Qompass AI Environemnt.d QT Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
QML_IMPORT_PATH=/usr/lib/qt6/qml:$XDG_DATA_HOME/qml:$XDG_CONFIG_HOME/qml
QML2_IMPORT_PATH=/usr/lib/qt6/qml:$XDG_DATA_HOME/qml:$XDG_CONFIG_HOME/qml
QT_QPA_PLATFORM=wayland;xcb
QT_QPA_PLATFORMTHEME=xdgdesktopportal
