# /qompassai/dotfiles/.config/environment.d/hypr.conf
# Qompass AI Environment.d Hypr Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
BEMENU_BACKEND=wayland
EGL_PLATFORM=wayland
HYPRSHOT_DIR="$HOME/.Pictures"
SDL_VIDEODRIVER=wayland,x11
WLR_NO_HARDWARE_CURSORS=0
_JAVA_AWT_WM_NONREPARENTING=1
