# /qompassai/dotfiles/.config/environment.d/git.conf
# Qompass AI Environment.d Git Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
GIT_CONFIG_GLOBAL=$XDG_CONFIG_HOME/git/config
GIT_CREDENTIAL_CACHE_TIMEOUT=3600
GIT_DISCOVERY_ACROSS_FILESYSTEM=1
GIT_EDITOR=nvim
GIT_LFS_SKIP_SMUDGE=1
GIT_OPTIONAL_LOCKS=0
GIT_PAGER=nvimpager
GIT_PROTOCOL_VERSION=2
GIT_SSH_COMMAND=ssh -o ControlMaster=auto -o ControlPersist=600
GIT_SSL_CAINFO=/etc/ssl/certs/ca-certificates.crt
GIT_TERMINAL_PROMPT=1
JJ_EDITOR=nvim
JJ_PAGER=nvimpager
JJ_TERMINAL_PROMPT=1
SOPS_AGE_KEY_FILE=$XDG_CONFIG_HOME/sops/age/keys.txt

