# /qompassai/dotfiles/.config/environment.d/bemenu.conf
# Qompass AI Environmentd Bemenu Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
BEMENU_BACKEND=wayland
BEMENU_OPTS=--fn 'FiraCode 12' --nb '#222' --nf '#fff'
BEMENU_RENDERER=gles2
