# /qompassai/dotfiles/.config.environment.d/hf.conf
# Qompass AI Environment.d HF Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
HF_API_ENDPOINT=https://huggingface.co/api
HF_DATASETS_CACHE=$XDG_CACHE_HOME/huggingface/datasets
HF_ENDPOINT=https://huggingface.co
HF_HOME=$XDG_CACHE_HOME/huggingface
HF_HUB_CACHE=$XDG_CACHE_HOME/huggingface/hub
HF_METRICS_CACHE=$XDG_CACHE_HOME/huggingface/metrics
HF_MODULES_CACHE=$XDG_CACHE_HOME/huggingface/modules
HF_HUB_ENABLE_HF_TRANSFER=1
HF_HUB_DISABLE_PROGRESS_BARS=0
HF_HUB_DISABLE_TELEMETRY=1
HF_HUB_OFFLINE=0
HF_TOKEN=$(pass show hf)
