# /qompassai/dotfiles/.config/environment.d/go.conf
# Qompass AI Environemnt.d Go Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###################################################
GOBIN=$HOME/.go/bin
GOCACHE=$XDG_CACHE_HOME/go-build
GOMODCACHE=$XDG_CACHE_HOME/go-mod
GOENV=$XDG_CONFIG_HOME/go/env
GO111MODULE=on
PATH="${HOME}/.go/bin:${PATH}"
PATH="$(go env GOPATH)/bin:$PATH"
