# /qompassai/dotfiles/.config/environment.d/lua.conf
# Qompass AI Environmentd Lua Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
LUAJIT_HOME=$HOME/.local
LUAJIT_INC=$LUAJIT_HOME/include/luajit-2.1
LUAJIT_LIB=$LUAJIT_HOME/lib
LUAJIT_BIN=$LUAJIT_HOME/bin/luajit-2.1.0-beta3
LUA_VERSION=luajit
LUA_PATH=$LUAJIT_HOME/share/luajit-2.1.0-beta3/?.lua;$LUAJIT_HOME/share/luajit-2.1.0-beta3/?/init.lua;;"
LD_LIBRARY_PATH=$LUAJIT_LIB:$LD_LIBRARY_PATH
PATH="$LUAJIT_HOME/bin:$PATH"
XMAKE_GLOBALDIR=$XDG_CONFIG_HOME/xmake
XMAKE_CONFIGDIR="$XDG_CONFIG_HOME/xmake/project"
XMAKE_PKG_CACHEDIR="$XDG_CACHE_HOME/xmake/pkg"
XMAKE_TMPDIR="$XDG_CACHE_HOME/xmake/tmp"
XMAKE_PKG_INSTALLDIR="$XDG_DATA_HOME/xmake/pkg"
XMAKE_LOGFILE=$XDG_CACHE_HOME/xmake/xmake.log
