# /qompassai/dotfiles/.config/environment.d/mojo.conf
# Qompass AI Environment.d Mojo Config
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
MOJO_HOME=$XDG_DATA_HOME/mojo
MOJO_CACHE_DIR=$XDG_CACHE_HOME/mojo
MOJO_RATTLER_CACHE_DIR=$XDG_CACHE_HOME/mojo/rattler
MODO_THEME=default
PATH="$HOME/.pixi/bin:$PATH"
RATTLER_BUILD_BIN=/usr/bin/rattler-build
