# /qompassai/dotfiles/.config/environment.d/mojo.conf
# Qompass AI Environment.d Mojo Config
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
PATH=$HOME/.modular/bin:$PATH
MOJO_HOME=%h/.local/share/mojo
MOJO_CACHE_DIR=$XDG_CACHE_HOME/mojo
MOJO_RATTLER_CACHE_DIR=$XDG_CACHE_HOME/mojo/rattler
MODO_THEME=default
RATTLER_BUILD_BIN=/usr/bin/rattler-build
