# /qompassai/dotfiles/.config/environment.d/rust.conf
# Qompass AI Environment.d Rust Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
CARGO_HOME=$HOME/.cargo
CARGO_INCREMENTAL=1
CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
CARGO_TARGET_DIR=$XDG_CACHE_HOME/cargo-target
CARGO_TERM_COLOR=auto
CARGO_TERM_PROGRESS_WHEN=auto
RUST_BACKTRACE=full
RUSTC_WRAPPER=sccache
RUST_LOG=debug
RUSTUP_HOME=$HOME/.rustup
