# /qompassai/dotfiles/.config/environment.d/rust.conf
# Qompass AI Environment.d Rust Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
CARGO_HOME=$XDG_DATA_HOME/.cargo
CARGO_PROFILE_RELEASE_BUILD_OVERRIDE_DEBUG=true
RUST_BACKTRACE=full
RUST_LOG=debug
RUSTUP_HOME=$XDG_DATA_HOME/rustup
