# /qompassai/dotfiles/.config/environment.d/zig.conf
# Qompass AI Environment.d Zig Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
ZIG_BTRFS_WORKAROUND=1
ZIGCC="zig cc"
ZIGCPP="zig c++"
ZIG_GLOBAL_CACHE_DIR=$XDG_CACHE_HOME/zig
ZIG_LIBC=x86_64-linux-gnu
ZIG_LIB_DIR=$HOME/.ziglibs
ZIG_LOCAL_CACHE_DIR=$XDG_DATA_HOME/zig/cache
ZIG_MCPU=native
ZIG_PKG_CONFIG_PATH=$HOME/.pkgconfig:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig
ZIG_SYSTEM_LINKER_HACK=1
ZIG_VERBOSE_CC=1
ZIG_VERBOSE_LINK=1
ZLS_CONFIG_PATH=$XDG_CONFIG_HOME/zls/zls.jsonc
ZVM_INSTALL=$HOME/.zvm/self
