# 28_android.conf
# Qompass AI Environment.d Android Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
ANDROID_NDK_ROOT=/opt/android-ndk
