# /qompassai/dotfiles/.config/environment.d/33_vckpkg.conf
# Qompass AI Environment.d Vcpkg Config
# Copyright (C) 2025 Qompass AI, All rights reserved
########################################
VCPKG_ROOT=$HOME/.local/share/vcpkg
CMAKE_TOOLCHAIN_FILE=$HOME/.local/share/vcpkg/scripts/buildsystems/vcpkg.cmake

