# 34_ninja.conf
# Qompass AI Environment.d Ninja Config
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
NINJA_FIX_REQUEST_FILES_METHODS=True
NINJA_DEFAULT_THROTTLE_RATES=60/min
DJANGO_SETTINGS_MODULE=myproject.settings
DEFAULT_THROTTLE_RATES=60/min
NUM_PROXIES=1
PAGINATION_MAX_LIMIT=100
NINJA_PAGINATION_MAX_LIMIT=100
PAGINATION_MAX_PER_PAGE_SIZE=100
