# /qompassai/dotfiles/.config/environment.d/35_distcc.conf
# Qompass AI Environment.d Distcc Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
DISTCC_DIR="$HOME/.config/distcc"
