# /qompassai/dotfiles/.config/environment.d/36_python.conf
# Qompass AI Environment.d Python Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###########################################################
BLACK_CACHE_DIR=$XDG_CACHE_HOME/black
CONDA_AUTO_ACTIVATE_BASE=false
HF_HOME=$XDG_CACHE_HOME/huggingface
IPYTHON_DIR="$HOME/.config/ipython"
JUPYTER_CONFIG_DIR="$HOME/.config/jupyter"
MPLCONFIGDIR="$HOME/.config/matplotlib"
NINJA_PAGINATION_CLASS="ninja_extra.pagination.LimitOffsetPagination"
NINJA_PAGINATION_PER_PAGE=100
MYPY_CACHE_DIR=$XDG_CACHE_HOME/mypy
NUMBA_CACHE_DIR=$XDG_CACHE_HOME/numba
PIP_CERT="/etc/ssl/certs/ca-certificates.crt"
PIP_DEFAULT_TIMEOUT=100
PIP_DISABLE_PIP_VERSION_CHECK=1
PIP_INDEX_URL="https://pypi.org/simple/"
PIP_NO_BUILD_ISOLATION=0
PIP_NO_CACHE_DIR=1
PIP_PROGRESS_BAR="on"
PIP_RESPECT_VENV_ENV=false
PIP_REQUIRE_HASHES=false
PIP_REQUIRE_VIRTUALENV=false
POETRY_CACHE_DIR=$XDG_CACHE_HOME/poetry
POETRY_HOME=$XDG_DATA_HOME/poetry
POETRY_VENV_IN_PROJECT=true
#PRE_COMMIT_HOME="$HOME/.cache/pre-commit"
PYENV_ROOT="$HOME/.pyenv"
PATH="$PYENV_ROOT/bin:$PATH"
#eval "$(pyenv init -)"
# eval "$(pyenv virtualenv-init -)"
PYTEST_CACHE_DIR=$XDG_CACHE_HOME/pytest
PYTHON="python3"
PYTHONFAULTHANDLER="1"
PYTHONHASHSEED="random"
PYTHONIOENCODING="utf-8"
PYTHONOPTIMIZE=1
PYTHONSTARTUP="$HOME/.config/pythonrc.py"
PYTHONUNBUFFERED=1
PYTHONNOUSERSITE=1
PYTHONWARNINGS="ignore::DeprecationWarning"
REQUESTS_CA_BUNDLE="/etc/ssl/certs/ca-certificates.crt"
SSL_CERT_FILE="/etc/ssl/certs/ca-certificates.crt"
TORCH_HOME=$XDG_CACHE_HOME/torch
VIRTUAL_ENV_DISABLE_PROMPT="1"
