# /qompassai/dotfiles/.config/environment.d/browser.conf
# Qompass AI Environment.d Browser Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
MOZ_ENABLE_WAYLAND=1
OZONE_PLATFORM=wayland
