# /qompassai/dotfiles/.config/environment.d/containers.conf
# Qompass AI Containers Environment.d Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
CONTAINERS_CONF=%h/.config/containers/containers.conf
CONTAINERS_REGISTRIES_CONF=%h/.config/containers/registries.conf
CONTAINERS_STORAGE_CONF=%h/.config/containers/storage.conf
DOCKER_BUILDKIT=1
DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
DOCKER_HOST=unix:///run/user/1000/docker.sock
