#~/.config/environment.d/envvars.conf

BEMENU_BACKEND=wayland
EDITOR=nvim
EGL_PLATFORM=wayland
GBM_BACKEND=nvidia-drm
GDK_BACKEND=wayland,x11
GTK_USE_PORTAL=1
LIBVA_DRIVER_NAME=nvidia
MESA_GLSL_CACHE_MAX_SIZE=32G
MESA_GLSL_CACHE_DIR=$XDG_CACHE_HOME/mesa_shader_cache
MESA_SHADER_CACHE_DIR=$XDG_CACHE_HOME/mesa_shader_cache_db
MESA_VK_WSI_DISPLAY=wayland
MOZ_ENABLE_WAYLAND=1
OZONE_PLATFORM=wayland
OCL_ICD_VENDORS=$XDG_CONFIG_HOME/OpenCL/vendors
RUSTICL_FEATURES=fp16,fp64
RUSTUP_HOME=$XDG_DATA_HOME/rustup
QML2_IMPORT_PATH=/usr/lib/qt6/qml
QT_QPA_PLATFORM=wayland;xcb
QT_STYLE_OVERRIDE=hyprland-quick-style
SDL_VIDEODRIVER=wayland,x11
SSH_AUTH_SOCK=$XDG_RUNTIME_DIR/ssh-agent.socket
VISUAL=nvim
WLR_NO_HARDWARE_CURSORS=0
_JAVA_AWT_WM_NONREPARENTING=1
__GL_ALLOW_FLIPPING=1
__GL_SHADER_DISK_CACHE_SIZE=10737418240
__GL_SHADER_DISK_CACHE_SKIP_CLEANUP=1
__GLX_VENDOR_LIBRARY_NAME=nvidia
