# ffmpeg.conf
# Qompass AI - [Add description here]
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
FFMPEG_INCLUDE_DIR=/usr/include
FFMPEG_LIB_DIR=/usr/lib
FFMPEG_DIR=/usr/include/ffmpeg4.4

