# /qompassai/dotfiles/.config/environment.d/git.conf
# Qompass AI Environment.d Git Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
GIT_DISCOVERY_ACROSS_FILESYSTEM=1
GIT_EDITOR='nvim'
GIT_LFS_SKIP_SMUDGE=1
GIT_PAGER='nvimpager'
GIT_TERMINAL_PROMPT=1
JJ_EDITOR='nvim'
JJ_PAGER='nvimpager'
JJ_TERMINAL_PROMPT=1
