# /qompassai/dotfiles/.config/environment.d/gtk.conf
# Qompass AI Environment.d GTK Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
GDK_BACKEND=wayland,x11
GDK_PIXBUF_MODULE_FILE=/usr/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache
GDK_RENDERING=wayland
GDK_SCALE=1
GTK_CSD=1
GTK_MEDIA=gstreamer
GTK_MODULES=colorreload
GTK_USE_PORTAL=1
GTK_VIDEOSINK=waylandsink
