# hf.conf
# Qompass AI - [Add description here]
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
HF_API_ENDPOINT=https://huggingface.co/api
HF_DATASETS_CACHE=%h/.cache/huggingface/datasets
HF_ENDPOINT=https://huggingface.co
HF_HOME=%h/.cache/huggingface
HF_HUB_CACHE=%h/.cache/huggingface/hub
HF_METRICS_CACHE=%h/.cache/huggingface/metrics
HF_MODULES_CACHE=%h/.cache/huggingface/modules
HF_HUB_ENABLE_HF_TRANSFER=1
HF_HUB_DISABLE_PROGRESS_BARS=0
HF_HUB_DISABLE_TELEMETRY=1
HF_HUB_OFFLINE=0
