# lang.conf
# Qompass AI - [Add description here]
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
LANG="en_US.UTF-8"
PATH="$XDG_DATA_HOME/tilt/bin:${PATH}"
PATH="$HOME/.local/share/racket/bin:$PATH"
