# /qompassai/dotfiles/.config/latex.conf
# Qompass AI Environment.d LaTeX Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
TEXMF=$XDG_DATA_HOME/texmf-dist/texmf-context
