# mojo.conf
# Qompass AI Environment Mojo Config
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
#MOJO_PROJECT_TOML=$MOJO_PROJECT_ROOT/mojoproject.toml
MOJO_CACHE_DIR=$XDG_CACHE_HOME/mojo
#MOJO_RATTLER_CACHE_DIR=$XDG_CACHE_HOME/mojo/rattler
#MODO_THEME=default
#MODO_OUTPUT_DIR=$MOJO_PROJECT_ROOT/docs
#RATTLER_BUILD_BIN=/usr/bin/rattler-build

