# /qompassai/dotfiles/.config/environment.d/nix.conf
# Qompass AI Environmentd Nix Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
NIXPKGS_ALLOW_UNFREE=1
XDG_DATA_DIRS=$HOME/.nix-profile/share:$HOME/.local/share:/usr/local/share:/usr/share
NIX_SHOW_TRACE=1
NIX_NETRC_FILE=$HOME/.config/nix/netrc
NIX_SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
