# utils.conf
# Qompass AI - [ ]
# Copyright (C) 2026 Qompass AI, All rights reserved
# ----------------------------------------
 INFODIR=$HOME/.local/share/info:/usr/local/share/info:/usr/share/info
 MANPATH=$HOME/.local/share/man:/usr/local/share/man:/usr/share/man
