# /qompassai/dotfiles/.config/sssd/sssd.conf
# Qompass AI SSSD Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
[domain/local]
id_provider = local
[sssd]
domains = local
services = nss, pam
debug_level = 9
