# /qompassai/dotfiles/.config/kismet/kismet_logging.conf
# Qompass AI Kismet Loggin Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
enable_logging=true
log_title=Kismet
log_prefix=./
log_types=kismet
log_template=%p/%n-%D-%t-%i.%l
kis_log_devices=true
kis_log_device_rate=30
kis_log_packets=true
# kis_log_duplicate_packets=true
kis_log_data_packets=true
kis_log_messages=true
kis_log_alerts=true
kis_log_datasources=true
kis_log_datasources_rate=30
kis_log_channel_history=true
kis_log_channel_history_rate=20
kis_log_gps_track=true
kis_log_system_status=true
kis_log_system_status_rate=30
kis_log_alert_timeout=86400
kis_log_device_timeout=86400
kis_log_message_timeout=86400
kis_log_packet_timeout=86400
kis_log_snapshot_timeout=86400
kis_log_ephemeral_dangerous=false
pcapng_log_duplicate_packets=true
pcapng_log_data_packets=true
ppi_log_duplicate_packets=true
ppi_log_data_packets=true
log_config_present=true
