# /qompassai/dotfiles/.config/kismet/kismet_memory.conf
# Qompass AI Kismet Memory Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
anuf_lookup=true
alertbacklog=50
keep_location_cloud_history=true
keep_per_datasource_stats=true
packet_backlog_limit=8192
packet_backlog_warning=0
packet_dedup_size=2048
rtl433_track_last=false
tracker_max_devices=10000
tracker_device_presize=1000
tracker_device_packets=20
track_device_rrds=true
track_device_seenby_views=true
tracker_device_timeout=7200
track_device_phy_views=true
ulimit_mbytes=16384
