# /qompassai/dotfiles/.config/kismet/kismet_wardrive.conf
# Qompass AI Kismet Wardrive Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
log_types+=wiglecsv
dot11_datasource_opt=ht_channels,false
dot11_datasource_opt=vht_channels,false
dot11_datasource_opt=default_ht20,false
dot11_datasource_opt=expand_ht20,false
dot11_datasource_opt=filter_mgmt,true
dot11_ap_only_survey=true
dot11_fingerprint_devices=false
dot11_keep_ietags=false
dot11_keep_eapol=false
kis_log_channel_history=false
kis_log_datasources=false
