# /qompassai/dotfiles/.config/kismet/kismet_httpd.conf
# Qompass AI Kismet Httpd Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
httpd_port=2501
httpd_allow_auth_creation=true
httpd_allow_auth_view=true
httpd_uri_prefix=/kismet
httpd_allow_cors=true
httpd_allowed_origin=https://some.proxy.server/
httpd_home=%S/kismet/httpd/
httpd_user_home=%h/.kismet/httpd/
httpd_session_db=%h/.kismet/session.db
httpd_auth_file=%h/.kismet/kismet_httpd.conf
httpd_session_timeout=7200
httpd_bind_address=127.0.0.1
httpd_mime=extension:mimetype
httpd_mime=html:text/html
httpd_redirect_unknown=/index.html
