 # /qompassai/dotfiles/.config/kismet/kisment_uav.conf
# Qompass AI Kismet UAV Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
# uav_match=matchname,option1="...",option2="..."
#  match_any=true
uav_match=skyrider:name="Propel",model="Sky Rider",ssid="Propel Sky Rider",mac=4C:0F:C7:00:00:00/FF:FF:FF:00:00:00
uav_match=skyrider_nighthawk:name="Propel",model="Sky Rider Night Hawk",ssid="^Sky Rider Vox-.*",mac=24:72:60:00:00:00/FF:FF:FF:00:00:00
uav_match=360flight:name="360 Flight",ssid="^360 Flight-.*",mac=E0:B9:4D:00:00:00/FF:FF:FF:00:00:00
uav_match=360lflight:name="360-L Flight",ssid="^360-L Flight-.*",mac=4C:0F:C7:00:00:00/FF:FF:FF:00:00:00
uav_match=3drsolo:name="3DRobotics",model="Solo",ssid="^SoloLink_.*",mac=8A:DC:96:00:00:00/FF:FF:FF:00:00:00
uav_match=dji_phantom:name="DJI",model="Phantom 3 Standard",ssid="^Phantom3_.*",mac=60:60:1F:00:00:00/FF:FF:FF:00:00:00
uav_match=dji_mavic:name="DJI",model="Mavic",ssid="^Mavic_.*",mac=60:60:1F:00:00:00/FF:FF:FF:00:00:00
uav_match=dji_spark:name="DJI",model="Spark",ssid="^Spark-(?!RC-).*",mac=60:60:1F:00:00:00/FF:FF:FF:00:00:00
uav_match=dji_spark_rc:name="DJI",model="Spark RC",ssid="^Spark-RC-.*",mac=60:60:1F:00:00:00/FF:FF:FF:00:00:00
uav_match=dji_tello:name="DJI",model="Tello",ssid="^TELLO.*",mac=60:60:1F:00:00:00/FF:FF:FF:00:00:00
uav_match=dji_osmo:name="DJI",model="Osmo",ssid="^OSMO_.*",mac=60:60:1F:00:00:00/FF:FF:FF:00:00:00
uav_match=propel_hd_1:name="Propel",model="HD Video Drone",ssid="Propel HD Video Drone",mac=EC:3D:FD:00:00:00/FF:FF:FF:00:00:00
uav_match=propel_hd_2:name="Propel",model="HD Video Drone",ssid="Propel HD Video Drone",mac=28:F3:66:00:00:00/FF:FF:FF:00:00:00
uav_match=propel_hd_3:name="Propel",model="HD Video Drone",ssid="Propel HD Video Drone",mac=E0:B9:4D:00:00:00/FF:FF:FF:00:00:00
uav_match=yd_ufo_1:name="Attop",model="UFO",ssid="^YD[_-]UFO[_-].*",mac=08:EA:40:00:00:00/FF:FF:FF:00:00:00
uav_match=yd_ufo_2:name="Attop",model="UFO",ssid="^YD[_-]UFO[_-].*",mac=4C:0F:C7:00:00:00/FF:FF:FF:00:00:00
uav_match=yd_ufo_3:name="Attop",model="UFO",ssid="^YD[_-]UFO[_-].*",mac=00:7E:56:00:00:00/FF:FF:FF:00:00:00
uav_match=yd_ufo_4:name="Attop",model="UFO",ssid="^YD[_-]UFO[_-].*",mac=B0:41:1D:00:00:00/FF:FF:FF:00:00:00
uav_match=yd_ufo_5:name="Attop",model="UFO",ssid="^YD[_-]UFO[_-].*",mac=E0:B9:4D:00:00:00/FF:FF:FF:00:00:00
uav_match=yd_ufo_6:name="Attop",model="UFO",ssid="^YD[_-]UFO[_-].*",mac=E8:AB:FA:00:00:00/FF:FF:FF:00:00:00
uav_match=xbm_720p_1:name="XBM",model="720P",ssid="^XBM-720P-.*",mac=90:97:D5:00:00:00/FF:FF:FF:00:00:00
uav_match=xbm_720p_2:name="XBM",model="720P",ssid="^XBM-720P-.*",mac=08:EA:40:00:00:00/FF:FF:FF:00:00:00
uav_match=parrot_bebop:name="Parrot",model="Bebop Drone",ssid="^BebopDrone.*",mac=A0:14:3D:00:00:00/FF:FF:FF:00:00:00
uav_match=parrot_bebop2_1:name="Parrot",model="Bebop 2",ssid="^Bebop2.*",mac=90:3A:E6:00:00:00/FF:FF:FF:00:00:00
uav_match=parrot_bebop2_2:name="Parrot",model="Bebop 2",ssid="^Bebop2.*",mac=A0:14:3D:00:00:00/FF:FF:FF:00:00:00
uav_match=parrot_sumo:name="Parrot",model="Jumping Sumo",ssid="^JumpingSumo-.*",mac=A0:14:3D:00:00:00/FF:FF:FF:00:00:00
uav_match=parrot_ardrone:name="Parrot",model="AR Drone",ssid="^ardrone[^2].*",mac=00:26:7E:00:00:00/FF:FF:FF:00:00:00
uav_match=parrot_ardrone2_1:name="Parrot",model="AR Drone 2.0",ssid="^ardrone2.*",mac=90:03:B7:00:00:00/FF:FF:FF:00:00:00
uav_match=parrot_ardrone2_2:name="Parrot",model="AR Drone 2.0",ssid="^ardrone2.*",mac=00:26:7E:00:00:00/FF:FF:FF:00:00:00
uav_match=parrot_skycontroller:name="Parrot",model="SkyController",ssid="^SkyController.*",mac=A0:14:3D:00:00:00/FF:FF:FF:00:00:00
uav_match=syma:name="GuangDong Syma",ssid="^FPV_WIFI__[0-9A-F]{4}$",mac=58:04:54:00:00:00/FF:FF:FF:00:00:00
