# /qompassai/dotfiles/.config/kismet/kisment_filter.conf
# Qompass AI Kismet Filter Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
device_location_signal_threshold_dbm=-65
btle_ignore_random=false
kis_log_device_filter_default=pass
# kis_log_device_filter=IEEE802.11,aa:bb:cc:dd:ee,pass
# kis_log_device_filter=IEEE802.11,11:22:33:00:00:00/FF:FF:FF:00:00:00,block
kis_log_device_filter=802.15.4,*,pass
kis_log_packet_filter_default=pass
kis_log_packet_filter=phyname,addresstype,macaddress,value
kis_log_packet_filter=IEEE802.11,source,aa:bb:cc:dd:ee,pass
kis_log_packet_filter=IEEE802.11,any,11:22:33:00:00:00/ff:ff:ff:00:00:00,block
kis_log_packet_filter=802.15.4,any,*,pass
