; /qompassai/dotfiles/.config/php/conf.d/imagick.ini
; Qompass AI PHP Conf.d Imagick Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
extension = imagick
