; /qompassai/dotfiles/.config/php/conf.d/uuid.ini
; Qompass AI PHP Conf.d UUID Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
extension=uuid.so
