; /qompassai/dotfiles/.config/php/conf.d/xdebug.ini
; Qompass AI PHP Conf.d XDebugger Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
zend_extension=xdebug.so
xdebug.mode=debug
