; /qompassai/dotfiles/.config/php/conf.d/zend_debugger.ini
; Qompass AI PHP Conf.d Zend Debugger Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
extension=yaml.so
