  Alias /simpleid "/usr/share/webapps/simpleid"
  <Directory "/usr/share/webapps/simpleid/www">
    AllowOverride All
    Options FollowSymlinks
    Order allow,deny
    Allow from all
  </Directory>
