# /qompassai/dotfiles/.config/paru/paru.conf
# Qompass AI Paru Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[options]
#AurOnly
#BatchInstall
BottomUp
CleanAfter
CombinedUpgrade
#Devel
DevelSuffixes = -always -bzr -cvs -darcs -fossil -git -hg -svn
#KeepRepoCache
#LocalRepo
NewsOnUpgrade
PgpFetch
Provides
#Rebuild = yes
#Redownload = all
RemoveMake
SaveChanges
Sign
SignDb
SudoLoop
UseAsk

[bin]
FileManager = nvim
#MFlags = 
#Sudo = doas

