# /qompassai/arch/etc/modprobe.d/blacklist.conf
# Qompass AI Modprobe.d Blacklist Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
blacklist airspy
blacklist dvb_usb_rtl28xxu
blacklist hackrf
blacklist r8169
blacklist nouveau
options nouveau modeset=0
install nouveau /bin/false
# legacy media
blacklist bttv
blacklist cx23885
blacklist cx25821
blacklist cx24110
blacklist cx24113
blacklist cx24116
blacklist cx24123
### legacy device
blacklist mousedev #legacy device
blacklist mISDN_core # ISDN telephony 
blacklist mISDN_dsp #  ISDN telephony
blacklist mISDNinfineon #  ISDN telephony
