; /qompassai/dotfiles/.config/displaycal/DisplayCal.ini
; Qompass AI Display Cal Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[Default]
3dlut.gamap.use_b2a = 0
3dlut.trc = bt1886
argyll.version = 3.3.0
calibration.file = /usr/share/DisplayCAL/presets/default.icc
calibration.update = 0
colorimeter_correction_matrix_file = AUTO:
display.number = 1
display_lut.link = 1
displays = Monitor 1, Output DP-1 @ 0, 0, 3840x1080:Monitor 2, Output HDMI-A-1 @ 3840, 0, 2560x1440:Web @ localhost:madVR:Prisma:Resolve:Untethered
last_launch = 3.9.14
lut_viewer.show = 0
measurement_mode = l
position.x = 0
position.y = 0
profile.name = %dns_%out_%Y-%m-%d_%H-%M_%cb_%wp_%cB_%ck_%cg_%cq-%pq_%pt
profile.name.expanded = Monitor_1_#1_2025-03-09_17-13_2.2_F-S_XYZLUT+MTX
profile.update = 0
show_donation_message = 1
testchart.file = auto
