# /qompassai/dotfiles/.config/strongswan.d/charon-systemd.conf
# Qompass AI StrongSwan.d Charon-Systemd Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
charon-systemd {
    journal {
        # <subsystem> = <default>
        default = 1
    }
}
