# /qompassai/dotfiles/.config/strongswan.d/pki.conf
# Qompass AI StrongSwan.d PKI Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
pki {
     load = openssl x509 pem pkcs1 pkcs8 pkcs12
     rsa_key_size = 4096
     digest = sha384
     validity = 1095
     x509 {
        enforce_critical = yes
    }
    scep {
        # http_bind =
        http_timeout = 60s
        renewal_via_pkcs_req = no
    }
}
