# /qompassai/dotfiles/.config/strongswan.d/pool.conf
# Qompass AI StrongSwan.d Pool Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
pool {

    # database =
    # load =
}
