# /qompassai/dotfiles/.config/strongswan.d/starter.conf
# Qompass AI StrongSwan.d Starter Config
# Copyright (C) 2025 Qompass AI, All rights reserved
########################################################
starter {
    config_file = ${sysconfdir}/ipsec.conf
    load_warning = yes
}
