charon {
    load_modular = yes
    prefer_configured_proposals = yes
    crypto_test {
        required = no
        on_add = yes
    }
    proposal_pqc = yes
    ike_proposals {
        pqc_hybrid = "X25519MLKEM768-aes256gcm16-prfsha384-prfsha256"
        traditional = "aes256gcm16-prfsha384-ecp384,aes256gcm16-prfsha256-ecp256"
    }
    esp_proposals {
        default = "aes256gcm16-ecp384,aes256gcm16-ecp256"
    }

    plugins {
        include strongswan.d/charon/*.conf
        openssl {
            engine_id = "default"
            load_ciphers = yes
            fips_mode = no
            use_post_quantum = yes
        }
    }
}
libstrongswan {
    plugins {
        aes {
            load = yes
        }
        curve25519 {
            load = yes
        }
        hmac {
            load = yes
        }
        kdf {
            load = yes
        }
        openssl {
            load = yes
        }
        pem {
            load = yes
        }
        sha1 {
            load = yes
        }
        sha2 {
            load = yes
        }
        x509 {
            load = yes
        }
        stroke {
            load = no
        }
    }
}
charon-systemd {
    load = yes
    start-scripts {
        creds = /usr/sbin/swanctl --load-creds
        conns = /usr/sbin/swanctl --load-conns
    }
}
vici {
    load = yes
    socket = unix:///var/run/charon.vici
}
include strongswan.d/*.conf
