# /qompassai/dotfiles/.config/postsrsd/postsrsd.conf
# Qompass AI PostSrsd Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

domains = {}
#domains-file =
#srs-domain =
socketmap = unix:$XDG_RUNTIME_DIR/postsrsd.sock
keep-alive = 30
#milter =
original-envelope = embedded
envelope-database = "sqlite:$XDG_RUNTIME_DIR/senders.db"
secrets-file = "$(pass show postsrsd/sf)"
separator = "="
hash-length = 4
hash-minimum = 4
always-rewrite = off
unprivileged-user = "$USER"
chroot-dir = "/var/lib/postsrsd"
syslog = off
debug = off
