# /qompassai/dotfiles/.config/webapps/phpvirtualbox/apache.conf
# Qompass AI PHP VirtualBox Config
# Copyright (C) 2025 Qompass AI, All rights reserved
################################################################
Alias /phpvirtualbox "/usr/share/webapps/phpvirtualbox"
  <Directory "/usr/share/webapps/phpvirtualbox">
    Options FollowSymlinks
    AllowOverride All
    Require all granted
  </Directory>
