# /qompassai/dotfiles/.config/hatch/config.toml
# Qompass AI Hatch Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
mode = "local"
project = ""
shell = ""
[dirs]
project = []
python = "isolated"
data = "/home/phaedrus/.local/share/hatch"
cache = "/home/phaedrus/.cache/hatch"
[dirs.env]
[projects]
[publish.index]
repo = "main"
[template]
name = "phaedrusflow"
email = "map@qompass.ai"
[template.licenses]
headers = true
default = [
    "MIT",
]
[template.plugins.default]
tests = true
ci = true
src-layout = true
[terminal.styles]
info = "bold"
success = "bold cyan"
error = "bold red"
warning = "bold yellow"
waiting = "bold magenta"
debug = "bold"
spinner = "simpleDotsScrolling"
