#!/usr/bin/env bash
# /qompassai/dotfiles/.config/gh/extensions/gh-mdv/gh-mdv
# Qompass AI Github CLI MDV Extension
# Copyright (C) 2026 Qompass AI, All rights reserved
# ----------------------------------------
repo="qompassai/dotfiles/.config/gh/extensions/gh-mdv"
tag="v1.0"
extension_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" &> /dev/null && pwd)"
tag_path="${extension_path}/dist/${tag}"
exe="gh-mdv"
platform=""
extension=""
determine_platform()
{
  local arch
  arch="$(uname -m)"
  if uname -a | grep -qi msys; then
    extension=".exe"
    if [ "${arch}" = "x86_64" ]; then
      platform="windows_amd64"
    fi
  elif uname -a | grep -qi darwin; then
    if [ "${arch}" = "x86_64" ]; then
      platform="darwin_amd64"
    elif [ "${arch}" = "arm64" ]; then
      platform="darwin_arm64"
    fi
  elif uname -a | grep -qi linux; then
    if [ "${arch}" = "x86_64" ]; then
      platform="linux_amd64"
    elif [ "${arch}" = "arm64" ]; then
      platform="linux_arm64"
    fi
  fi
}
download_latest_release()
{
  mkdir -p "${tag_path}"
  gh release -R "${repo}" download "${tag}" --pattern "*${platform}*" --dir "${tag_path}"
  mv "${tag_path}/${exe}_${tag}_${platform}${extension}" "${tag_path}/${exe}"
  chmod +x "${tag_path}/${exe}"
}

if [ ! -e "${tag_path}/${exe}" ]; then
  determine_platform
  if [ -z "${platform}" ]; then
    if ! command -v go > /dev/null 2>&1; then
      echo "go must be installed to use this gh extension on this platform" >&2
      exit 1
    fi
    mkdir -p "${tag_path}"
    pushd || "${extension_path}" > /dev/null
    go build -o "${tag_path}/${exe}"
    popd > /dev/null || true
  else
    if [ ! -d "${tag_path}" ]; then
      download_latest_release
    fi
  fi
fi
exec "${tag_path}/${exe}" "$@"
