# /qompassai/dotfiles/.config/uwsgi/emperor.ini
# Qompass AI UWSGI Emperor Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
[uwsgi]
emperor = /etc/uwsgi/vassals
