# /qompassai/dotfiles/.config/uwsgi/postorius.ini
# Qompass AI UWSGI Postorius Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
[uwsgi]
procname-master = postorius
master = true
plugins = python
socket = $XDG_RUNTIME_DIR//postorius/%n.sock
stats = $XDG_RUNTIME_DIR/postorius/%n-stats.sock
uid = postorius
gid = postorius
processes = 10
cheaper = 2
cheaper-step = 1
idle = 120
die-on-idle = true
chdir = /usr/share/webapps/postorius
module = wsgi
home = /
touch-reload = %p
vacuum = true
