schema_version = "1.0.0"

id = "character_pipeline_tracker"
version = "1.1.0"
name = "Character Pipeline Tracker"
tagline = "Track and automate character creation pipeline stages"
maintainer = "Lisichik Evgeny <md15.db@gmail.com>"
type = "add-on"

tags = ["3D View", "Render", "Import-Export", "Mesh", "User Interface"]  

blender_version_min = "5.0.0"
license = ["SPDX:GPL-3.0-or-later"]

platforms = ["windows-x64", "macos-arm64", "macos-x64", "linux-x64"]