# /qompassai/dotfiles/.config/wofi-pass/wofi-pass.conf
# Qompass AI Wofi-pass Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

PASSWORD_STORE_DIR="${HOME}/.password-store"
WOFI_PASS_AUTOTYPE=":username :tab :password"
WOFI_PASS_DELAY=2
#WOFI_PASS_AUTO_ENTER="false"
CMD_COPY="wl-copy"
CMD_TYPE="wtype -"
#PASS_FIELD_USERNAME="username"
#HOTKEY_USERNAME=Alt-u
#HOTKEY_PASSWORD=Alt-p
#HOTKEY_AUTOTYPE=Alt-a
#HOTKEY_OTP=Alt-o
