#!/bin/sh
# /qompassai/dotfiles/.config/githooks/pre-push
# Qompass AI GitHooks Pre-push Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
if ! gitleaks detect --source . --exit-code=1; then
  echo "Secrets detected! Push aborted."
  exit 1
fi
command -v git-lfs >/dev/null 2>&1 || {
  printf >&2 "\\n%s\\n\\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."
  exit 2
}
git lfs pre-push "$@"
