# /qompassai/dotfiles/.config/clustershell/topology.conf
# Qompass AI Clustershell Topology Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
#  rio0
#  |- rio[10-11]
#  |  `- rio[100-240]
#  `- rio[12-13]
#     `- rio[300-440]

[routes]
rio0: rio[10-13]
rio[10-11]: rio[100-240]
rio[12-13]: rio[300-440]
