# /qompassai/dotfiles/.config/security/faillock.conf
# Qompass AI Security Faillock Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
audit
silent
no_log_info
local_users_only
deny = 3
fail_interval = 900
unlock_time = 600
# even_deny_root
# root_unlock_time = 900
