# /qompassai/dotfiles/.config/security/geoip.conf
# Qompass AI Security GeoIP Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################

# Domain   Service  Action  Location
*         *        ignore  UNKNOWN
*         *        allow   US,CA,UK
*         sshd     deny    CN,RU,BR
*         smtp     deny    *
@wheel    sshd     allow   DE,SE,US
@guest    *        deny    *
*         *        log     CN,RU,UNKNOWN
meike     sshd     allow   JP,KR
