#!/usr/bin/env sh
# /qompassai/dotfiles/.config/security/namespace.init
# Qompass AI Security NameSpace Init
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
if [ "$5" = 1 ]; then

    if [ "$3" = 1 ]; then
            [ -x /sbin/restorecon ] && /sbin/restorecon "$1"
            user="$4"
            passwd=$(getent passwd "$user")
            homedir=$(echo "$passwd" | cut -f6 -d":")
            if [ "$1" = "$homedir" ]; then
                    gid=$(echo "$passwd" | cut -f4 -d":")
                    cp -rT /etc/skel "$homedir"
                    chown -R "$user":"$gid" "$homedir"
                    mask=$(sed -E -n 's/^UMASK[[:space:]]+([^#[:space:]]+).*/\1/p' /etc/login.defs)
                    mode=$(printf "%o" $((0777 & ~mask)))
                    chmod ${mode:-700} "$homedir"
                    [ -x /sbin/restorecon ] && /sbin/restorecon -R "$homedir"
            fi
    fi
fi
exit 0
