# /qompassai/dotfiles/.config/security/pam_encfs.conf
# Qompass AI Security Encrypted File System (EncFS) Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
drop_permissions
encfs_default --idle=1
fuse_default allow_root,nonempty
root           /mnt/enc/root         /root          -v,--idle=1       allow_root
@wheel         /mnt/enc/@USER        /home/@USER    -v,--idle=1       allow_root
@audio         /mnt/enc/media/audio  /media/audio   -v,--idle=1       allow_other
@video         /mnt/enc/media/video  /media/video   -v,--idle=1       allow_other
@render        /mnt/enc/media/render /media/render  -v,--idle=1       allow_other
@bluetooth     /mnt/enc/media/bt     /media/bt      -v,--idle=1       allow_other
@media         /mnt/enc/media/common /media/common  -v,--idle=1       allow_other
-              /mnt/enc             -              -v,--idle=1       allow_other
