# /qompassai/dotfiles/.config/security/pam_env.conf
# Qompass AI Security Pam Env Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
ATSIGN                  DEFAULT="" OVERRIDE=\\@
CLUTTER_BACKEND         DEFAULT=wayland
DIFFPROG                DEFAULT=nvimpager
DISPLAY                 DEFAULT=:0.0
DOLLAR                  DEFAULT=\\$
DOLLARDOLLAR            DEFAULT= OVERRIDE=\\$${DOLLAR}
DOLLARPLUS              DEFAULT=\\${REMOTEHOST}${REMOTEHOST}
GDK_BACKEND             DEFAULT=wayland,x11
LESS                    DEFAULT="M q e h15 z23 b80"
MANPAGER                DEFAULT=nvimpager
MOZ_ENABLE_WAYLAND      DEFAULT=1
NNTPSERVER              DEFAULT=localhost
NVIM                    DEFAULT=nvim
NVIMPAGER_NVIM          DEFAULT=nvim
PATH                    DEFAULT=@{HOME}/bin:/usr/local/bin:/bin:/usr/bin:/usr/local/bin/X11:/usr/bin/X11
PAGER                   DEFAULT=nvimpager OVERRIDE=nvimpager
QT_QPA_PLATFORM         DEFAULT=wayland
REMOTEHOST              DEFAULT=localhost OVERRIDE=@{PAM_RHOST}
SDL_VIDEODRIVER         DEFAULT=wayland
WAYLAND_DISPLAY         DEFAULT=wayland-0
XDG_CACHE_HOME          DEFAULT=@{HOME}/.cache
XDG_CURRENT_DESKTOP     DEFAULT=Hyprland OVERRIDE=Niri
XDG_RUNTIME_DIR         DEFAULT=/run/user/@{PAM_UID}
XDG_SESSION_DESKTOP     DEFAULT=Hyprland OVERRIDE=Niri
XDG_SESSION_TYPE        DEFAULT=wayland
XDG_STATE_HOME          DEFAULT=@{HOME}/.local/state
/tmp                    DEFAULT=/tmp
