# /qompassai/dotfiles/.config/security/pam_abl.conf
# Qompass AI Security Pam_ABL Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
db_home=/var/lib/abl
db_module=/usr/lib/security/pam_abl_kc.so
host_purge=1d
user_purge=1d
host_rule=*:5/1h,15/1d
user_rule=*:10/1h,20/1d
user_rule=!root|!@wheel:15/1h,30/1d
host_whitelist=127.0.0.1,::1
user_whitelist=root,@wheel
host_clear_cmd=[/usr/bin/logger] [clear] [host] [%h] [timestamp:%t]
host_block_cmd=[/usr/bin/logger] [block] [host] [%h] [timestamp:%t]
user_clear_cmd=[/usr/bin/logger] [clear] [user] [%u] [timestamp:%t]
user_block_cmd=[/usr/bin/logger] [block] [user] [%u] [timestamp:%t]
limits=500-800
audit_log_cmd=[/usr/bin/logger] [audit] [abl_action:%a] [target:%t] [details:%d]
