# /qompassai/dotfiles/.config/security/pwhistory.conf
# Qompass AI Security PW History Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
debug
enforce_for_root
remember = 10
retry = 1
# file = /etc/security/opasswd
