# /qompassai/dotfiles/.config/security/pwquality.conf
# Qompass AI Security PW Quality Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
enforce_for_root
local_users_only
minlen = 12
minclass = 4
difok = 5
dcredit = -1
ucredit = -1
lcredit = -1
ocredit = -1 
maxrepeat = 2
maxclassrepeat = 3
maxsequence = 3
usercheck = 1
usersubstr = 3
gecoscheck = 1
dictcheck = 1
dictpath = 
enforcing = 1
retry = 3
