# /qompassai/dotfiles/.config/security/time.conf
# Qompass AI Security Time Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
* ; * ; root | @wheel | @audio | @video | @media | @render | @bluetooth ; Al0000-2400
* ; * ; @guest | @automation ; !Al0000-2400
* ; * ; svc_* | service_* ; !Al0000-2400
login | sshd | xsh ; * ; * & !root & !@wheel & !@audio & !@video & !@media & !@render & !@bluetooth ; Wk0700-2000
* ; pts/* | hvc* ; * & !root & !@wheel & !@audio & !@video & !@media & !@render & !@bluetooth ; !Al0000-2400
