# /qompassai/dotfiles/.config/security/user_map.conf
# Qompass AI Security User Map Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
@wheel: admin
svc_monitor: monitor
@guest: guestreadonly
@automation: automator
#* : !deny
