# /qompassai/dotfiles/.config/mini_httpd/mini_http_ssl.conf
# Qompass AI Mini Http Daemon SSL Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
certfile=/etc/ssl/private/mini_httpd.pem
cgipat=**.cgi
charset=utf-8
dir=/srv/http
logfile=/var/log/mini_httpd.log
pidfile=/run/mini_httpd.pid
port=4443
ssl
user=nobody
