# /qompassai/dotfiles/.config/mini_httpd/mini_httpd.conf
# Qompass AI Mini Http Daemon Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#######################################################
cgipat=**.cgi
charset=utf-8
dir=/srv/http
logfile=/var/log/mini_httpd.log
pidfile=/run/mini_httpd.pid
port=80
user=nobody
