% /qompassai/dotfiles/.config/yass/yass.conf
% Qompass AI Yass Config
% Copyright (C) 2025 Qompass AI, All rights reserved
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Yass.nchan: 8
Yass.trace.colors: 11223344
Yass.input_1: alsa_pcm:capture_1
Yass.input_2: alsa_pcm:capture_2
Yass.input_3: alsa_pcm:capture_3
Yass.input_4: alsa_pcm:capture_4
Yass.input_5: alsa_pcm:capture_5
Yass.input_6: alsa_pcm:capture_6
Yass.input_7: alsa_pcm:capture_7
Yass.input_8: alsa_pcm:capture_8

%
%Yass.color.main.bg:    black
%Yass.color.trace.bg:   white
%Yass.color.trace.c0    gray50
%Yass.color.trace.c1    blue
%Yass.color.trace.c2    coral
%Yass.color.trace.c3    darkgreen
%Yass.color.trace.c4    black

