# /qompassai/dotfiles/.config/smbldap-tools/smbldap_bind.conf
# Qompass AI SMB LDAP Tools Bind Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
# $Id$
#
slaveDN="cn=Manager,dc=example,dc=com"
slavePw="secret"
masterDN="cn=Manager,dc=example,dc=com"
masterPw="secret"
