#!/hint/bash
# shellcheck disable=2034,2155
## /qompassai/dotfiles/.config/pacman/makepkg.conf.d/cmake.conf
# Qompass AI CMake Config
##########################################################
export CMAKE_BUILD_TYPE="Release"
export CMAKE_EXPORT_COMPILE_COMMANDS=ON
export CMAKE_C_COMPILER="clang"
export CMAKE_CXX_COMPILER="clang++"
#export CMAKE_GENERATOR="Ninja"
export CMAKE_GENERATOR="Ninja Multi-Config"
export CMAKE_MAKE_PROGRAM="/usr/bin/ninja"
export CMAKE_C_FLAGS="${CFLAGS}"
export CMAKE_CXX_FLAGS="${CXXFLAGS}"
export CMAKE_EXE_LINKER_FLAGS="${LDFLAGS}"
export CMAKE_SHARED_LINKER_FLAGS="${LDFLAGS}"
