#!/hint/bash
# shellcheck disable=2034,2155
# /qompassai/dotfiles/.config/pacman/makepkg.conf.d/cuda.conf
## Qompass AI Makepkg Cuda Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#############################################################
export NVHPC_ROOT="/opt/nvidia/hpc_sdk/Linux_x86_64/2026"
export PATH="$NVHPC_ROOT/compilers/bin:$PATH"
export PATH="$NVHPC_ROOT/comm_libs/mpi/bin:$PATH"
export MANPATH="$NVHPC_ROOT/compilers/man:$MANPATH"
export LD_LIBRARY_PATH="$NVHPC_ROOT/compilers/lib:$LD_LIBRARY_PATH"
export LD_LIBRARY_PATH="$NVHPC_ROOT/comm_libs/mpi/lib:$LD_LIBRARY_PATH"
export CMAKE_CUDA_COMPILER="/opt/cuda/bin/nvcc"
export CUDA_ARCHITECTURES="89"
export CUDACXX="/opt/cuda/bin/nvcc"
export CUDA_DIR="/opt/cuda"
export CUDA_HOME="/opt/cuda"
export CUDA_PATH="/opt/cuda"
export CUDAToolkit_ROOT="/opt/cuda"
export CUDA_TOOLKIT_ROOT_DIR=/opt/cuda
export PATH="/opt/cuda/bin:${PATH}"
export LD_LIBRARY_PATH="/opt/cuda/lib64:${LD_LIBRARY_PATH}"
#export NVCCFLAGS="-arch=sm_89 -O3 -use_fast_math"
export CMAKE_ARGS="-DCUTLASS_NVCC_ARCHS='89' -DCUTLASS_UNITY_BUILD_ENABLED=ON -DCUTLASS_ENABLE_TESTS=OFF"
export CUDAFLAGS="-arch=lto_89 \
  -O3 \
  -use_fast_math \
  --ftz=true \
  --prec-div=false \
  --prec-sqrt=false \
  --threads $(nproc) \
  -Xptxas=-O3,-v \
  -Xcompiler=-march=x86-64-v3,-mtune=native,-O3,-mf16c \
  -lineinfo"
export NVCCFLAGS="$CUDAFLAGS"
