#!/hint/bash
# shellcheck disable=2034,2155
# /qompassai/dotfiles/.config/pacman/makepkg.conf.d/cuda.conf
## Qompass AI Makepkg Cuda Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#############################################################
export CUDA_ARCHITECTURES="89"
export CUDAFLAGS="-arch=sm_89 -O3 -use_fast_math --threads $(nproc)"
export CUDA_HOME="/opt/cuda"
export CUDA_PATH="/opt/cuda"
export CUDAToolkit_ROOT="/opt/cuda"
export PATH="/opt/cuda/bin:${PATH}"
export LD_LIBRARY_PATH="/opt/cuda/lib64:${LD_LIBRARY_PATH}"
export CMAKE_CUDA_COMPILER="/opt/cuda/bin/nvcc"
export NVCCFLAGS="-arch=sm_89 -O3 -use_fast_math"
