#!/hint/bash
# shellcheck disable=2034
## Qompass AI - CUDA Build Environment
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
export CUDA_HOME="/opt/cuda"
export CUDA_PATH="/opt/cuda"
export CUDAToolkit_ROOT="/opt/cuda"
export PATH="/opt/cuda/bin:${PATH}"
export LD_LIBRARY_PATH="/opt/cuda/lib64:${LD_LIBRARY_PATH}"
export CMAKE_CUDA_COMPILER="/opt/cuda/bin/nvcc"
