#!/hint/bash
# shellcheck disable=2034
# /qompassai/dotfiles/.config/pacman/makepkg.conf.d/go.conf
## Qompass AI - Go Build Environment
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
export CGO_ENABLED=0
export GOCACHE="${XDG_CACHE_HOME:-$HOME/.cache}/go-build"
export GOMAXPROCS=$(nproc)
export GOMODCACHE="${XDG_CACHE_HOME:-$HOME/.cache}/go/mod"
export GOTMPDIR="${BUILDDIR}/go-tmp"
export GOPROXY="https://proxy.golang.org,direct"
export GOSUMDB="sum.golang.org"
export GOTELEMETRY=off
