#!/hint/bash
# shellcheck disable=2034,2155
## /qompassai/dotfiles/.config/pacman/makepkg.conf.d/haskell.conf
# Qompass AI Haskell Config
##########################################################
export GHCFLAGS="-O2 -optc-O3 -optc-march=x86-64-v3"
export CABAL_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/cabal"
export STACK_ROOT="${XDG_DATA_HOME:-$HOME/.local/share}/stack"
