#!/hint/bash
# shellcheck disable=2034
## Qompass AI - Node.js/PNPM Build Environment
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
nvm_default_version=24
export NVM_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nvm"
[ -s "/usr/share/nvm/nvm.sh" ] && source /usr/share/nvm/nvm.sh
export npm_config_engine_strict=false
PNPM_CONFIG_ENGINE_STRICT=false
NODE_OPTIONS="--max-old-space-size=4096"
