#!/hint/bash
# shellcheck disable=2034,2155
## /qompassai/dotfiles/.config/pacman/makepkg.conf.d/julia.conf
# Qompass AI Julia Config
##########################################################
export JULIA_NUM_THREADS=$(nproc)
export JULIA_DEPOT_PATH="${XDG_DATA_HOME:-$HOME/.local/share}/julia"
export JULIA_CPU_TARGET="x86-64-v3"
