#!/hint/bash
# shellcheck disable=2034,2155
## /qompassai/dotfiles/.config/pacman/makepkg.conf.d/nim.conf
# Qompass AI Nim Config
##########################################################
export NIMFLAGS="-d:release -d:danger --opt:speed --passC:'-march=x86-64-v3' --passC:'-O3'"
export NIMBLE_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/nimble"

