#!/usr/bin/env bash
# shellcheck disable=2034
## Qompass AI - Rust Build Environment
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
export CARGO_HOME="${BUILDDIR}/.cargo"
export CARGO_BUILD_JOBS=$(nproc)
export CARGO_INCREMENTAL=0
export CARGO_HTTP_CHECK_REVOKE=false
