#!/hint/bash

export CARGO_HOME="$HOME/.cache/cargo"

export CARGO_TARGET_DIR="target"

export CARGO_BUILD_JOBS=$(nproc)
export CARGO_INCREMENTAL=0
export CARGO_HTTP_CHECK_REVOKE=false
export CARGO_PROFILE_RELEASE_LTO=true
export CARGO_PROFILE_RELEASE_CODEGEN_UNITS=1
export CARGO_PROFILE_RELEASE_OPT_LEVEL=3
export CARGO_PROFILE_RELEASE_STRIP="symbols"

if command -v mold &>/dev/null; then
    export RUSTFLAGS="-C link-arg=-fuse-ld=mold"
fi
