#CFLAGS+=" -Wimplicit-function-declaration -Wno-error=unsafe-buffer-usage -flto=thin"
#CFLAGS+="-Wmissing-prototypes"
# -Wno-non-literal-null-conversion"
#CXXFLAGS+=" -flto=thin -Wno-error=unsafe-buffer-usage  -Wno-vla-cxx-extension"
