#!/hint/bash
# shellcheck disable=2034,2155
## /qompassai/dotfiles/.config/pacman/makepkg.conf.d/wasm.conf
# Qompass AI WebAssembly Config
##########################################################
export EMSCRIPTEN="/usr/lib/emscripten"
export EMSDK="/opt/emsdk"
export WASI_SDK_PATH="/opt/wasi-sdk"
export EMCC_CFLAGS="-O3 -flto"
