#!/hint/bash
# shellcheck disable=2034,2155
## /qompassai/dotfiles/.config/pacman/makepkg.conf.d/zig.conf
# Qompass AI Zig Config
##########################################################
export ZIG="/usr/bin/zig"
export ZIG_GLOBAL_CACHE_DIR="${XDG_CACHE_HOME:-$HOME/.cache}/zig"
export ZIG_LOCAL_CACHE_DIR="${BUILDDIR:-${XDG_CACHE_HOME:-$HOME/.cache}/makepkg}/.zig-cache"
ZIGFLAGS="-Doptimize=ReleaseFast -Dcpu=x86_64_v3"
export ZIGFLAGS
mkdir -p "${ZIG_GLOBAL_CACHE_DIR}"
