-- /qompassai/Diver/lsp/harper_ls.lua
-- Qompass AI Harper LSP Spec
-- Copyright (C) 2025 Qompass AI, All rights reserved
-- --------------------------------------------------
---@source https://github.com/automattic/harper
---@type vim.lsp.Config
return {
    cmd = {
        'harper-ls',
        '--stdio',
    },
    filetypes = {
        'asciidoc',
        'c',
        'clojure',
        'cmake',
        'cpp',
        'cs',
        'dart',
        'gitcommit',
        'go',
        'haskell',
        'html',
        'java',
        'javascript',
        'lua',
        'markdown',
        'nix',
        'php',
        'python',
        'ruby',
        'rust',
        'sh',
        'swift',
        'toml',
        'typescript',
        'typescriptreact',
        'typst',
    },
    root_markers = {
        '.git',
    },
    settings = {
        ['harper-ls'] = {
            codeActions = {
                ForceStable = false,
            },
            diagnosticSeverity = 'hint',
            dialect = 'American',
            excludePatterns = {},
            fileDictPath = '',
            ignoredLintsPath = '',
            isolateEnglish = false,
            linters = {
                AnA = true,
                Anywhere = true,
                AsFarBackAs = true,
                CorrectNumberSuffix = true,
                LongSentences = true,
                Matcher = true,
                RepeatedWords = true,
                SentenceCapitalization = true,
                Spaces = true,
                SpellCheck = true,
                SpelledNumbers = false,
                UnclosedQuotes = true,
                WrongQuotes = false,
            },
            markdown = {
                IgnoreLinkTitle = false,
            },
            maxFileLength = 120000,
            rules = {
                Alongside = true,
                ApartFrom = true,
                Anywhere = true,
                AsFarBackAs = true,
                AsLongAs = true,
                BackInTheDay = true,
                ByAccident = true,
                Cant = true,
                ChangeTack = true,
                Confident = true,
                CriteriaPhenomena = true,
                Didnt = true,
                DoNotWant = true,
                EllipsisLength = true,
                Everybody = true,
                ExpandBecause = true,
                FootTheBill = true,
                Freezing = true,
                GoogleNames = true,
                HadOf = true,
                HelloGreeting = true,
                Holidays = true,
                InMyOpinion = true,
                InRealLife = true,
                ItCan = true,
                IveGotTo = true,
                Koreas = true,
                LastButNotLeast = true,
                LongSentences = true,
                ManagerialReins = true,
                Misunderstood = true,
                MootPoint = true,
                Multicore = true,
                Nothing = true,
                NotTo = true,
                Notwithstanding = true,
                Overall = true,
                PossessiveNoun = false,
                PrayingMantis = true,
                ProperNouns = true,
                RapidFire = true,
                Theres = true,
                ThoughtProcess = true,
                TransposedSpace = true,
                Unless = true,
                VerbToAdjective = true,
            },
            userDictPath = '$XDG_CONFIG_HOME/harper-ls/dictionary.txt',
            workspaceDictPath = '',
        },
    },
}
