[general]
ipv6=true
enable-transcoding=true
video-upload-folder=@.VIDEOS@
music-upload-folder=@.MUSIC@
picture-upload-folder=@.PICTURES@
media-engine=librygel-media-engine-gst.so
interface=
port=0
log-level=*:5
allow-upload=true
allow-deletion=true
acl-fallback-policy=true
strict-dlna=true
[GstMediaEngine]
transcoders=mp3;lpcm;mp2ts;wmv;aac;avc
[Renderer]
image-timeout = 15
[Tracker3]
enabled=true
only-export-from=@.MUSIC@;@.VIDEOS@;@.PICTURES@
share-pictures=true
share-videos=true
share-music=true
strict-sharing=false
title=@REALNAME@'s media on @PRETTY_HOSTNAME@
[Tracker]
enabled=true
only-export-from=@MUSIC@;@VIDEOS@;@PICTURES@
share-pictures=true
share-videos=true
share-music=true
strict-sharing=false
title=@REALNAME@'s media on @PRETTY_HOSTNAME@
[LMS]
enabled=true
title=@REALNAME@'s media on @PRETTY_HOSTNAME@

[MediaExport]
enabled=true
title=@REALNAME@'s media on @PRETTY_HOSTNAME@
uris=@MUSIC@;@VIDEOS@;@PICTURES@
extract-metadata=true
monitor-changes=true
monitor-grace-timeout=5
virtual-folders=true

[Playbin]
enabled=true
title=Audio/Video playback on @PRETTY_HOSTNAME@
#audio-sink=autoaudiosink
#video-sink=fakesink

[GstLaunch]
enabled=true
launch-items=audiotestsrc;videotestsrc;videotestoverlay
audiotestsrc-title=Audiotestsrc
audiotestsrc-mime=audio/x-wav
audiotestsrc-launch=audiotestsrc ! wavenc
videotestsrc-title=Videotestsrc
videotestsrc-mime=video/mpeg
videotestsrc-launch=videotestsrc ! video/x-raw,width=640,height=480 ! avenc_mpeg2video ! mpegtsmux
videotestoverlay-title=Videotestsrc with timeoverlay 2
videotestoverlay-mime=video/mpeg
videotestoverlay-launch=videotestsrc ! video/x-raw,width=640,height=480 ! timeoverlay ! avenc_mpeg2video ! mpegtsmux
[Test]
enabled=true
[ExampleServerPluginVala]
enabled=true
[ExampleServerPluginC]
enabled=true
[ExampleRendererPluginVala]
enabled=true
[ExampleRendererPluginC]
enabled=false
[MPRIS]
enabled=true

[External]
enabled=true

[Ruih]
enabled=true
title=Rygel Remote UI Server
