; /qompassai/dotfiles/.config/nvtop/interface.ini
; Qompass AI NVTop Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

[GeneralOption]
UseColor = true
UpdateInterval = 1000
ShowInfoMessages = true

[HeaderOption]
UseFahrenheit = true
EncodeHideTimer = 3.000000e+01
GPUInfoBar = true

[ChartOption]
ReverseChart = false

[ProcessListOption]
HideNvtopProcess = true
SortOrder = descending
SortBy = memory
DisplayField = pId
DisplayField = user
DisplayField = gpuId
DisplayField = type
DisplayField = gpuRate
DisplayField = memory
DisplayField = cpuUsage
DisplayField = cpuMem
DisplayField = cmdline

[Device]
Pdev = 0000:00:02.0
Monitor = true
ShownInfo = gpuRate
ShownInfo = gpuMemRate
