# /qompassai/dotfiles/.config/samba/smb.conf
# Qompass AI Samba Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[global]
   workgroup = WORKGROUP
   netbios name = $USER
   server string = Samba User Test
   map to guest = Bad User
   smb ports = 1445
   log file = $XDG_STATE_HOME/samba/log/log.samba
   state directory = $XDG_STATE_HOME/samba
   cache directory = $XDG_CACHE_HOME/samba
   lock directory = $XDG_STATE_HOME/samba/lock
   pid directory = $XDG_STATE_HOME/samba/pid
   private dir = $XDG_STATE_HOME/samba/private
   ncalrpc dir = $XDG_STATE_HOME/samba/ncalrpc
   load printers = no
   disable spoolss = yes

[public]
   path = $XDG_DATA_HOME/samba/public
   guest ok = yes
   read only = no
