# /qompassai/dotfiles/.config/cvechecker/chechecker.conf
# Qompass AI CVE Checker Config
# Copyright (C) 2025 Qompass AI, All rights reserved
########################################################
dbtype = "sqlite"; 
#dbtype="mysql";
cvecache = "/var/cvechecker/cache";
datadir = "/usr/share/cvechecker";
stringcmd = "/usr/bin/strings -n 3 '@file@'";
version_url = "https://raw.github.com/sjvermeu/cvechecker/master/versions.dat";
#userkey = "servertag";
sqlite3: {
  localdb = "/var/cvechecker/local";
  globaldb = "/var/cvechecker/global.db";
};
mysql: {
  dbname = "cvechecker";
  dbuser = "cvechecker_rw";
  dbpass = "$(pass show cvechecker/dbp)";
  dbhost = "mysql.company.com";
};
