# /qompassai/dotfiles/.config/turnserver/turnserver.conf
# Qompass AI TurnServer Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
allow-loopback-peers
aux-server=172.17.19.110:33478
aux-server=[2607:f0d0:1002:51::4]:33478
bps-capacity=100000000
channel-lifetime=600
check-origin-consistency
cli-ip=127.0.0.1
cli-max-output-sessions=1000
cli-password=exampleCliPass
#cli-port=5766
denied-peer-ip=83.166.64.0-83.166.95.255
dns-backward-compatibility
dns-server=8.8.8.8
external-ip=60.70.80.91/172.17.19.101
external-ip=60.70.80.92/172.17.19.102
fingerprint
firewall=on
#firewall-rules=/etc/turnserver/firewall.rules
heartbeat=60  
keep-address-family
listening-device=eth0
listening-ip=0.0.0.0
listening-ip=::
listening-ip=172.17.19.101
listening-ip=10.207.21.238
listening-ip=2607:f0d0:1002:51::4
listening-port=3478
log-binding
log-file=/var/log/turnserver/turn.log
log-level=info
max-allocate-lifetime=3600
max-allocate-timeout=60
max-bps=1000000
min-port=49152
mobility
mysql-userdb="$(pass show turnserver/mysql)"
ne=1
new-log-timestamp
new-log-timestamp-format="%FT%T%z"
no-auth
no-dtls
no-multicast-peers
no-software-attribute
no-stun
no-stdout-log
no-tcp
no-tcp-relay
no-tls
no-tlsv1_2
no-udp
no-udp-relay
oauth
out-bandwidth=10000000
permission-lifetime=300
pidfile=/run/turnserver/turnserver.pid
prometheus
prometheus-port=9641
prometheus-username-labels
proc-group=turngroup
proc-user=turnuser
psql-userdb="$(pass show turnserver/psql)"
raw-public-keys
realm=blackdow.carleon.gov
relay-device=eth1
relay-ip=172.17.19.105
relay-ip=2607:f0d0:1002:51::5
relay-threads=4
respond-http-unsupported
rest-api-separator=:
route-backward-compatibility
routes="10.0.0.0/8,192.168.1.0/24"
secure-stun
server-name=blackdow.carleon.gov
server-relay
simple-log
skip-tcp=off
skip-udp=off
split-tcp=on
split-udp=on
sql-db-path=/var/db/turndb
stale-nonce=600
static-auth-secret="$(pass show turnserver/authsec)"
stats-db-path=/var/db/turnstats
stun-backward-compatibility
stun-only
syslog
syslog-facility="LOG_LOCAL1"
tcp-proxy-port=5555
timeout=30
tls-alternate-server=1.2.3.4:5678
tls-alternate-server=11.22.33.44:56789
tls-alternate-server=[2001:db8:85a3:8d3:1319:8a2e:370:7348]:3478
tls-listening-port=5349
total-quota=100                # Example global connection/session quota
udp-self-balance
user="$(pass show turnserver/user)"
user-quota=10 
userdb=/var/db/turndb
verbose
Verbose
web-admin
web-admin-listen-on-workers
