## /qompassai/dotfiles/.config/archive/archive.conf
# Qompass AI Archive Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
# vim:set sw=2 ts=2 ft=sh et:
ARCHIVE_RSYNC='rsync://polymorf.fr/archlinux/'
ARCHIVE_DIR='/srv/archive'
ARCHIVE_USER=archive
ARCHIVE_GROUP=archive
PKGREGEX='\.pkg\.tar(\.(gz|bz2|xz|zst|lrz|lzo|Z|lz4|lz))?'
PKGSIGREGEX="$PKGREGEX\.sig"
UMASK=022
ARCHIVE_REPO=1
REPO_DAYLY=1
REPO_PACKAGES=1
REPO_PACKAGES_INDEX=1
REPO_PACKAGES_FULL_SEARCH=1
REPO_RSYNC_TIMEOUT=80000
ARCHIVE_ISO=1
ISO_RSYNC_TIMEOUT=6400
