## /qompassai/dotfiles/.config/archive/archive.conf
# Qompass AI Archive Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
# vim:set sw=2 ts=2 ft=sh et:
ARCHIVE_DIR='/srv/archive'
ARCHIVE_GROUP=archive
ARCHIVE_ISO=1
ARCHIVE_REPO=1
ARCHIVE_RSYNC='rsync://polymorf.fr/archlinux/'
ARCHIVE_USER=archive
ISO_RSYNC_TIMEOUT=6400
PKGREGEX='\.pkg\.tar(\.(gz|bz2|xz|zst|lrz|lzo|Z|lz4|lz))?'
PKGSIGREGEX="$PKGREGEX\.sig"
REPO_DAYLY=1
REPO_PACKAGES=1
REPO_PACKAGES_FULL_SEARCH=1
REPO_PACKAGES_INDEX=1
REPO_RSYNC_TIMEOUT=80000
UMASK=022
