schema_version = "1.0.0"

id = "surface_diagnostics"
version = "1.4.3"
name = "Surface Diagnostics"
tagline = "Set of tools for diagnosing surface quality"
maintainer = "Josef Ludvík Böhm"
type = "add-on"

# Optional: Add website, tracker_url, documentation_url, tags etc.
website = "https://discord.gg/cWVT9a6sNe"
documentation_url = "https://discord.gg/cWVT9a6sNe"
tags = ["Modeling", "3D View", "Geometry Nodes"]

blender_version_min = "4.5.0"

license = ['SPDX:GPL-3.0-or-later']