# /qompassai/dotfiles/.config/wallust/wallusts.toml
# Qompass AI Wallust Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#####################################################
# Reference: https://explosion-mental.codeberg.page/wallust/
backend = "kmeans"
color_space = "labmixed"
palette = "dark16"
threshold = 11
[templates]
cava.template = 'colors-cava'
cava.target = '~/.config/cava/config'
hypr.template = 'colors-hyprland.conf'
hypr.target = '~/.config/wallust/templates/colors-hyprland.conf'
rofi.template = 'colors-rofi.rasi'
rofi.target = '~/.config/rofi/wallust/colors-rofi.rasi'
waybar.template = 'colors-waybar.css'
waybar.target = '~/.config/waybar/wallust/colors-waybar.css'
kitty.template = 'colors-kitty.conf'
kitty.target = '~/.config/wallust/templates/colors-kitty.conf'
