# SPDX-License-Identifier: GPL-2.0-or-later


# ##### BEGIN AUTOGENERATED I18N SECTION #####
# NOTE: You can safely move around this auto-generated block (with the begin/end markers!),
#       and edit the translations by hand.
#       Just carefully respect the format of the tuple!

# Tuple of tuples:
# ((msgctxt, msgid), (sources, gen_comments), (lang, translation, (is_fuzzy, comments)), ...)
translations_tuple = (
    (
        ("*", ""),
        ((), ()),
        (
            "zh_HANS",
            "Project-Id-Version: AnimReviewer 1.0.2 (0)\nReport-Msgid-Bugs-To: \nPOT-Creation-Date: 2025-10-27 02:58+0800\nPO-Revision-Date: 2025-11-07 10:00+0800\nLast-Translator: GitHub Copilot <EMAIL@ADDRESS>\nLanguage-Team: Chinese Simplified <LL@li.org>\nLanguage: zh_CN\nMIME-Version: 1.0\nContent-Type: text/plain; charset=UTF-8\nContent-Transfer-Encoding: 8bit",
            (False, ("FIRST AUTHOR <FhyTan@outlook.com>, 2023.",)),
        ),
    ),
    (
        ("Operator", "Export Settings"),
        (
            (
                "bpy.types.ANIM_REVIEWER_OT_export_settings",
                "bpy.types.ANIM_REVIEWER_OT_export_settings",
            ),
            (),
        ),
        ("zh_HANS", "导出设置", (False, ())),
    ),
    (
        ("Operator", "Import Settings"),
        (
            (
                "bpy.types.ANIM_REVIEWER_OT_import_settings",
                "bpy.types.ANIM_REVIEWER_OT_import_settings",
            ),
            (),
        ),
        ("zh_HANS", "导入设置", (False, ())),
    ),
    (
        ("*", "Add a Anim Reviewer Preset"),
        (
            (
                "bpy.types.ANIM_REVIEWER_OT_preset_add",
                "bpy.types.ANIM_REVIEWER_OT_preset_add",
            ),
            (),
        ),
        ("zh_HANS", "添加 Anim Reviewer 预设", (False, ())),
    ),
    (
        ("Operator", "Add Anim Reviewer Preset"),
        (
            (
                "bpy.types.ANIM_REVIEWER_OT_preset_add",
                "bpy.types.ANIM_REVIEWER_OT_preset_add",
            ),
            (),
        ),
        ("zh_HANS", "添加 Anim Reviewer 预设", (False, ())),
    ),
    (
        ("Operator", "Run Anim Review"),
        (
            (
                "bpy.types.RENDER_OT_anim_review",
                "bpy.types.RENDER_OT_anim_review",
                "extensions/vscode_development/anim_reviewer/panels.py:40",
            ),
            (),
        ),
        ("zh_HANS", "运行拍屏", (False, ())),
    ),
    (
        ("*", "Export current Anim Reviewer settings to a file"),
        (("bpy.types.ANIM_REVIEWER_OT_export_settings",), ()),
        ("zh_HANS", "将当前 Anim Reviewer 设置导出到文件", (True, ())),
    ),
    (
        ("*", "Import Anim Reviewer settings from a file"),
        (("bpy.types.ANIM_REVIEWER_OT_import_settings",), ()),
        ("zh_HANS", "从文件中导入 Anim Reviewer 设置", (False, ())),
    ),
    (
        (
            "*",
            "Create a playblast video of the current scene.\nPlease ensure you have an active camera and ffmpeg is installed in your system.",
        ),
        (("bpy.types.RENDER_OT_anim_review",), ()),
        (
            "zh_HANS",
            "为当前场景创建拍屏视频。\n请确保场景有激活的相机且系统已安装 ffmpeg。",
            (False, ()),
        ),
    ),
    (
        ("*", "Collection Definition"),
        (("bpy.types.CollectionProperty",), ()),
        ("zh_HANS", "集合定义", (False, ())),
    ),
    (
        ("*", "RNA collection property to define lists, arrays and mappings"),
        (("bpy.types.CollectionProperty",), ()),
        ("zh_HANS", "RNA 集合属性，用于定义列表、数组和映射", (False, ())),
    ),
    (
        ("*", "Pointer Type"),
        (("bpy.types.CollectionProperty.fixed_type",), ()),
        ("zh_HANS", "指针类型", (False, ())),
    ),
    (
        ("*", "Fixed pointer type, empty if variable type"),
        (("bpy.types.CollectionProperty.fixed_type",), ()),
        ("zh_HANS", "固定指针类型，如为可变类型则为空", (False, ())),
    ),
    (
        ("*", "Text to display in the bottom center"),
        (("bpy.types.BurnInProperties.bottom_center",), ()),
        ("zh_HANS", "在底部中央显示的文字", (False, ())),
    ),
    (
        ("*", "Text to display in the bottom left corner"),
        (("bpy.types.BurnInProperties.bottom_left",), ()),
        ("zh_HANS", "在左下角显示的文字", (False, ())),
    ),
    (
        ("*", "Text to display in the bottom right corner"),
        (("bpy.types.BurnInProperties.bottom_right",), ()),
        ("zh_HANS", "在右下角显示的文字", (False, ())),
    ),
    (
        ("*", "Color of the burn-in text"),
        (("bpy.types.BurnInProperties.color",), ()),
        ("zh_HANS", "叠加文字颜色", (False, ())),
    ),
    (
        ("*", "Enable Burn-In Data"),
        (("bpy.types.BurnInProperties.enable",), ()),
        ("zh_HANS", "启用叠加信息", (False, ())),
    ),
    (
        ("*", "Enable burn-in text overlay on the playblast."),
        (("bpy.types.BurnInProperties.enable",), ()),
        ("zh_HANS", "在拍屏上启用叠加文字", (False, ())),
    ),
    (
        ("*", "Font Family"),
        (("bpy.types.BurnInProperties.font_family",), ()),
        ("zh_HANS", "字体", (False, ())),
    ),
    (
        ("*", "Font family for the burn-in text"),
        (("bpy.types.BurnInProperties.font_family",), ()),
        ("zh_HANS", "叠写文字的字体", (False, ())),
    ),
    (
        ("*", "Size of the burn-in text font"),
        (("bpy.types.BurnInProperties.font_size",), ()),
        ("zh_HANS", "叠写文字的字体大小", (False, ())),
    ),
    (
        ("*", "Text margin from the edges of the viewport"),
        (("bpy.types.BurnInProperties.margin",), ()),
        ("zh_HANS", "文本与视口边缘的间距", (False, ())),
    ),
    (
        ("*", "Preview in Viewport"),
        (("bpy.types.BurnInProperties.preview",), ()),
        ("zh_HANS", "在视口中预览", (False, ())),
    ),
    (
        (
            "*",
            "Preview the burn-in text in the 3D viewport\nYou need to be in Camera view to see it",
        ),
        (("bpy.types.BurnInProperties.preview",), ()),
        ("zh_HANS", "在 3D 视口中预览叠写文字\n需要处于相机视图才能看到", (False, ())),
    ),
    (
        ("*", "Text to display in the top center"),
        (("bpy.types.BurnInProperties.top_center",), ()),
        ("zh_HANS", "在顶部中央显示的文字", (False, ())),
    ),
    (
        ("*", "Text to display in the top left corner"),
        (("bpy.types.BurnInProperties.top_left",), ()),
        ("zh_HANS", "在左上角显示的文字", (False, ())),
    ),
    (
        ("*", "Text to display in the top right corner"),
        (("bpy.types.BurnInProperties.top_right",), ()),
        ("zh_HANS", "在右上角显示的文字", (False, ())),
    ),
    (
        (
            "*",
            "Directory to save the playblast file. \nDefaults to the current blend file's directory (`//`). \nIf the blend file is not saved, a temporary directory will be used instead.",
        ),
        (("bpy.types.FileProperties.directory",), ()),
        (
            "zh_HANS",
            "保存拍屏文件的目录。\n默认为当前 .blend 文件所在目录 (`//`)。\n如果 .blend 文件尚未保存，将使用临时目录。",
            (False, ()),
        ),
    ),
    (
        ("*", "File extension for playblast"),
        (("bpy.types.FileProperties.extension",), ()),
        ("zh_HANS", "拍屏文件的扩展名", (False, ())),
    ),
    (
        ("*", "MP4 format"),
        (("bpy.types.FileProperties.extension:'.mp4'",), ()),
        ("zh_HANS", "MP4 格式", (False, ())),
    ),
    (
        ("*", "MOV format"),
        (("bpy.types.FileProperties.extension:'.mov'",), ()),
        ("zh_HANS", "MOV 格式", (False, ())),
    ),
    (
        ("*", "AVI format"),
        (("bpy.types.FileProperties.extension:'.avi'",), ()),
        ("zh_HANS", "AVI 格式", (False, ())),
    ),
    (
        ("*", "MKV format"),
        (("bpy.types.FileProperties.extension:'.mkv'",), ()),
        ("zh_HANS", "MKV 格式", (False, ())),
    ),
    (
        (
            "*",
            "Read-only properties.\nJoin all parts to get the full path of the playblast file.",
        ),
        (("bpy.types.FileProperties.full_path",), ()),
        (
            "zh_HANS",
            "只读属性。\n将所有部分拼接以获取拍屏文件的完整路径。",
            (False, ()),
        ),
    ),
    (
        ("*", "Base name for playblast file"),
        (("bpy.types.FileProperties.name",), ()),
        ("zh_HANS", "拍屏文件的名称", (False, ())),
    ),
    (
        ("*", "Use Version"),
        (("bpy.types.FileProperties.use_version",), ()),
        ("zh_HANS", "使用版本", (False, ())),
    ),
    (
        ("*", "Version number for the playblast file"),
        (("bpy.types.FileProperties.version",), ()),
        ("zh_HANS", "拍屏文件的版本号", (False, ())),
    ),
    (
        ("*", "Version String"),
        (("bpy.types.FileProperties.version_str",), ()),
        ("zh_HANS", "版本字符串", (False, ())),
    ),
    (
        (
            "*",
            "Read-only properties.\nGet version string from the version number.If version is 1, return v001.Else return empty string.",
        ),
        (("bpy.types.FileProperties.version_str",), ()),
        (
            "zh_HANS",
            "只读属性。\n从版本号获取版本字符串。如果版本为 1，返回 v001；否则返回空字符串。",
            (False, ()),
        ),
    ),
    (
        ("*", "End frame for the playblast"),
        (("bpy.types.OverrideProperties.frame_end",), ()),
        ("zh_HANS", "拍屏的结束帧", (False, ())),
    ),
    (
        ("*", "Start frame for the playblast"),
        (("bpy.types.OverrideProperties.frame_start",), ()),
        ("zh_HANS", "拍屏的起始帧", (False, ())),
    ),
    (
        ("*", "Scale factor for the playblast resolution"),
        (("bpy.types.OverrideProperties.scale",), ()),
        ("zh_HANS", "拍屏分辨率的缩放因子", (False, ())),
    ),
    (
        ("*", "Show overlays like gizmos and outlines in the playblast"),
        (("bpy.types.OverrideProperties.show_overlays",), ()),
        ("zh_HANS", "在拍屏中显示诸如操纵器和轮廓线等叠加元素", (False, ())),
    ),
    (
        (
            "*",
            "Use specific frame range for the playblast instead of the entire scene frame range\nIf disabled, the playblast will use the scene's start and end frames",
        ),
        (("bpy.types.OverrideProperties.use_frame_range",), ()),
        (
            "zh_HANS",
            "为拍屏使用指定的帧范围而非整个场景的帧范围\n如果禁用，拍屏将使用场景的开始和结束帧",
            (False, ()),
        ),
    ),
    (
        ("*", "Use Viewport Shading"),
        (("bpy.types.OverrideProperties.use_viewport_shading",), ()),
        ("zh_HANS", "使用视口着色", (False, ())),
    ),
    (
        (
            "*",
            "Use specific viewport shading mode for the playblast\nIf disabled, the playblast will use the scene's viewport shading mode",
        ),
        (("bpy.types.OverrideProperties.use_viewport_shading",), ()),
        (
            "zh_HANS",
            "为拍屏使用指定的视口着色模式\n如果禁用，拍屏将使用场景的视口着色模式",
            (False, ()),
        ),
    ),
    (
        ("*", "Viewport shading mode for the playblast"),
        (("bpy.types.OverrideProperties.viewport_shading",), ()),
        ("zh_HANS", "拍屏的视口着色模式", (False, ())),
    ),
    (
        ("*", "Wireframe shading"),
        (("bpy.types.OverrideProperties.viewport_shading:'WIREFRAME'",), ()),
        ("zh_HANS", "线框着色", (False, ())),
    ),
    (
        ("*", "Solid shading"),
        (("bpy.types.OverrideProperties.viewport_shading:'SOLID'",), ()),
        ("zh_HANS", "实体着色", (False, ())),
    ),
    (
        ("*", "Material shading"),
        (("bpy.types.OverrideProperties.viewport_shading:'MATERIAL'",), ()),
        ("zh_HANS", "材质着色", (False, ())),
    ),
    (
        ("*", "Rendered shading"),
        (("bpy.types.OverrideProperties.viewport_shading:'RENDERED'",), ()),
        ("zh_HANS", "渲染着色", (False, ())),
    ),
    (
        ("*", "Video codec for playblast"),
        (("bpy.types.VideoProperties.codec",), ()),
        ("zh_HANS", "拍屏的视频编码器", (False, ())),
    ),
    (
        ("*", "H.264 codec"),
        (("bpy.types.VideoProperties.codec:'libx264'",), ()),
        ("zh_HANS", "H.264 编码", (False, ())),
    ),
    (
        ("*", "H.265"),
        (("bpy.types.VideoProperties.codec:'libx265'",), ()),
        ("zh_HANS", "H.265", (False, ())),
    ),
    (
        ("*", "H.265/HEVC codec"),
        (("bpy.types.VideoProperties.codec:'libx265'",), ()),
        ("zh_HANS", "H.265/HEVC 编码", (False, ())),
    ),
    (
        ("*", "MPEG-4 codec"),
        (("bpy.types.VideoProperties.codec:'mpeg4'",), ()),
        ("zh_HANS", "MPEG-4 编码", (False, ())),
    ),
    (
        ("*", "AV1 codec"),
        (("bpy.types.VideoProperties.codec:'libsvtav1'",), ()),
        ("zh_HANS", "AV1 编码", (False, ())),
    ),
    (
        ("*", "Include Audio"),
        (("bpy.types.VideoProperties.include_audio",), ()),
        ("zh_HANS", "包含音频", (False, ())),
    ),
    (
        ("*", "Include audio in the playblast video"),
        (("bpy.types.VideoProperties.include_audio",), ()),
        ("zh_HANS", "在拍屏视频中包含音频", (False, ())),
    ),
    (
        ("*", "FFmpeg is not installed or not found in PATH."),
        (("extensions/vscode_development/anim_reviewer/operators.py:151",), ()),
        ("zh_HANS", "未安装 FFmpeg 或未在 PATH 中找到。", (False, ())),
    ),
    (
        ("*", 'Playblast completed, saved to "{}", opening video...'),
        (
            (
                "extensions/vscode_development/anim_reviewer/operators.py:417",
                "extensions/vscode_development/anim_reviewer/operators.py:417",
            ),
            (),
        ),
        ("zh_HANS", '拍屏完成，已保存到 "{}"，正在打开视频...', (False, ())),
    ),
    (
        ("*", "FFmpeg processing failed, please open console for details."),
        (("extensions/vscode_development/anim_reviewer/operators.py:424",), ()),
        ("zh_HANS", "FFmpeg 处理失败，请打开控制台查看详细信息。", (False, ())),
    ),
    (
        ("*", "Frame Range"),
        (("extensions/vscode_development/anim_reviewer/panels.py:69",), ()),
        ("zh_HANS", "帧范围", (False, ())),
    ),
    (
        ("*", "Start"),
        (("extensions/vscode_development/anim_reviewer/panels.py:73",), ()),
        ("zh_HANS", "开始", (False, ())),
    ),
    (
        ("*", "End"),
        (("extensions/vscode_development/anim_reviewer/panels.py:74",), ()),
        ("zh_HANS", "结束", (False, ())),
    ),
    (
        ("*", "Viewport Shading"),
        (("extensions/vscode_development/anim_reviewer/panels.py:79",), ()),
        ("zh_HANS", "视口着色", (False, ())),
    ),
    (
        ("*", "Default to current blend file directory"),
        (("extensions/vscode_development/anim_reviewer/panels.py:107",), ()),
        ("zh_HANS", "默认使用当前 .blend 文件目录", (False, ())),
    ),
    (
        ("*", "Version"),
        (("extensions/vscode_development/anim_reviewer/panels.py:111",), ()),
        ("zh_HANS", "版本", (False, ())),
    ),
    (
        ("*", "Default to Blender Font"),
        (("extensions/vscode_development/anim_reviewer/panels.py:151",), ()),
        ("zh_HANS", "默认使用 Blender 字体", (False, ())),
    ),
    (
        (
            "*",
            "Use curly braces {} to denote variables in text, for example {datetime} for the current time.",
        ),
        (("extensions/vscode_development/anim_reviewer/panels.py:176",), ()),
        (
            "zh_HANS",
            "在文本中使用花括号 {} 表示变量，例如 {datetime} 表示当前时间。",
            (False, ()),
        ),
    ),
    (
        ("*", "The following variables are currently available:"),
        (("extensions/vscode_development/anim_reviewer/panels.py:178",), ()),
        ("zh_HANS", "当前可用的变量如下：", (False, ())),
    ),
    (
        ("Operator", "Import"),
        (("extensions/vscode_development/anim_reviewer/panels.py:201",), ()),
        ("zh_HANS", "导入", (False, ())),
    ),
    (
        ("Operator", "Export"),
        (("extensions/vscode_development/anim_reviewer/panels.py:202",), ()),
        ("zh_HANS", "导出", (False, ())),
    ),
    (
        ("*", "{}"),
        (("extensions/vscode_development/anim_reviewer/panels.py:182",), ()),
        ("zh_HANS", "{}", (False, ())),
    ),
    (
        ("*", "File not found: {!r}"),
        (("extensions/vscode_development/anim_reviewer/utils.py:56",), ()),
        ("zh_HANS", "未找到文件：{!r}", (False, ())),
    ),
    (
        ("*", "Couldn't run external animation player with command {!r}\n{:s}"),
        (("extensions/vscode_development/anim_reviewer/utils.py:141",), ()),
        ("zh_HANS", "无法使用命令 {!r} 运行外部动画播放器\n{:s}", (False, ())),
    ),
    (
        ("*", "Anim Reviewer"),
        (("Add-on Anim Reviewer info: name",), ()),
        ("zh_HANS", "", (False, ())),
    ),
    (
        ("*", "Enhance blender playblast capabilities for animation review"),
        (("Add-on Anim Reviewer info: description",), ()),
        ("zh_HANS", "增强 blender 拍屏功能", (False, ())),
    ),
)

translations_dict = {}
for msg in translations_tuple:
    key = msg[0]
    for lang, trans, (is_fuzzy, comments) in msg[2:]:
        if trans and not is_fuzzy:
            translations_dict.setdefault(lang, {})[key] = trans

# ##### END AUTOGENERATED I18N SECTION #####

# Manual translations can be added here
translations_dict["zh_HANS"].update(
    {
        ("*", "Burn-In Data"): "叠加信息",
        ("*", "Current date and time"): "当前日期和时间",
        ("*", "Playblast width in pixels"): "拍屏宽度（像素）",
        ("*", "Playblast height in pixels"): "拍屏高度（像素）",
        ("*", "Name of the output file without extension"): "输出文件名（不含扩展名）",
        ("*", "Version string of the output file"): "输出文件的版本字符串",
        ("*", "File extension of the output file"): "输出文件的扩展名",
        ("*", "Full name of the output file with extension",): "包含扩展名的完整输出文件名",
        ("*", "Current frame number"): "当前帧数",
        ("*", "Start frame of the playblast"): "拍屏起始帧",
        ("*", "End frame of the playblast"): "拍屏结束帧",
        ("*", "Frame rate of the playblast"): "拍屏帧率",
        ("*", "Name of the active camera"): "激活相机的名称",
        ("*", "Focal length of the active camera in mm"): "激活相机的焦距（毫米）",
    }
)  # fmt: skip
