# /qompassai/dotfiles/.config/krb5/krb5.conf
# Qompass AI Krb5 Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

[libdefaults]
	default_realm = QOMPASS.AI
	dns_lookup_realm = false
	dns_lookup_kdc = false
	ticket_lifetime = 24h
	renew_lifetime = 7d
	forwardable = true

[realms]
	QOMPASS.AI = {
        kdc = kerberos.qompass.ai
		admin_server = kerberos.qompass.ai
	}

[domain_realm]
  .qompass.ai = QOMPASS.AI
  qompass.ai = QOMPASS.AI
[logging]
  kdc = FILE:/var/log/krb5kdc.log
  admin_server = FILE:/var/log/kadmin.log
  default = FILE:/var/log/krb5lib.log

