# /qompassai/dotfiles/.config/java-jdk/jaxp.properties
javax.xml.parsers.DocumentBuilderFactory=com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl
jdk.xml.enableExtensionFunctions=true
jdk.xml.overrideDefaultParser=false
javax.xml.accessExternalDTD=file
javax.xml.accessExternalSchema=file, http
javax.xml.accessExternalStylesheet=""
javax.xml.accessExternalStylesheet="all"
javax.xml.catalog.files = file:///users/auser/catalog/catalog.xml
javax.xml.catalog.defer=true
javax.xml.catalog.resolve=strict
javax.xml.useCatalog=true
Implementation Specific Properties - jdkcatalog.resolve
jdk.xml.jdkcatalog.resolve=continue
jdk.xml.dtd.support=deny
jdk.xml.dtd.support=allow
jdk.xml.entityExpansionLimit=2500
jdk.xml.totalEntitySizeLimit=100000
jdk.xml.maxGeneralEntitySizeLimit=100000
jdk.xml.maxParameterEntitySizeLimit=15000
jdk.xml.entityReplacementLimit=100000
jdk.xml.elementAttributeLimit=200
jdk.xml.maxOccurLimit=5000
jdk.xml.maxElementDepth=100
jdk.xml.maxXMLNameLimit=1000
jdk.xml.xpathExprGrpLimit=10
jdk.xml.xpathExprOpLimit=100
jdk.xml.xpathTotalOpLimit=10000
