javax.sound.midi.Receiver
javax.sound.midi.Sequencer
javax.sound.midi.Synthesizer
javax.sound.midi.Transmitter
javax.sound.sampled.Clip
javax.sound.sampled.Port
javax.sound.sampled.SourceDataLine
javax.sound.sampled.TargetDataLine
javax.sound.midi.Receiver=com.sun.media.sound.MidiProvider#SunMIDI1
