# font.conf
# Qompass AI - [Add description here]
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
font-family = DaddyTimeMono Nerd Font Mono
font-feature = +liga
font-feature = +calt
font-size = 13
font-style = Regular
foreground = #7DF9FF
freetype-load-flags = hinting
gtk-single-instance = desktop

