# /qompassai/dotfiles/.config/ghostty/gtk.conf
# Qompass AI Ghostty GTK Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
gtk-opengl-debug = true
gtk-single-instance = detect
gtk-tabs-location = top
gtk-titlebar = true
gtk-titlebar-hide-when-maximized = true
gtk-toolbar-style = raised-border
gtk-quick-terminal-layer = overlay
