# /qompassai/dotfiles/.config/ghostty/mouse.conf
# Qompass AI Ghostty Mouse Config
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
click-repeat-interval = 0
focus-follows-mouse = true
mouse-scroll-multiplier = 1
mouse-shift-capture = true
right-click-action = copy-or-paste

