# /qompassai/dotfiles/qai/diver/lua/selene.toml
# Qompass AI Diver selene.toml
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
std = "luajit"

[diagnostics]
empty_if = false
global_usage = { severity = "allow", names = ["vim", "jit", "LazyVim"] }
redefined_variable = false
unused_function = "warn"
unused_variable = { severity = "deny", ignore = ["_"] }

[globals]
"bit" = {}
"coroutine" = {}
"debug" = {}
"io" = {}
"ipairs" = {}
"jit" = {}
"os" = {}
"package" = {}
"pcall" = {}
"require" = {}
"string" = {}
"table" = {}
"utf8" = {}
"vim" = {}
"vim.api" = {}
"vim.fn" = {}
"vim.opt" = {}
"LazyVim" = {}

[output]
color = "auto"
display_style = "rich"
quiet = false

[performance]
num_threads = 8

exclude = ["lua/bench/**", "lua/tests/**"]
include = ["lua/**/*.lua"]

[if_std = "luajit"]
 [diagnostics]
 check_globals = false

[types]
 "UserConfig" = [[
   {
     theme: "dark"|"light",
     keymaps: { [string]: string }
   }
 ]]
