# /qompassai/dotfiles/.config/ipp-usb/ipp-usb.conf
# Qompass AI Ipp-USB Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[network]
  http-min-port = 60000
  http-max-port = 65535
  dns-sd = enable
  interface = loopback
  ipv6 = enable
[auth uid]
  all = *
[logging]
  device-log    = all
  main-log      = debug
  console-log   = debug
  max-file-size    = 256K
  max-backup-files = 5
  console-color = enable
  get-all-printer-attrs = true
# vim:ts=8:sw=2:et
