// qompassai/dotfiles/.config/firebuild/firebuild.conf
// Qompass AI Firebuild Config
// Copyright (C) 2025 Qompass AI, All rights reserved
/////////////////////////////////////////////////////
// Reference: https://combust-labs.github.io/firebuild-docs/configuration/
env_vars = {
  fingerprint_skip = [
    "CARGO_MAKEFLAGS", "MAKE_TERMERR", "MAKE_TERMOUT",
    "MAKEFLAGS", "MFLAGS"
  ];
  pass_through = [
    "HOME", "PATH", "PWD", "SHELL"
  ];
  preset = [
    "CCACHE_DISABLE=1"
  ];
};
ignore_locations = [
  "/dev/autofs_nowait",
  "/dev/full",
  "/dev/null",
  "/dev/random",
  "/dev/tty",
  "/dev/urandom",
  "/dev/zero",
  "/proc/cpuinfo",
  "/proc/filesystems",
  "/proc/meminfo",
  "/proc/net",
  "/proc/self",
  "/proc/stat",
  "/sys/devices",
  "/sys/fs/cgroup",
  "/var/run/syslog",
  "/var/run/usbmuxd"
];
min_cpu_time = 0.000;
processes = {
  dont_intercept = [
    "ccache",
    "fakeroot",
    "gradle",
    "go",
    "sandbox-exec"
  ];
  dont_shortcut = [
    "ls",
    "make",
    "ninja",
    "stat"
    // "sleep"
  ];
  shells = [
    "/bin/bash", "/bin/dash", "/bin/sh",
    "bash", "dash", "sh"
  ];

  shortcut_allow_list = [
    // Add more as desired
  ];

  skip_cache = [
    "[", "arch", "basename", "cat", "chgrp", "chmod", "chown", "cp", "cut",
    "dd", "dir", "dirname", "echo", "egrep", "expr", "false", "fgrep", "grep",
    "head", "install", "link", "ln", "mkdir", "mv", "printf", "pwd", "rgrep",
    "readlink", "realpath", "rm", "rmdir", "seq", "sed", "tail", "test",
    "touch", "tr", "true", "unlink", "sh"
  ];
};

quirks = [
  "guess-file-params",
  "ignore-statfs",
  "ignore-time-queries",
  "ignore-tmp-listing",
  "lto-wrapper"
];

read_only_locations = [
  "/bin", "/etc", "/lib", "/lib32", "/lib64", "/libx32",
  "/opt", "/proc/sys", "/sbin", "/snap", "/usr"
];

shortcut_tries = 20;
version = 1.0;
max_cache_size = 5.0;
max_entry_size = 250.0;
