# /qompassai/dotfiles/.config/udev/udev.conf
# Qompass AI UDev Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
#children_max=
event_timeout=180
resolve_names=early
udev_log=info
#exec_delay=
timeout_signal=SIGKILL
