# /qompassai/dotfiles/.config/infnoise/infnoise.conf
# Qompass AI InfNoise Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
INFNOISE_DEBUG=true
INFNOISE_MULTIPLIER=10
#INFNOISE_SERIAL=DO0032ZA
# Use `infnoise --list-devices` to find your serial number
