schema_version = "1.0.0"
id = "PivotTools"
name = "Pivot Tools"
version = "1.48.13"
tagline = "Fast pivot placement with Auto Pick, BBox targets, Saved Pivots"

maintainer = "Henrik Drygas"
type = "add-on"

blender_version_min = "4.5.0"


license = ["SPDX:GPL-3.0-or-later"]

website = "https://extensions.blender.org"
