# /qompassai/dotfiles/.config/sysusers.d/swtpm.conf
# Qompass AI SWTPM Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
g swtpm - -
u swtpm - "Software TPM" /var/lib/swtpm
