# /qompassai/dotfiles/.config/dxvk/dxvk.conf
# Qompass AI Direct X Vulkan (DXVK) Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
dxvk.allowFse = True
dxvk.allowMemoryOvercommit = True
# dxvk.enableAsync = True
dxvk.enableStateCache = True
dxvk.useRawSsbo = True
# dxgi.hideAmdGpu = True
# dxgi.hideNvidiaGpu = True
# dxgi.customDeviceId = 1234
# dxgi.customVendorId = 10de
dxgi.fakeDx10Support = True
dxgi.maxFrameLatency = 1
# dxgi.maxDeviceMemory = 4096
# dxgi.maxSharedMemory = 8192
# dxgi.syncInterval = 1
# d3d11.maxFeatureLevel = 11_0
# dxvk.hud = fps,memory
# dxvk.pollPeriod = 0
# DXVK_SHADER_CACHE_PATH=<path>
# DXVK_LOG_PATH=<path>
# https://github.com/doitsujin/dxvk/wiki/Configuration
