# /qompassai/dotfiles/.config/webapps/gitlab-shell/config.yml
# Qompass AI GitLab-Shell WebApp Config
# Copyright (C) 2025 Qompass AI, All rights reserved
##############################################################
# References: 
# - https://gitlab.com/groups/gitlab-org/-/epics/11872
# - https://docs.gitlab.com/ee/development/distributed_tracing.html
# - https://docs.gitlab.com/ee/development/gitlab_shell/features.html#personal-access-token
# - https://github.com/pires/go-proxyproto/blob/195fedcfbfc1be163f3a0d507fac1709e9d81fed/policy.go#L20

auth_file: "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/authorized_keys"
audit_usernames: true
gitlab_relative_url_root: "/"
gitlab_tracing: "opentracing://driver"
gitlab_url: "http+unix://%2Frun%2Fgitlab%2Fgitlab-workhorse.socket"
lfs:
  pure_ssh_protocol: false
log_file: "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/gitlab-shell.log"
log_format: json
log_level: INFO
pat:
  allowed_scopes: [read_repository]
  enabled: true
secret: "$(pass show gls/pat)"
secret_file: "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/.gitlab_shell_secret"
sl_cert_dir: "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/ssl/certs/"
sshd:
  client_alive_interval: 15
  concurrent_sessions_limit: 10
  ciphers:
    - aes128-ctr
    - aes128-gcm@openssh.com
    - aes192-ctr
    - aes256-ctr
    - aes256-gcm@openssh.com
    - chacha20-poly1305@openssh.com
  gssapi:
    enabled: true
    keytab: "$(pass show gls/gssapikeytab)"
    service_principal_name: "$(pass show gls/serverpname)"
  grace_period: 10
  host_key_certs:
    - "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/ssh-hostkeys/ssh_host_rsa_key-cert.pub"
    - "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/ssh-hostkeys/ssh_host_ecdsa_key-cert.pub"
    - "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/ssh-hostkeys/ssh_host_ed25519_key-cert.pub"
  host_key_files:
    - "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/ssh-hostkeys/ssh_host_rsa_key"
    - "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/ssh-hostkeys/ssh_host_ecdsa_key"
    - "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/ssh-hostkeys/ssh_host_ed25519_key"
  kex_algorithms:
    - curve25519-sha256
    - curve25519-sha256@libssh.org
    - diffie-hellman-group14-sha1
    - diffie-hellman-group14-sha256
    - ecdh-sha2-nistp256
    - ecdh-sha2-nistp384
    - ecdh-sha2-nistp521
  listen: "[::]:22"
  liveness_probe: "/health"
  login_grace_time: 60
  macs:
    - hmac-sha1
    - hmac-sha2-256
    - hmac-sha2-256-etm@openssh.com
    - hmac-sha2-512
    - hmac-sha2-512-etm@openssh.com
  proxy_allowed:
    - "$(pass show gls/proxy1)"
    - "$(pass show gls/proxy2)"
  proxy_header_timeout: 500ms
  proxy_policy: "use"
  proxy_protocol: true
  public_key_algorithms:
    - ecdsa-sha2-nistp256
    - ecdsa-sha2-nistp384
    - ecdsa-sha2-nistp521
    - rsa-sha2-256
    - rsa-sha2-512
    - sk-ecdsa-sha2-nistp256@openssh.com
    - sk-ssh-ed25519@openssh.com
    - ssh-dss
    - ssh-ed25519
    - ssh-rsa
  readiness_probe: "/start"
  web_listen: "localhost:9122"
"http_settings":
  ca_file: "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/ssl/cert.pem"
  ca_path: "${XDG_DATA_HOME:-/home/${USER}/.local/share}/gitlab-shell/ssl/certs/"
  password: "$(pass show gls/pass)"
  read_timeout: 300
  user: "$(pass show gls/user)"
user: "$(pass show gls/user)"
