#!/usr/bin/env bash
# /qompassa/dotfiles/.config/pacman/archpkgs.sh
# Qompass AI Pacman Archpkgs Script
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
# pacman -Qq | sort > archpkgs.sh
PKGS=(
	389-ds-base
	3cpio
	6tunnel
	aalib
	abeluna
	abuild
	acme-cli
	acme-user
	acpi_call-dkms
	acsccid
	act
	actionlint
	adbfs-rootless-git
	addr-book-combine-git
	adlplug-lv2
	adriconf
	aeolus
	aerc
	af9015-firmware
	afew
	afl-utils
	agda
	agda-stdlib
	age
	age-plugin-tkey
	age-plugin-tpm
	age-plugin-yubikey
	aha
	aida-x
	aida-x-clap
	aida-x-lv2
	aida-x-vst
	aida-x-vst3
	airgorah
	airshipper
	airspy
	akvcam-dkms
	alejandra
	algernon
	alliedvision-vimba-x
	alot
	alpine
	alpm-lint
	alpm-pkgbuild-bridge
	alsacap
	alsa-config-utils
	alsa-control
	alsaequal
	alsa-firmware
	alsa-hdspeconf
	alsa-oss
	alsa-rnnoise
	alsa-tools
	alsause
	alsa-utils
	alure
	alvr
	amavisd-milter
	amavisd-new
	ambix
	ambix-lv2
	amb-plugins
	amfora
	ammonite
	ams
	amsynth
	amsynth-dssi
	amsynth-lv2
	amsynth-vst
	androguard
	android-emulator
	android-file-transfer
	android-google-repository
	android-meson
	android-ndk
	android-platform
	android-sdk-build-tools
	android-sdk-build-tools-17
	android-sdk-platform-tools
	android-studio-canary
	android-tethering
	android-tools
	android-udev
	angryoxide
	anoise-media
	ansible-aur
	ansible-bender
	ansible-creator
	ansible-gopass
	ansible-gpg-key-git
	ansible-gsetting-git
	ansible-language-server
	ansible-lint
	ansible-navigator
	anthy
	antigravity-preview
	anubis
	anyremote
	apache-ant-contrib
	apache-ant-maven-tasks
	apache-cxf
	apache-flink
	apache-lucene
	apache-mod_auth_mellon
	apfsprogs
	apk-mitm
	apko
	apksigcopier
	apparmor
	app-icon-preview
	apptainer
	apt-swarm
	aravis
	arch-audit
	arch-checkfw
	archinstall
	archiso
	archivetools
	archlinux-contrib
	archlinux-xdg-menu
	arch-rebuild-order
	arch-repro-status
	arch-sign-modules
	arch-signoff
	arch-udev-usb-sync
	ardour
	arduino-fwuploader
	arduino-language-server
	arpfox
	arrow-tools
	artyfx
	ascii
	asciidoc
	asciidoctor
	asciidoctor-pdf
	asciinema
	asciiquarium
	asm-lsp
	asmx
	asnmap
	asoundconf
	aspeak
	aspnet-targeting-pack
	aspnet-targeting-pack-6.0
	aspnet-targeting-pack-7.0
	aspnet-targeting-pack-8.0
	ast-grep
	astroid
	astrojs-language-server
	astronaut
	at51
	atool
	atools
	audacity
	audacity-plugins
	audaspace
	audio-convert
	audio-share
	audio-sharing
	audiosource
	audispd-plugins
	audispd-plugins-zos
	augratin
	aurpublish
	aur-pull
	aurum
	aurutils
	auth-get-sso-cookie
	authoscope
	autofs
	autogen
	automattermostatus
	autossh
	autotools-language-server
	avisynthplus
	avldrums.lv2
	avrdude
	avr-gdb
	avr-libc
	awesome
	awesome-omarchy-tui
	awesome-terminal-fonts
	awesome-terminal-fonts-patched
	awk-language-server
	awstats
	aws-vault
	awxkit
	ayugram-desktop-bin
	azcopy
	azure-cli
	azure-kubelogin
	b3sum
	b4
	b43-fwcutter
	bacon
	bagels
	baikal
	bandit
	barnyard2
	bar-protonmail
	base
	base-devel
	basedpyright
	bash-completion
	bashdb
	bash-debugger
	bash-language-server
	bastyon
	bat-extras
	bazelrc-lsp
	bchoppr
	bear
	beautysh
	bettercap
	bettercap-caplets
	bettercap-ui
	bezier
	bibata-cursor-theme
	bibata-cursor-translucent
	bibata-extra-cursor-theme
	bibclean
	biber
	bibiman
	bibtex2website
	bibtex-tidy
	bibtool
	bigsh0t
	binaryen
	biome
	birdfont
	bkcrack
	blackmagic
	black-magic-probe-utils
	blade-formatter
	bladerf
	blas64-openblas
	blas-openblas
	blender
	blendnet
	blendr
	bloop
	bloop-systemd
	blop
	bltui
	bluealsa
	bluemail
	blueman
	bluesync
	bluetooth-autoconnect
	bluetooth-bitrate-manager
	bluetui
	bluetuith
	bluez-cups
	bluez-deprecated-tools
	bluez-hid2hci
	bluez-mesh
	bluez-monitor
	bluez-obex
	bluez-qt
	bluez-qt5
	bluez-tools
	bluez-utils
	blur-effect
	bmkdep
	bmputil
	bmusb
	bob
	bogofilter-sqlite
	bolt
	bonzomatic
	bookshelf
	bootconfig
	borgctl
	borgit
	borgmatic
	borgreport
	borgrestore
	bottles
	bounty-git
	broadcom-bt-firmware
	broadcom-wl-dkms
	browserify
	browserpass
	browserpass-chrome
	browserpass-chromium
	browserpass-firefox
	bsum
	btattach
	btcpayserver
	btctl
	bthandler
	btlescan
	btmenu
	btop
	btrfs-assistant
	btrfs-desktop-notification
	btrfs-list-git
	btrfs-progs
	btscanner
	bugzilla
	buildkit
	bully
	burp-backup
	burpsuite
	bus-pirate
	bw-pinentry
	byobu
	c3-lsp
	cable
	cache-cleaner
	cacti
	cacti-spine
	cadaver
	caido-cli
	cairo-xml
	caja
	caja-admin
	caja-audio-video-properties
	caja-image-converter
	caja-open-any-terminal
	caja-open-terminal
	caja-share
	calendarsupport
	caligula
	cameracontrol-bin
	cameractrls
	capnproto
	capypdf
	carbonyl
	cardinal
	cardinal-clap
	cardinal-vst
	cardinal-vst3
	cargo-make
	cargo-rdme
	cargo-supply-chain
	cargo-zigbuild
	carla
	casync
	catdoc
	catdvi
	catgirl
	catgirl-engine
	catimg
	cava
	cb3sum
	cc1541
	ccache
	ccls
	cdrtools
	cern-phone-app
	cern-vdt
	certbot-apache
	certbot-dns-cloudflare
	cfssl
	cgasm
	cgproxy
	check-cve-2019-19781
	check-jsonschema
	checkmake
	checkra1n-cli
	checkra1n-gui
	checkstyle-bin
	chipsec-dkms-git
	chkrootkit
	chromaprint-fftw
	chromium
	chromium-bypass-paywalls-clean
	circumflex
	cisco-regex
	cjdns
	clamav
	clamav-unofficial-sigs
	clang18
	clang19
	clap
	clash-ghc
	claude-code
	claude-code-acp
	claude-code-router
	claude-desktop-native
	clazy
	clblast
	clcal
	clcbrowser-git
	clevis
	clightd
	clion-eap-lldb
	clion-gdb
	clion-lldb
	cliphist
	clojure
	cloudemoticon-rs
	cloudflared
	cloudflare-dynamic-dns
	cloudflarespeedtest
	clpeak
	clspv-git
	clusterssh
	clutter-gst
	clvk-git
	cmake
	cmake-extras
	cmake-language-server
	cmark-gfm
	cmctl
	cmm-svn
	cni-plugins
	cocogitto
	codeberg-cli
	codebook-lsp
	codec2
	codecvisa-bin
	code-format-bin
	codelldb
	codeql
	collision
	colord-gtk
	colord-gtk4
	colord-sane
	colorgcc
	commitlint
	commitmsgfmt
	compiler-rt18
	compiler-rt19
	composer
	concrnt-gateway
	connman
	consul
	consul-template
	container-diff
	context-modules
	convmv
	coolkey
	cops-mikespub-org
	copyparty
	corefreq-dkms
	corkscrew
	corrosion
	cosign
	cotire
	cotp-converters
	cowrie
	cowsql
	cpio
	cppcodec
	cpupower
	crack-attack
	crack-attack-sounds
	crackpkcs12
	crawl-data
	crawl-ncurses
	crawl-tiles
	crictl
	cri-o
	cryfs
	cryptodev-linux-dkms
	cryptol
	cryptominisat
	cryptonose
	cryptsetup-gui
	cryptsetup-multidisk
	cryptsetup-vault
	cs-crypto
	csfml
	csharp-ls
	csound
	cspell-lsp
	csrf-brute
	ctags
	ctf-ynetd
	cuda
	cuda-demux
	cuda-tools
	cuishark
	cups-gssapi
	curlftpfs
	curl-impersonate
	curseforge
	curtail
	cutensor
	cvc4
	cvechecker
	cvector
	cvs
	cxltx-styles
	cxxbridge
	cxxopts
	cyan
	cyclops
	cyme
	cyrus-sasl-gssapi
	cython
	dante
	dark-reader
	darkstat
	davfs2
	davinconv
	davix
	davmail
	davutils
	dbeaver
	dblatex
	dbmail
	dbmate
	dbus-app-launcher
	dbus-docs
	dbus-soundrecorder
	dbus-term-launcher
	dbxtool
	dcd
	dcnnt
	dconf-editor
	dctl
	ddclient
	debian-archive-keyring
	debian-keyring
	debian-ports-archive-keyring
	decklink
	decklink-sdk
	dehydrated
	dehydrated-cloudflare-hook
	dehydrated-pdns-hook
	deltachat-rpc-server
	delve
	deno
	denoiseit-git
	depthcharge
	deskflow
	desktop-notify
	desktop-privileges
	desktop-privileges-nogroups
	desync
	detox
	devtools
	dex
	dfc
	dfrs
	dfu-programmer
	dfu-util
	dgen-sdl
	dhall-lsp-server
	dhcpcd
	dhcp-helper
	dialog
	diffstat
	dioxus-cli
	directx-headers-cmake
	direnv
	direnv-backup-git
	discord_db
	discord-game-sdk
	discordo-git
	discordo-launcher
	displaycal
	distcc
	distrho-ports
	distrho-ports-lv2
	dive
	dkms
	dleyna
	dleyna-docs
	dmenu
	dms-shell-hyprland
	dms-shell-niri
	dmtx-utils
	dnschanger-desktop
	dnsdiag
	dnsdist
	dnshunter
	dnsperf
	dnssec-tools
	docbook2x
	docbook5-xml
	docbook-dsssl
	docbook-mathml
	docbook-sgml
	docbook-sgml31
	docbook-utils
	docker-buildx
	docker-credential-pass
	docker-credential-secretservice
	dockerfile-language-server
	dockerize
	docker-rootless-extras
	dockle
	dokuwiki
	dolphin
	dolphin-emu
	dolt
	dos2unix
	dot2tex
	dot-language-server
	dotnet-aot-xc
	dotnet-install
	dotnet-runtime-7.0
	dotnet-sdk-7.0
	dotnet-source-built-artifacts
	dotnet-source-built-artifacts-6.0
	dotnet-source-built-artifacts-7.0
	dotnet-source-built-artifacts-8.0
	dotnet-targeting-pack-7.0
	dovecot
	doxx
	dpdk
	dprint
	dqlite
	dra
	drgn
	drm-info
	drminfo
	drm_tool
	droidcam
	drone-oss
	drone-runner-ssh
	dropbear
	dropbear-socket
	drumgizmo-lv2
	drupal
	dse
	d-spy
	dsq
	dssi
	dtk6declarative
	duckdb
	dumpling
	dump-shm
	dumptorrent
	dunst
	duplicity
	dv-processing
	dwayland
	dxvk-mingw
	easyeffects
	easyeffects-bundy01-presets
	easyeffects-digitalone1-presets-git
	easyeffects-jtrv-presets-git
	easyeffects-record
	easyfeh
	easyjson
	easyrpg-player
	ecasound
	eclint
	ecryptfs-utils
	edb-debugger
	editorconfig-checker
	editorconfiger
	edk2-aarch64
	edk2-arm
	edk2-ovmf
	efifs
	efm-langserver
	element
	element-desktop
	elf2nucleus
	elf2uf2-rs
	elixir
	elixir-ls
	ember-language-server
	emby-ffmpeg
	emmylua-ls-bin
	enola
	epic-asset-manager
	epydoc
	eq10q
	erdtree
	erlang
	erlang_ls
	esbonio
	esbuild
	eslint
	eslint_d
	eslint-language-server
	etckeeper
	etc-update
	eteroj.lv2
	ettercap
	evemu
	evilginx
	evolution
	exploitdb
	extra-cmake-modules
	f3
	fabric
	facetimehd-data
	facetimehd-dkms
	facetimehd-firmware
	fasm
	fastfetch
	fasttext
	fasttext-langid-models
	fasttuna
	fatfrog.lv2
	faust
	fcitx5
	fcitx5-anthy
	fcitx5-gtk
	fcitx5-qt
	fcrackzip
	fdm
	fdmf
	fdroidserver
	feh
	fehbg-mgr
	fennel
	ferium
	fern-wifi-cracker
	festival-english
	festival-us
	fetch-hosts
	fetchmail
	ffmpegthumbnailer
	ffmpegthumbs
	ffms2
	ffnvcodec-headers
	fftw-openmpi
	figma-agent-linux
	figma-linux
	figma-linux-font-helper
	filecast
	fil-plugins
	fingerprintx
	fingwit
	firecracker
	firecracker-docs
	firefox
	firefox-debugadapter
	firefox-extension-mailvelope
	firefoxpwa
	firefox-syncstorage
	firefox-user-autoconfig
	firmware-manager
	fish
	fish-autopair
	fish-bash2env
	fisher
	fish-fisher_path-git
	fish-fzf
	fish-lsp
	fishui
	flare-game
	flashmq
	flawz
	fluxcomp
	fmtools
	fnlfmt
	folder-color-switcher
	fomp.lv2
	fontobene-qt5
	fontobene-qt-qt6
	fontpreview_sixel
	foomatic-db-engine
	foot
	foot-terminfo
	fop
	foremost
	fortitude-bin
	fortls
	fprintd
	fractal
	freealut
	freecell-solver
	freehdl
	freeradius
	freerdp2
	freerdp-sdl3
	frog-protocols
	fscrypt
	fsverity-utils
	fulcio
	furmark
	fuse2fs
	fuseiso
	fuse-overlayfs
	futuresql
	fuzzel
	fuzzel-pass
	fuzzy
	fwupd
	fwupd-docs
	fwupd-efi
	fwupd-openrc
	fxload
	fzf
	fzf-extras
	fzffm
	fzf-kill
	fzfmenu
	fzf-vjour-git
	galera
	gallia
	gambas3-gb-db2-form
	gambas3-gb-db2-postgresql
	gambas3-gb-db2-sqlite3
	gambas3-gb-db-form
	gambas3-gb-db-postgresql
	gambas3-gb-db-sqlite3
	gambas3-gb-dbus
	gambas3-gb-gtk3-opengl
	gambas3-gb-mime
	gambas3-gb-openal
	gambas3-gb-opengl-glsl
	gambas3-gb-openssl
	gambas3-gb-qt5-opengl
	gambas3-gb-v4l
	game-devices-udev
	gamehub
	gamemode
	gamescope
	gameshell
	gaphor
	gap-packages
	garage
	garcon
	gasket-dkms-git
	gcc14
	gcc14-fortran
	gcc14-libs
	gcc-m2
	gcc-objc
	gcovr
	gdgbatterysaver
	gdk-pixbuf2-docs
	gdm
	gdrcopy
	gef
	gegl
	gemini-cli
	gensio
	getnf
	getssl
	ghidra
	ghostty
	ghostty-shell-integration
	ghostty-terminfo
	giblib
	gif2png
	gifify
	gifsicle
	gifski
	ginkgo-hpc-cuda
	ginko-git
	git
	git-bug
	git-credential-azure
	git-credential-github
	git-credential-gopass
	git-credential-keepassxc
	git-credential-msal
	git-credential-oauth
	git-credential-pass
	git-crypt
	git-delta
	gitea
	gitfetch
	git-grab
	githttptossh
	github-actions-bin
	github-cli
	gitlab
	gitlab-ci-local
	gitlab-ci-ls
	gitlab-container-registry
	gitlab-exporter
	gitlab-runner
	gitlab-shell
	gitleaks
	git-mr
	gitoxide
	git-publish
	git-remote-gcrypt
	git-revise
	gitrob
	git-secrets
	gitsign
	git-smash
	gitswitcher
	gitsync
	gitversion
	gkrellm-bluez
	gkrellm-git
	glab
	glad
	glade
	gleam
	glide
	glmark2
	globalprotect-openconnect
	gmime3
	gmni
	gmsl
	gnome-firmware
	gnome-mime-data
	gnupg-pkcs11-scd
	gnustep-make
	go2rtc
	go-checksum
	gocr
	godash
	goenv
	goffice
	gofumpt
	gogs
	goimapnotify
	golangci-lint
	gom
	gom-docs
	google-chrome-canary
	gopass
	gopass-fuse
	gopass-hibp
	gopass-jsonapi
	gopass-summon-provider
	gopls
	goplus
	gortr
	gosop
	go-tools
	gparted
	gpd-pocket-4-pipewire
	gpgkeymgr
	gpgsync
	gprename
	gpscorrelate
	gptfdisk
	gpu-trace
	gpu-viewer
	gradle-src
	granite
	graphicsmagick
	graphql-cli
	graphql-client-cli
	graphql-lsp
	graphqurl
	grayjay
	graylog
	grim
	grobi
	gron
	groovy
	grub-netboot-archlinux
	gscal
	gsettings-qt5
	gsettings-qt6
	gssproxy
	gst-devtools
	gstpeaq
	gst-plugin-aws
	gst-plugin-cdg
	gst-plugin-claxon
	gst-plugin-dav1d
	gst-plugin-elevenlabs
	gst-plugin-fallbackswitch
	gst-plugin-ffv1
	gst-plugin-fmp4
	gst-plugin-gif
	gst-plugin-gopbuffer
	gst-plugin-gtk4
	gst-plugin-hlsmultivariantsink
	gst-plugin-hsv
	gst-plugin-json
	gst-plugin-lewton
	gst-plugin-libcamera
	gst-plugin-livesync
	gst-plugin-mp4
	gst-plugin-mpegtslive
	gst-plugin-msdk
	gst-plugin-onnx
	gst-plugin-opencv
	gst-plugin-originalbuffer
	gst-plugin-pipewire
	gst-plugin-qml6
	gst-plugin-qmlgl
	gst-plugin-qsv
	gst-plugin-quinn
	gst-plugin-raptorq
	gst-plugin-reqwest
	gst-plugin-rsaudiofx
	gst-plugin-rsclosedcaption
	gst-plugin-rsfile
	gst-plugin-rsflv
	gst-plugin-rsinter
	gst-plugin-rsonvif
	gst-plugin-rspng
	gst-plugin-rsrtsp
	gst-plugin-rstracers
	gst-plugin-rsvideofx
	gst-plugin-rswebp
	gst-plugin-rswebrtc
	gst-plugins-espeak
	gst-plugins-intel-msdk-git
	gst-plugin-skia
	gst-plugin-sodium
	gst-plugin-speechmatics
	gst-plugin-spotify
	gst-plugin-streamgrouper
	gst-plugins-ugly
	gst-plugin-textahead
	gst-plugin-textwrap
	gst-plugin-threadshare
	gst-plugin-togglerecord
	gst-plugin-uriplaylistbin
	gst-plugin-webrtchttp
	gst-plugin-wpe
	gstreamer0.10-bad
	gstreamer0.10-base-plugins
	gstreamer-docs
	gstreamer-vaapi
	gst-rtsp-server
	gtk3-demos
	gtk4-demos
	gtkhash
	gtkmm3
	gucharmap
	guichan
	guile-git-lib
	guile-semver
	guitarix
	gulkan
	gummi
	guvcview
	guvcview-qt
	gvfs-dnssd
	gvfs-gphoto2
	gvfs-mtp
	gvfs-smb
	hackrf
	hagrid-git
	half
	haruna
	hashcat
	hashcat-utils
	haskell-alsa-core
	haskell-alsa-mixer
	haskell-cabal-doctest
	haskell-cmark-gfm
	haskell-cracknum
	haskell-dav
	haskell-direct-sqlite
	haskell-doctest
	haskell-doctest-discover
	haskell-doctest-driver-gen
	haskell-doctest-exitcode-stdio
	haskell-doctest-lib
	haskell-doctest-parallel
	haskell-double-conversion
	haskell-ed25519
	haskell-email-validate
	haskell-encoding
	haskell-floatinghex
	haskell-genvalidity
	haskell-genvalidity-hspec
	haskell-genvalidity-property
	haskell-gi-dbusmenu
	haskell-gi-dbusmenugtk3
	haskell-gi-gdk
	haskell-gi-gdk3
	haskell-gi-gdk3x11
	haskell-gi-gdkpixbuf
	haskell-gi-gdkx11
	haskell-hasql
	haskell-hls-test-utils
	haskell-hopenpgp
	haskell-hspec-contrib
	haskell-html-conduit
	haskell-iwlib
	haskell-language-glsl
	haskell-language-server
	haskell-lrucache
	haskell-openssl-streams
	haskell-persistent-sqlite
	haskell-pgp-wordlist
	haskell-pid1
	haskell-pipes
	haskell-pipes-http
	haskell-pipes-safe
	haskell-ral
	haskell-rerebase
	haskell-rvar
	haskell-skylighting-format-latex
	haskell-sqlite-simple
	haskell-svg-builder
	haskell-tasty-ant-xml
	haskell-validity
	haskell-xss-sanitize
	hath-rust
	hauk-server
	haxm-dkms-git
	hcxdumptool
	hcxkeys
	hcxtools
	hddtemp
	hdf5-openmpi
	hdisplays
	hdparm
	hdrmerge
	hdx-realtime-media-engine
	headscale
	heimdal
	heimdall
	helm-ls
	helvum
	heroic-gogdl
	hhd-user
	hieroglyphic
	himalaya
	homebank
	hopenpgp-tools
	hostapd-wpe
	hostsblock
	hostsctl
	hotp-totp-php
	htmlcxx
	htmlq
	html-xml-utils
	htop
	hub
	huntarr
	hunter
	hwdetect
	hwinfo
	hw-probe
	hydock
	hydra
	hyprcap
	hyprcursor
	hypr-dock
	hypremoji
	hyprfindr
	hyprgraphics
	hyprhide
	hypridle
	hyprkeys
	hyprland
	hyprland-protocols
	hyprland-workspaces
	hyprlang
	hyprlauncher
	hyprlax
	hyprlock
	hyprlux
	hyprmixer
	hyprpanel
	hyprpaper
	hyprpicker
	hyprpolkitagent
	hyprproxlock
	hyprpwcenter
	hyprqt6engine
	hyprscratch
	hyprsession
	hyprshade
	hyprshell
	hyprshot
	hyprsunset
	hyprswitch
	hyprviz
	hyprvoice-bin
	hyprwayland-scanner
	hyprwhspr
	hyprwindow
	iaito
	ibm-sw-tpm2
	ical
	ice9-bluetooth-sniffer
	icecream
	icecream-sundae
	icedtea-web
	icemon
	icmake
	icon-library
	icon-naming-utils
	icoutils
	id3lib
	iddawc
	idesk
	ifdtool
	ifuse
	igsc
	iio-niri
	iioutils
	ijq
	imaginary
	imapfilter
	imapgoose
	img2pdf
	imv
	imvirt
	inferno-aoip
	influxdb
	infnoise
	infnoise-tools
	informant
	innernet
	inotify-info
	inspircd
	instaloader
	instamancer
	intel-gpu-tools
	intel-lms
	intel-media-driver
	intel-media-sdk
	intel-oneapi-basekit
	intel-opencl
	intel-opencl-sdk
	intelpwm
	intel-speed-select
	inteltool
	intel-ucode
	intel-undervolt
	intel-xed
	interception-tools
	interceptty
	intiface-central
	invoice
	invoiceninja
	invoiceplane
	inxi
	ipmitool
	ipp-usb
	ipv6calc
	ir.lv2
	isa-l
	isoimagewriter
	isomd5sum
	ispell
	iucode-tool
	ivre
	iwd
	jaaa
	jacktrip
	jad
	jadx
	jailbox-git
	jake
	janus-gateway
	jaq
	java-batik
	java-commons-daemon
	java-hamcrest
	java-rhino
	java-service-wrapper
	java-simpleitk
	jc
	jc303-lv2
	jcli
	jddbusdebugger
	jdtls
	jedi-language-server
	jellyfin-ffmpeg
	jenkins
	jenq
	jenv
	jetring
	jfsutils
	jhentai-bin
	jitsi-meet
	jlatexmath
	jnoisemeter
	jnv
	jo
	jobqueue
	john
	jomon
	journal-gateway-gelf
	jp2-pixbuf-loader
	jq-lsp
	jshon
	jsonc
	jsoncons
	jsoncpp-cmake
	jsonnet-language-server
	jsonrpc-glib
	jsonrpc-glib-docs
	jujutsu
	jupyterlab-lsp
	jupyter-lsp
	jupyter-metakernel
	just-lsp
	jwt-ui
	jython
	k9s
	kakoune-lsp
	kamailio
	katex
	kbfs
	kbuilder
	kcaldav
	kcpuid
	kcrap
	kcron
	kdav
	kdeconnect
	kdump
	keepass-plugin-favicon
	keepass-plugin-keeagent
	keepassxc
	keeper-secrets-manager-core
	kernel-builder
	kernel-modules-hook
	kernelpatch
	keybase
	keychain
	keycloak
	keycloak-metrics-spi
	keystone
	khal
	khip
	kill-net
	kismet
	kismet-plugin-ubertooth
	kismon
	kitty
	kmodcache
	kmon
	kmscon
	kmsvnc
	knc
	knot-resolver
	kodi-addon-visualization-shadertoy
	kompose
	kotlin
	kotlin-debug-adapter-bin
	kotlin-language-server
	kpatch
	kraft
	krb5-auth-dialog
	krita
	krita-plugin-gmic
	krita-plugin-pythonplugindevelopertools-git
	ksanecore
	kscript
	kseexpr
	ksops-bin
	kstart
	ksvg
	ktfmt
	ktlint
	ktlint-compose-rules
	ktoblzcheck
	ktrip
	kube-linter
	kubeseal
	kubetui
	kvantum
	kvantum-qt5
	kwayland
	kwayland5
	ladder
	laravel-kit
	laravel-ls-git
	lasem-docs
	laszip
	laszip2
	latex2html
	lazycc
	lazygit
	lazyjj
	lazyssh
	lbb
	lcov
	ldc
	ldns
	ledger-udev
	lefthook
	legba
	lei
	leiningen
	lemminx
	lemmy
	lemon
	lemonade-server
	lemurs
	lenspect
	lftp
	lib32-alsa-oss
	lib32-bluez-libs
	lib32-bluez-plugins
	lib32-egl-wayland
	lib32-fluidsynth
	lib32-gamemode
	lib32-glm
	lib32-gst-plugins-base
	lib32-gst-plugins-base-libs
	lib32-gst-plugins-good
	lib32-gstreamer
	lib32-libappindicator
	lib32-libavtp
	lib32-libb2
	lib32-libdv
	lib32-libdxvk
	lib32-libevdev
	lib32-libevent
	lib32-libindicator
	lib32-libnewt
	lib32-libsodium
	lib32-libsrtp
	lib32-libva-intel-driver
	lib32-libvpx
	lib32-mesa-demos
	lib32-mesa-git
	lib32-mesa-utils
	lib32-neon
	lib32-obs-vkcapture
	lib32-ocl-icd
	lib32-opencl-nvidia
	lib32-pipewire-jack
	lib32-pipewire-v4l2
	lib32-renderdoc
	lib32-sbc
	lib32-shaderc
	lib32-slang
	lib32-smpeg
	lib32-speex
	lib32-spirv-llvm-translator
	lib32-spirv-tools
	lib32-vkbasalt
	lib32-vkd3d
	lib32-vulkan-gfxstream
	lib32-vulkan-nouveau
	lib32-vulkan-utility-libraries
	lib32-vulkan-validation-layers
	libartnet
	libastal-bluetooth-git
	libcamera-tools
	libcgroup
	libchardet
	libcmrt
	libcomps
	libcss
	libcups-gssapi
	libcvec
	libdbi
	libdbi-drivers
	libdwarf
	libdxvk
	libepc
	libesmtp
	libetpan
	libfilteraudio
	libfprint
	libg15
	libgdm
	libgepub
	libgfshare
	libgit2-glib
	libgit2-glib-docs
	libglademm
	libgmpris
	libgpiod
	libgringotts
	libgssglue
	libilbc
	libindicator
	libindi-celestronaux
	libinfnoise
	libinsane
	libkcapi
	libkeybinder3
	libkrun
	libkrunfw
	libksane
	liblastfm-qt5
	liblcf
	libldm
	libmediaart
	libmesode
	libmesode-doc
	libmodbus
	libnma
	libnma-common
	libnma-gtk4
	libnoise
	libnvidia-container
	libopencm3
	libopensmtpd
	liboqs
	libp11
	libpam-google-authenticator
	libpam_pwdfile
	libpg_query
	libpkcs11-dnie
	libqaccessibilityclient-qt5
	libqatemcontrol-git
	libqt5xdg
	libquvi
	libratbag
	libraw
	librdkafka
	libreoffice-extension-texmaths
	libreoffice-extension-writer2latex
	libresprite
	librsvg-docs
	librustls
	libscanmem
	libsecret-docs
	libsfdo
	libsieve
	libsmbios
	libspecbleach
	libstrophe
	libstrophe-doc
	libsvgtiny
	libtiger
	libtraceevent
	libuecc
	libuhd
	libuhd-utils
	libultrahdr
	libusbgx
	libuvc-git
	libva1-compat
	libva-intel-driver
	libvarlink
	libva-utils
	libva-vdpau-driver
	libvdpau-va-gl
	libvirt-dbus
	libvolk
	libvpl-tools
	libvpx1.10
	libwebp-utils
	libwireplumber-4.0-compat
	libwmf
	libxdg-basedir
	libxml2-docs
	libxmlrpc
	libxnvctrl
	libxpid
	libxsd
	lightdm-webkit-theme-sequoia-git
	lighthouse
	lightning-terminal
	limine
	limine-entry-tool
	limine-snapper-sync
	linenoise-ng
	links
	linkwarden
	linset
	linuxconsole
	linux-firmware
	linux-firmware-hauppauge
	linux-firmware-marvell
	linux-firmware-qcom
	linux-firmware-valve
	linux-gpib-dkms
	linux-mdss-dsi-panel-driver-generator
	linux-smart-enumeration-git
	linux-tools-meta
	linux-zen
	linux-zen-headers
	liquidsfz-lv2
	litemanager
	livekit-ingress
	live-media
	lkrg-dkms
	lldb
	lldb-mi
	lmms
	log4j-detector
	logpresso-log4j-scan
	lokalize
	loki-canary
	looking-glass-module-dkms
	loop-aes-dkms
	love
	lrs
	lsix
	lsof
	lsp-ai
	lsp-plugins
	lsp-plugins-clap
	lsp-plugins-gst
	lsp-plugins-ladspa
	lsp-plugins-standalone
	lsp-plugins-vst
	lsp-plugins-vst3
	lua51
	lua51-cqueues
	lua51-expat
	lua51-linenoise
	lua51-lpeglabel
	lua51-luacheck
	lua51-luaossl
	lua51-luarocks-build-rust-mlua
	lua51-luv
	lua51-semver
	lua51-tl
	lua52-luarocks-build-rust-mlua
	lua53-luarocks-build-rust-mlua
	lua53-sdl2
	lua-dkjson
	lua-expat
	luajit-sdl3-git
	luakit
	lua-language-server
	lua-linenoise
	lua-lpeglabel
	lua-luarocks-build-rust-mlua
	lua-lub
	lua-lut
	lua-luv
	luametatex
	luaoptions-git
	luarocks
	luau
	lucene++
	luky-borg-backup
	lvm2
	lxqt-build-tools-qt5
	lynis
	lynx
	lzop
	m4acut
	macchanger
	mado
	maelstrom-worker
	mage
	magiskboot-bin
	mail4one
	mailcommon
	mailimporter
	mailman3-hyperkitty
	mailman3-public-inbox
	mailman-web
	mailnag
	mailnag-goa-plugin
	mailspring
	mailutils
	mairix
	makedumpfile
	makepkg-optimize-mold
	mako
	maldet
	malt
	mame
	mame-tools
	man2html
	man-db
	mangareader
	man-pages
	mariadb-jdbc
	markdownlint
	markdownlint-cli
	markdownlint-cli2
	markdown-oxide
	marksman
	masscanned-git
	mathjax
	matrirc
	matrix-appservice-irc
	matrix-authentication-service
	matrix_cpp
	matrix-sliding-sync
	matrix-synapse
	matterbridge
	mattermost
	mattermost-plugin-boards
	mattermost-plugin-calls
	mattermost-plugin-collabora
	mattermost-plugin-gitlab
	mattermost-plugin-jitsi
	mattermost-plugin-matterpoll
	mattermost-plugin-playbooks
	mattersend
	matui
	maubot
	mautrix-meta
	mbake
	mbelib
	mbrola
	mcabber
	mcp-gearbox-git
	mcphost
	mcpp
	mcproxy
	mcptools
	mdbook-katex
	mdevd
	mdformat
	mdformat-tables
	mdpls-git
	mdserve
	meanalyzer
	me_cleaner
	mediaexpress
	mediamtx
	med-openmpi
	medusa
	megasync
	mek-security
	meld
	mellite
	memcached
	memtest_vulkan
	menu-cache
	menuconfig-git
	menumaker
	menu-qalc-wayland-git
	mercurial
	mergiraf
	mermaid-cli
	mesa-demos
	mesa-docs
	mesaflash
	mesa-git
	mesarun
	mesa-utils
	meson
	mesonlsp
	meson-python
	metals
	metis
	mic-indicator
	mic-mute-led-reverse
	midi_matrix.lv2
	mighttpd2
	mill
	mimemagic
	mimetreeparser
	mimic-bpf-dkms
	mimir
	mingw-w64-doctest
	mingw-w64-vulkan-headers
	miniflux
	ministore
	minq-nhentai-git
	mip.rs
	mise
	mitmproxy
	mitmproxy2swagger
	mkcert
	mkinitcpio-archiso
	mkinitcpio-bluetooth
	mkinitcpio-btrfs
	mkinitcpio-encrypt-detached-header
	mkinitcpio-firmware
	mkinitcpio-mlx4
	mkinitcpio-mlx5
	mkinitcpio-overlayfs
	mkinitcpio-tinyssh
	mkinitcpio-utils
	mkvtoolnix-cli
	mlir
	mmc-utils
	mmm
	mobydroid
	mod_authnz_external
	modclean
	mod_dnssd
	modemmanager
	moderntimeline
	mod_fcgid
	mod_itk
	mod-lv2-extensions
	modo
	mod_passenger
	mod_perl
	mod_rpaf
	mokutil
	mold
	monero
	monero-api-cli
	moneydance
	moneymanagerex
	monit
	mono-msbuild
	mono-msbuild-sdkresolver
	moony.lv2
	moreutils
	mosh-agent
	mosh-scheme
	motion
	movit
	mox
	mozplugger
	mp3gain
	mp3unicode
	mplayer
	mpls-git
	mpop
	mpv-mpris
	mpv-shim-default-shaders
	mqtt-cpp
	mqttui
	mr.duppl
	mricrogl
	mscp
	msedit
	msi-psu-dkms
	msktutil
	msl
	msr-tools
	mstflint
	mtd-utils
	mtp
	mtpaint
	mtpfs
	mtxclient
	mu
	muchsync
	mulle-semver
	multibg-wayland
	multilib-devel
	munge
	mupdf-gl
	mupdf-tools
	muse
	mutt
	mutt-ics
	mutt-wizard
	mvnd
	mvnsh
	mvnvm
	mxml
	mxml-docs
	mytop
	nafe
	nano
	nanosvg
	ncdu
	ncrack
	ndiff
	ndisc6
	neard
	nebula
	nekoget
	nemo-python
	nemo-seahorse
	neocmakelsp
	neomutt
	neovim
	neovim-decasify
	nerdctl
	nerd-dictation-git
	netatop-dkms
	netboot
	netcdf-fortran-openmpi
	netexec
	netfilter-fullconenat-dkms-git
	nethsm-pkcs11
	netscout-git
	netsniff-ng
	netsurf
	networkmanager
	network-manager-applet
	networkmanager-dispatcher-chrony
	networkmanager-dmenu
	networkmanager-fortisslvpn
	networkmanager-l2tp
	networkmanager-openconnect
	networkmanager-pptp
	networkmanager-ssh
	network-manager-sstp
	networkmanager-strongswan
	networkmanager-vpnc
	networkmanager-vpn-plugin-l2tp
	networkmanager-vpn-plugin-openconnect
	networkmanager-vpn-plugin-pptp
	networkmanager-vpn-plugin-sstp
	networkmanager-vpn-plugin-vpnc
	newaita-icons-git
	new-session-manager
	nextcloud-app-calendar
	nextcloud-app-contacts
	nextcloud-app-mail
	nextcloud-app-spreed
	nextcloud-client
	nfs-utils-rdma-server
	nginx-mod-auth-pam
	nginx-mod-dav-ext
	nginx-mod-echo
	nginx-mod-geoip
	nginx-mod-geoip2
	nginx-mod-mail
	nginx-mod-memc
	nginx-mod-naxsi
	nginx-mod-ndk
	nginx-mod-njs
	nginx-mod-perl
	nginx-mod-redis
	nginx-mod-redis2
	nginx-mod-set-misc
	nginx-mod-srcache
	nginx-mod-vts
	nginx-mod-xslt
	nginx-src
	ngrok
	nhentai-git
	nickel-language-server
	nilfs-utils
	nil-git
	ninja-kitware
	ninjam-client
	ninjam-server
	niri
	niri-float-sticky
	niri-switch
	niriswitcher
	nirius
	nitrokey-udev-rules
	nitroshare
	nix
	nix-busybox
	nixfmt
	nix-melt
	nixpacks
	nixpkgs-fmt-git
	nix-search-cli
	nmail
	nmap
	nmap-parse-output
	nm-connection-editor
	noctalia
	noctalia-shell
	nodejs-emmet-ls
	nodejs-intelephense
	nodejs-maildev
	noise-repellent
	noise-suppression-for-voice
	noisetorch-bin
	nomachine
	nomad-driver-containerd
	nomad-driver-lxc
	nomad-driver-nspawn
	nomad-driver-podman
	nordzy-hyprcursors
	notcurses
	notification-daemon
	notmuch-mutt
	notmuch-tools-git
	npapi-vlc
	nq
	nrf5-sdk
	nrf5x-command-line-tools
	nrf5x-sniffer
	nrf-sniffer-ble
	nrftool
	nrf-udev
	nrfutil
	ntfs-3g
	nuget
	nullfsvfs-dkms
	nvc
	nvcards
	nvchecker
	nvhpc
	nvhpc-comm-libs
	nvhpc-compilers
	nvidia-cg-toolkit
	nvidia-container-toolkit
	nvidia-docker-compose
	nvidia-fs-dkms
	nvidia-mft
	nvidia-open-dkms
	nvidia-prime
	nvm
	nvme-cli
	nvmetcli
	nvshmem
	nvtop
	nwg-displays
	nwg-dock-hyprland
	nwg-panel
	nwg-readme-browser
	nxproxy
	nyarchassistant-git
	nyx
	nyxt
	nzsl-git
	obfs4proxy
	obs-backgroundremoval
	obs-gstreamer
	obs-infowriter
	obs-noise
	obs-pipewire-audio-capture
	obs-retro-effects
	obs-vaapi
	obs-vban
	obs-vkcapture
	ob-xd-lv2
	ocamlbuild
	ocaml-pp
	ocaml-sqlite3
	ocrad
	ocrfeeder
	octave-doctest
	odin2-synthesizer
	odin2-synthesizer-clap
	odin2-synthesizer-lv2
	odin2-synthesizer-standalone
	odin2-synthesizer-vst3
	odinfmt
	offlineimap
	ofxstatement-paypal
	oidc-agent
	oidcwarden
	oidcwarden-web
	oinkmaster
	ojs
	ollama-cuda
	ollama-vulkan
	onefetch
	onionbalance
	onioncat
	onioncircuits
	oniongen-rs
	onionshare
	opam
	openai-codex
	openal-examples
	openblas64
	openboardview
	opencascade
	opencl-caps-viewer-wayland
	opencl-clhpp
	openclipart-svg
	opencomic
	openconnect-sso
	opencryptoki
	opencsg
	openfire
	opengl-man-pages
	opengv
	openimagedebugger
	openimagedenoise
	openipmi
	openldap
	openmp
	openmpi
	openmpi-docs
	openmpt
	openocd
	openpgl
	openpgp-ca
	openpgp-card-ssh-agent
	openpgp-card-tool-git
	openpgp-card-tools
	openpgp-ca-restd
	open-plc-utils
	open-policy-agent
	openra
	openrct2
	opensc
	openscad
	openscad-lsp
	openscenegraph
	opensearch-alerting-plugin
	opensearch-analysis-icu-plugin
	opensearch-analysis-kuromoji-plugin
	opensearch-analysis-nori-plugin
	opensearch-analysis-phonetic-plugin
	opensearch-analysis-smartcn-plugin
	opensearch-analysis-stempel-plugin
	opensearch-analysis-ukrainian-plugin
	opensearch-anomaly-detection-plugin
	opensearch-asynchronous-search-plugin
	opensearch-cli
	opensearch-cross-cluster-replication-plugin
	opensearch-dashboards-alerting-plugin
	opensearch-dashboards-anomaly-detection-plugin
	opensearch-dashboards-index-management-plugin
	opensearch-dashboards-maps-plugin
	opensearch-dashboards-notifications-plugin
	opensearch-dashboards-observability-plugin
	opensearch-dashboards-query-workbench-plugin
	opensearch-dashboards-reports-plugin
	opensearch-dashboards-security-plugin
	opensearch-discovery-azure-classic-plugin
	opensearch-discovery-ec2-plugin
	opensearch-discovery-gce-plugin
	opensearch-geospatial-plugin
	opensearch-index-management-plugin
	opensearch-ingest-attachment-plugin
	opensearch-job-scheduler-plugin
	opensearch-knn-plugin
	opensearch-mapper-annotated-text-plugin
	opensearch-mapper-murmur3-plugin
	opensearch-mapper-size-plugin
	opensearch-ml-commons-plugin
	opensearch-neural-search-plugin
	opensearch-notifications-plugin
	opensearch-observability-plugin
	opensearch-performance-analyzer-plugin
	opensearch-reports-scheduler-plugin
	opensearch-repository-azure-plugin
	opensearch-repository-gcs-plugin
	opensearch-repository-hdfs-plugin
	opensearch-repository-s3-plugin
	opensearch-security-plugin
	opensearchserver
	opensearch-sql-plugin
	opensearch-store-smb-plugin
	opensmtpd-filter-rspamd
	opensmtpd-table-postgres
	openssh
	opentracker
	open-unmix-umxhq-weights
	openvdb
	openvino-intel-gpu-plugin
	openvino-models
	openvkl
	openvpn-mbedtls
	openvr
	operator-sdk
	optiimage
	opus-tools
	oqsprovider
	orca
	ory-hydra
	oryx
	osinfo-db-tools
	osl
	osslsigncode
	oss-nonfree
	otf-font-awesome
	otf-ipamjfont
	otf-latin-modern
	otf-latinmodern-math
	otf-league-mono
	otf-material-icons
	otf-monaspace
	otf-monaspace-nerdfonts
	ovenmediaengine
	ovpn-dco-dkms
	oxc-language-server
	oxipng
	oxygen-icons-svg
	p0f
	p2pool
	p4
	p4d
	pacguard
	packagekit
	packer
	pacleaner
	pacman-fix-permissions
	pacman-offline
	pacman-venv
	pacquery
	padthv1-lv2
	pairing_tool
	palletizer
	pam-fprint-grosshack-unlimited-timeout
	pam-gnupg
	pam-ihosts
	pamixer
	pam-krb5
	pam_mount
	pam_p11
	pam_pkcs11
	pam_rundir
	pam_ssh
	pam-ssh-agent
	pamtester
	pam-u2f
	pam_wrapper
	pam_wrapper-docs
	pa-notify
	paperkey
	papirus-icon-theme
	paros
	parsehub
	partclone
	partimage
	partitionmanager
	paru
	paruz
	pass-attr
	pass-clip
	passdmenu
	pass-file
	pass-git-helper
	passh
	passim
	pass-import
	pass-ln
	passly
	pass-notify-git
	pass-otp
	pass-secret-service
	pass-ssh
	pass-tomb
	passtools
	pass-update
	passwordfile
	passwordmanager
	patatt
	patchmatrix
	patchup
	pavucontrol
	pc-nrfconnect-programmer
	pcp-pmda-mysql
	pcp-pmda-nutcracker
	pdav
	pdf2svg
	pdfcrack
	pdfgrep_sixel
	pdfjs
	pdfslicer
	pd-sfizz
	peda
	peergos
	pentmenu
	perf
	perl-alien-cmake3
	perl-anyevent-xmpp
	perl-apache2-soap
	perl-cache-memcached
	perl-canary-stability
	perl-common-sense
	perl-config-autoconf
	perl-config-onion
	perl-convert-uulib
	perl-crypt-openssl-bignum
	perl-crypt-smbhash
	perl-crypt-ssleay
	perl-data-password
	perl-dbd-odbc
	perl-dbd-pg
	perl-dbd-sqlite
	perl-dbd-sqlite2
	perl-debug-adapter
	perl-device-gsm
	perl-device-modem
	perl-device-serialport
	perl-digest-bubblebabble
	perl-djabberd-rosterstorage-sqlite
	perl-email-address
	perl-email-address-xs
	perl-email-mime
	perl-email-mime-attachment-stripper
	perl-email-mime-contenttype
	perl-email-mime-encodings
	perl-email-send
	perl-email-sender
	perl-email-simple
	perl-email-valid
	perl-fcgi-client
	perl-file-basedir
	perl-file-libmagic
	perl-file-rsyncp
	perl-file-slurper
	perl-file-slurp-tiny
	perl-gnupg-interface
	perl-gravatar-url
	perl-gssapi
	perl-html-formatter
	perl-html-tree
	perl-http-multipartparser
	perl-image-sane
	perl-lingua-ru-number
	perl-locale-po
	perl-mail-imapclient
	perl-mail-sendmail
	perl-mime-base32
	perl-mp4-info
	perlnavigator
	perl-net-caldavtalk
	perl-net-ipv6addr
	perl-net-openssh
	perl-nix
	perl-regexp-ipv6
	perl-template-provider-encoding
	perl-test-manifest
	perl-test-mockmodule
	perl-text-iconv
	perl-text-patch
	perl-unicode-string
	perl-unix-syslog
	perl-xml-parser-lite
	perl-xml-rpc
	perl-xml-rss
	perl-xml-stream
	pesign
	pflogsumm
	pg_auto_failover
	pgbackrest
	pgbouncer
	pgcli
	pgformatter
	pgindent
	pgloader
	pgmodeler
	pgpdump
	pg-safeupdate
	pgxnclient
	phoc
	phonegap
	php81-pecl
	phpactor
	php-apache
	php-codesniffer
	php-codesniffer-drupal
	php-dblib
	phpdox
	php-enchant
	php-fpm
	php-geoip
	php-grpc
	php-imagick
	php-kadm5
	php-language-server-git
	phpldapadmin
	php-legacy-apache
	php-legacy-apcu
	php-legacy-cgi
	php-legacy-dblib
	php-legacy-enchant
	php-legacy-fpm
	php-legacy-gd
	php-legacy-geoip
	php-legacy-grpc
	php-legacy-igbinary
	php-legacy-imagick
	php-legacy-memcache
	php-legacy-odbc
	php-legacy-pgsql
	php-legacy-phpdbg
	php-legacy-pspell
	php-legacy-redis
	php-legacy-smbclient
	php-legacy-snmp
	php-legacy-sodium
	php-legacy-sqlite
	php-legacy-tidy
	php-legacy-xsl
	php-memcache
	php-memcached
	php-mongodb
	phpmyadmin
	php-odbc
	phppgadmin
	php-pgsql
	php-phpdbg
	php-redis
	php-rrd
	php-snuffleupagus
	php-sodium
	php-sqlite
	phpstan-bin
	php-virtphp
	phpvirtualbox
	php-xmlrpc
	php-xsl
	picom
	pigz
	pimsync
	pinact
	pinentry-bemenu
	pinentry-dispatch
	pinentry-dmenu
	pint
	pipeglade
	pipemixer
	piper-voices-common
	pipesocks
	pipeswitchd
	pipewire-alsa
	pipewire-autostart
	pipewire-docs
	pipewire-enable-bluez5
	pipewire-ffado
	pipewire-libcamera
	pipewire-module-xrdp
	pipewire-openrc
	pipewire-pulse
	pipewire-pulse-openrc
	pipewire-roc
	pipewire-screenaudio
	pipewire-session-manager
	pipewire-v4l2
	pipewire-zeroconf
	piping-server
	pipxu
	piratebay
	pitivi
	pius
	pixelorama
	pixiecore-git
	pixz
	pkcreate
	pkcs11-helper
	pkcs11-provider
	pkg-audit
	pkgbuild-updater
	pkgbuild-version-updater
	pkgdiff
	plantuml
	plantuml-ascii-math
	plantuml-server
	platformflashtoollite
	platformio-core-udev
	pnetcdf-openmpi
	png2svg
	pngout
	pocketsphinx
	pocl
	polkit-kde-agent
	polkit-qt5
	polly
	polyphone
	popsift
	portchaos
	portmux
	posixovl
	posix-user-portability
	postfinger
	postfixadmin
	postfix-cdb
	postfix-ldap
	postfix-mysql
	postfix-pcre
	postfix-pgsql
	postfix-policyd-spf-perl
	postfix-sqlite
	postfix-tlspol
	postfwd
	postgis
	postgresql
	postgresql-docs
	postgresql-ip4r
	postgresql-libs
	postgresql-old-upgrade
	postgresql-plsh
	postgresql-semver
	postgrest
	postgrestools-bin
	postgrey
	postsrsd
	potd
	povray
	powerdns
	powerline
	powermanga
	powershell
	powershell-editor-services
	powscript
	poxml
	praat
	pre-commit
	premake3
	prettierd
	pretzel-web
	prisma-language-server
	probe-rs
	profile-cleaner
	profile-sync-daemon
	profile-sync-daemon-zotero
	promtail
	prosemd-lsp
	prosody-mod-http-upload-external-hg
	prosody-mod-onions
	protobuf-language-server
	protolint
	protols
	protomd
	protonmail-bridge
	protonmail-bridge-core
	proton-vpn-gtk-app
	proxyboi
	proxychains-ng
	proxyguard
	psad
	psalm
	psensor
	psi
	ptags
	pulldocker
	pulledpork
	pulseaudio-alsa
	pulseaudio-dlna
	pulse-native-provider
	pulumi-language-dotnet
	puncia
	puppet
	puppet-bolt
	puppet-editor-services
	puppeteer
	puppet-lint
	puppetserver
	pv
	pvoc
	pwru
	pwsp
	pw-volume
	pydio
	pyenv
	pyenv-latest
	pyenv-virtualenv
	pyopencl-headers
	pyprland
	pyprpaper
	pypy3
	pypy3-cppy
	pyside6
	pyside6-tools
	python2-v4l2capture
	python3-aria2jsonrpc
	python-aaf2
	python-aafigure
	python-agate-excel
	python-aiobotocore
	python-aiogram
	python-aiohttp-socks-git
	python-aiopg
	python-aiosqlite
	python-ajsonrpc
	python-ansibug
	python-ansicolors
	python-anysqlite
	python-api4jenkins
	python-apsw
	python-ast-grep
	python-astropy
	python-asyncpg
	python-audioread
	python-audit
	python-awaitable
	python-awkward
	python-b2sdk
	python-babel-glade
	python-barectf
	python-bases
	python-bitcoinlib
	python-bivalve
	python-blake3
	python-bluepy
	python-boto3
	python-botocore
	python-bottleneck
	python-cairosvg
	python-caja
	python-caldav
	python-capng
	python-casttube
	python-cchardet
	python-cfn-lint
	python-chacha20poly1305-reuseable
	python-chardet
	python-click-completion
	python-cloudflare
	python-cmarkgfm
	python-colorthief
	python-cppy
	python-crazy-complete
	python-crispy-bootstrap4
	python-cssselect
	python-ctfcli
	python-cucumber-tag-expressions
	python-cuda
	python-cuda-bindings
	python-cuda-core
	python-curl-cffi
	python-daemon
	python-daemonize
	python-daemonocle
	python-dbus-deviation
	python-dbus-fast
	python-dbusmock
	python-debugpy
	python-devicetree
	python-django-classy-tags
	python-django-crispy-forms
	python-django-csp
	python-django-htmx
	python-django-modeltranslation
	python-django-ninja
	python-django-paypal
	python-django-sekizai
	python-dleyna
	python-docker-pycreds
	python-doctest-ignore-unicode
	python-dokuwikidumper
	python-ed25519-blake2b
	python-editorconfig
	python-elementpath
	python-email-validator
	python-fabulous
	python-fastimport
	python-fasttext
	python-favicons
	python-feedgenerator
	python-fido2
	python-flask-debug
	python-flask-jsonrpc
	python-flask-mail
	python-flask-mailman
	python-flippernested
	python-flup
	python-fontawesome
	python-forbiddenfruit
	python-github3py
	python-glfw
	python-gnupg
	python-gnupginterface
	python-google-generativeai
	python-gpgme
	python-gp-libs
	python-graphene
	python-graphql-core
	python-graphql-relay
	python-graphql-server-core
	python-grpcio-tools
	python-gssapi
	python-gtts
	python-h5py-openmpi
	python-haas-proxy
	python-hkp4py-git
	python-hunter
	python-hvac
	python-hydra-core
	python-hyperqueue
	python-imap-tools
	python-ipympl
	python-ipyparallel
	python-isomd5sum
	python-jenkinsapi-git
	python-johnnycanencrypt
	python-jq
	python-json-rpc
	python-k5test
	python-keyrings.google-artifactregistry-auth
	python-keystone
	python-keystoneauth1
	python-keystoneclient
	python-kikit
	python-kismetdb
	python-kismet-rest
	python-kivy
	python-latex2mathml
	python-latexcodec
	python-libcamera
	python-lib-detect-testenv
	python-libevdev
	python-libnmap
	python-librosa
	python-libsass
	python-libseccomp
	python-libusb1
	python-logging_tree
	python-lsp-black
	python-lsp-jsonrpc
	python-luma-core
	python-lxc
	python-lz4
	python-magic-wormhole-mailbox-server
	python-manuf
	python-matplotlib-sixel-git
	python-mattermostdriver
	python-mdx-gh-links
	python-memcached
	python-mesa
	python-minesight-git
	python-minidb
	python-mitmproxy-rs
	python-mitmproxy-wireguard
	python-mkdoc
	python-mkl-service
	python-modern-colorthief
	python-moto
	python-mplhep
	python-mpv
	python-msal
	python-msal-extensions
	python-mujson
	python-mygpoclient
	python-mypy-protobuf
	python-mysql-connector
	python-nativemessaging-ng
	python-nbval
	python-nbxmpp
	python-nclcmaps-git
	python-netaudio
	python-netcdf4
	python-nitrokey
	python-nkdfu
	python-nmap
	python-nodegraphqt
	python-node-semver
	python-noiseprotocol
	python-numpydoc
	python-olm
	python-onion-location
	python-onnxruntime-cuda
	python-onnxscript
	python-openai-whisper
	python-opencv-cuda
	python-opengl
	python-opensearch
	python-openvino
	python-orjson
	python-pam
	python-parsel
	python-passlib
	python-pbkdf2
	python-pbr
	python-pdm-build-locked
	python-pgpy
	python-pillowfight
	python-pillow-heif
	python-pillow-heif-docs
	python-pillow-jpegxl-plugin
	python-pip
	python-pipx
	python-playwright
	python-pocketsphinx
	python-postfix-policyd-spf
	python-promise
	python-proton-core
	python-proton-keyring-linux
	python-proton-vpn-api-core
	python-proton-vpn-local-agent
	python-proton-vpn-network-manager
	python-psycopg
	python-psycopg2
	python-pwntools
	python-py3nvml
	python-pyacoustid
	python-pyadi-iio
	python-pyalsa
	python-pyaudio
	python-pyaxmlparser
	python-pybluez
	python-pybrowserstack-screenshots
	python-pycuda
	python-pydbus
	python-pydub
	python-pyfavicon
	python-pygal
	python-pygaljs
	python-pygelf
	python-pygithub
	python-pyhibp
	python-pyinotify
	python-pykerberos
	python-pylatexenc
	python-pylint-venv
	python-pynvim
	python-pyodoo
	python-pyopencl
	python-pypatchelf
	python-pypdf
	python-pypdf3
	python-pypdfium2
	python-pypng
	python-pypresence
	python-pypubsub
	python-pyqrcode
	python-pyqt5-sip
	python-pyqt5-webengine
	python-pyqt5-webkit
	python-pysaml2
	python-pyscreenshot
	python-pysdl3
	python-pysequoia
	python-pyshark
	python-pysmb
	python-pysmbc
	python-pytest-aiohttp
	python-pytest-asyncio
	python-pytest-click
	python-pytest-django
	python-pytest-env
	python-pytest-isort
	python-pytest-lsp
	python-pytest-mpi
	python-pytest-mpl
	python-pytest-playwright
	python-pytest-qt
	python-pytest-repeat
	python-pytest-ruff
	python-pytest-trio
	python-python-pkcs11
	python-pyttsx3
	python-pytube
	python-pyu2f
	python-pyudev
	python-pyusb
	python-pyxdg
	python-qpageview
	python-qstylizer
	python-qtawesome
	python-qt-material
	python-qtpy
	python-qutescript-git
	python-railroad-diagrams
	python-rapidjson
	python-readability-lxml
	python-readthedocs-sphinx-ext
	python-requests
	python-requests-aws4auth
	python-requests-gssapi
	python-requests-kerberos
	python-rstr
	python-ruff-api
	python-saml
	python-sane
	python-scanpydoc
	python-scipy-mkl
	python-securesystemslib
	python-seedir
	python-sentinels
	python-setuptools-protobuf
	python-shtab
	python-signedjson
	python-sixelcrop
	python-slycot-mkl
	python-smbprotocol
	python-sphinxcontrib-apidoc
	python-sphinxcontrib-autoprogram
	python-sphinxcontrib-bibtex
	python-sphinxcontrib-doxylink
	python-sphinxcontrib-katex
	python-sphinxcontrib-log-cabinet
	python-sphinxcontrib-plantuml
	python-sphinxcontrib-spelling
	python-sphinx_rtd_dark_mode
	python-sphinxygen
	python-spsdk-pqc
	python-sqlite-anyio
	python-sqlitedict
	python-squarify
	python-srctools
	python-standard-pipes
	python-svada
	python-svglib
	python-svgwrite
	python-sybil
	python-term-image
	python-tflite
	python-tf-playwright-stealth
	python-threadloop
	python-thrift
	python-tika-client
	python-torchattacks
	python-torchcodec
	python-torchvision-cuda
	python-tpm2-pytss
	python-tree-sitter-zathurarc
	python-trytond_account_payment_sepa
	python-trytond_account_payment_stripe
	python-trytond_sale_advance_payment
	python-uhd
	python-unidecode
	python-uproot
	python-uproot-docs
	python-uv
	python-uv-build
	python-v4l2capture
	python-validate-email
	python-vcversioner
	python-vector
	python-vl-convert
	python-volume_key
	python-vsg
	python-vunit_hdl
	python-warlock
	python-web-compile
	python-webrtcvad
	python-whitenoise
	python-willow
	python-x256
	python-xdg-base-dirs
	python-xlwt
	python-xmlformatter
	python-xtermcolor
	python-zenmoney
	python-ziamath
	qastools
	qatlib
	qbootctl
	qbpm-git
	qconnect
	qdirstat-git
	qemu-audio-alsa
	qemu-audio-pipewire
	qemu-guest-agent
	qemu-hw-display-virtio-gpu
	qemu-hw-display-virtio-gpu-gl
	qemu-hw-display-virtio-gpu-pci
	qemu-hw-display-virtio-gpu-pci-gl
	qemu-hw-display-virtio-gpu-rutabaga
	qemu-hw-display-virtio-vga
	qemu-hw-display-virtio-vga-gl
	qemu-hw-display-virtio-vga-rutabaga
	qemu-hw-s390x-virtio-gpu-ccw
	qemu-hw-usb-host
	qemu-hw-usb-redirect
	qemu-hw-usb-smartcard
	qemu-system-alpha-firmware
	qemu-system-arm-firmware
	qemu-system-hppa-firmware
	qemu-system-microblaze-firmware
	qemu-system-ppc-firmware
	qemu-system-riscv-firmware
	qemu-system-s390x-firmware
	qemu-system-sparc-firmware
	qemu-system-x86-firmware
	qemu-ui-egl-headless
	qflipper
	qlcplus
	qmidiarp-lv2
	qml-lsp-git
	qperf-nordma
	qt5-connectivity
	qt5ct
	qt5-tools
	qt5-wayland
	qt5-webview
	qt5-xcb-private-headers
	qt6-connectivity
	qt6ct
	qt6-grpc
	qt6-languageserver
	qt6-multimedia-gstreamer
	qt6-quickeffectmaker
	qt6-tools-desktop
	qt6-wayland
	qt6-xcb-private-headers
	qtdbusextended
	qtkeychain-qt5
	qtkeychain-qt6
	quickdocs
	quota-tools
	qutebrowser
	qutebrowser-profile-git
	qxlsx
	qxmpp
	r10k
	r8125-dkms
	radcli
	radicale
	radsecproxy
	radvd
	rage-encryption
	rainbowcrack
	rainfrog
	r-air-bin
	randomart
	rapiddisk-dkms
	rarcrack
	rathole
	rattler-build
	rauc
	razor
	rclone
	rdesktop
	rdma-core
	realtime-privileges
	realtime-suggestions
	reaver
	reboot-checker
	redbean
	reddit-tui
	reddix
	redland-storage-sqlite
	redot-git
	release-cli
	relibre
	remake
	remark-language-server
	remctl
	remind
	remmina-plugin-folder
	remmina-plugin-open
	remmina-plugin-rdesktop
	remmina-plugin-rustdesk
	remmina-plugin-url
	remote-desktop-manager
	renderdoc
	restack
	resvg
	retsnoop
	revive
	rev-plugins
	ricochet-refresh
	ripsecrets
	rkhunter
	rng-tools
	rnp
	robotframework-lint
	rocksdb
	rocksndiamonds-contrib
	root-cuda
	rootlesskit
	rootmp-hook
	rosenpass
	roundcubemail
	roundcubemail-plugin-authres_status
	roundcubemail-plugin-caldavzap
	roundcubemail-plugin-carddav
	roundcubemail-plugin-contextmenu
	roundcubemail-plugin-delete_old
	roundcubemail-plugin-persistent_login
	roundcubemail-plugin-showfoldersize
	roundcubemail-plugin-twofactor-webauthn
	roundcubemail-skin-classic
	roundcubemail-skin-larry
	rpacket
	rpg-cli
	rpgp
	rpm-sequoia
	rsop
	rsop-oct
	rspamd
	rst2pdf
	rstcheck
	rsvndump
	rtaudio
	rtirq
	rtl8723du-dkms-git
	rtpengine-kernel-dkms
	rtptools
	rt-tests
	rtw89bt-dkms-git
	rtw89-dkms-git
	rubocop
	ruby-bundled-gems
	ruby-crack
	ruby-default-gems
	ruby-evdev
	ruby-gdk3
	ruby-gdk4
	ruby-google-protobuf
	ruby-gpgme
	ruby-http_parser.rb
	ruby-kramdown-parser-gfm
	ruby-language_server-protocol
	ruby-lint_roller
	ruby-lsp
	ruby-metadata_json_deps
	ruby-metadata-json-lint
	ruby-mime-types
	ruby-mini_portile
	ruby-octokit
	ruby-puppet_forge
	ruby-puppet_metadata
	ruby-rack-protection
	ruby-rake-contrib
	ruby-rbnacl
	ruby-revdev
	ruby-rubocop-performance
	ruby-rubocop-rspec
	ruby-ruby_wasm
	ruby-rugged
	ruby-sinatra-contrib
	ruby-spdx-licenses
	ruby-sqlite3
	ruby-stdlib
	rudder-agent
	ruff-lsp
	rust-analyzer
	rustdesk
	rustdesk-openrc
	rustdesk-server
	rustywind
	ruuvitag-listener
	rvm
	rvpk
	rxvt-unicode
	rxvt-unicode-terminfo
	rye
	rz-cutter
	sabnzbd-docker
	sagetex
	samsung-ssd-fwupdate
	samurai
	sane
	sane-airscan
	sane-gt68xx-firmware
	sanoid
	satintel-git
	sbsigntools
	scala
	scala3
	scalafmt
	scala-sources
	scanmem
	scap-dkms
	sccache-dist
	sccmhunter-git
	scdtools
	schedtool
	schroot
	scim
	scons
	scotch
	scour
	scrape-cli
	scrcpy
	scream_cypher
	scrypt
	scute
	sdcv
	sddm
	sdl2_fontcache
	sdl2_gfx
	sdl2_mixer
	sdl2_net
	sdl3_image
	sdl3_ttf
	sdlconsole
	sdl_gfx
	sdl_image
	sdlk
	sdl_mixer
	sdl_net
	sdl_sound
	sdl_ttf
	sdparm
	sdrpp-headers-git
	seahorse
	seahorse-nautilus
	seanime
	seclists
	secretpixel
	secret-service
	semt
	semver-cpp
	sentry-native
	sequoia-chameleon-gnupg
	sequoia-keyring-linter
	sequoia-octopus-librnp
	sequoia-sop
	sequoia-sqv
	serialdv
	serial-port-json-server
	servicemix
	session-desktop
	sfizz-lib
	sfml
	sfml2
	sh4d0wup
	sha3sum
	shadergen
	shader-slang
	shadowsocks-v2ray-plugin
	shairport-sync
	shared-bootdir-helper
	sharry
	shell-advancedutils
	shellharden
	sherlock.lv2
	shfmt
	shfs-utils
	shibboleth-sp
	shikane
	shlink
	shufflecake
	shunit2
	sidedoor
	sieve-connect
	signal-hound-udev
	signing-party
	signstar-sign
	sile-labelrefs
	simpleid
	simpleorcapluginsystem-git
	simreader
	simtrace
	sipcrack
	sipvicious
	slicer-udev
	slowhttptest
	slsa-builder-docker
	slsa-builder-go
	slsa-generator-container
	slsa-generator-generic
	slsa-github-generator
	slsa-github-generator-common
	slskd-bin
	slurp
	smail
	smartcam
	smartcam-dkms
	smartcat
	smartmontools
	smartreboot
	smbnetfs
	smithery-cli
	smtpdane
	sn0int
	s-nail
	snapback
	snapborg
	snapchat
	snap-pac
	snapper-rollback
	snapper-support
	snap-sync
	snd-hdspe-dkms
	snd-pcsp-dkms
	snd-usb-audio-fasttrack-dkms
	sniffert
	sniffglue
	sniffit
	sniproxy
	snort-nfqueue
	soapyairspy
	soapyaudio
	social-engineer-toolkit
	socid-extractor
	sof-firmware
	sofia-sip
	sof-tools
	soft-serve
	solang-bin
	solidigm-sst-storage-tool-cli
	solr
	somoclu
	sops
	soulseekqt
	sound-icons
	soundwire
	spamassassin
	sparsehash
	spicedb
	spirv-cross
	spirv-headers
	spyder
	spytrap-adb
	sqlcipher
	sqlfluff
	sqlite-analyzer
	sqlitebrowser
	sqlite-doc
	sqliteodbc
	sqlite-tcl
	sql-language-server
	sqlmap
	sqls
	squid
	squidview
	srs
	srsgui
	srslte-avx2
	srs-state-threads
	ssb
	ssfconv
	ssh-audit
	ssh-chat
	sshesame
	sshfs
	sshguard
	ssh-key-confirmer
	ssh-list
	sshpass
	sshs
	ssh-studio
	sshtool
	ssh-tools
	ssh-tpm-agent
	sshtunnel
	sshuttle
	ssh-vault
	sshx
	sshyp
	sslh
	sslsplit
	stalwart-cli
	stalwart-mail
	standard
	staplegl-git
	starpls
	starship
	stash
	staticcheck
	statix-git
	steam
	steam-hdr
	steamlink
	steamrun
	steamtinkerlaunch
	steam-tools-ng
	steghide
	stegseek
	step-ca
	stoken
	strongswan
	sttr
	stumpwm-contrib
	stylelint
	stylelint-config-recommended
	subcat-git
	subnetcalc
	sugar-artwork
	sunshine
	superfile
	supergfxctl
	superhtml
	supervisor
	surge-xt-clap
	surge-xt-vst3
	svelte-language-server
	svgcleaner
	svgo
	svgpart
	svlangserver
	svls
	svt-vp9
	swaybg
	sway-scroll-stable
	swaytreesave
	sweeper
	sweethome3d
	sweethome3d-3dmodels-blendswap-cc0
	sweethome3d-3dmodels-blendswap-ccby
	sweethome3d-3dmodels-contributions
	sweethome3d-3dmodels-katorlegaz
	sweethome3d-3dmodels-lucapresidente
	sweethome3d-3dmodels-reallusion
	sweethome3d-3dmodels-scopia
	sweethome3d-3dmodels-trees
	sweethome3d-furniture-library
	sweethome3d-textures-contributions
	sweethome3d-textures-scopia
	swengine
	swtpm
	swww
	symlinks
	syncplay
	sysboost
	systemc
	systemctl-policy
	systemctl-tui
	systemd-language-server
	systemdlint
	systemd-lsp
	sysz
	tailwindcss-cli
	tailwindcss-language-server
	tamarin-prover
	taplo-cli
	tara
	tarantool
	tarsnap
	tarsnapper
	tbtools
	tcp-brutal-dkms
	tcppc
	teal
	teamtype
	tectonic
	telegram-desktop
	templ
	tempo
	tensorflow-cuda
	tensorrt
	tensorrt-cross-builder-libs
	terminus-font
	term-pdf
	termshark
	termux-keyring
	termux-language-server
	tern
	terrafire
	terraform
	terraformer
	terraform-ls
	terraform-lsp
	terragrunt
	testdisk
	testssl.sh
	tex-fmt
	texlab
	texlive-bibtexextra
	texlive-binextra
	texlive-fontsextra
	texlive-formatsextra
	texlive-humanities
	texlive-langczechslovak
	texlive-langenglish
	texlive-langfrench
	texlive-langgerman
	texlive-latexextra
	texlive-luatex
	texlive-mathscience
	texlive-meta
	texlive-metapost
	texlive-music
	texlive-pstricks
	texlive-publishers
	texlive-tikz-uml
	texlive-xetex
	texturepacker
	tflint
	tfsec
	tgcli
	thc-ipv6
	thefuck
	thelounge
	thorium
	throttled
	thunderbird-dark-reader
	thunderbird-dkimverifier
	thunderbird-tbsync
	tigervnc
	timescaledb-old-upgrade
	tinycompress
	tinymist
	tinysparql-docs
	tlsh
	tlsrpt-reporter
	tmate
	tmon
	tmpcleaner
	tmux
	tmux-cssh
	tmuxinator
	tmux-language-server
	tmuxp
	tmux-resurrect
	tnftpd
	tntnet
	tofu-ls-bin
	tomb
	tombi
	toolame
	toolblex
	torbrowser-launcher
	torcheck
	torchvision-cuda
	torphantom
	toxic
	tpm2-abrmd
	tpm2-openssl
	tpm2-pkcs11
	tpm2-tools
	tpm2-totp
	tpm2-tss-engine
	trackerjacker
	tractor
	traefik
	treeify
	trivy
	trojan
	trufflehog
	trunk
	tslint
	tsshd
	ttf-arphic-tex-extra
	ttf-charis
	ttf-courier-prime
	ttf-daddytime-mono-nerd
	ttf-droid
	ttf-font-icons
	ttf-input-nerd
	ttf-jetbrains-mono-nerd
	ttf-mona-sans
	ttf-monaspace-frozen
	ttf-monaspace-variable
	ttf-nerd-fonts-symbols
	ttf-nerd-fonts-symbols-common
	ttf-nerd-fonts-symbols-mono
	ttf-terminus-nerd
	ttmath
	tufw
	tuna
	turbo-attack-git
	turbo-scanner-git
	turbostat
	tutanota-desktop-bin
	twa
	twine
	twitch
	twitch-cli
	twitch-indicator
	txt2tags
	ty
	typescript-language-server
	typetalk
	typos-lsp
	uasm
	ublock-origin
	uboot-tools
	udev-hid-bpf
	udev-media-automount
	udftools
	udiskie
	udisks2-lvm2
	udisks2-qt5
	udpxy
	ueberzugpp
	uefitool
	ufw
	ufw-extras
	ugm
	ugrep
	umbrello
	umlet
	uml_utilities
	umockdev
	umu-launcher
	unarchiver
	unbound
	unbound-china-list-git
	unbound-roothints
	unbound-root-hints-updater
	unetbootin
	unhide
	unicode-character-database
	unicorn-cal
	unison
	unixodbc
	unoconv
	unrealircd
	up
	updlockfiles
	uptime-kuma
	urh
	urlview-xdg-git
	urxvt-perls
	usbasp-udev
	usbip
	usb_modeswitch
	usbmuxd
	usbview
	usd
	util-linux-aes
	util-linux-libs-aes
	uudeview
	uv
	uvm-systemc
	uwsgi-plugin-cgi
	uwsgi-plugin-lua51
	uwsgi-plugin-mono
	uwsgi-plugin-notfound
	uwsgi-plugin-php
	uwsgi-plugin-php-legacy
	uwsgi-plugin-psgi
	uwsgi-plugin-pypy
	uwsgi-plugin-python
	uwsgi-plugin-rack
	uwsgi-plugin-webdav
	uwsgi-plugin-zabbix
	uwsm
	uwufetch
	v2ray
	v2ray-domain-list-community
	v2ray-geoip
	v4l2loopback-dc-dkms
	v4l2loopback-dkms
	v4l2loopback-utils
	v4l2ucp-qt5
	vacuum
	vagrant
	vale
	vale-ls
	valkey
	vanity-monero
	vault
	vbetool
	vblade
	vc
	vcal
	vco-plugins
	vcvrack
	vdirsyncer
	vdr
	vdrctl
	vdr-softhddevice-drm-gles
	vector
	vector-slicer
	verible
	veridian-bin
	verilator
	verus-analyzer-bin
	verus-bin
	verusfmt-bin
	verylup
	vesktop
	vfio-isolate
	vfio-kvm
	vhba-module-dkms
	vim
	vim-ale
	vim-language-server
	vint
	violetumleditor
	virglrenderer
	virt-firmware
	virt-install
	virtme-ng
	virtualbox-host-dkms
	virt-viewer
	vivaldi
	vivaldi-ffmpeg-codecs
	vkbasalt
	vkbasalt-cli
	vkd3d
	vkd3d-docs
	vkdevicechooser
	vkmark
	vkvg
	vl-convert
	vlc-plugin-aalib
	vlc-plugin-caca
	vlc-plugin-ffmpeg
	vlc-plugin-freetype
	vlc-plugin-gstreamer
	vlc-plugin-pipewire
	vlc-plugin-smb
	vlc-plugin-svg
	vlc-plugin-udev
	voa-verifiers-arch
	volk
	vpl-gpu-rt
	vrpn
	vscode-css-languageserver
	vscode-html-languageserver
	vscode-js-debug
	vscode-json-languageserver
	vscode-php-debug
	vsqlite++
	vte3-utils
	vte4-utils
	vtsls
	vtun
	vue-language-server
	vulkan-caps-viewer-wayland
	vulkan-extra-layers
	vulkan-extra-tools
	vulkan-freedreno
	vulkan-gfxstream
	vulkan-headers
	vulkan-html-docs
	vulkan-memory-allocator
	vulkanscenegraph
	vulkan-tools
	vulkan-utility-libraries
	vulkan-validation-layers
	vulkan-wsi-layer-git
	vulscan
	w3m
	wabt
	wah-plugins
	waifu2x-ncnn-vulkan
	wallabag
	wallutils
	warp-cli
	warp-plus
	wasi-compiler-rt
	wasmer
	wasm-language-tools
	wasm-server-runner
	wasmtime
	wasm-tools
	wavemon
	waybar
	waybar-weather
	waydroid-magisk
	waydroid-script-git
	waydroidsu
	wayland-display-info
	wayland-utils
	waylock
	waypaper
	waypipe
	wayvnc
	wayweather
	wazuh-agent
	wazuh-dashboard
	wazuh-filebeat
	wazuh-indexer
	webdavfs
	webkitgtk-6.0
	webkitgtk-6.0-docs
	weborf
	webp-pixbuf-loader
	webrtc-audio-processing
	webrtc-audio-processing-0.3
	websocat
	websocketpp
	websploit
	websvn
	weron
	wev
	wgcf
	wget
	whipper
	whisper.cpp-cuda
	whois
	wifi-password
	wifite
	wifi_version
	wiggly-stt
	wildcard
	windutils
	wine
	wine-gecko
	wine-mono
	wine-nine
	winesync-dkms
	winesync-header
	winesync-udev-rule
	winetricks
	wire-desktop
	wireguard-dkms
	wireguard-vanity-address
	wireless-regdb
	wireless_tools
	wiremix
	wireplumber
	wireplumber-docs
	wireplumber-openrc
	wireproxy
	wireshark-cli
	wireshark-minecraft-dissector
	wireshark-qt
	wiresmith
	with-b3-git
	wkd-exporter
	wl-clip-persist
	wmenu
	wofi
	wol
	woob
	worker-build
	workerd
	wpaperd
	wpa_supplicant
	wpebackend-fdo
	wpebackend-fdo-docs
	wpmeta
	wrangler
	write-good
	wsdd
	wt
	wxsqlite3
	wxsvg
	x11-ssh-askpass
	x86_energy_perf_policy
	xandikos
	xdebug
	xde-menu
	xdg-autostart
	xdg-base-dir-env
	xdg-dbus-proxy
	xdg-desktop-portal-gtk
	xdg-desktop-portal-hyprland
	xdg-desktop-portal-shana
	xdg-environment
	xdgmenumaker
	xdg-ninja
	xdg-open-server
	xdg-sanity
	xdg-sound
	xdgterm
	xdg-terminal-exec
	xdg-unused-data-git
	xdg-user-dirs
	xdg-user-dirs-gtk
	xdg-utils
	xdg-utils-cxx
	xdotool
	xdph-dmenu-sharepicker
	xf86-input-evdev
	xfmpc
	xmldiff
	xmlindent
	xmlto
	xmltoman
	xmonad-contrib
	xmonad-dbus
	xmonk.lv2
	xmppc
	xmrig
	xorg-iceauth
	xorg-server
	xorg-xinit
	xorg-xvidtune
	xosd
	xpipe
	xray
	xr-hardware
	xtables-addons-dkms
	xt_wgobfs-dkms
	yamlfix
	yamlfmt
	yaml-language-server
	yamllint
	yank
	yara
	yay
	yaycache-hook
	yay-debug
	yayfzf
	ydotool
	yggdrasil
	ynot-fossil
	youtube-tui
	yq
	ytdl
	yt-dlp-ejs
	ytdl-sub
	ytdownloader
	ytfzf
	yubico-pam
	zabbix-agent
	zabbix-frontend-php
	zabbix-web-service
	zam-plugins
	zam-plugins-vst
	zathura
	zathura-cb
	zathura-djvu
	zathura-language-server
	zathura-pdf-mupdf
	zathura-ps
	zdhpctl
	zectl
	zedenv
	zend-debugger
	zenmap
	zephyr-sdk
	zettli
	zfsbootmenu
	zfs-dkms
	zfsnap
	zig
	zigbee2mqtt
	ziggy
	zita-ajbridge
	zita-at1
	zita-bls1
	zizmor
	zls
	zmap
	znapzend
	zoiper-classic
	zoom
	zoom-citrix-plugin
	zoom-l8-dkms
	zoom-native
	zotero
	zotero-extension-ocr
	zoxide
	zram-generator
	zsa-udev
	zsync
	zvm
)
for pkg in "${PKGS[@]}"; do
	yay -Sy --noconfirm "$pkg"
done
