# shellcheck disable=2034
## /qompassai/dotfiles/.config/pacman/makepkg.conf
# Qompass AI Pacman Makepkg Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
AR="llvm-ar"
#BUILDDIR=/tmp/makepkg
ASFLAGS="-march=x86-64 -mtune=native"
BUILDENV=(!distcc color !ccache check !sign)
CARCH="x86_64"
CC="clang"
CXX="clang++"
CHOST="x86_64-pc-linux-gnu"
CFLAGS="-march=x86-64 -mtune=native -O2 -pipe -fno-plt -fexceptions \
        -Wp,-D_FORTIFY_SOURCE=3 -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wno-error=unsafe-buffer-usage"
#-Wimplicit-function-declaration
#CFLAGS+=" -flto=thin"
#CFLAGS+="-Wmissing-prototypes"
# -Wno-non-literal-null-conversion"
COMPRESSBZ2=(lbzip2 -c -f)
COMPRESSGZ=(pigz -c -f -n)
COMPRESSLRZ=(lrzip -q)
COMPRESSLZ=(lzip -c -f)
COMPRESSLZ4=(lz4 -q)
COMPRESSLZO=(lzop -q)
COMPRESSXZ=(xz -c -z -T0 -)
COMPRESSZ=(compress -c -f)
COMPRESSZST=(zstd -c -T0 --ultra -3 -)
CPPFLAGS=""
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS -DABSL_ATTRIBUTE_LIFETIME_BOUND= -Wno-vla-cxx-extension -Wno-error=unsafe-buffer-usage"
#CXXFLAGS+=" -flto=thin"
DEBUG_CFLAGS="-g"
DEBUG_CXXFLAGS="-g"
DEBUG_FFLAGS="-g"
#DISTCC_HOSTS=""
DLAGENTS=('file::/usr/bin/curl -qgC - -o %o %u'
    'ftp::/usr/bin/curl -qgfC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u'
    'http::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
    'https::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
    'rsync::/usr/bin/rsync --no-motd -z %u %o'
    'scp::/usr/bin/scp -C %u %o')
DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc})
FCFLAGS="-march=x86-64 -mtune=native -O2 -pipe -fno-plt -fstack-clash-protection -fcf-protection -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer"
FFLAGS="$FCFLAGS"
GOFLAGS="-tags=release -trimpath -buildvcs=false"
GPGKEY="FF3DF12925AA841877AE6864BA8D40BF292A6CD9"
INTEGRITY_CHECK=(md5 sha1 sha256 sha384 sha512 b2 b3)
#LD=ld.lld
LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-z,pack-relative-relocs"
#LDFLAGS+=" -fuse-ld=lld -flto=thin"
LIB_DIRS=('lib:usr/lib' 'lib32:usr/lib32' 'lib64:usr/lib64')
#LTOFLAGS="-flto"
#LTOFLAGS="-flto=thin"
MAKEFLAGS="-j8"
MAN_DIRS=({usr{,/local}{,/share},opt/*}/{man,info})
NM="llvm-nm"
OPTIPNGFLAGS="-o7 -zm1-9"
OPTIONS=(autodeps strip docs libtool !staticlibs !emptydirs zipman purge !debug !lto)
PKGEXT='.pkg.tar.zst'
PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod)
RANLIB="llvm-ranlib"
RUSTFLAGS="-C target-cpu=native -C opt-level=2 -C force-frame-pointers=yes"
SRCEXT='.src.tar.gz'
STRIP_BINARIES="--strip-all"
STRIP_SHARED="--strip-unneeded"
STRIP_STATIC="--strip-debug"
SVGOFLAGS="--multipass"
UPXFLAGS="--ultra-brute"
VCSCLIENTS=('bzr::breezy'
    'fossil::fossil'
    'git::git'
    'hg::mercurial'
    'svn::subversion')
