# shellcheck disable=2034
## /qompassai/dotfiles/.config/pacman/makepkg.conf
# Qompass AI Pacman Makepkg Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
AR="llvm-ar"
#BUILDDIR=/tmp/makepkg
#BUILDDIR=$HOME/.local/share/makepkg
BUILDDIR=/home/phaedrus/.cache/makepkg
ASFLAGS="-march=x86-64-v3 -mtune=native"
BUILDENV=(!distcc color ccache !check sign)
CARCH="x86_64"
CC="/usr/bin/clang"
#CMAKE_MAKE_PROGRAM="/usr/bin/ninja"
CXX="/usr/bin/clang++"
CHOST="x86_64-pc-linux-gnu"
CFLAGS="-march=x86-64-v3 -mtune=native -O2 -pipe -fno-plt -fexceptions \
        -Wformat -Werror=format-security \
        -fstack-clash-protection -fcf-protection \
        -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer  \
        -mavx2 -mfma -mbmi -mbmi2 -mf16c \
 -fno-math-errno -fno-signed-zeros -fno-trapping-math -fassociative-math"
#CMAKE_PREFIX_PATH="/usr"
CMAKE=/opt/cmake3/bin/cmake
CMAKE_BUILD_TYPE=Release
CMAKE_GENERATOR="Unix Makefiles"
CMAKE_POLICY_DEFAULT_CMP0000=NEW
COMPRESSBZ2=(lbzip2 -c -f)
COMPRESSGZ=(pigz -c -f -n)
COMPRESSLRZ=(lrzip -q)
COMPRESSLZ=(lzip -c -f)
COMPRESSLZ4=(lz4 -q)
COMPRESSLZO=(lzop -q)
COMPRESSXZ=(xz -c -z -T0 -)
COMPRESSZ=(compress -c -f)
COMPRESSZST=(zstd -c -T0 --ultra -3 -)
CPPFLAGS="-D_FORTIFY_SOURCE=3 -D_GLIBCXX_ASSERTIONS"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS -DABSL_ATTRIBUTE_LIFETIME_BOUND= -Wno-varargs"
DEBUG_CFLAGS="-g"
DEBUG_CXXFLAGS="-g"
DEBUG_FFLAGS="-g"
#DISTCC_HOSTS=""
DLAGENTS=('file::/usr/bin/curl -qgC - -o %o %u'
    'ftp::/usr/bin/curl -qgfC - --ftp-pasv --retry 3 --retry-delay 3 -o %o %u'
    'http::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
    'https::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 3 -o %o %u'
    'rsync::/usr/bin/rsync --no-motd -z %u %o'
    'scp::/usr/bin/scp -C %u %o')
DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc} opt/*/{doc,gtk-doc})
GPGKEY="FF3DF12925AA841877AE6864BA8D40BF292A6CD9"
INTEGRITY_CHECK=(md5 sha1 sha256 sha384 sha512 b2 b3)
LD="/usr/bin/lld"
LDFLAGS="-Wl,-O1 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now \
         -Wl,-z,pack-relative-relocs -fuse-ld=lld"
#LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -fuse-ld=gold"
LIB_DIRS=('lib:usr/lib' 'lib32:usr/lib32' 'lib64:usr/lib64')
MAKEFLAGS="-j$(nproc)"
MAN_DIRS=({usr{,/local}{,/share},opt/*}/{man,info})
NM="llvm-nm"
OPTIPNGFLAGS="-o7 -zm1-9"
OPTIONS=(autodeps strip docs !libtool !staticlibs !emptydirs zipman purge !debug !lto)
PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl"
PKGEXT='.pkg.tar.zst'
PURGE_TARGETS=(usr/{,share}/info/dir .packlist *.pod)
RANLIB="llvm-ranlib"
SRCEXT='.src.tar.gz'
STRIP_BINARIES="--strip-all"
STRIP_SHARED="--strip-unneeded"
STRIP_STATIC="--strip-debug"
SVGOFLAGS="--multipass"
SYCLFLAGS="-O3 -fp-model fast"
UPXFLAGS="--ultra-brute"
VCSCLIENTS=('bzr::breezy'
    'fossil::fossil'
    'git::git'
    'hg::mercurial'
    'svn::subversion')
########################
