# /qompassai/dotfiles/.config/pacman/pacman.conf
# Qompass AI Pacman User Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
# Reference: https://man.archlinux.org/man/pacman.conf.5.en | https://wiki.archlinux.org/title/Pacman
[options]
Architecture        = auto #x86_64_v3 x86_64
CacheDir            = /var/cache/pacman/pkg/
CheckSpace
CleanMethod         = KeepCurrent
Color
DBPath              = /var/lib/pacman/
#DisableDownloadTimeout
#DisableSandbox
#DisableSandboxFilesystem
#DisableSandboxSyscalls
DownloadUser        = alpm
#GPGDir             = /etc/pacman.d/gnupg/
HoldPkg             = pacman glibc
HookDir             = /home/phaedrus/.config/pacman/hooks/
IgnoreGroup         = deepin-extra deepin
IgnorePkg           = appimage-installer autozen deepin-desktop-base dtkcore dtk6declarative dtk6gui dtkwidget dtklog python-pytest-lsp deepin-desktop-schemas-git deepin-desktop-schemas python-pynvml omarchy/python-terminaltexteffects wps-office-cn wps-office-mime-cn wps-office-mui-zh-cn clion clion-eap datagrip libselinux libsemanage libsepol phpstorm python-blivet foxit-pdf-editor fortran-language-server libcamera python-blurhash python-pytest-docker-tools xapp-symbolic-icons xapp nemo twitch-indicator xed mintlocale hypnotix nemo-python nemo-seahorse xed-coreplugins-c fingwit srs shairplay
ILoveCandy
#Include
#LocalFileSigLevel  = Never
#LogFile            = /var/log/pacman.log
#Optional DatabaseOptional
#NoExtract          =
#NoProgressBar
NoUpgrade           = etc/mkinitcpio.d/linux-zen.preset
ParallelDownloads   = 15
#RemoteFileSigLevel = Required
RootDir             = /
SigLevel            = Optional DatabaseOptional
UseSyslog
VerbosePkgLists
#XferCommand        = /usr/bin/aria2c --allow-overwrite=true --max-connection-per-server=4 --min-split-size=1M --dir=/ -o %o %u
#XferCommand        = /usr/bin/wget --passive-ftp -c -O %o %u
#Optional
[core-testing]
#CacheServer
Include             = /etc/pacman.d/mirrorlist
#Server
#SigLevel
#Usage
[core]
Include            = /etc/pacman.d/mirrorlist
[extra-testing]
Include           = /etc/pacman.d/mirrorlist
[extra]
Include            = /etc/pacman.d/mirrorlist
[multilib-testing]
Include           = /etc/pacman.d/mirrorlist
[multilib]
Include            = /etc/pacman.d/mirrorlist
#[blackarch]
#Include           = /etc/pacman.d/blackarch-mirrorlist
#[omarchy]
#Server            = https://pkgs.omarchy.org/stable/$arch
#[omarchy]
#Server             = https://pkgs.omarchy.org/edge/$arch
