# /qompassai/dotfiles/.config/pacman/pacman.conf
# Qompass AI Pacman Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[options]
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/aria2c --allow-overwrite=true --continue=true --file-allocation=none --log-level=error --max-tries=2 --max-connection-per-server=2 --min-split-size=5M --no-conf --remote-time=true --summary-interval=60 --timeout=5 --dir=%o --out=%n %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
Architecture = auto
IgnorePkg   = vulkan-mesa-device-select lib32-vulkan-mesa-device-select
#IgnoreGroup =
#NoUpgrade   =
#NoExtract   =
#UseSyslog
Color
#NoProgressBar
CheckSpace
VerbosePkgLists
ParallelDownloads = 10
DownloadUser = alpm
#DisableSandbox
ILoveCandy
#SigLevel = Required DatabaseOptional
#Optional DatabaseOptional
#LocalFileSigLevel = Never
#Optional
#RemoteFileSigLevel = Required
[core-testing]
Include = /etc/pacman.d/mirrorlist
[core]
Include = /etc/pacman.d/mirrorlist
[extra-testing]
Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
[multilib-testing]
Include = /etc/pacman.d/mirrorlist
[multilib]
Include = /etc/pacman.d/mirrorlist
#[blackarch]
#Include = /etc/pacman.d/blackarch-mirrorlist
