# /qompassai/dotfiles/.config/pacman/pacman.conf
# Qompass AI Pacman Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[options]
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/aria2c --allow-overwrite=true --max-connection-per-server=4 --min-split-size=1M --dir=/ -o %o %u

#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u
#CleanMethod = KeepInstalled
Architecture = auto
IgnorePkg   = appimage-installer deepin-desktop-base dtkcore dtk6declarative dtk6gui dtkwidget dtklog python-pytest-lsp deepin-desktop-schemas-git deepin-desktop-schemas python-pynvml
IgnoreGroup = deepin-extra deepin
#NoUpgrade   =
#NoExtract   =
UseSyslog
Color
#NoProgressBar
CheckSpace
VerbosePkgLists
ParallelDownloads = 15
DownloadUser = alpm
#DisableSandbox
ILoveCandy
SigLevel = Optional DatabaseOptional
#Optional DatabaseOptional
#LocalFileSigLevel = Never
#Optional
#RemoteFileSigLevel = Required
#[core-testing]
#Include = /etc/pacman.d/mirrorlist
[core]
Include = /etc/pacman.d/mirrorlist
#[extra-testing]
#Include = /etc/pacman.d/mirrorlist
[extra]
Include = /etc/pacman.d/mirrorlist
#[multilib-testing]
#Include = /etc/pacman.d/mirrorlist
[multilib]
Include = /etc/pacman.d/mirrorlist
#[blackarch]
#Include = /etc/pacman.d/blackarch-mirrorlist
#[omarchy]
Server = https://pkgs.omarchy.org/edge/$arch
