# /qompassai/dotfiles/.config/nut/hosts.conf
# Qompass AI Nut Hosts Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
# MONITOR <system> "<host description>"
# MONITOR myups@localhost "Local UPS"
# MONITOR su2200@10.64.1.1 "Finance department"
# MONITOR matrix@shs-server.example.edu "Sierra High School data room #1"
