# /qompassai/dotfiles/.config/nut/ups.conf
# Qompass AI Nut UPS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
MONITOR snoopy@doghouse 1 monuser mypassword primary
MONITOR snoopy@doghouse 1 monuser mypassword secondary
maxretry = 3
usb_config_index=hexnum, usb_hid_rep_index=hexnum,
usb_hid_desc_index=hexnum, usb_hid_ep_in=hexnum, usb_hid_ep_out=hexnum:
[powerpal]
   driver = blazer_ser
   port = /dev/ttyS0
   desc = "Web server"

[myups]
   driver = mydriver
   port = /dev/ttyS1
   cable = 1234
   desc = "Something descriptive"
