# /qompassai/dotfiles/.config/synapse/log_config.yaml
# Qompass AI Synapse Log Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#######################################################################
version: 1

formatters:
    journal_fmt:
        format: '%(name)s: [%(request)s] %(message)s'
filters:
    context:
        (): synapse.logging.context.LoggingContextFilter
        request: ""
handlers:
    journal:
        class: systemd.journal.JournalHandler
        formatter: journal_fmt
        filters: [context]
        SYSLOG_IDENTIFIER: synapse
root:
    level: INFO
    handlers: [journal]
disable_existing_loggers: False
