# /qompassai/dotfiles/.config/e2scrub/e2scrub.conf
# Qompass AI E2Scrub Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
periodic_e2scrub=1
recipient=root
sender=e2scrub@qompass.ai
snap_size_mb=256
fstrim=0
e2fsck_opts="-vtt"
scrub_all=1
