# /qompassai/dotfiles/.config
protocol=dev
host=localhost
port=4334
# h2-port=4335
# storage-admin-password=
# old-storage-admin-password=
# storage-datomic-password=
# old-storage-datomic-password=
# storage-access=local
# memory-index-threshold=32m
# memory-index-max=512m
# object-cache-max=1g
memory-index-threshold=32m
memory-index-max=256m
object-cache-max=128m
# encrypt-channel=true
data-dir=/var/lib/datomic
log-dir=/var/log/datomic
# pid-file=transactor.pid
# valcache-path=
# valcache-max-gb=
# memcached=host:port,host:port,...
# memcached-username=datomic
# memcached-password=datomic
# write-concurrency=4
# read-concurrency=8
# index-parallelism=1
# aws-s3-log-bucket-id=
# aws-cloudwatch-region=
# aws-cloudwatch-dimension-value=ph43dru5
# Default: 5000, Miniumum: 5000
# heartbeat-interval-msec=5000
# default-partition=:db.part/user
