# /qompassai/dotfiles/.config/nsswitch/nsswitch.conf
# Qompass AI NSSwitch Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
passwd: files systemd
group: files [SUCCESS=merge] systemd
shadow: files systemd
gshadow: files systemd
publickey: files
hosts: mymachines resolve [!UNAVAIL=return] files myhostname dns
networks: files
protocols: files
services: files
ethers: files
rpc: files
netgroup: files
