schema_version = "1.0.0"

id = "simple_audio_visualizer"
version = "1.2.0"
name = "Simple Audio Visualizer"
tagline = "Creates a simple audio visualizer"
maintainer = "Polyfjord <support@polyfjord.com>"
type = "add-on"

website = "https://github.com/polyfjord/Simple-Audio-Visualizer"

tags = ["Animation"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

[permissions]
files = "Import audio from disk"
