# /qompassai/dotfiles/cg/cgconfig.conf
# Qompass AI CGroup Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
#group daemons/www {
#	perm {
#		task {
#			uid = root;
#			gid = webmaster;
#		}
#		admin {
#			uid = root;
#			gid = root;
#		}
#	}
#	cpu {
#		cpu.shares = 1000;
#	}
#}
#
#group daemons/ftp {
#	perm {
#		task {
#			uid = root;
#			gid = ftpmaster;
#		}
#		admin {
#			uid = root;
#			gid = root;
#		}
#	}
#	cpu {
#		cpu.shares = 500;
#	}
#}
#
#mount {
#	cpu = /sys/fs/cgroup/cpu;
#	cpuacct = /sys/fs/cgroup/cpuacct;
#}
