# /qompassai/dotfiles/cg/cgrules.conf
# Qompass AI CGroup Rules Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
#<user>		<controllers>	<destination>
#@student	cpu,memory	usergroup/student/
#peter		cpu		test1/
#%		memory		test2/
