# /qompassai/dotfiles/.config/zfsbootmenu/mkinitcpio.conf
# Qompass AI ZFS BootMenu Mkinitcpio Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
MODULES=(xe nvidia nvidia_drm nvidia_modeset nvidia_uvm btrfs r8125)
BINARIES=()
FILES=()
HOOKS=(base udev autodetect modconf block filesystems keyboard zfsbootmenu)
COMPRESSION="zstd"
#COMPRESSION="gzip"
#COMPRESSION="bzip2"
#COMPRESSION="lzma"
#COMPRESSION="xz"
#COMPRESSION="lzop"
#COMPRESSION="lz4"
#COMPRESSION_OPTIONS=()
zfsbootmenu_module_root="/usr/share/zfsbootmenu"
zfsbootmenu_miser="no"
zfsbootmenu_hook_root="/etc/zfsbootmenu/hooks"
