; /qompassai/dotfiles/.config/looking-glass/client.ini
; Qompass AI Looking Glass Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[app]
shmFile=/dev/kvmfr0
[audio]
micDefault=allow
[egl]
doubleBuffer=yes
[win]
fullscreen=yes
maximize=yes
autoresize=yes
