# /qompassai/dotfiles/.config/gnuradio/conf.d/gr-audio.conf
# Qompass AI Gnuradio Audio Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###################################################################
[audio]
audio_module = auto
