# /qompassai/dotfiles/.config/gnuradio/conf.d/gr-audio-oss.conf
# Qompass AI Gnuradio Audio OSS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###################################################################
[audio_oss]
default_input_device = /dev/dsp
default_output_device = /dev/dsp
latency = 0.005
