# /qompassai/dotfiles/.config/gnuradio/conf.d/gr-audio-portaudio.conf
# Qompass AI Gnuradio Port Audio Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###################################################################
[audio_portaudio]
default_input_device = hw:0,0
default_output_device = hw:0,0
verbose = true
