# /qompassai/dotfiles/.config/gnuradio/conf.d/gr-audio-also.conf
# Qompass AI Gnuradio Alsa Audio Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###################################################################
[audio_alsa]
default_input_device = default
default_output_device = default
period_time = 0.010
nperiods = 32
verbose = true
