# /qompassai/dotfiles/.config/gnuradio/conf.d/gr-audio-jack.conf
# Qompass AI Gnuradio Audio Jack Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###################################################################
[audio_jack]
default_input_device = gr_source
default_output_device = gr_sink
