#!/usr/bin/env bash
#/qompassai/dotfiles/.local/share/bash-completions/completions/ninja
# Copyright (C) 2025 Qompass AI, All rights reserved
###########################################################################
_ninja_target() {
    local cur prev targets dir line targets_command OPTIND

    if _get_comp_words_by_ref cur prev &>/dev/null ; then
        case $prev in
            -f)
                _filedir
                return 0
                ;;
            -C)
                _filedir -d
                return 0
                ;;
        esac
    else
        cur="${COMP_WORDS[COMP_CWORD]}"
    fi

    if [[ "$cur" == "--"* ]]; then
	COMPREPLY=($(compgen -P '--' -W 'version' -- "${cur:2}"))
    else
	dir="."
	line=$(echo ${COMP_LINE} | cut -d" " -f 2-)
	while getopts :C:f:j:l:k:nvd:t: opt $line; do
	    case $opt in
		C) eval dir="$OPTARG" ;;
	    esac
	done;
	targets_command="eval ninja -C \"${dir}\" -t targets all 2>/dev/null | cut -d: -f1"
	COMPREPLY=($(compgen -W '`${targets_command}`' -- "$cur"))
    fi
    return
}
complete -F _ninja_target ninja
