# /qompassai/dotfiles/.config/daxctl.conf.d/daxctl.conf
# Qompass AI Daxctl Config
# Copyright (C) 2025 Qompass AI, All rights reserved
############################################

# 'system-ram'.
#   "ndctl list --device-dax"
# [reconfigure-device unique_identifier_foo]
# nvdimm.uuid=ed93e918-e165-49d8-921d-383d7b9660c5
# mode = system-ram
# online = true
# movable = false
