# /qompassai/dotfiles/.config/swtpm/swtpm-localca.conf
# Qompass AI Software Trusted Platform Module (SWTPM) Local Cert Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#######################################################################
# Reference: https://man.archlinux.org/man/swtpm-localca.conf.5 | https://github.com/stefanberger/swtpm
certserial = ${XDG_DATA_HOME}/swtpm-localca/certserial
issuercert = ${XDG_DATA_HOME}/swtpm-localca/issuercert.pem
signingkey = ${XDG_DATA_HOME}/swtpm-localca/signkey.pem
signingkey_password = ${SWTPM_SIGNING_KEY_PASSWORD}
statedir = ${XDG_DATA_HOME}/swtpm-localca
TSS_TCSD_HOSTNAME = localhost
TSS_TCSD_PORT = 30003
