include		/etc/openldap/schema/core.schema
referral	ldap://root.openldap.org
pidfile		/run/openldap/slapd.pid
argsfile	/run/openldap/slapd.args
modulepath	/usr/lib/openldap
moduleload	back_mdb.la
moduleload	back_ldap.la
 security ssf=1 update_ssf=112 simple_bind=64
access to dn.base="" by * read
access to dn.base="cn=Subschema" by * read
access to *
	by self write
	by users read
	by anonymous auth
database config
rootpw secret
database	mdb
maxsize		1073741824
suffix		"dc=my-domain,dc=com"
rootdn		"cn=Manager,dc=my-domain,dc=com"
rootpw		"$(pass show old/slapd)"
directory	/var/lib/openldap/openldap-data
index	objectClass	eq

database monitor
