global {
    site site.info
}

access {
  allow *
}
#LASTLINE
database jargon {
	data /usr/share/dictd/jargon.dict.dz
	index /usr/share/dictd/jargon.index
}
database wn {
	data /usr/share/dictd/wn.dict.dz
	index /usr/share/dictd/wn.index
}
