# /qompassai/dotfiles/.config/wpg/wpg.confg
# Qompass AI WPG Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[settings]
active = 1
alpha = 100
auto_adjust = false
backend = wal
command = urxvt -e echo hi
editor = urxvt -e nvim
execute_cmd = false
gtk = true
light_theme = false
reload = true
set_wallpaper = true
smart_sort = true
terminal = true

[keywords]
