; /qompassai/dotfiles/.config/snap-pac/snap-pac.ini
; Qompass AI Snap-Pac Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[root]
desc_limit = 72
snapshot = True
cleanup_algorithm = number
pre_description = pacman pre snapshot
post_description = pacman post snapshot
important_packages = ["linux", "linux-lts"]
important_commands = ["pacman -Syu"]
userdata = ["key=value","foo=bar"]
[home]
snapshot = True
