# /qompassai/dotfiles/.config/icecream/icecream.conf
# Qompass AI Icecream Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

ICECREAM_NICE_LEVEL="19"
ICECREAM_LOG_FILE="$XDG_CACHE_HOME/icecream/iceccd.log"
ICECREAM_SCHEDULER_LOG_FILE="$XDG_CACHE_HOME/icecream/scheduler.log"
ICECREAM_NETNAME=""
ICECREAM_SCHEDULER_HOST=""
ICECREAM_MAX_JOBS=""
ICECREAM_ALLOW_REMOTE="yes"
ICECREAM_BASEDIR="$XDG_CACHE_HOME/icecream/envs"
## ICECREAM_RUN_SCHEDULER="no" 
## ICECREAM_SCHEDULER_LOG_FILE="$XDG_STATE_HOME/icecream/scheduler.log"
