# /qompassai/dotfiles/.config/icecream/soft_serve.conf
# Qompass AI soft_serve Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

SOFT_SERVE_PORT='$(pass show ss/port)'
SOFT_SERVE_HOST=domain.tld
SOFT_SERVE_BIND_ADDRESS=0.0.0.0
SOFT_SERVE_KEY_PATH='$(pass show ss/key)'
SOFT_SERVE_REPO_PATH=.repos
SOFT_SERVE_INITIAL_ADMIN_KEY='$(pass show ss/akey)'
