-- /qompassai/Diver/lua/config/core/tree.lua
-- Qompass AI Diver TreeSitter Config Module
-- Copyright (C) 2025 Qompass AI, All rights reserved
------------------------------------------------------
---@source https://github.com/tree-sitter/tree-sitter/wiki/List-of-parsers
---@meta
---@module 'config.core.tree'
local M = {}
function M.treesitter(opts) ---@param opts table<string, any>|nil
    opts = opts or {}
    require('nvim-treesitter.install').prefer_git = true
    local configs = require('nvim-treesitter.configs')
    local base_config = {
        auto_install = true,
        ensure_installed = { ---@type string[]
            'ada',
            'agda',
            'angular',
            -- 'asciidoc',
            --'asciidoc_inline',
            'asm',
            'astro',
            'awk',
            'bash',
            'bass',
            -- 'bazelrc',
            'bibtex',
            'bicep',
            --'bison',
            'bitbake',
            'blueprint',
            'c',
            --'c3',
            'cairo',
            'comment',
            'cmake',
            'commonlisp',
            'cpp',
            'css',
            'csv',
            'cuda',
            'd',
            'dart',
            'desktop',
            'diff',
            'dockerfile',
            'dot',
            'doxygen',
            'editorconfig',
            'elixir',
            'erlang',
            'faust',
            'fish',
            'fortran',
            'fsharp',
            'gitattributes',
            'git_config',
            'gitignore',
            'gdscript',
            'gdshader',
            'gleam',
            'glsl',
            'go',
            'goctl',
            'gomod',
            'gowork',
            'gpg',
            'graphql',
            'haskell',
            'hcl',
            'hoon',
            'html',
            'hyprlang',
            'ini',
            'java',
            'javadoc',
            'jinja',
            'jq',
            'jsdoc',
            'json',
            'json5',
            'jsonc',
            -- 'json_schema',
            'julia',
            'just',
            'kcl',
            'kconfig',
            'kotlin',
            'llvm',
            -- 'llvm_mir',
            'lua',
            'luadoc',
            'luap',
            'luau',
            'latex',
            --'mail',
            --'lilypond',
            'make',
            'markdown',
            'markdown_inline',
            'matlab',
            'mermaid',
            'meson',
            'mlir',
            'nginx',
            'nix',
            'muttrc',
            'objc',
            'objdump',
            'ocaml',
            'odin',
            -- 'openscad',
            'passwd',
            'pem',
            'perl',
            'php',
            'phpdoc',
            --'plantuml',
            'po',
            'powershell',
            'printf',
            'proto',
            'puppet',
            'python',
            'pymanifest',
            'query',
            'r',
            'regex',
            'rego',
            'requirements',
            'rescript',
            'robot',
            'ruby',
            'rust',
            'scala',
            'scfg',
            'smithy',
            'solidity',
            'scss',
            'sql',
            'ssh_config',
            'supercollider',
            'superhtml',
            'svelte',
            'swift',
            'tablegen',
            'teal',
            'templ',
            'terraform',
            'tmux',
            'toml',
            'tsx',
            'typescript',
            'typst',
            'udev',
            'verilog',
            'v',
            'vim',
            'vimdoc',
            'vue',
            'wgsl',
            'wgsl_bevy',
            'xcompose',
            'xml',
            'yaml',
            'zathurarc',
            'zig',
            'ziggy',
            'ziggy_schema',
        },
        highlight = { ---@type boolean[]
            enable = true,
            additional_vim_regex_highlighting = true,
        },
        ignore_install = {
            'ipkg',
            'norg',
        },
        incremental_selection = {
            enable = true,
            keymaps = {
                init_selection = 'gnn',
                node_decremental = 'grm',
                node_incremental = 'grn',
                scope_incremental = 'grc',
            },
        },
        indent = {
            enable = true,
        },
        sync_install = false,
        textobjects = {
            select = {
                enable = true,
                keymaps = {
                    ['af'] = '@function.outer',
                    ['if'] = '@function.inner',
                },
            },
        },
    }
    local final_config = vim.tbl_deep_extend('force', base_config, opts) ---@cast final_config TSConfig
    configs.setup(final_config)
end

function M.tree_cfg(opts)
    opts = opts or {}
    M.treesitter(opts)
    return {
        treesitter = vim.tbl_deep_extend('force', M.options and M.options.treesitter or {}, opts),
    }
end

vim.treesitter.query.set(
    'c',
    'highlights',
    [[;inherits c
  (identifier) @spell]]
)
return M
