# Qompass AI eepm/epm Config
#direct=--direct
#dryrun=--dry-run
#force=--force
#inscript=1
#nodeps=--nodeps
#noremove=--no-remove
#quiet=--quiet
#repack=--repack
#scripts=--scripts
#short=--short
#sort=<arg>
#verbose=--verbose
allow_repack_install=0
allow_thirdparty_install=0
force_yes=--force-yes
non_interactive=--auto
#interactive=--interactive
skip_installed=1
skip_missed=1
#EPM_BACKEND=pacman
#eget_backend=curl
#eget_backend=wget
#eget_options=
#ipfs=--ipfs
#eget_ipfs_db=/var/lib/eepm/eget-ipfs-db.txt
suggest_count=7
#suggest_interactive=1
#full_upgrade_no_atomic_image_update=1
#full_upgrade_no_clean=1
#full_upgrade_no_epm_play=1
#full_upgrade_no_epm_update_check=1
#full_upgrade_no_flatpak=1
#full_upgrade_no_kernel_update=1
#full_upgrade_no_snap=1
#full_upgrade_no_stplr=1
#full_upgrade_no_update=1
#full_upgrade_no_upgrade=1
#use_local_repo=1
#show_command_only=1
#http_proxy=http://proxy.example.com:8080
#https_proxy=http://proxy.example.com:8080
#ftp_proxy=http://proxy.example.com:8080
#no_proxy=localhost,127.0.0.1,.local
BIGTMPDIR=/var/tmp
#warmup=1

