# /qompassai/dotfiles/.config/miniflux/miniflux.conf
# Qompass AI Miniflux Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################### 
RUN_MIGRATIONS=1
