#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Qompass AI
#
# Create modprobe.d-style parameter templates for installed DKMS modules.
#
# For each DKMS module with modinfo parameters, write:
#   ./<module>.conf
#
# Existing effective `options <module> ...` declarations are retained as
# active lines. All other available parameters are documented as commented
# templates.

set -euo pipefail

kernel="$(uname -r)"
arch="$(uname -m)"
dkms_tree="/var/lib/dkms"
output_dir="$PWD"

declare -A module_path=()
declare -A module_options=()

command -v dkms >/dev/null 2>&1 ||
  { printf 'error: dkms was not found in PATH\n' >&2; exit 1; }

command -v modinfo >/dev/null 2>&1 ||
  { printf 'error: modinfo was not found in PATH\n' >&2; exit 1; }

command -v modprobe >/dev/null 2>&1 ||
  { printf 'error: modprobe was not found in PATH\n' >&2; exit 1; }

[[ -d "$dkms_tree" ]] ||
  { printf 'error: DKMS tree not found: %s\n' "$dkms_tree" >&2; exit 1; }

printf 'DKMS status for kernel %s:\n' "$kernel"
dkms status -k "$kernel" 2>/dev/null || true
printf '\n'

# Discover the actual module artifacts built by DKMS for the running kernel.
# Do not assume they were installed into updates/dkms: individual DKMS
# packages may choose another module destination.
while IFS= read -r -d '' path; do
  name="$(modinfo -F name "$path" 2>/dev/null || true)"
  [[ -n "$name" ]] || continue

  # modprobe treats dashes and underscores as equivalent.
  name="${name//-/_}"

  # Keep one actual .ko artifact per module name.
  module_path["$name"]="$path"
done < <(
  find "$dkms_tree" \
    -path "*/${kernel}/${arch}/module/*" \
    -type f \
    \( -name '*.ko' -o -name '*.ko.gz' -o -name '*.ko.xz' -o -name '*.ko.zst' \) \
    -print0 2>/dev/null
)

if ((${#module_path[@]} == 0)); then
  printf 'error: no DKMS module artifacts found for %s (%s)\n' \
    "$kernel" "$arch" >&2
  exit 1
fi

# Capture current effective modprobe options for DKMS modules.
while IFS= read -r line; do
  [[ "$line" =~ ^options[[:space:]]+([^[:space:]]+)[[:space:]]+(.+)$ ]] ||
    continue

  name="${BASH_REMATCH[1]}"
  name="${name//-/_}"

  [[ -v "module_path[$name]" ]] || continue

  module_options["$name"]+="${line}"$'\n'
done < <(modprobe -c)

created=0
skipped=0

while IFS= read -r name; do
  path="${module_path[$name]}"

  # Example output:
  #   video_nr:video device numbers (-1=auto, ...)
  #   card_label:card labels
  parameters="$(modinfo -p "$path" 2>/dev/null || true)"

  # No `parm:` metadata means there is no useful template to generate.
  if [[ -z "$parameters" ]]; then
    ((skipped += 1))
    continue
  fi

  conf_file="${output_dir}/${name}.conf"

  {
    printf '# Generated by %s\n' "${BASH_SOURCE[0]##*/}"
    printf '# Module: %s\n' "$name"
    printf '# Kernel: %s\n' "$kernel"
    printf '# DKMS artifact: %s\n' "$path"
    printf '#\n'
    printf '# Uncomment and replace <value> only for parameters you intend\n'
    printf '# to set. Do not copy every option blindly: module defaults are\n'
    printf '# usually preferable unless you have a specific reason to override.\n'
    printf '\n'

    if [[ -v "module_options[$name]" ]]; then
      printf '# Current effective modprobe configuration\n'
      printf '%s' "${module_options[$name]}"
      printf '\n'
    else
      printf '# Current effective modprobe configuration: none found\n'
      printf '\n'
    fi

    printf '# Available parameters from: modinfo -p %s\n' "$name"

    while IFS= read -r parameter; do
      [[ "$parameter" == *:* ]] || continue

      parameter_name="${parameter%%:*}"
      parameter_description="${parameter#*:}"

      printf '# %s\n' "$parameter_description"
      printf '# options %s %s=<value>\n' "$name" "$parameter_name"
      printf '\n'
    done <<<"$parameters"
  } >"$conf_file"

  printf 'created: %s\n' "$conf_file"
  ((created += 1))
done < <(printf '%s\n' "${!module_path[@]}" | sort)

printf '\nCreated %d module parameter template(s); skipped %d module(s) with no parameters.\n' \
  "$created" "$skipped"
