# source_tree="/usr/src"
# dkms_tree="/var/lib/dkms"
# install_tree="/usr/lib/modules"
tmp_location="/dev/shm"
verbose="1"
# symlink_modules=""
 autoinstall_all_kernels="1"
# sign_file="/path/to/sign-file"
# mok_signing_key=/var/lib/dkms/mok.key
# mok_certificate=/var/lib/dkms/mok.pub
modprobe_on_install="true"
parallel_jobs=0
# maximum compression, at the expense of speed when compressing.
# compress_gzip_opts="-6"
compress_zstd_opts="-q --rm -T0 -19"
compress_xz_opts="--check=crc32 --lzma2=dict=8MiB -9"
load_dependencies="true"
modprobe_timeout=30
