# autoinstall_all_kernels=""
build_environment="CFLAGS='-march=x86-64-v3 -O3' CXXFLAGS='-march=x86-64-v3 -O3'"
compress_gzip_opts="-3"
compress_xz_opts="--check=crc32 --lzma2=dict=1MiB -3 -T0"
compress_zstd_opts="-q -T0 -19" 
dkms_tree="/var/lib/dkms"
install_tree="/usr/lib/modules"
mok_certificate="/var/lib/dkms/mok.pub"
mok_signing_key="/var/lib/dkms/mok.key"
modprobe_on_install="true"
parallel_jobs=$(nproc)
post_transaction="mkinitcpio -p linux-zen"
# sign_file="/path/to/sign-file"
source_tree="/usr/src"
symlink_modules=""
tmp_location="/dev/shm"
verbose="1"
