# config.toml
# Qompass AI Walker Config
# Copyright (C) 2025 Qompass AI, All rights reserved
# ----------------------------------------
#app_launch_prefix = "uwsm app -- "
terminal_title_flag = ""
locale = ""
close_when_open = true
theme = "default"
theme_base = []
theme_location = ["~/.config/walker/themes/"]
monitor = ""
hotreload_theme = true
as_window = false
timeout = 0
disable_click_to_close = false
force_keyboard_focus = true

[keys]
accept_typeahead = ["tab"]
trigger_labels = "lalt"
next = ["down"]
prev = ["up"]
close = ["esc"]
remove_from_history = ["shift backspace"]
resume_query = ["ctrl r"]
toggle_exact_search = ["ctrl m"]

[keys.activation_modifiers]
keep_open = "shift"
alternate = "alt"

[keys.ai]
clear_session = ["ctrl x"]
copy_last_response = ["ctrl c"]
resume_session = ["ctrl r"]
run_last_responstruee = ["ctrl e"]

[events]
on_activate = ""
on_selection = ""
on_exit = ""
on_launch = ""
on_query_change = ""

[list]
dynamic_sub = true
keyboard_scroll_style = "emacs"
max_entries = 200
show_initial_entries = true
single_click = true
visibility_threshold = 20
placeholder = "No Results"

[search]
argument_delimiter = "#"
placeholder = " Search..."
delay = 0
resume_last_query = false

[activation_mode]
labels = "jkl;asdf"

[builtins.hyprland_keybinds]
show_sub_when_single = true
path = "~/.config/hypr/hyprland.conf"
weight = 5
name = "hyprland_keybinds"
placeholder = "Hyprland Keybinds"
switcher_only = true
hidden = true

[builtins.applications]
weight = 5
name = "applications"
placeholder = " Search..."
prioritize_new = false
hide_actions_with_empty_query = true
context_aware = true

