# /qompassai/dotfiles/akvcam/config.ini
; d.ini
; Qompass AI Akvcam Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[Cameras]
cameras/size = 2
cameras/1/type = output
cameras/1/mode = mmap, userptr, rw
cameras/1/description = Virtual Camera (output device)
cameras/1/formats = 2
cameras/1/videonr = 7
cameras/2/type = capture
cameras/2/mode = mmap, r YUY2 640x480 is one of the most widely supported formats in webcam capture
formats/1/format = YUY2
formats/1/width = 640
formats/1/height = 480
formats/1/fps = 60
formats/2/format = RGB24, YUY2
formats/2/width = 640
formats/2/height = 480
formats/2/fps = 20/1, 15/2
[Connections]
connections/size = 1
connections/1/connection = 1:2
[General]
default_frame = /etc/akvcam/default_frame.bmp
