// vim:set ts=4 sw=4 et:
// /qompassai/dotfiles/.config/named/named.conf
// Qompass AI Named Config
// Copyright (C) 2025 Qompass AI, All rights reserved
/////////////////////////////////////////////////////
options {
    allow-recursion { 127.0.0.1; ::1; };
    allow-transfer { none; };
    allow-update { none; };
    directory "/var/named";
    hostname none;
    listen-on-v6 { any; };
    pid-file "/run/named/named.pid";
    server-id none;
    version none;
};
logging {
    channel xfer-log {
        file "/var/log/named.log";
        print-category yes;
        print-severity yes;
        severity info;
    };
    category notify { xfer-log; };
    category xfer-in { xfer-log; };
    category xfer-out { xfer-log; };
};
zone "0.0.127.in-addr.arpa" IN {
    type master;
    file "127.0.0.zone";
};
zone "1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa" {
    type master;
    file "localhost.ip6.zone";
};
zone "localhost" IN {
    type master;
    file "localhost.zone";
};
zone "$(pass show named/domain)" IN {
    type slave;
    file "$(pass show named/zonefile)";
    masters {
        192.168.1.100;
    };
    allow-query { any; };
    allow-transfer { any; };
};
