# /qompassai/dotfiles/.config/wlnfancurve/wlnfancurve.conf
# Qompass AI Wlnfancurve Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

[time]
interval = 7
hysteresis = 7
[curve]
fan_curve  = [0,  30, 40, 52, 64, 76, 89]
temp_curve = [30, 40, 50, 59, 65, 70, 75]
