# /qompassai/dotfiles/.config/pamac/pamac.conf
# Qompass AI Pamac Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
BuildDirectory = /var/tmp
CheckAURUpdates
CheckAURVCSUpdates
DownloadUpdates
EnableAUR
EnableDowngrade
#KeepBuiltPkgs
#KeepNumPackages = 2
MaxParallelDownloads = 10
#NoUpdateHideIcon
OfflineUpgrade
OnlyRmUninstalled
RefreshPeriod = 6
RemoveUnrequiredDeps
SimpleInstall
