# /qompassai/dotfiles/.config/flexiblasrc.d/OpenBLASOpenMP.conf
# Qompass AI Flexibasrc.d Netlib Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#######################################################
[OpenBLASOpenMP]
library = libflexiblas_openblasopenmp.so 

