#!/bin/sh
# Copyright © 2005-2007  Roger Leigh <rleigh@debian.org>
# Copyright © 2019       Steve Langasek <vorlon@debian.org>
#
# schroot is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# schroot is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#####################################################################

set -e

. "$SETUP_DATA_DIR/common-data"
. "$SETUP_DATA_DIR/common-functions"
. "$SETUP_DATA_DIR/common-config"

if [ "$CHROOT_TYPE" = "zfs-snapshot" ] && [ -n "$CHROOT_ZFS_CLONE_NAME" ]; then

    if [ $STAGE = "setup-start" ]; then

        if ! zfs list "$CHROOT_ZFS_DATASET" >/dev/null 2>&1; then
            fatal "Dataset '$CHROOT_ZFS_DATASET' does not exist"
        fi

        if [ "$VERBOSE" = "verbose" ]; then
            zfs snapshot "$CHROOT_ZFS_SNAPSHOT_NAME" \
                $CHROOT_ZFS_SNAPSHOT_OPTIONS
            zfs clone "$CHROOT_ZFS_SNAPSHOT_NAME" \
                "$CHROOT_ZFS_CLONE_NAME" -o mountpoint=legacy
        else
            zfs snapshot "$CHROOT_ZFS_SNAPSHOT_NAME" \
                $CHROOT_ZFS_SNAPSHOT_OPTIONS > /dev/null
            zfs clone "$CHROOT_ZFS_SNAPSHOT_NAME" \
                "$CHROOT_ZFS_CLONE_NAME" -o mountpoint=legacy > /dev/null
        fi

    elif [ $STAGE = "setup-stop" ]; then

        if zfs list "$CHROOT_ZFS_CLONE_NAME" >/dev/null 2>&1
        then
            if [ "$VERBOSE" = "verbose" ]; then
                zfs destroy "$CHROOT_ZFS_CLONE_NAME"
                zfs destroy "$CHROOT_ZFS_SNAPSHOT_NAME"
            else
                zfs destroy "$CHROOT_ZFS_CLONE_NAME" > /dev/null
                zfs destroy "$CHROOT_ZFS_SNAPSHOT_NAME" > /dev/null
            fi
        else
            # The dataset no longer exists, or was never created,
            # for example on zfs clone failure.
            warn "$CHROOT_ZFS_SNAPSHOT_NAME does not exist (it may have been removed previously)"
        fi

    fi

fi

