schema_version = "1.0.0"

id = "timeline_audio_visualizer"
version = "0.2.5"
name = "Timeline Audio Visualizer"
tagline = "Visualize audio waveforms inside Blender animation timelines"
maintainer = "Maxim K. <Telegram: @qsOwOsp>"
type = "add-on"

tags = ["Animation", "Sequencer"]
blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2026 Maxim K.",
]

[permissions]
files = "Read audio files for waveform generation"

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "/.git/",
  "/*.zip",
]
