# /qompassai/dotfiles/.config/keycloak/keycloak.conf
# Qompass AI KeyCloak Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
db=postgres
db-url=jdbc:postgresql://localhost/keycloak
db-username=phaedrus
db-password=mypassword
http-port=8080
hostname=localhost
log-level=INFO
proxy=edge
#db=postgres
#db-username=keycloak
#db-password=password
#db-url=jdbc:postgresql://localhost/keycloak
#health-enabled=true
#metrics-enabled=true
#https-certificate-file=${kc.home.dir}/conf/server.crt.pem
#https-certificate-key-file=${kc.home.dir}/conf/server.key.pem
#proxy=reencrypt
#spi-sticky-session-encoder-infinispan-should-attach-route=false
#hostname=myhostname
