schema_version = "1.0.0"

id = "curve_generator"
version = "1.2.1"
name = "Curve Generator"
tagline = "Generate float curves"
maintainer = "The French Monkey"
license = ["SPDX:GPL-3.0-or-later"]
type = "add-on"
blender_version_min = "4.2.0"
tags = ["Node", "Geometry Nodes", "Add Curve"]

website = "https://tfmstyle.com"
report_issues = "https://github.com/TFMSTYLE/Curve_Generator/issues"

