# /qompassai/dotfiles/vale/.vale.ini
#<!-- Qompass AI - [ ] -->
#<!-- Copyright (C) 2025 Qompass AI, All rights reserved -->
############################################################
MinAlertLevel = suggestion
Packages = alex, RedHat
StylesPath = .
[*]
BasedOnStyles = Vale, RedHat, alex
MinAlertLevel = suggestion
TokenIgnores =
  (\w+://[^\s]+),
  (\S+@\S+),
  (`[^`]+`)
[*.adoc]
BasedOnStyles = Vale, RedHat, alex
BasedOnStyles = Vale, RedHat, alex
[*.md]
BasedOnStyles = Vale, RedHat, alex
[*.rst]
BasedOnStyles = Vale, RedHat, alex
[*.tex]
BasedOnStyles = Vale, RedHat, alex
[*.txt]
BasedOnStyles = Vale, RedHat, alex
[tests/**, vendor/**, node_modules/**]
BasedOnStyles = None
