# /qompassai/dotfiles/.config/steamtinkerlaunch/default_template.conf
# Qompass AI SteamTinkerLaunch Default Template Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################################
KEEPSTLOPEN="0"
USESLR="1"
FORCESLR="0"
USEREAP="1"
FORCEREAP="0"
USEPROTON=""
REDIRCOMPDATA="disabled"
REDIRSTEAMUSER="disabled"
AUTOBUMPGE="0"
AUTOBUMPPROTON="0"
USECUSTOMCMD="0"
CUSTOMCMD="echo"
CUSTOMCMD_ARGS="none"
ONLY_CUSTOMCMD="0"
FORK_CUSTOMCMD="0"
EXTPROGS_CUSTOMCMD="0"
CUSTOMCMDFORCEWIN="0"
WAITFORCUSTOMCMD="0"
INJECT_CUSTOMCMD="0"
INJECTWAIT="0"
USEIGCS="0"
UUUSEIGCS="0"
IGCSWAIT="0"
UUUSEPATCH="0"
UUUPATCHWAIT="0"
UUUSEVR="0"
GAMEARGS="none"
HARDARGS="nope"
USEGAMEMODERUN="0"
USEGAMESCOPE="0"
GAMESCOPE_ARGS="--"
USEOBSCAP="0"
USEZINK="0"
USEPRIMERUN="0"
TOGSTEAMWEBHELPER="0"
USEMANGOHUD="0"
USEMANGOAPP="0"
MAHUBIN="/usr/bin/mangohud"
MAHUARGS="none"
LDPMAHU="0"
MAHUVAR="0"
USEMANGOHUDSTLCFG="0"
ENABLE_VKBASALT="0"
RUN_NYRNA="0"
RUN_REPLAY="0"
RUN_X64DBG="0"
RUN_GDB="0"
USE_WDIB="0"
USEVORTEX="0"
WAITVORTEX="2"
RUN_VORTEX_WINETRICKS="0"
RUN_VORTEX_WINECFG="0"
CHANGE_PULSE_LATENCY="0"
STL_PULSE_LATENCY_MSEC="60"
TOGGLEWINDOWS="0"
RUN_WINETRICKS="0"
WINETRICKSPAKS="none"
RUN_WINECFG="0"
USEWINE="0"
USEWICO="0"
WINEVERSION="echo"
WINEDEFAULT="echo"
VIRTUALDESKTOP="0"
VDRES="none"
USEBOXTRON="0"
USEROBERTA="0"
USELUXTORPEDA="0"
REGEDIT="0"
USEGEOELF="0"
AUTOGEOELF="0"
INSTALL_RESHADE="0"
RESHADE_DEPTH3D="0"
USERESHADE="0"
CUSTOMCMDRESHADE="0"
RESHADEUPDATE="0"
RSOVRD="0"
RSOVRVERS="5.4.2"
CHOOSESHADERS="0"
ALTEXEPATH="/tmp"
ARCHALTEXE="echo"
USEOPENVRFSR="0"
RUNSBSVR="0"
VRVIDEOPLAYERARGS="--flat"
SBSZOOM="1.0"
SBSVRGEOELF="0"
SBSVRRS="0"
SBSRS="0"
MINVRWINH="640"
WAITFORTHISPID="none"
WAITEDITOR="2"
STEAMAPPIDFILE="0"
CHECKCOLLECTIONS="1"
BACKUPSTEAMUSER="0"
RESTORESTEAMUSER="none"
USESUSYM="0"
USEGLOBSUSYM="0"
USE_STLDXVKCFG="0"
DXVK_HUD="0"
DXVK_LOG_LEVEL="none"
DXVK_LOG_PATH="STLCFGDIR/logs/dxvk"
DXVK_SCALE="1.0"
DXVK_FPSLIMIT="none"
DXVK_ASYNC="0"
DXVK_HDR="1"
STRACERUN="0"
STRACEOPTS="-f -t -e trace=file"
USENETMON="0"
BLOCKINTERNET="0"
PROTON_LOG="1"
PROTON_LOG_DIR="STLCFGDIR/logs/proton/id"
USEWINEDEBUGPROTON="0"
PROTON_DUMP_DEBUG_COMMANDS="0"
PROTON_DEBUG_DIR="/tmp"
PROTON_USE_WINED3D="0"
PROTON_NO_D3D11="0"
PROTON_NO_D3D10="0"
PROTON_NO_ESYNC="0"
PROTON_NO_FSYNC="0"
ENABLE_WINESYNC="0"
PROTON_ENABLE_NVAPI="1"
PROTON_HIDE_NVIDIA_GPU="0"
USEDLSS="1"
USERAYTRACING="0"
PROTON_FORCE_LARGE_ADDRESS_AWARE="1"
WINE_FULLSCREEN_INTEGER_SCALING="0"
WINE_FULLSCREEN_FSR="0"
WINE_FULLSCREEN_FSR_STRENGTH="2"
CLEANPROTONTEMP="0"
STLWINEDEBUG="-all"
STLWINEDLLOVERRIDES="none"
WINE_LOG_DIR="STLCFGDIR/logs/wine"
USERSTART="echo"
USERSTOP="echo"
AUTOCONTY="0"
USECONTY="0"
CRASHGUESS="60"
ONLYWICO="0"
GAMESCREENRES="none"
HELPURL="none"
CREATEDESKTOPICON="0"
FIXSYMLINKS="0"
UNSYMLINK="0"
DELPFX="0"
RUN_DEPS="0"
SORTGARGS="0"
WAITMO2="2"
MO2MODE="disabled"
USESPECIALK="0"
SDLUSEWAYLAND="0"
STLRAD_PFTST="none"
SPEKVERS="default"
AUTOSPEK="0"
USEFWS="0"
USEPEV_PELDD="0"
USEPEV_PEPACK="0"
USEPEV_PERES="0"
USEPEV_PESCAN="0"
USEPEV_PESEC="0"
USEPEV_PESTR="0"
USEPEV_READPE="0"
STL_VKD3D_CONFIG="none"
STL_VKD3D_DEBUG="none"
STL_VKD3D_SHADER_DEBUG="none"
STL_VKD3D_LOG_FILE="none"
STL_VKD3D_VULKAN_DEVICE="none"
STL_VKD3D_FILTER_DEVICE_NAME="none"
STL_VKD3D_DISABLE_EXTENSIONS="none"
STL_VKD3D_TEST_DEBUG="0"
STL_VKD3D_TEST_FILTER="none"
STL_VKD3D_TEST_EXCLUDE="none"
STL_VKD3D_TEST_PLATFORM="none"
STL_VKD3D_TEST_BUG="none"
STL_VKD3D_PROFILE_PATH="none"
