# /qompassai/dotfiles/.config/loki/lokinet.ini
[router]
netid=lokinet
min-connections=4
max-connections=6
data-dir=.
worker-threads=0
[network]
#strict-connect=
#keyfile=

# Set the endpoint authentication mechanism.
# none/whitelist/lmq/file
#auth=

# lmq endpoint to talk to for authenticating new sessions
# ipc:///var/lib/lokinet/auth.socket
# tcp://127.0.0.1:5555
#auth-lmq=

# lmq function to call for authenticating new sessions
# llarp.auth
auth-lmq-method=llarp.auth

# manually add a remote endpoint by .loki address to the access whitelist
#auth-whitelist=

# Read auth tokens from file to accept endpoint auth
# Can be provided multiple times
#auth-file=

# Possible values: hashes, plaintext
#auth-file-type=
#auth-static=
#reachable=true
hops=4
paths=6
################exit=false

# When in exit mode announce we allow a private range in our introset.  For example:
#     owned-range=10.0.0.0/24
#owned-range=

# Adds an IP traffic type whitelist; can be specified multiple times.  If any are
# specified then only matched traffic will be allowed and all other traffic will be
# dropped.  Examples:
#     traffic-whitelist=tcp
# would allow all TCP/IP packets (regardless of port);
#     traffic-whitelist=0x69
# would allow IP traffic with IP protocol 0x69;
#     traffic-whitelist=udp/53
# would allow UDP port 53; and
#     traffic-whitelist=tcp/smtp
# would allow TCP traffic on the standard smtp port (21).
#traffic-whitelist=

# Specify a `.loki` address and an optional ip range to use as an exit broker.
# Examples:
#     exit-node=whatever.loki
# would map all exit traffic through whatever.loki; and
#     exit-node=stuff.loki:100.0.0.0/24
# would map the IP range 100.0.0.0/24 through stuff.loki.
# This option can be specified multiple times (to map different IP ranges).
#exit-node=

# Specify an optional authentication code required to use a non-public exit node.
# For example:
#     exit-auth=myfavouriteexit.loki:abc
# uses the authentication code `abc` whenever myfavouriteexit.loki is accessed.
# Can be specified multiple times to store codes for different exit nodes.
#exit-auth=

# Enable / disable automatic route configuration.
# When this is enabled and an exit is used Lokinet will automatically configure the
# operating system routes to route public internet traffic through the exit node.
# This is enabled by default, but can be disabled if advanced/manual exit routing
# configuration is desired.
#auto-routing=true

# Enable / disable route configuration blackholes.
# When enabled lokinet will drop IPv4 and IPv6 traffic (when in exit mode) that is not
# handled in the exit configuration.  Enabled by default.
#blackhole-routes=true

# Interface name for lokinet traffic. If unset lokinet will look for a free name
# matching 'lokinetN', starting at N=0 (e.g. lokinet0, lokinet1, ...).
#ifname=

# Local IP and range for lokinet traffic. For example, 172.16.0.1/16 to use
# 172.16.0.1 for this machine and 172.16.x.y for remote peers. If omitted then
# lokinet will attempt to find an unused private range.
#ifaddr=

# For all IPv6 exit traffic you will use this as the base address bitwised or'd with 
# the v4 address in use.
# To disable ipv6 set this to an empty value.
# !!! WARNING !!! Disabling ipv6 tunneling when you have ipv6 routes WILL lead to 
# de-anonymization as lokinet will no longer carry your ipv6 traffic.
#ip6-range=fd00::

# Map a remote `.loki` address to always use a fixed local IP. For example:
#     mapaddr=whatever.loki:172.16.0.10
# maps `whatever.loki` to `172.16.0.10` instead of using the next available IP.
# The given IP address must be inside the range configured by ifaddr=
#mapaddr=

# Adds a lokinet relay `.snode` address to the list of relays to avoid when
# building paths. Can be specified multiple times.
#blacklist-snode=

# Specify SRV Records for services hosted on the SNApp for protocols that use SRV
# records for service discovery. Each line specifies a single SRV record as:
#     srv=_service._protocol priority weight port target.loki
# and can be specified multiple times as needed.
# For more info see
# https://docs.oxen.io/products-built-on-oxen/lokinet/snapps/hosting-snapps
# and general description of DNS SRV record configuration.
#srv=

# How long to wait (in seconds) for a path to align to a pivot router when establishing
# a path through the network to a remote .loki address.
#path-alignment-timeout=

# If given this specifies a file in which to record mapped local tunnel addresses so
# the same local address will be used for the same lokinet address on reboot.  If this
# is not specified then the local IP of remote lokinet targets will not persist across
# restarts of lokinet.
#persist-addrmap-file=./addrmap.dat


[paths]
unique-range-size=32
[dns]
#upstream=
# Intercept all dns traffic (udp/53) going into our lokinet network interface instead of binding a local udp socket
#l3-intercept=false

#bind=127.0.0.1:0
#bind=127.3.2.1:53
#add-hosts=

# Can be uncommented and set to 1 to disable resolvconf configuration of lokinet DNS.
# (This is not used directly by lokinet itself, but by the lokinet init scripts
# on systems which use resolveconf)
#no-resolvconf=


[bind]
# will be used.
# 
# Examples:
#     outbound=1.2.3.4:5678
#     outbound=:9000
#     outbound=8.9.10.11
# 
# The second example binds on the wildcard address using port 9000; the third example
# binds on the given IP address using a random high port.
#outbound=


[api]
enabled=true
# Recommend localhost-only for security purposes.
#bind=tcp://127.0.0.1:1190
[bootstrap]
#seed-node=false
#add-node=
[logging]
type=print
level=info
#file=
