; /qompassai/dotfiles/.config/php/php.ini
; Qompass AI PHP INI Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[PHP]
; display_errors
; display_startup_errors
; error_reporting
; log_errors
; max_input_time
; output_buffering
; register_argc_argv
; request_order
; session.gc_divisor
; short_open_tag
; zend.assertions
; zend.exception_ignore_args
; zend.exception_string_param_max_len
user_ini.filename = ".user.ini"
;user_ini.filename =
user_ini.cache_ttl = 300
engine = On
short_open_tag = On
precision = 14
output_buffering = 4096
;output_handler =
;url_rewriter.tags

; URL rewriter will not rewrite absolute URL nor form by default. To enable
; absolute URL rewrite, allowed hosts must be defined at RUNTIME.
; Refer to session.trans_sid_hosts for more details.
; Default Value: ""
; Development Value: ""
; Production Value: ""
;url_rewriter.hosts

zlib.output_compression = On
;zlib.output_compression_level = -1
;zlib.output_handler =
implicit_flush = On
unserialize_callback_func =
unserialize_max_depth = 4096
serialize_precision = -1
;open_basedir =
disable_functions =
disable_classes =
highlight.string  = #DD0000
highlight.comment = #FF9900
highlight.keyword = #007700
highlight.default = #0000BB
highlight.html    = #000000
ignore_user_abort = On
realpath_cache_size = 4096k
realpath_cache_ttl = 120
zend.enable_gc = On
zend.multibyte = On
;zend.script_encoding =
zend.exception_ignore_args = On
zend.exception_string_param_max_len = 0
expose_php = On
max_execution_time = 30
max_input_time = 60
max_input_nesting_level = 64
max_input_vars = 1000
max_multipart_body_parts = 1500
memory_limit = 128M
error_reporting = E_ALL & ~E_DEPRECATED
display_errors = On
display_startup_errors = On
log_errors = On
ignore_repeated_errors = Off
ignore_repeated_source = Off
report_memleaks = On
;report_zend_debug = 0
;xmlrpc_errors = 0
;xmlrpc_error_number = 0
html_errors = On
docref_root = "/phpmanual/"
docref_ext = .html
error_prepend_string = "<span style='color: #ff0000'>"
error_append_string = "</span>"
error_log = php_errors.log
; Log errors to syslog (Event Log on Windows).
;error_log = syslog
;syslog.ident = php
syslog.facility = user
syslog.filter = ascii
arg_separator.output = "&amp;"
arg_separator.input = ";&"
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off
auto_globals_jit = On
enable_post_data_reading = On
post_max_size = 8M
auto_prepend_file =
auto_append_file =
default_mimetype = "text/html"
default_charset = "UTF-8"
;internal_encoding =
;input_encoding =
;output_encoding =
include_path = ".:/php/includes"
;include_path = ".;c:\php\includes"
doc_root =
user_dir =
extension_dir = "/usr/lib/php/modules/"
;extension_dir = "ext"
sys_temp_dir = "/tmp"
enable_dl = On

;cgi.force_redirect = 1
;cgi.nph = 1
;cgi.redirect_status_env =
cgi.fix_pathinfo=1
cgi.discard_path=1
fastcgi.impersonate = 1
fastcgi.logging = 1
cgi.rfc2616_headers = 0
cgi.check_shebang_line=1
file_uploads = On
;upload_tmp_dir =
upload_max_filesize = 2M
max_file_uploads = 20
allow_url_fopen = On
allow_url_include = On
;from="john@doe.com"
;user_agent="PHP"
default_socket_timeout = 60
auto_detect_line_endings = On
;extension=bcmath
;extension=bz2
;extension=calendar
extension=curl
;extension=dba
;extension=enchant
;extension=exif
extension=ffi
extension=ftp
;extension=gd
;extension=gettext
;extension=gmp
extension=iconv
;extension=intl
extension=ldap
extension=mysqli
extension=odbc
zend_extension=opcache
extension=pdo_dblib
extension=pdo_mysql
extension=pdo_odbc
extension=pdo_pgsql
extension=pdo_sqlite
extension=pgsql
extension=shmop
extension=snmp
extension=soap
extension=sockets
extension=sodium
extension=sqlite3
extension=sysvmsg
extension=sysvsem
extension=sysvshm
extension=tidy
extension=xsl
extension=zip


[CLI Server]
cli_server.color = On
[Date]
; https://php.net/date.timezone
;date.timezone =
; https://php.net/date.default-latitude
;date.default_latitude = 31.7667

; https://php.net/date.default-longitude
;date.default_longitude = 35.2333

; https://php.net/date.sunrise-zenith
;date.sunrise_zenith = 90.833333

; https://php.net/date.sunset-zenith
;date.sunset_zenith = 90.833333

[filter]
filter.default = unsafe_raw
; https://php.net/filter.default-flags
;filter.default_flags =

[iconv]
;iconv.input_encoding =
;iconv.internal_encoding =
;iconv.output_encoding =

[intl]
;intl.default_locale =
intl.use_exceptions = 0
[sqlite3]
;sqlite3.extension_dir =
sqlite3.defensive = 1

[Pcre]
pcre.backtrack_limit=100000
pcre.recursion_limit=100000
pcre.jit=1
[Pdo]
pdo_odbc.connection_pooling=strict
[Pdo_mysql]
; Default socket name for local MySQL connects.  If empty, uses the built-in
; MySQL defaults.
pdo_mysql.default_socket=

[Phar]
; https://php.net/phar.readonly
phar.readonly = On
phar.require_hash = On
;phar.cache_list =

[mail function]
; For Win32 only.
; https://php.net/smtp
SMTP = localhost
; https://php.net/smtp-port
smtp_port = 25
;sendmail_path =
;mail.force_extra_parameters =
mail.add_x_header = On
mail.mixed_lf_and_crlf = On
[ODBC]
; https://php.net/odbc.default-db
;odbc.default_db    =  Not yet implemented

; https://php.net/odbc.default-user
;odbc.default_user  =  Not yet implemented

; https://php.net/odbc.default-pw
;odbc.default_pw    =  Not yet implemented

; Controls the ODBC cursor model.
; Default: SQL_CURSOR_STATIC (default).
;odbc.default_cursortype
odbc.allow_persistent = On

odbc.check_persistent = On
odbc.max_persistent = -1
odbc.max_links = -1
odbc.defaultlrl = 4096
odbc.defaultbinmode = 1
[MySQLi]
mysqli.max_persistent = -1
mysqli.allow_local_infile = On
;mysqli.local_infile_directory =
mysqli.allow_persistent = On
mysqli.max_links = -1
mysqli.default_port = 3306
mysqli.default_socket =
mysqli.default_host =
mysqli.default_user =
mysqli.default_pw =
mysqli.rollback_on_cached_plink = On
[mysqlnd]
mysqlnd.collect_statistics = On
mysqlnd.collect_memory_statistics = On
; Records communication from all extensions using mysqlnd to the specified log
; file.
; https://php.net/mysqlnd.debug
;mysqlnd.debug =
; Defines which queries will be logged.
;mysqlnd.log_mask = 0
; Default size of the mysqlnd memory pool, which is used by result sets.
;mysqlnd.mempool_default_size = 16000

; Size of a pre-allocated buffer used when sending commands to MySQL in bytes.
;mysqlnd.net_cmd_buffer_size = 2048

; Size of a pre-allocated buffer used for reading data sent by the server in
; bytes.
;mysqlnd.net_read_buffer_size = 32768

; Timeout for network requests in seconds.
;mysqlnd.net_read_timeout = 31536000

; SHA-256 Authentication Plugin related. File with the MySQL server public RSA
; key.
;mysqlnd.sha256_server_public_key =

[PostgreSQL]
pgsql.allow_persistent = On
pgsql.auto_reset_persistent = On
pgsql.max_persistent = -1
pgsql.max_links = -1
pgsql.ignore_notice = 0
pgsql.log_notice = 0
[bcmath]
bcmath.scale = 0

[browscap]
;browscap = extra/browscap.ini

[Session]
session.save_handler = files
session.save_path = "/tmp"
session.use_strict_mode = 0
session.use_cookies = 1
;session.cookie_secure =
session.use_only_cookies = 1
session.name = PHPSESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_domain =
session.cookie_httponly =
; Current valid values are "Strict", "Lax" or "None". When using "None",
; make sure to include the quotes, as `none` is interpreted like `false` in ini files.
; https://tools.ietf.org/html/draft-west-first-party-cookies-07
session.cookie_samesite = "Strict"
session.serialize_handler = php
session.gc_probability = 1
session.gc_divisor = 1000
session.gc_maxlifetime = 1440
session.referer_check =
session.cache_limiter = nocache
session.cache_expire = 180
session.use_trans_sid = 0
session.trans_sid_tags = "a=href,area=href,frame=src,form="
session.trans_sid_hosts=""
session.upload_progress.enabled = On
session.upload_progress.cleanup = On
session.upload_progress.prefix = "upload_progress_"
session.upload_progress.name = "PHP_SESSION_UPLOAD_PROGRESS"
session.upload_progress.freq =  "1%"
session.upload_progress.min_freq = "1"
session.lazy_write = On
[Assertion]
zend.assertions = -1

[COM]
;com.typelib_file =
com.allow_dcom = true
com.autoregister_typelib = true
com.autoregister_casesensitive = false
com.autoregister_verbose = true
;com.code_page=
;com.dotnet_version=
[mbstring]
; language for internal character representation.
; This affects mb_send_mail() and mbstring.detect_order.
; https://php.net/mbstring.language
mbstring.language = English
mbstring.encoding_translation = On
mbstring.detect_order = auto
mbstring.substitute_character = none
mbstring.strict_detection = On
;mbstring.http_output_conv_mimetypes=
mbstring.regex_stack_limit=100000
mbstring.regex_retry_limit=1000000
[gd]
gd.jpeg_ignore_warning = 1

[exif]
;exif.encode_unicode = ISO-8859-15
;exif.decode_unicode_motorola = UCS-2BE
; https://php.net/exif.decode-unicode-intel
;exif.decode_unicode_intel    = UCS-2LE
; https://php.net/exif.encode-jis
;exif.encode_jis =
; https://php.net/exif.decode-jis-motorola
;exif.decode_jis_motorola = JIS
; https://php.net/exif.decode-jis-intel
;exif.decode_jis_intel    = JIS
[Tidy]
;tidy.default_config = /usr/local/lib/php/default.tcfg
tidy.clean_output = Off
[soap]
soap.wsdl_cache_enabled=1
soap.wsdl_cache_dir="/tmp"
soap.wsdl_cache_ttl=86400
soap.wsdl_cache_limit = 5
[sysvshm]
sysvshm.init_mem = 10000
[ldap]
ldap.max_links = -1

[dba]
;dba.default_handler=
[opcache]
opcache.enable=1
opcache.enable_cli=0
opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=10000
opcache.max_wasted_percentage=5
opcache.use_cwd=0
opcache.validate_timestamps=1
opcache.revalidate_freq=2
opcache.revalidate_path=1
opcache.save_comments=1
opcache.record_warnings=0
opcache.enable_file_override=1
opcache.optimization_level=0x7FFFBFFF
opcache.dups_fix=0
;opcache.blacklist_filename=
opcache.max_file_size=1
opcache.force_restart_timeout=180
;opcache.error_log=
opcache.log_verbosity_level=4
opcache.preferred_memory_model=
opcache.protect_memory=0
opcache.restrict_api=""
;opcache.mmap_base=
;opcache.cache_id=
;opcache.file_cache=
opcache.file_cache_only=1
opcache.file_cache_consistency_checks=1
opcache.huge_code_pages=1
opcache.validate_permission=1
opcache.validate_root=1
opcache.opt_debug_level=1
;opcache.preload=
;opcache.preload_user=
opcache.file_update_protection=0
opcache.lockfile_path=/tmp
[curl]
;curl.cainfo =
[openssl]
;openssl.cafile=
;openssl.capath=
[ffi]
ffi.enable=preload
;ffi.preload=
