schema_version = "1.0.0"

id            = "io_directx_x"
version       = "1.1.6"
name          = "DirectX X Format (.x)"
tagline       = "Import/Export DirectX .x"
maintainer    = "io_directx_x contributors"
type          = "add-on"

# Blender Extensions Platform tags
tags = ["Import-Export"]

blender_version_min = "4.2.0"

license = ["SPDX:GPL-3.0-or-later"]

[build]
paths_exclude_pattern = [
  "__pycache__/",
  "*.pyc",
  ".git/",
  "*.x",
]
