# /qompassai/dotfiles/.config/icegrid/icegridregistry.conf
# Qompass AI IceGrid Registry Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################

IceGrid.InstanceName=DemoIceGrid
IceGrid.Registry.Client.Endpoints=tcp -p 4061 -h localhost
#IceGrid.Registry.Client.Endpoints=ssl -p 4062 -h localhost
#IceGrid.Registry.Client.Endpoints=tcp -p 4061 -h localhost:ssl -p 4062 -h localhost
IceGrid.Registry.Server.Endpoints=tcp -h localhost
IceGrid.Registry.Internal.Endpoints=tcp -h localhost
IceGrid.Registry.LMDB.Path=/var/lib/ice/icegrid/registry
IceGrid.Registry.PermissionsVerifier=DemoIceGrid/NullPermissionsVerifier
IceGrid.Registry.AdminPermissionsVerifier=DemoIceGrid/NullPermissionsVerifier
IceGrid.Registry.DefaultTemplates=/usr/share/ice/templates.xml
Ice.UseSystemdJournal=1
Ice.ProgramName=icegridregistry (DemoIceGrid Master)
IceGrid.Registry.Trace.Node=1
IceGrid.Registry.Trace.Replica=1
IceMX.Metrics.Debug.GroupBy=id
IceMX.Metrics.Debug.Disabled=1
IceMX.Metrics.Debug.Reject.parent=Ice\.Admin
IceMX.Metrics.ByParent.GroupBy=parent
IceMX.Metrics.ByParent.Disabled=1
