# #################################################################
# /qompassai/dotfiles/.config/icegrid/icegridnode.conf
# Qompass AI Icegrid Node Config
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Qompass AI
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at:
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# #################################################################


Ice.Default.Locator=DemoIceGrid/Locator:tcp -h localhost -p 4061
#Ice.Default.Locator=DemoIceGrid/Locator:ssl -h localhost -p 4062
IceGrid.Node.Name=node1
IceGrid.Node.Endpoints=tcp -h localhost
IceGrid.Node.Data=/var/lib/ice/icegrid/node1
IceGrid.Node.Output=/var/lib/ice/icegrid/node1
#IceGrid.Node.RedirectErrToOut=1
Ice.UseSystemdJournal=1
Ice.ProgramName=icegridnode (DemoIceGrid node1)
IceGrid.Node.Trace.Replica=2
IceMX.Metrics.Debug.GroupBy=id
IceMX.Metrics.Debug.Disabled=1
IceMX.Metrics.Debug.Reject.parent=Ice\.Admin
IceMX.Metrics.ByParent.GroupBy=parent
IceMX.Metrics.ByParent.Disabled=1
