# /qompassai/dotfiles/.config/libva/libva.conf
# Qompass AI Libva Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
LIBVA_MESSAGING_LEVEL=1
