# /qompassai/dotfiles/.config/webapps/dokuwiki/scheme.conf
# Qompass AI DokuWiki Scheme Config
# Copyright (C) 2025 Qompass AI, All rights reserved
############################################################
http
https
telnet
gopher
wais
ftp
ed2k
irc
ldap
