# /qompassai/dotfiles/.config/knockerencryptssh/knockd.sh
# Qompass AI KnockerEncryptssh Knock Daemon Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
[knockKeyfile]
    sequence    = 23
    seq_timeout = 5
    command     = /etc/knockencryptssh/knocked.sh keyfile
    tcpflags    = syn

[knockPassphrase]
    sequence    = 22
    seq_timeout = 5
    command     = /etc/knockencryptssh/knocked.sh passphrase
    tcpflags    = syn

[options]
    logfile = /var/log/knockd-knockencryptssh.log
    pidfile = /var/run/knockd-knockencryptssh.pid
    interface = eth0
