# /qompassai/dotfiles/.config/amanda/ksc.conf
# Qompass AI Amanda Security Config
# Copyright (C) 2026 Qompass AI, All rights reserved
########################################################
[bugzilla]
user=user@redhat.com
partner=partner-name
partnergroup=partner-group
server=https://bugzilla.redhat.com/xmlrpc.cgi
api_key=api_key
