#!/hint/bash
# shellcheck disable=2034
# /qompassai/dotfiles/.config/makepkg.conf.d/rust.conf
# Qompass AI Makepkg Rust Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
#CARGO_TARGET_DIR="$BUILDDIR/cargo-target"
#CARGO_HOME="$BUILDDIR/cargo-home"
RUSTC_WRAPPER=""
RUSTUP_TOOLCHAIN="stable"
DEBUG_RUSTFLAGS="-C debuginfo=2"
#RUSTFLAGS="${RUSTFLAGS:+${RUSTFLAGS} }-C force-frame-pointers=yes \
#  -C target-cpu=x86-64-v3 \
#  -C opt-level=3 \
#  -C codegen-units=1 \
#  -C link-arg=-fuse-ld=lld"
