#!/hint/bash
# shellcheck disable=2034
# /qompassai/dotfiles/.config/makepkg.conf.d/rust.conf
# Qompass AI Makepkg Rust Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
DEBUG_RUSTFLAGS="-C debuginfo=2"
RUSTFLAGS="${RUSTFLAGS:+${RUSTFLAGS} }-C force-frame-pointers=yes"
