schema_version = "1.0.0"

id = "spline_generator"
version = "1.0.3"
name = "Spline Generator"
tagline = "Generate parametric spline"
maintainer = "The French Monkey"
license = ["SPDX:GPL-3.0-or-later"]
type = "add-on"
blender_version_min = "4.2.0"
tags = ["3D View", "Add Curve"]

website = "https://tfmstyle.com"
report_issues = "https://github.com/TFMSTYLE/Spline_Generator/issues"

