#!/usr/bin/env bash
# dkms.conf
# Qompass AI NVIDIA FS DKMS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
PACKAGE_NAME="nvidia-fs"
PACKAGE_VERSION="2.7"
kernelver=${kernelver:-$(uname -r)}
kernel_source_dir=${kernel_source_dir:-/lib/modules/$kernelver/build}
NVFS_MAX_PEER_DEVS=${NVFS_MAX_PEER_DEVS:-64}
NVFS_MAX_PCI_DEPTH=${NVFS_MAX_PCI_DEPTH:-16}
ofedver=""
check_ofed=$(which ofed_info)
if [ $? -eq 0 ]; then
	ofed_version=$(ofed_info -s)
	if [ $? -eq 0 ]; then
		testofed_version=$(echo "$ofed_version" | cut -d '-' -f 2)
                major_ver=$(echo "$testofed_version" | cut -d '.' -f 1)
                minor_ver=$(echo "$testofed_version" | cut -d '.' -f 2)
                if [ "$testofed_version" == "4.6" ] || [ "$testofed_version" == "4.7" ] || [[ "$major_ver" =~ ^[0-9]+$ && "$major_ver" -gt 4 ]]; then
                        check=$(cat /proc/kallsyms | grep -w "__ksymtab_ib_register_peer_memory_client")
                        if [ $? -eq 0 ]; then
                                ofedver=$testofed_version
                        fi
                else
                        echo "unsupported MOFED version $ofed_version"
                fi
	fi
fi
BUILT_MODULE_NAME[0]="nvidia-fs"
DEST_MODULE_LOCATION[0]="/kernel/fs/nvidia-fs/"
BUILD_DEPENDS[0]="nvidia"
MAKE[0]="NVFS_MAX_PEER_DEVS=${NVFS_MAX_PEER_DEVS} NVFS_MAX_PCI_DEPTH=${NVFS_MAX_PCI_DEPTH} 'make' -j32 KVER=${kernelver} IGNORE_CC_MISMATCH='1'"
AUTOINSTALL="yes"
#POST_REMOVE=nvidia-fs-dkms.prerm
#POST_INSTALL=nvidia-fs-dkms.postinst
