#!/bin/sh
# /qompassai/dotfiles/.config/rosenpass/quickstart.sh
# Interactive quickstart for Qompass AI Rosenpass
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################### 
set -eu
CONFIG_FILE="rosenpass.toml"
PEERS=""
DEFAULT_PORT="9999"
DEFAULT_LISTEN="[::]:$DEFAULT_PORT"
DEFAULT_VERBOSITY="Quiet"

echo "╭──────────────────────────────────────────╮"
echo "│ Qompass AI Rosenpass Config Quickstart   │"
echo "╰──────────────────────────────────────────╯"
echo "  (c) 2025 Qompass AI. All rights reserved"
echo
printf "Server public key (e.g. rosenpass-public): "
read PUBLIC_KEY
[ -z "$PUBLIC_KEY" ] && PUBLIC_KEY="rosenpass-public"
printf "Server secret key (e.g. rosenpass-sk): "
read SECRET_KEY
[ -z "$SECRET_KEY" ] && SECRET_KEY="rosenpass-secret"
printf "Listen address [$DEFAULT_LISTEN]: "
read LISTEN
[ -z "$LISTEN" ] && LISTEN="$DEFAULT_LISTEN"
printf "Verbosity [Quiet/Info/Debug] [$DEFAULT_VERBOSITY]: "
read VERBOSITY
[ -z "$VERBOSITY" ] && VERBOSITY="$DEFAULT_VERBOSITY"
peer_count=1
while :; do
    echo
    echo "→ Configure peer #$peer_count (leave public_key blank to finish)"
    printf "Peer public key [blank to finish]: "
    read PEER_PK
    [ -z "$PEER_PK" ] && break
    printf "Peer endpoint [peer$peer_count.example.com:$DEFAULT_PORT]: "
    read PEER_ENDPOINT
    [ -z "$PEER_ENDPOINT" ] && PEER_ENDPOINT="peer$peer_count.example.com:$DEFAULT_PORT"
    printf "Peer key output file [\$XDG_RUNTIME_DIR/rosenpass/peer$peer_count.key]: "
    [ -z "$PEER_KEY_OUT" ] && PEER_KEY_OUT="\$XDG_RUNTIME_DIR/rosenpass/peer$peer_count.key"
    printf "Peer allowed IPv4 [10.66.66.$((100+peer_count))/32]: "
    read PEER_IPV4
    [ -z "$PEER_IPV4" ] && PEER_IPV4="10.66.66.$((100+peer_count))/32"
    printf "Peer allowed IPv6 [fd00:db8::${peer_count}/128]: "
    read PEER_IPV6
    [ -z "$PEER_IPV6" ] && PEER_IPV6="fd00:db8::${peer_count}/128"
    printf "WireGuard set interface name [wg1]: "
    read WG_IFACE
    [ -z "$WG_IFACE" ] && WG_IFACE="wg1"
    printf "WireGuard peer public key [PEER${peer_count}-WG-PUBLIC-KEY]: "
    read WG_PK
    [ -z "$WG_PK" ] && WG_PK="PEER${peer_count}-WG-PUBLIC-KEY"
    EXCHANGE_CMD="[
  'wg', 'set', '${WG_IFACE}', 'peer', '${WG_PK}', 'preshared-key', '/dev/stdin'
]"
    PEERS="$PEERS
[[peers]]
public_key = '${PEER_PK}'
endpoint = '${PEER_ENDPOINT}'
key_out = '${PEER_KEY_OUT}'
allowed_ips = ['${PEER_IPV4}', '${PEER_IPV6}']
exchange_command = $EXCHANGE_CMD
"
    peer_count=$((peer_count + 1))
done
cat > "$CONFIG_FILE" <<EOF
# /qompassai/rosenpass/rosenpass.toml
# Qompass AI Rosenpass Server Config
# Generated by quickstart $(date -u)
####################################################

public_key = '${PUBLIC_KEY}'
secret_key = '${SECRET_KEY}'
listen = ["${LISTEN}"]
verbosity = "${VERBOSITY}"
$PEERS
EOF
echo
echo "✅ Config generated and saved as $CONFIG_FILE"
echo "You can now run your Rosenpass server using this configuration."
