# /qompassai/rosenpass/ristretto.toml
# Qompass AI Ristretto Rosenpass Server Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

public_key = 'ristretto-rpk'
secret_key = 'ristretto-rsk'
listen = ["[::]:9999"]
verbosity = "Quiet"

[[peers]]
public_key = 'caffe-rpk'
endpoint = 'caffe.qompass.ai:9999'
key_out = '$XDG_RUNTIME_DIR/rosenpass/caffe.key'
allowed_ips = ['10.66.66.5/32', 'fd00:db8::5/128']
exchange_command = [
  'wg',
  'set',
  'hatif',
  'peer',
  'HATIF-WG-PUBLIC-KEY',
  'preshared-key',
  '/dev/stdin'
]

[[peers]]
public_key = 'doppio-rpk'
endpoint = 'doppio.qompass.ai:9999'
key_out = '$XDG_RUNTIME_DIR/rosenpass/doppio.key'
allowed_ips = ['10.66.66.3/32', 'fd00:db8::3/128']
exchange_command = [
  'wg',
  'set',
  'wg1',
  'peer',
  '<DOPPIO-WG-PUBLIC-KEY>',
  'preshared-key',
  '/dev/stdin'
]

[[peers]]
public_key = 'pensare-rpk'
endpoint = 'pensare.qompass.ai:9999'
key_out = '$XDG_RUNTIME_DIR/rosenpass/pensare.key'
allowed_ips = ['10.66.66.5/32', 'fd00:db8::5/128']
exchange_command = [
  'wg',
  'set',
  'pensare',
  'peer',
  'PENSARE-WG-PUBLIC-KEY',
  'preshared-key',
  '/dev/stdin'
]

[[peers]]
public_key = 'primo-rpk'
endpoint = 'primo.qompass.ai:9999'
key_out = '$XDG_RUNTIME_DIR/rosenpass/primo.key'
allowed_ips = ['10.66.66.4/32', 'fd00:db8::4/128']
exchange_command = [
  'wg',
  'set',
  'wg1',
  'peer',
  '<PRIMO-WG-PUBLIC-KEY>',
  'preshared-key',
  '/dev/stdin'
]
