# /qompassai/dotfiles/.config/dkms/snd-pcsp/dkms.conf
# Qompass AI SND-PCSP DKMS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
PACKAGE_NAME="snd-pcsp"
PACKAGE_VERSION="6.15.8"
BUILT_MODULE_NAME[0]="$PACKAGE_NAME"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build CONFIG_SND_PCSP=m modules"
BUILT_MODULE_NAME[0]="snd-pcsp"
DEST_MODULE_LOCATION[0]=/kernel/sound/drivers
AUTOINSTALL=yes
