# /qompassai/dotfiles/.config/nvme/discovery.conf
# Qompass AI NVME Discovery Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
# --transport=<trtype> --traddr=<traddr> --trsvcid=<trsvcid> --host-traddr=<host-traddr> --host-iface=<host-iface>
