# /qompassai/dotfiles/.config/strongswan.d/charon/agent.conf
# Qompass AI StrongSwan.d Charon Agent Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
agent {
    load = yes
}
