# /qompassai/dotfiles/.config/strongswan.d/charon/attr.conf
# Qompass AI StrongSwan.d Charon ATTR Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
attr {
    # <attr> =
    load = yes
}
