# /qompassai/dotfiles/.config/strongswan.d/charon/bypass-lan.conf
# Qompass AI StrongSwan.d Charon Bypass-Lan Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
bypass-lan {
    # interfaces_ignore =
    # interfaces_use =
    load = yes
}

