# /qompassai/dotfiles/.config/strongswan.d/charon/aesni.conf
# Qompass AI StrongSwan.d Charon AESNI Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
chapoly {

    # Whether to load the plugin. Can also be an integer to increase the
    # priority of this plugin.
    load = yes

}

