# /qompassai/dotfiles/.config/strongswan.d/charon/connmark.conf
# Qompass AI StrongSwan.d Charon Connmark Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
connmark {
    load = yes
}
