# /qompassai/dotfiles/.config/strongswan.d/charon/constraints.conf
# Qompass AI StrongSwan.d Charon Constraints Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
constraints {
    load = yes
}
