# /qompassai/dotfiles/.config/strongswan.d/charon/curl.conf
# Qompass AI StrongSwan.d Charon Curl Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
curl {
    load = yes
     redir = -1
    # tls_backend =
}
