# /qompassai/dotfiles/.config/strongswan.d/charon/dhcp.conf
# Qompass AI StrongSwan.d Charon DHCP Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
dhcp {
    force_server_address = no
    identity_lease = no
    # interface =
    interface_receive = charon.plugins.dhcp.interface
    load = yes
    server = 255.255.255.255
    use_server_port = no
}
