# /qompassai/dotfiles/.config/strongswan.d/charon/dnskey.conf
# Qompass AI StrongSwan.d Charon DNSKey Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
dnskey {
    load = yes
}
