# /qompassai/dotfiles/.config/strongswan.d/charon/aesni.conf
# Qompass AI StrongSwan.d Charon EAP-TLS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
eap-tls {
    fragment_size = 1024
    include_length = yes
    load = yes
    max_message_count = 32
}
