# /qompassai/dotfiles/.config/strongswan.d/charon/eap-sim-file.conf
# Qompass AI StrongSwan.d Charon EAP-SIM-File Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
eap-sim-file {
    load = yes
}
