# /qompassai/dotfiles/.config/strongswan.d/charon/aka.conf
# Qompass AI StrongSwan.d Charon EAP-AKA Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
eap-aka {
    load = yes
    request_identity = yes
}
