# /qompassai/dotfiles/.config/strongswan.d/charon/eap-identity.conf
# Qompass AI StrongSwan.d Charon EAP-Identity Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
eap-identity {
    load = yes
}
