# /qompassai/dotfiles/.config/strongswan.d/charon/eap-mschapv2.conf
# Qompass AI StrongSwan.d Charon EAP-MSCHAPV2 Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
eap-mschapv2 {
    load = yes
}
