# /qompassai/dotfiles/.config/strongswan.d/charon/EAP-MD5.conf
# Qompass AI StrongSwan.d Charon EAP-MD5 Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
eap-md5 {
    load = yes
}
