# /qompassai/dotfiles/.config/strongswan.d/charon/eap-dynamic.conf
# Qompass AI StrongSwan.d Charon EAP-Dynamic Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
eap-dynamic {
    load = yes
    prefer_user = no
    # preferred =
}

