# /qompassai/dotfiles/.config/strongswan.d/charon/eap-ttls.conf
# Qompass AI StrongSwan.d Charon EAP-TTLS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
eap-ttls {
    fragment_size = 1024
    include_length = yes
    load = yes
    max_message_count = 32
    phase2_method = md5
    phase2_piggyback = no
    phase2_tnc = no
    phase2_tnc_method = pt
    request_peer_auth = no
}
