# /qompassai/dotfiles/.config/strongswan.d/charon/ext-auth.conf
# Qompass AI StrongSwan.d Charon Ext-Auth Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
ext-auth {
    load = yes
    # script =
}
