# /qompassai/dotfiles/.config/strongswan.d/charon/farp.conf
# Qompass AI StrongSwan.d Charon Farp Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
farp {
    load = yes
}
