# /qompassai/dotfiles/.config/strongswan.d/charon/fips-prf.conf
# Qompass AI StrongSwan.d Charon FIPS-PRF Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
fips-prf {
    load = yes
}
