# /qompassai/dotfiles/.config/strongswan.d/charon/forecast.conf
# Qompass AI StrongSwan.d Charon Forecast Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
forecast {
    groups = 224.0.0.1,224.0.0.22,224.0.0.251,224.0.0.252,239.255.255.250
    # interface =
    load = yes
    # reinject =
}
