# /qompassai/dotfiles/.config/strongswan.d/charon/ha.conf
# Qompass AI StrongSwan.d Charon HA Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
ha {
    ad = yes
    # autobalance = 0
    buflen = 2048
    fifo_interface = yes
    heartbeat_delay = 1000
    heartbeat_timeout = 2100
    # local =
    monitor = yes
    # pools =
    # remote =
    resync = yes
    # secret =
    segment_count = 1
}
