# /qompassai/dotfiles/.config/strongswan.d/charon/kdf.conf
# Qompass AI StrongSwan.d Charon KDF Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
kdf {
    load = yes
}
