# /qompassai/dotfiles/.config/strongswan.d/charon/kernel-netlink.conf
# Qompass AI StrongSwan.d Charon Kernel-Netlink Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
kernel-netlink {
    buflen = <min(PAGE_SIZE, 8192)>
    # fwmark =
    hw_offload_feature_interface = lo
    ignore_retransmit_errors = no
    install_routes_xfrmi = no
    load = yes
    mss = 0
    mtu = 0
    parallel_route = no
    parallel_xfrm = no
    policy_update = no
    port_bypass = no
    process_rules = no
    receive_buffer_size = 8388608
    retries = 0
    roam_events = yes
    set_proto_port_transport_sa = no
    timeout = 0
    xfrm_acq_expires = 165
    spdh_thresh {
        ipv4 {
            lbits = 32
            rbits = 32
        }
        ipv6 {
            lbits = 128
            rbits = 128
        }
    }
}
