# /qompassai/dotfiles/.config/strongswan.d/charon/ldap.conf
# Qompass AI StrongSwan.d Charon Ldap Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
ldap {
    load = yes
}
