# /qompassai/dotfiles/.config/strongswan.d/charon/pem.conf
# Qompass AI StrongSwan.d Charon PEM Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
pem {
    load = yes
}
