# /qompassai/dotfiles/.config/strongswan.d/charon/pkcs8.conf
# Qompass AI StrongSwan.d Charon PKCS8 Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
pkcs8 {
    load = yes
}
