# /qompassai/dotfiles/.config/strongswan.d/charon/pkcs11.conf
# Qompass AI StrongSwan.d Charon PKCS11 Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
pkcs11 {
    load = yes
    reload_certs = no
    use_dh = no
    use_ecc = no
    use_hasher = no
    use_pubkey = no
    use_rng = no
    use_rsa_pss_hashers = no
    modules {
        <name> {
            load_certs = yes
            os_locking = no
            # path =
        }
    }
}
