# /qompassai/dotfiles/.config/strongswan.d/charon/random.conf
# Qompass AI StrongSwan.d Charon Random Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
random {
    load = yes
    random = ${random_device}
    strong_equals_true = no
    urandom = ${urandom_device}
}
