# /qompassai/dotfiles/.config/strongswan.d/charon/socket-default.conf
# Qompass AI StrongSwan.d Charon Socket-Default Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
socket-default {
    # fwmark =
    load = yes
    set_source = yes
    set_sourceif = no
    use_ipv4 = yes
    use_ipv6 = yes
}
