# /qompassai/dotfiles/.config/strongswan.d/charon/sql.conf
# Qompass AI StrongSwan.d Charon SQL Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
sql {
    # database =
    load = yes
    loglevel = -1
}
