# /qompassai/dotfiles/.config/strongswan.d/charon/aesni.conf
# Qompass AI StrongSwan.d Charon AESNI Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
stroke {
    allow_swap = yes
    ignore_missing_ca_basic_constraint = no
    load = yes
    max_concurrent = 4
    prevent_loglevel_changes = no
    secrets_file = ${sysconfdir}/ipsec.secrets
    socket = unix://${piddir}/charon.ctl
    timeout = 0
}
