# /qompassai/dotfiles/.config/strongswan.d/charon/updown.conf
# Qompass AI StrongSwan.d Charon UpDown Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
updown {
    dns_handler = no
    load = yes
}
