# /qompassai/dotfiles/.config/strongswan.d/charon/xauth-generic.conf
# Qompass AI StrongSwan.d Charon XAuth-Generic Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
xauth-generic {
    load = yes
}
