# /qompassai/dotfiles/.config/strongswan.d/charon/xauth-pam.conf
# Qompass AI StrongSwan.d Charon XAuth-PAM Config
# Copyright (C) 2025 Qompass AI, All rights reserved
######################################################
xauth-pam {
     load = yes
     pam_service = login
     session = no
     trim_email = yes
}
