# /qompassai/dotfiles/.config/shadowvpn/server.conf
# Qompass AI ShadowVPN Server Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
server="$(pass show shadowvpn/addr)"
port="$(pass show shadowvpn/port)"
user_token="$(pass show shadowvpn/token)"
password="$(pass show shadowvpn/clientpass)"
mode="$(pass show shadowvpn/mode)"
concurrency=1
mtu="$(pass show shadowvpn/mtu)"
intf="$(pass show shadowvpn/intf)"
net="$(pass show shadowvpn/net)"
up=$XDG_CONFIG_HOME/shadowvpn/client_up.sh
down=$XDG_CONFIG_HOME/shadowvpn/client_down.sh
pidfile="$(pass show shadowvpn/pidf)"
logfile="$(pass show shadowvpn/logfile)"
