# /qompassai/dotfiles/.config/acetoneiso/acetoneiso_advanced.conf
# Qompass AI Acetone ISO Advanced Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
TRAYICON = enabletrayicon
TRAYICON_CLOSE = closetrayicon
HISTORY_CLEAN = cleanhistory
HISTORY_REMOVE_FAKE = removefakehistory
