# /qompassai/dotfiles/.config/acetoneiso/acetoneiso.conf
# Qompass AI Acetone ISO Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
ISO_FROM_FOLDER = standard
PLAYER = kaffeine
FILE_BROWSER = kde
DB = /home/phaedrus
recursive = norecursive
