## /qompassai/dotfiles/.config/puppetlabs/puppet/puppet.conf
# Qompass AI Puppetlabs Puppet Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
# - https://puppet.com/docs/puppet/latest/config_important_settings.html
# - https://puppet.com/docs/puppet/latest/config_about_settings.html
# - https://puppet.com/docs/puppet/latest/config_file_main.html
# - https://puppet.com/docs/puppet/latest/configuration.html
