# /qompassai/dotfiles/.config/qemu/qemu-ga.conf
# Qompass AI Qemu-GA Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
[general]
daemonize = 1
fsfreeze-hook = /etc/qemu/fsfreeze-hook
method = virtio-serial
path = /dev/virtio-ports/org.qemu.guest_agent.0
pidfile = /run/qemu-ga.pid
statedir = /run
verbose = 0
# blacklist =
# logfile =
