# /qompassai/dotfiles/.config/remctl/conf.d/user.conf
# Qompass AI RemCtl User Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
kadmin reset-password /usr/local/bin/kadmin-remctl logmask=3 \
    $XDG_DATA_HOME/remctl/acl/kadmin-password
