# /qompassai/dotfiles/.config/zfsbootmenu/dracut.conf.d/zfsbootmenu.conf
# Qompass AI ZFS BootMenu Dracut Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###########################################################################
nofsck="yes"
add_dracutmodules+=" zfsbootmenu bash "
omit_dracutmodules+=" btrfs zfs resume systemd systemd-initrd dracut-systemd plymouth dash "
