# /qompassai/dotfiles/.config/audit/plugins.d/audispd-zos-remote.conf
# Qompass AI Audispd Zos Remote Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
active = yes
direction = out
path = /usr/bin/audispd-zos-remote
type = always 
args = /home/phaedrus/.config/audit/zos-remote.conf
format = string
