# /qompassai/dotfiles/.config/audit/plugins.d/filter.conf
# Qompass AI Audit Plugins Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
active = yes
direction = out
path = /sbin/audisp-filter
type = always
args = allowlist /etc/audit/audisp-filter.conf /sbin/audisp-syslog LOG_USER LOG_INFO interpret
format = string
