# /qompassai/dotfiles/.config/audit/plugins.d/syslog.conf
# Qompass AI Remote Audit AF Unix Plugin Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
active = yes
direction = out
path = /usr/bin/audisp-syslog
type = always 
args = LOG_INFO
format = string
