# /qompassai/dotfiles/.config/overlayroot/overlayroot.conf
# Qompass AI Overlayroot Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
OVLROOT_FS_ROONLY="msdos,fat,vfat,iso9660,udf,ntfs-3g,ntfs3"
OVLROOT_FS_RAMONLY="tmpfs,devpts,devtmpfs,tracefs,debugfs,\
configfs,securityfs,proc,sysfs,swap,ramfs"
OVLROOT_FSTAB="/tmp/overlayroot.fstab"
OVLROOT_MAINDIR="/.overlay"
OVLROOT_LOWERDIR_NAME="ro"
OVLROOT_UPPERDIR_NAME="rw"
OVLROOT_WORKDIR_NAME="work"
FSTAB_SYSTEM="/etc/fstab"
#ROOTMNT="/new_root"
