build-users-group =
sandbox = false
use-xdg-base-directories = true
trusted-users = phaedrus
allowed-users = phaedrus
experimental-features = nix-command flakes ca-derivations git-hashing verified-fetches
keep-build-log = true
print-missing = true
show-trace = true
