# /qompassai/dotfiles/.config/udisks2/udisks2.conf
# Qompass AI UDisks2 Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
[udisks2]
modules=*
modules_load_preference=ondemand
[defaults]
encryption=luks2
