# /qompassai/dotfiles/.config/dkms/facetimehd/dkms.conf
# Qompass AI FaceTimeHD DKMS Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################
PACKAGE_NAME=facetimehd
PACKAGE_VERSION=0.6.8
BUILT_MODULE_NAME[0]="facetimehd"
BUILT_MODULE_LOCATION[0]="."
DEST_MODULE_LOCATION[0]="/extra"
AUTOINSTALL="yes"
MODULES_CONF[0]="blacklist bdc_pci"
