; /qompassai/dotfiles/.config/icaclient/appsrv.ini
; Qompass AI Citrix Client App Server Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[ApplicationServers]
[WFClient]
Version = 2
