; /qompassai/dotfiles/.config/icaclient/Unknown_Region.ini
; Qompass AI Citrix Client Unknown Region Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
[Preferences]
[Top Level]
AllowConnection=false
AllowUnrecognisedICAParameters=false
EnableLockdown=true
OverrideInvalidICAParameters=true
Version Minimum=10000
Version Maximum=10000
