# /qompassai/dotfiles/.config/wiremix/wiremix.toml
# Qompass AI WireMix Config
# Copyright (C) 2026 Qompass AI, All rights reserved
## ##################################################
# Reference: https://github.com/tsowell/wiremix/blob/main/wiremix.toml
char_set = "default"
enforce_max_volume = false
# fps = 60.0 #
max_volume_percent = 150.0
mouse = true
peaks = "auto"
# remote = "pipewire-0"
tab = "playback"
theme = "default"

# [names]
# stream = [ "{node:node.name}: {node:media.name}" ]
# endpoint = [ "{device:device.nick}", "{node:node.description}" ]
# device = [ "{device:device.nick}", "{device:device.description}" ]
[char_sets.default]
default_device = "◇"
default_stream = "◇"
dropdown_border = "Rounded"
dropdown_icon = "▼"
dropdown_more = "•••"
dropdown_selector = ">"
help_border = "Rounded"
help_more = "•••"
list_more = "•••"
meter_center_left_active = "▮"
meter_center_left_inactive = "▮"
meter_center_right_active = "▮"
meter_center_right_inactive = "▮"
meter_left_active = "▮"
meter_left_inactive = "▮"
meter_left_overload = "▮"
meter_right_active = "▮"
meter_right_inactive = "▮"
meter_right_overload = "▮"
selector_bottom = "░"
selector_middle = "▒"
selector_top = "░"
tab_marker_left = "["
tab_marker_right = "]"
volume_empty = "╌"
volume_filled = "━"

[char_sets.extracompat]
default_device = "*"
default_stream = "*"
dropdown_border = "Plain"
dropdown_icon = "\\"
dropdown_more = "~~~"
dropdown_selector = ">"
help_border = "Plain"
help_more = "~~~"
list_more = "~~~"
meter_center_left_active = "["
meter_center_left_inactive = "["
meter_center_right_active = "]"
meter_center_right_inactive = "]"
meter_left_active = "#"
meter_left_inactive = "="
meter_left_overload = "!"
meter_right_active = "#"
meter_right_inactive = "="
meter_right_overload = "!"
selector_bottom = "-"
selector_middle = "="
selector_top = "-"
tab_marker_left = "["
tab_marker_right = "]"
volume_empty = "-"
volume_filled = "="

[char_sets.compat]
default_device = "◊"
default_stream = "◊"
dropdown_border = "Plain"
dropdown_icon = "▼"
dropdown_more = "•••"
dropdown_selector = ">"
help_border = "Plain"
help_more = "•••"
list_more = "•••"
meter_center_left_active = "█"
meter_center_left_inactive = "█"
meter_center_right_active = "█"
meter_center_right_inactive = "█"
meter_left_active = "┃"
meter_left_inactive = "┃"
meter_left_overload = "┃"
meter_right_active = "┃"
meter_right_inactive = "┃"
meter_right_overload = "┃"
selector_bottom = "░"
selector_middle = "▒"
selector_top = "░"
tab_marker_left = "["
tab_marker_right = "]"
volume_empty = "─"
volume_filled = "━"
keybindings = [
  { key = { Char = "0" }, action = { SetAbsoluteVolume = 1.00 } },
  { key = { Char = "1" }, action = { SetAbsoluteVolume = 0.10 } },
  { key = { Char = "2" }, action = { SetAbsoluteVolume = 0.20 } },
  { key = { Char = "3" }, action = { SetAbsoluteVolume = 0.30 } },
  { key = { Char = "4" }, action = { SetAbsoluteVolume = 0.40 } },
  { key = { Char = "5" }, action = { SetAbsoluteVolume = 0.50 } },
  { key = { Char = "6" }, action = { SetAbsoluteVolume = 0.60 } },
  { key = { Char = "7" }, action = { SetAbsoluteVolume = 0.70 } },
  { key = { Char = "8" }, action = { SetAbsoluteVolume = 0.80 } },
  { key = { Char = "9" }, action = { SetAbsoluteVolume = 0.90 } },
  { key = { Char = "?" }, action = "Help" },
  { key = { Char = "`" }, action = { SetAbsoluteVolume = 0.00 } },
  { key = "BackTab", modifiers = "SHIFT", action = "TabLeft" },
  { key = { Char = "c" }, action = "ActivateDropdown" },
  { key = { Char = "d" }, action = "SetDefault" },
  { key = "Down", action = "MoveDown" },
  { key = "Enter", action = "ActivateDropdown" },
  { key = "Esc", action = "CloseDropdown" },
  { key = { Char = "h" }, action = { SetRelativeVolume = -0.01 } },
  { key = { Char = "H" }, action = "TabLeft" },
  { key = { Char = "j" }, action = "MoveDown" },
  { key = { Char = "k" }, action = "MoveUp" },
  { key = { Char = "L" }, action = "TabRight" },
  { key = { Char = "l" }, action = { SetRelativeVolume = 0.01 } },
  { key = { Char = "m" }, action = "ToggleMute" },
  { key = { Char = "q" }, action = "Exit" },
  { key = "Left", action = { SetRelativeVolume = -0.01 } },
  { key = "Right", action = { SetRelativeVolume = 0.01 } },
  { key = "Tab", action = "TabRight" },
  { key = "Up", action = "MoveUp" },
]

[themes.default]
config_device = {  }
config_profile = {  }
default_device = {  }
default_stream = {  }
dropdown_border = {  }
dropdown_icon = {  }
dropdown_item = {  }
dropdown_more = { fg = "DarkGray" }
dropdown_selected = { fg = "LightCyan", add_modifier = "REVERSED" }
help_border = {  }
help_item = {  }
help_more = { fg = "DarkGray" }
list_more = { fg = "DarkGray" }
meter_active = { fg = "LightGreen" }
meter_center_active = { fg = "LightGreen" }
meter_center_inactive = { fg = "DarkGray" }
meter_inactive = { fg = "DarkGray" }
meter_overload = { fg = "Red" }
node_target = {  }
node_title = {  }
selector = { fg = "LightCyan" }
tab = {  }
tab_marker = { fg = "LightCyan" }
tab_selected = { fg = "LightCyan" }
volume = {  }
volume_empty = { fg = "DarkGray" }
volume_filled = { fg = "LightBlue" }
