# /qompassai/dotfiles/.config/tailscale/tsdns_settings.ini
# Qompass AI TailScale DNS Settings Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
*.teamspeak-systems.de=1.2.3.4:15000
*=12.13.14.15:$(pass show ts/port)
external.api=8.8.8.8:53
internal.lan=192.168.1.1:53
private.teamspeak.com=12.13.14.15:14000
public.teamspeak.com=12.13.14.15:10000
public2.teamspeak.com=[2001:0db8::1]:9987 1.2.3.4:9987 5.6.7.8:9987
region-eu.teamspeak.com=23.45.67.89:12345
subdomain.dev.example.com=[fd00:dead:beef::1]:5300
test.teamspeak.com=12.13.14.15:12000
voice.teamspeak.com=NORESPONSE
