# /qompassai/dotfiles/.config/violet/violet.conf
# Qompass AI Violet Config
# Copyright (C) 2025 Qompass AI, All rights reserved
####################################################

log-level=info
#log=/var/log/violet.log
#port=3478
#range=49152:65535
#bind=0.0.0.0
#external=X.Y.Z.W
#credentials=user1:pass1
#quota=50
#credentials=user2:pass2
#quota=60
#max=1024
