# /qompassai/dotfiles/.config/nvoc.d/gpu0-preset.conf
# Qompass AI Nvoc.d Config
# Copyright (C) 2025 Qompass AI, All rights reserved
###########################################
gpu=0
gpu_core_clock_offset_low="0"
gpu_core_clock_offset_medium="0"
gpu_core_clock_offset_high="0"
mem_clock_offset_low="0" 
mem_clock_offset_medium="0"
mem_clock_offset_high="0" 
