## /qompassai/dotfiles/.config/pacman.d/patch-kernel.conf
# Qompass AI Pacman Patch-Kernel Config
# Copyright (C) 2026 Qompass AI, All rights reserved
####################################################
MAKEPKG_USER=""
BUILD_DIRECTORY=""
KERNEL_PATCHES=""
# MAKEPKG_OPTIONS="--clean --skippgpcheck"
# PACMAN_CACHE_DIR=/var/cache/pacman/pkg
