#! /bin/sh
set -e
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin
MAXNS=3
RDNSS_LIMIT=$(($MAXNS - 1))
sysconfdir='/etc'
localstatedir='/var'
resolvconf="$sysconfdir/resolv.conf"
myresolvconf="$localstatedir/run/rdnssd/resolv.conf"
RE_NSV4='^nameserver  *\([0-9]\{1,3\}\.\)\{3,3\}[0-9]\{1,3\} *$'
RE_NSV4OR6='^nameserver  *[a-fA-F0-9:\.]\{1,46\}\(%[a-zA-Z0-9]\{1,\}\)\{0,1\} *$'
limit=$RDNSS_LIMIT
nnsv4=`grep -c "$RE_NSV4" $resolvconf || [ $? -le 1 ]`
room=$(($MAXNS - $nnsv4))
if [ $limit -lt $room ]; then
	limit=$room
fi
{
	sed -e "/$RE_NSV4OR6/d" < $resolvconf
	grep -m $limit "$RE_NSV4OR6" < $myresolvconf || [ $? -le 1 ]
	sed -ne "/$RE_NSV4/p" < $resolvconf
} > $resolvconf.tmp
mv -f $resolvconf.tmp $resolvconf

