# /qompassai/dotfiles/.config/docker/buildx/buildkitd.default.toml
# Qompass AI Rootless Docker Daemon Config
# Copyright (C) 2025 Qompass AI, All rights reserved
# #################################################################
address = ["tcp://127.0.0.1:1234"]

[grpc]
address = ["unix:///run/user/1000/buildkit/buildkitd.sock"]

[grpc.tls]
cert = ""
key = ""

[registry."docker.io"]
mirrors = ["mirror.gcr.io"]

[registry."myregistry:5000"]
http = true
insecure = true

[worker.oci]
gc = true
gckeepstorage = 20000

[worker.containerd]
cpus = 4
enabled = true
platforms = ["linux/amd64", "linux/arm64"]
memory = "4096M"

[metrics]
address = "127.0.0.1:9436"
