# ~/.config/jj/config.toml
# ------------------------
# Copyright (C) 2025 Qompass AI, All rights reserved

[user]
name = "Matt A. Porter"
email = "map@qompass.ai"

[ui]
color = "always"          # or "auto" or "never"
paginate = "auto"         # or "never"

[pager]
diff = "delta"

[template-aliases]
"format_short_id(id)" = "id.shortest(12)"

