# /qompassai/dotfiles/.config/syncplay/server.conf
# Qompass AI Syncplay Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
# References: See https://syncplay.pl/guide/server/ 
chat="--disable-chat"
isolate="--isolate-room"
maxChars="--max-chat-message-length 500"
password="--password '$(pass show syncplay/pass)'"
port="--port=8999"
ready="--disable-ready"
salt="--salt '$(pass show syncplay/salt)"
statsFile="--stats-db-file $XDG_CONFIG_HOME/syncplay/stats.db"
tls="--tls $XDG_CONFIG_HOME/letsencrypt/live/syncplay.com/"
usernameLength="--max-username-length 20"
