# /qompassai/dotfiles/.config/motion/camera2-dist.conf
# Qompass AI Motion Camera2-Dist Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
camera_name Patio
camera_id 102
netcam_url http://yourcamera2ip:port/camera/specific/url
width 352
height 288
text_left Camera2
text_right Patio\n%Y-%m-%d\n%T-%q
movie_filename CAM02_%t-%v-%Y%m%d%H%M%S
