# /qompassai/dotfiles/.config/motion/camera3-dist.conf                    # Qompass AI Motion Camera3-Dist Config                                   # Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
camera_name Front Door
camera_id 103
netcam_url rtmp://yourcamera3ip:port/camera/specific/url
netcam_userpass myusername:mypassword
width 2048
height 1536
text_left Camera3
text_right FrontDoor\n%Y-%m-%d\n%T-%q
text_scale 4
movie_filename CAM03_%t-%v-%Y%m%d%H%M%S
