# /qompassai/dotfiles/.config/motion/camera1-dist.conf
# Qompass AI Motion Camera1-Dist Config
# Copyright (C) 2025 Qompass AI, All rights reserved
#################################################
camera_name MyCam1
camera_id 101
netcam_url rtsp://yourcamera1ip:port/camera/specific/url
width 1280
height 720
text_left CAMERA 1
movie_filename CAM01_%t-%v-%Y%m%d%H%M%S
