; /qompassai/dotfiles/.config/motion/motion-dist.conf
; Qompass AI Motion-Dist Config
; Copyright (C) 2025 Qompass AI, All rights reserved
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
daemon off
setup_mode off
; pid_file value
; log_file value
log_level 6
; target_dir value
video_device /dev/video0
; video_params value
; netcam_url value
width 640
height 480
framerate 15
text_left CAMERA1
text_right %Y-%m-%d\n%T-%q
emulate_motion off
threshold 1500
; noise_level 32
despeckle_filter EedDl
minimum_motion_frames 1
event_gap 60
pre_capture 3
post_capture 0
; on_event_start value
; on_event_end value
; on_movie_end value
picture_output off
picture_filename %Y%m%d%H%M%S-%q
movie_output on
movie_max_time 60
movie_quality 45
movie_codec mkv
movie_filename %t-%v-%Y%m%d%H%M%S
webcontrol_port 8080
webcontrol_localhost on
webcontrol_parms 0
stream_port 8081
stream_localhost on
; camera /usr/etc/motion/camera1.conf
; camera /usr/etc/motion/camera2.conf
; camera /usr/etc/motion/camera3.conf
; camera /usr/etc/motion/camera4.conf
; camera_dir /usr/etc/motion/conf.d
